### PR TITLE
Reduce size of test names to fix long path breaks on VSO builds

### PR DESCRIPTION
**Pull request by brthor**
cc @piotrpMSFT @Sridhar-MS @eerhardt 

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2603)

### CODE REVIEW

**Comment by eerhardt** [comment]
:shipit:

**Comment by brthor** [comment]
This will fix the current issues we are seeing but I'm wondering if we should change the key for test asset copying from test method names, to something which has a consistent length.

Thoughts on this?

**Comment by eerhardt** [comment]
> This will fix the current issues we are seeing but I'm wondering if we should change the key for test asset copying from test method names, to something which has a consistent length.

I think that could break things like multiple tests running at the same time that use the same test asset. If you don't isolate them per test, they could be stomping on each other. (I remember hearing a rumor that @Sridhar-MS is working on making our tests fully parallel.)

**Comment by brthor** [comment]
> I think that could break things like multiple tests running at the same time that use the same test asset. If you don't isolate them per test, they could be stomping on each other. (I remember hearing a rumor that @Sridhar-MS is working on making our tests fully parallel.)

It need not be the same name it's using to isolate tests, it could be something like the truncated method name, with collision handling (happen _1 or similar)

**Comment by eerhardt** [comment]
> It need not be the same name it's using to isolate tests, it could be something like the truncated method name, with collision handling (happen _1 or similar)

Yes, I think something like that could work.  But I'd think that would be work for RTM. Your current change is all that's needed for RC2.

**Comment by brthor** [comment]
Fair enough, just want to get this on Folks' mind.

**Comment by Sridhar-MS** [comment]
When creating the `TestInstance` you can specify your own name too - https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.TestFramework/Microsoft.DotNet.TestFramework.TestAssetsManager.cs#L87

**Pull request merged**
