### PR TITLE
Update postinstall

### PR DESCRIPTION
**Pull request by Sridhar-MS**
Fixing a typo.

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2095)

### CODE REVIEW

**Comment by Sridhar-MS** [comment]
cc: @mellinoe

**Comment by Sridhar-MS** [comment]
@dotnet-bot test OSX x64 Release Build please

**Comment by Sridhar-MS** [comment]
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by Sridhar-MS** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by mellinoe** [comment]
LGTM

**Pull request merged**
