### PR TITLE
Merge rel/1.1.0-MSRC to rel/1.1.0

### PR DESCRIPTION
**Pull request by peterhuene**

### CODE REVIEW

**Comment by peterhuene** [comment]
@dotnet-bot test this please

**Comment by peterhuene** [comment]
@dotnet-bot test this please

**Comment by livarcocc** [comment]
CLI Deps is still being used. We probably have more than one nuget.config file in the repo (some that are used by tests only) where we need to remove CLI deps from as well.

**Comment by peterhuene** [comment]
Yeah, mistake on my part when I rebased from another machine.  This should now pass except for missing `dotnet-deb-tool` in BlobFeed.  I'll request it to be pushed up.

**Comment by peterhuene** [comment]
Waiting to hear back from @crummel about pushing up the older version of `dotnet-deb-tool` to blob feed.

**Comment by livarcocc** [comment]
Could we move the ubuntu package up to the one available in the feed to unblock the PR?

**Comment by peterhuene** [comment]
I'll give it a try.

**Comment by peterhuene** [comment]
Unfortunately, `2.0.0-preview2-25331-01` of the package is netcoreapp2.0.  We'll need the older version.

**Comment by peterhuene** [comment]
@dotnet-bot test Ubuntu x64 Release Build please.

**Comment by peterhuene** [comment]
@dotnet-bot test Ubuntu x64 Release please.

**Comment by peterhuene** [comment]
@mmitche I'm seeing very long queue times for Ubuntu x64 (never seems to start).  Any ideas?

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Release please.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
It doesn't appear to be an issue with machines, it just looked like Jenkins was ignoring the retest phrase.

**Pull request merged**
