### PR TITLE
LOC CHECKIN | dotnet/cli release/2.1.3xx | 20180427

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by peterhuene** [comment]
Investigating the test failure.

**Comment by peterhuene** [comment]
The failure appears to be a test bug.  I'll update the PR with the fix.

**Comment by peterhuene** [comment]
@MattGertz for approval

## Issues fixed

N/A

## Description of Issue

This is a LOC update PR.

## Customer Impact

Customers will see out of date resource strings or non-localized resource strings without this PR.

## Risk

Low

## Testing

Automated CI tests.

**Comment by MattGertz** [comment]
Go ahead.  (No functional changes, so no need to take to shiproom.)

**Comment by peterhuene** [comment]
@dotnet-bot test Linux x64 Release Build please.

**Comment by peterhuene** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please.

**Pull request merged**
