### PR TITLE
add back docker hub builds trigger

### PR DESCRIPTION
**Pull request by brthor**
cc @naamunds @MichaelSimons

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2033)

### CODE REVIEW

**Comment by MichaelSimons** [comment]
:shipit: - Thanks for fixing this.

**Comment by naamunds** [comment]
I think it would be a good idea to add dependencies on `PublishDebFilesToDebianRepo` and `PublishSdkInstallerFileToAzure` to `TriggerDockerHubBuilds`. Do you want to do that in this change, or should I do it in a separate change?

**Comment by brthor** [comment]
build timed out
@dotnet-bot test Ubuntu x64 Debug Build please

**Comment by naamunds** [comment]
Actually `TriggerDockerHubBuilds` is not dependent on `PublishDebFilesToDebianRepo`, but will be dependent on all three installer files being published to Azure (@MichaelSimons is planning to make a change to dotnet-docker-preview to install the other two Debian files in addition to the CLI SDK package). I can make a change to add the `TriggerDockerHubBuilds` dependencies separately.

This PR LGTM.

**Comment by brthor** [comment]
@naamunds I don't know what we gain from moving the trigger, but am not opposed to it :smile:

**Comment by brthor** [comment]
@MichaelSimons When installing the .debs via dpkg, you'll need to install the host, shared fx, then sdk in order. Sure you would've figured it out but we ran into in our testing so figured I'd call it out :smile:

**Comment by MichaelSimons** [comment]
@brthor - yep already discovered this :smile: Are there plans to update the readme in this regard?  Having a link to the sdk .deps doesn't seem real helpful without the other two.

**Comment by brthor** [comment]
yes adding this soon

**Comment by brthor** [comment]
ahhhh hit update branch instead of merge......

**Pull request merged**
