### PR TITLE
fix #745: dotnet new should not expose public types

### LINKED ISSUE #745: dotnet new template should not expose public types
The "new" template exposes a public type with a public method:

```C#
public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
```
These should not be public. 

Also, maybe we should remove the namespace once there are no public types. it will simplify our "hello world"

### PR DESCRIPTION
**Pull request by krwq**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2353)

### CODE REVIEW

**Comment by krwq** [comment]
cc: @KrzysztofCwalina

**Comment by davidfowl** [comment]
I have to ask, why does this matter?

**Comment by brthor** [comment]
@dotnet-bot test this please

**Comment by krwq** [comment]
@davidfowl, it's generally bad practice to expose public APIs

**Comment by troydai** [comment]
I can offer one reason to make a program class publish. It could be useful for test. For example dotnet-projectmodel-server test initially "new" a program to run the server in process. (it is not the case now since the dotnet-projectmodel-server was wrapped into the dotnet project and the Program turn into a command).

**Comment by eerhardt** [comment]
@krwq @davidfowl @blackdwarf Are we still interested in taking this PR for Preview2?  If not, it should be closed.

**Comment by krwq** [comment]
I honestly think it actually doesn't matter, this is just a single word to change for user.

**Comment by eerhardt** [comment]
Closing as this appears to have zero traction.

**Pull request closed without merging**
