### PR TITLE
Show version guide only when restore fails

### PR DESCRIPTION
**Pull request by wli3**
fix https://github.com/dotnet/cli/issues/8927

### CODE REVIEW

**Comment by wli3** [comment]
@MattGertz for tell mode

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT x64 Release Build

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT_ES x64 Debug Build

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT_ES x64 Debug Build

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT_ES x64 Debug Build

**Comment by wli3** [comment]
@dotnet-bot test Linux arm Debug Build

**Comment by wli3** [comment]
@livarcocc I can still checkin this today?

**Comment by livarcocc** [comment]
Yes.

**Comment by livarcocc** [comment]
@MattGertz TELL MODE.

**Pull request merged**
