### PR TITLE
Add commit hash to dotnet

### PR DESCRIPTION
**Pull request by schellap**
Helps in debugging and finding symbols etc. quickly.

@gkhanna79 PTAL.

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2749)

### CODE REVIEW

**Comment by gkhanna79** [comment]
LGTM

**Comment by anurse** [comment]
Could we embed this and the version in the same way that CoreCLR is now doing (i.e. an SCCS ID: https://en.wikipedia.org/wiki/Source_Code_Control_System)? Then I can run `what dotnet` and it will tell me the version and commit hash :)

**Comment by schellap** [comment]
@anurse, for RTM: https://github.com/dotnet/cli/issues/2761

**Comment by schellap** [comment]
That would be super useful, btw!

**Pull request merged**
