### PR TITLE
Update project.json

### PR DESCRIPTION
**Pull request by kinguru**
Fixed json formatting, by notepad++ jstools jsformat command.

### CODE REVIEW

**Comment by davidfowl** [comment]
Looks like tabs

**Comment by kinguru** [comment]
Yes, it is just formatting with tabs.

**Comment by davidfowl** [comment]
Pleas don't use tabs. Also, if you're going to format the JSON files, do all of them in a single change. Changes like this usually conflict with other changes to the JSON files.

**Comment by shahid-pk** [comment]
also the contribution guidelines discourage code formatting contributions

**Comment by davidfowl** [comment]
I made a change that formats all of the files and fixes a few dependency problems. Thanks for the PR.

**Pull request closed without merging**
