### PR TITLE
Insert NuGet Build 5.0.1-rtm.5946 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 5.0.1-rtm.5946 into cli release/2.1.6xx branch

### CODE REVIEW

**Comment by nkolev92** [comment]
Unclear yet whether this actually needs to happen. 

Will ping again when I know more.

**Comment by nguerrera** [comment]
Test CentOS7.1 x64 Debug Build

**Comment by nguerrera** [comment]
cc @peterhuene

**Comment by vivmishra** [comment]
Approved for 2.1.604

**Comment by peterhuene** [comment]
Will merge as soon as the branding update is in.

**Pull request merged**
