### PR TITLE
Remove Project Model Server

### PR DESCRIPTION
**Pull request by piotrpMSFT**
Removes the Project Model Server from the msbuild feature branch. We won't be using this component once projects are migrated to MSBuild.

/cc @troydai @davidfowl @DustinCampbell @srivatsn @BillHiebert 
/cc @eerhardt @brthor @livarcocc @sokket

### CODE REVIEW

**Comment by sokket** [comment]
LGTM...love seeing code deletions!

**Comment by brthor** [comment]
> Took 24 min on Azure0629083937

:+1:  :shipit:  :shipit:  :shipit:

**Comment by eerhardt** [comment]
:shipit:

**Comment by troydai** [comment]
Shall I cry?

**Pull request merged**
