### PR TITLE
Insert Microsoft.TestPlatform.cli for update3 preview1

### PR DESCRIPTION
**Pull request by Faizan2304**
1) https://github.com/Microsoft/vstest/issues/755
2) https://github.com/Microsoft/vstest/issues/687
3) https://github.com/Microsoft/vstest/issues/737
4) Enable couple of disabled tests

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test Debian8.2 x64 Debug Build
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@MattGertz for approval.

**Comment by singhsarab** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by livarcocc** [comment]
@Faizan2304 the failures here seem legit. Can you investigate?

**Comment by Faizan2304** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please
@dotnet-bot  test Ubuntu16.04 x64 Debug Build  please

**Comment by Faizan2304** [comment]
@livarcocc Creating repro machine on our side to root cause the issue.

**Comment by Faizan2304** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by Faizan2304** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please
@dotnet-bot test Debian8.2 x64 Debug Build please
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by Faizan2304** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by Faizan2304** [comment]
@dotnet-bot test Linux x64 Release Build please

**Pull request merged**
