### PR TITLE
Insert NuGet Build 5.1.0-rtm.5921 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 5.1.0-rtm.5921 into cli release/2.2.3xx branch

### CODE REVIEW

**Comment by nkolev92** [comment]
@nguerrera @dsplaisted 
This insertion contains the PackageDownload, FrameworkReference work.

**Comment by nkolev92** [comment]
Note that this is for 16.1 preview 2!

**Comment by nguerrera** [comment]
> Note that this is for 16.1 preview 2!

Are your preview 1 bits already in these branches?

**Comment by nkolev92** [comment]
> Are your preview 1 bits already in these branches?

Our preview1 bits are the previous insertion, `5.1.0-rtm.5906`.

**Comment by zivkan** [comment]
This PR is superseded by #11112. Please close this one.

**Pull request closed without merging**
