### PR TITLE
Branding changes for  TestPlatform 15.6 RTM

### PR DESCRIPTION
**Pull request by jayaranigarg**
VS insertion [PR](https://devdiv.visualstudio.com/DevDiv/Automated%20Testing/_git/VS/pullrequest/106851?_a=files&path=%2F.corext%2FConfigs%2Fcomponents.json&discussionId=1014812)

### CODE REVIEW

**Comment by smadala** [comment]
@livarcocc Please don't merge this for now. More validation need to be done on this bits. We will update the thread once the validation complete.

**Comment by livarcocc** [comment]
We can't take any more changes for 15.6, unfortunately. We are locked down due to a MSRC release happening after 15.6.

**Comment by jayaranigarg** [comment]
@livarcocc : We are not with validations on our end.

**Comment by livarcocc** [comment]
@MattGertz This missed the train for 15.6 in 2.1.100 because of the MSRC lock down. Could we take it for a servicing of 2.1.1xx? We will need one for other fixes. Should we go ahead and file a VSO bug to get approval for this? It is a branding change only, from my understanding.

**Comment by MattGertz** [comment]
@livarcocc Per our discussion, I'm OK with taking this with whatever the next appropriate servicing fix that we have planned for 2.1.1xx (obviously, this change by itself is not sufficient to generate a servicing release).

**Comment by MattGertz** [comment]
Also, same goes for 15.6 -- if we happen to have a servicing payload for that (which we think is likely), we'd soak this up then as well.  Livar will create a VSO bug.

**Comment by jayaranigarg** [comment]
@livarcocc : Taking the fix for servicing of 2.1.1xx would be wonderfull !! Please go ahead.

**Pull request merged**
