### PR TITLE
Added --nologo option

### LINKED ISSUE #10825: Implement --nologo for MSBuild forwarding commands.
## Steps to reproduce

1. `dotnet new console`.
2. `dotnet build --help`.
3. `dotnet build --nologo`.

See discussion at #10165.

## Expected  behavior

For step 2, the command help displays a `--nologo` option.  Note: `dotnet test` already does this.

For step 3, the command succeeds because `--nologo` is forwarded to MSBuild as `/nologo`.

**Note: this should apply to all commands that forward options to MSBuild.**

## Actual behavior

For step 2, the command does not make any mention of a `nologo` option, which is commonly used for MSBuild users.

For step 3, the command fails since `--nologo` isn't an option for MSBuid (`-nologo` and `/nologo` are supported instead).

## Environment data

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-010380
 Commit:    fc40010104

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview4-010380/

Host (useful for support):
  Version: 3.0.0-preview4-27418-3
  Commit:  6d5e4a7932

.NET Core SDKs installed:
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.502 [/usr/local/share/dotnet/sdk]
  2.1.504 [/usr/local/share/dotnet/sdk]
  2.2.100 [/usr/local/share/dotnet/sdk]
  2.2.101 [/usr/local/share/dotnet/sdk]
  3.0.100-preview-009812 [/usr/local/share/dotnet/sdk]
  3.0.100-preview4-010380 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19118-01 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27418-3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by Potapy4**
Close #10825

I added the `--nologo` option for the `dotnet build`, `dotnet clean`, `dotnet pack` and `dotnet publish` commands. @peterhuene Did I miss other commands or is everything OK?

### CODE REVIEW

**Comment by peterhuene** [comment]
@Potapy4 thank you for this contribution!

I'll get this reviewed soon.

**Comment by Potapy4** [comment]
@peterhuene just a quick question:
Should we modify existing tests (where possible) and run tests with `--nologo` option, for example:
https://github.com/dotnet/cli/blob/643c3784d520c4551510cd6d66162cc52abd0d1f/test/dotnet-build.Tests/GivenDotnetBuildBuildsCsproj.cs#L126-L143

In this test, we can add smth like `.ExecuteWithCapturedOutput("--nologo");` and  `cmd.Should().Pass().And.NotHaveStdOutContaining("Microsoft (R) Build Engine");`

**Comment by Potapy4** [comment]
And one more question: Is the project with tests calling `msbuild` directly and ignore `dotnet cli`? After rebuilt everything, I can't use the `--nologo` option in the test method, but I can pass `-nologo` or `/nologo` (msbuild recognizes these commands), and the test will pass successfully.

capture

**Comment by peterhuene** [comment]
Hi @Potapy4:

I think a new test to `test/dotnet-build.Tests/GivenDotnetBuildBuildsCsproj.cs` would be justified so that it can call out that `--nologo` is explicitly what is being tested.

It can effectively be a copy of the test you pasted, except it would pass `--nologo` and ensure that the output does not have `Microsoft (R) Build Engine` using `ContainVisuallySameFragmentIfNotLocalized` (use this instead of `NotHaveStdOutContaining` as I'm not sure if we localize "Build Engine" in that text).

Regarding running the tests in Visual Studio, I always run the tests from the command line using `build.cmd -test` when on Windows.  I also use [this part of the Developer Guide](https://github.com/dotnet/cli/blob/master/Documentation/project-docs/developer-guide.md#using-the-built-dotnet) to test out my changes manually.

I think @wli3 might run the CLI tests from within Visual Studio, so he might have some insight to share.

**Comment by Potapy4** [comment]
@peterhuene thanks for clarifying! I added tests, but I got confused with `ContainVisuallySameFragmentIfNotLocalized` - I didn't find conditions to revert this (like `Shouldnt().ContainVisuallySameFragmentIfNotLocalized()` - anyway, the logic is that, we can successfully build with `--no logo` option, and if it is en-us culture, we will additionally check the output:

https://github.com/dotnet/cli/blob/e0a373f2f90af9d6c5e521c7fb3e77de2f80e41a/test/dotnet-build.Tests/GivenDotnetBuildBuildsCsproj.cs#L153-L162

P.S. - And could you restart the CI build? 🔄

**Comment by peterhuene** [comment]
Hi @Potapy4.  You're right, there isn't a negated version of `ContainVisuallySameFragmentIfNotLocalized`.  Let's keep what you have.

**Comment by peterhuene** [comment]
It looks like the Windows leg failed due to a locked file; it's unrelated to these changes and I will restart it in the morning once all other CI builds complet).  I hope we can get this merged tomorrow.  Thanks!

**Comment by wli3** [comment]
> I think @wli3 might run the CLI tests from within Visual Studio, so he might have some insight to share.

Not all tests can run in VS (tests related to project tools). You need to run `.\build.cmd` first and run  `.\scripts\cli-build-env.bat` and run `devenv Microsoft.DotNet.Cli.sln` in the same session

**Comment by peterhuene** [comment]
@Potapy4 Thank you very much for this excellent contribution and for taking the issue off my plate 😄.

**Comment by livarcocc** [comment]
Thanks @Potapy4.

@peterhuene do you want to mark this PR as community so that we can keep track of that?

**Comment by peterhuene** [comment]
Good idea.  I'll do that to this and the other PRs.

**Pull request merged**
