### PR TITLE
Improve Sln reader/writer tests

### LINKED ISSUE #5004: SLN reader/writer: Add comprehensive tests

### PR DESCRIPTION
**Pull request by jgoshi**
Fixes #5004 

@piotrpMSFT @livarcocc @krwq @jonsequitur

### CODE REVIEW

**Comment by jgoshi** [comment]
This basically is just a test change (in product code I only changed an exception class to be public). What is the policy for merging this one?

**Comment by jgoshi** [comment]
@piotrpMSFT @livarcocc @krwq @jonsequitur is it ok to just merge this? It's an improvement for sln reader/writer tests. There is a code change (making the InvalidSolutionFormatException class public instead of internal).

**Comment by jgoshi** [comment]
@srivatsn Is it ok for me to merge this? It's a test only change (except for making the InvalidSolutionFormatException class public instead of internal). I want to build on this change for another issue I'm looking at (to improve the error messages for why a solution failed to load).

**Comment by srivatsn** [comment]
Yes go ahead. Test-only changes don't need approval.

**Pull request merged**
