### PR TITLE
updating dotnet/templating build to 20171004-309

### PR DESCRIPTION
**Pull request by seancpeters**

### CODE REVIEW

**Comment by livarcocc** [comment]
@seancpeters Is this the one in VS as well?

**Comment by seancpeters** [comment]
The changes being pushed here are for CLI-specific telemetry only. There should be no changes from dotnet/templating which affect VS.

**Comment by livarcocc** [comment]
Ok, just to be 100% sure, and these are targeting the 15.5?

**Comment by seancpeters** [comment]
This is for the telemetry changes requested by @wli3. This is the branch they should go in, yes?

**Pull request closed without merging**
