### PR TITLE
Update the runtime version to 2.1.0-preview3-26322-05

### PR DESCRIPTION
**Pull request by livarcocc**

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test Alpine3.6 x64 Debug Build
@dotnet-bot Test CentOS7.1 x64 Debug Build
@dotnet-bot Test RHEL7.2 x64 Release Build
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by livarcocc** [comment]
@danmosemsft can you investigate these failures? It has been failing consistently for CentOS and RHEL. So, there may be a runtime regression here.

**Comment by danmosemsft** [comment]
Looks like myget issues?

https://ci.dot.net/job/dotnet_cli/job/master/job/release_rhel7.2_x64_prtest/2462/consoleFull#-1173838752d31e50d-1517-49fc-92b3-2ca637122019

It cannot find this file on myget
Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file specified

but also

https://ci.dot.net/job/dotnet_cli/job/master/job/release_rhel7.2_x64_prtest/2462/consoleFull#-1173838752d31e50d-1517-49fc-92b3-2ca637122019

    15>D:\j\workspace\release_windo---f861f43b\bin\2\win-x64\dotnet\sdk\2.1.300-preview3-008393\NuGet.targets(114,5): error : Failed to retrieve information about 'Microsoft.Extensions.Configuration.Binder' from remote source 'https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/microsoft.extensions.configuration.binder/index.json'. [D:\j\workspace\release_windo---f861f43b\bin\3\win-x64\test\dotnet-new.Tests\TemplateRestoresAndBuildsWithoutWarningsC#_mvc\temp\temp.csproj] [D:\j\workspace\release_windo---f861f43b\build\test\RunTest.proj]

**Comment by livarcocc** [comment]
@danmosemsft The only change here is the runtime and this has been happening for the past two days while we have other PRs all turning green.

**Pull request closed without merging**
