### PR TITLE
Insert Roslyn 15.9 into CLI 2.1.5xx

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
@jaredpar @dotnet/roslyn-infrastructure This version is from https://github.com/dotnet/versions/blob/master/build-info/dotnet/roslyn/dev15.9p1/Latest_Packages.txt 

Please double check that this is the right build to be inserting into the CLI that will ship with 15.9 and approve the PR if so.

**Comment by jaredpar** [comment]
@jasonmalinowski, @jmarolf how can I see what the last insertion into 15.9 was?

**Comment by nguerrera** [comment]
@jasonmalinowski, @jmarolf Ping.

**Comment by eerhardt** [comment]
Does this have the fix for https://github.com/dotnet/roslyn/issues/29371 in it? We are hitting that bug in ML.NET.

**Comment by livarcocc** [comment]
No idea. I will let @jaredpar comment on that.

**Comment by agocke** [comment]
Based on that build having commit  45b371170fd8f9f3e9c14ea2a71d17db9469f8b7, it looks like it does contain the change.

**Pull request merged**
