### PR TITLE
Add nunit project and item templates to bundle

### PR DESCRIPTION
**Pull request by halex2005**
Changes according to https://github.com/nunit/dotnet-new-nunit/issues/13#issuecomment-400116922

### CODE REVIEW

**Comment by livarcocc** [comment]
We should add a nunit test for this: https://github.com/dotnet/cli/blob/5a5a245658726357525e61217728ae7303ec0e5b/test/dotnet-new.Tests/GivenThatIWantANewAppWithSpecifiedType.cs#L22.

**Comment by halex2005** [comment]
I've added tests for `dotnet new nunit`

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by halex2005** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by halex2005** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by halex2005** [comment]
All checks now passed. Ugh, why does Ubuntu x64 tests are so unstable?)

**Pull request merged**
