### PR TITLE
Update LKG SDK to 3.0.100-preview-009722.

### PR DESCRIPTION
**Pull request by peterhuene**
Updating LKG SDK to `3.0.100-preview-009722`.

### CODE REVIEW

**Comment by peterhuene** [comment]
Do we also need to bump `MicrosoftNETTestSdkPackageVersion`?

**Comment by peterhuene** [comment]
Looks like a breaking change from https://github.com/Microsoft/vstest/commit/3decca033435d70f6380c77214aeac38fb54911b#diff-52f82ee32b0efbc63d40285e884e47d1.

Previously, the test was expecting a `NETSDK1004` due to the assets file not existing.  Instead, the build invocation succeeds with the "skipped running tests" message.

**Comment by livarcocc** [comment]
@peterhuene yes. The test needs to be updated. It was updated in 2.1.5xx but that hasn't showed up on this branch yet.

**Comment by nguerrera** [comment]
Let me try cherry picking this onto the merge.

**Comment by nguerrera** [comment]
I've added the LKG update to https://github.com/dotnet/cli/pull/10203, in theory this should have consistent versions and tests.

**Comment by peterhuene** [comment]
Closing in favor of the merge PR.

**Pull request closed without merging**
