### PR TITLE
teach fsharp to dotnet new

### PR DESCRIPTION
**Pull request by enricosada**
ref #647 

this pr target branch `rel/1.0.0`

- add `--lang <LANG> [C#|F#]` with alias (csharp/cs)
- renamed template directories, format `LANGUAGE-TEMPLATE`
- add `--type <TYPE>`

    default to first template of the language ( `Console` )

- show all avaiable types, if invalid argument `--type`

    ```
    Unrecognized type: notexists
    Avaiable types for F# :
    - Console
    ```

### CODE REVIEW

**Comment by enricosada** [comment]
ok ready, same code as old pr

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX Release Build please.

**Comment by enricosada** [comment]
thx @piotrpMSFT

**Comment by dsyme** [comment]
Very nice!!!

**Comment by enricosada** [comment]
@dsyme next one is better with `dotnet new fsharp/console` .
If #1118 is ok (i hope), than also `dotnet new console` ( setting a global `DOTNET_DEFAULT_LANGUAGE` env var )

**Comment by dsyme** [comment]
Awesome!! Can you give a URL, e.g. 

    dotnet new http://github.com/suaveio/suave-templates/great-web-template

**Comment by enricosada** [comment]
@dsyme atm templates are embeeded in `dotnet-new.exe` as resources.
It's a nice idea, can you join #655 ( it's about dotnet new improvements )? i can for sure implement it if it's approved

**Pull request merged**
