### PR TITLE
Update postinstall script for OS X PKG

### LINKED ISSUE #786: `dotnet restore` doesn't work on a fresh osx install
Under the 1.0.1-beta-23516 (I believe, `dotnet` says 1.0.0, but running dnu restore references this version in the project.lock.json file) version of the dotnet tools, dotnet restore doesn't work:

```
~  ᐅ dotnet restore
No executable found matching command "dotnet-restore"
```

There is a `dotnet-restore` executable located in `/usr/local/share/dotnet/bin` and other dotnet commands, such as `dotnet new`, do work. `dotnet run`, doesn't work either, saying it can't find the executable `csc`.

### PR DESCRIPTION
**Pull request by blackdwarf**
Add symlink for dotnet-dnx. 

Fix #786 

/cc @brthor @Sridhar-MS

### CODE REVIEW

**Comment by brthor** [comment]
:+1:

**Comment by blackdwarf** [comment]
@dotnet-bot test Ubuntu Debug Build please

**Comment by livarcocc** [comment]
LGTM

**Comment by blackdwarf** [comment]
@dotnet-bot test Ubuntu Debug Build please

**Comment by blackdwarf** [comment]
Closing this one, will add a new PR to fix more symlink issues.

**Pull request closed without merging**
