### PR TITLE
Merge dev/release/2.0 in to dev/repo-refactoring

### PR DESCRIPTION
**Pull request by livarcocc**
@nguerrera this was a clean merge, but please review it to be sure the patches were not messed up.

### CODE REVIEW

**Comment by nguerrera** [comment]
What is different_merge_branch? If this is a clean merge, can we just send PR from dev/release/2.0 to dev/repo-refactoring. If we need interim branches to resolve conflicts, it would be helpful to give them (or at least the merge commits) readable names.

**Comment by nguerrera** [comment]
Source changes look fine. I just don't like the commit text on the merge commit.

**Comment by livarcocc** [comment]
I can fix that, for some reason, the branch I wanted to use was not being merged properly on github.

**Comment by livarcocc** [comment]
Fixed the merge message.

**Comment by nguerrera** [comment]
@dotnet-bot test OSX10.12 x64 Release Build 

(exit code 139 from restore)

**Pull request merged**
