### PR TITLE
Link CRT into hostpolicy

### LINKED ISSUE #870: Cannot load hostpolicy.dll on Win2012R2
dotnet.exe crashes on startup on Windows 2012 Server.

``Failed to load the dll from C:\dotnet\bin\hostpolicy.dll, HRESULT:0x8007007E``

Running from cmd prompt displays an error dialog:

`The pgoram can't start because MSVCP140.dll is missing from your computer`

Error started with changes in 262274b9681b6586e01d715703a13e1098c0be1e

### LINKED ISSUE #871: Unable to run dotnet on Windows after MSI installation
> C:\dotnet\bin>dotnet
Failed to load the dll from C:\dotnet\bin\hostpolicy.dll, HRESULT: 0x8007007E
Error loading the host library from own dir: C:\dotnet\bin; Status=00000041

@schellap I think its because of your recent changes - https://github.com/dotnet/cli/pull/843

/cc @piotrpMSFT @gkhanna79

### PR DESCRIPTION
**Pull request by schellap**
Fixes #870
Fixes #871

### CODE REVIEW

**Comment by schellap** [comment]
@gkhanna79 PTAL.

/Cc @Sridhar-MS @natemcmaster @piotrpMSFT

**Comment by natemcmaster** [comment]
thx @schellap

**Comment by Sridhar-MS** [comment]
:shipit:

**Comment by gkhanna79** [comment]
LGTM

**Comment by piotrpMSFT** [comment]
@dotnet-bot test CentOS7.1 Release Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu Release Build please.

**Comment by Sridhar-MS** [comment]
I just now installed and configured docker on CI machine - http://dotnet-ci.cloudapp.net/computer/dci-ub-fbld-2/. This should unblock the ubuntu build failure.

**Comment by Sridhar-MS** [comment]
@dotnet-bot test Ubuntu Release Build please.

**Pull request merged**
