### PR TITLE
Standardize Dependencies to 23714

### LINKED ISSUE #718: Beta Release Dependencies Change and Standardization
For the beta release we will need to make changes to the dependencies in our project.jsons across the repo.

This will need to happen after the beta version of NETStandard.Library is pushed to NuGet.

1. Move all dependencies on NETStandard.Library to the beta version (Including the dotnet new template)
2. Remove NuGet.config workaround (https://github.com/dotnet/cli/issues/656)
3. Resolve any dependency conflicts presented by the MultiProjectValidator, currently we are seeing many of these. `System.Reflection.Metadata` is one such example where different versions are being used in different projects.

As a side note, conflicts presented by the MultiProjectValidator will produce a build failure in our release branch. This ensures we have no dependency stomping: 
https://github.com/dotnet/cli/issues/541

cc @piotrpMSFT @krwq @Sridhar-MS

### PR DESCRIPTION
**Pull request by brthor**
Fixes #718 
This change upgrades all references to stdlib and other framework packages to -rc2-23714.

NOTE: there was a breaking change in a package which required us to upgrade to a bleeding edge version of DNX. These changes will be a temporary measure until NuGet xplat comes in.

There are still some dependency conflicts caused by packages like Microsoft.Extensions.Logging being used in a few of the projects. Will be filing an issue to track this.

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@brthor, zip.ZIP looks like a real issue...

**Comment by brthor** [comment]
Waiting on NuGet xplat to update this.

**Comment by brthor** [comment]
[1m[31m/mnt/j/workspace/dotnet_cli/debug_ubuntu_prtest/src/Microsoft.DotNet.ProjectModel/src/Microsoft.DotNet.ProjectModel/Utilities/VersionUtility.cs(19,37): error CS0103: The name 'AssemblyLoadContext' does not exist in the current context[39m[22m

@anurse I assume this is happening because we still use stage0 for restore. Will wait on that update.

**Comment by piotrpMSFT** [comment]
Title says 715 but comments say 714. What's the target version?

**Comment by brthor** [comment]
@piotrpMSFT Moved to 23715 this morning to see if it would unblock some issues. 

Right now waiting on NuGet in stage0 to try out 23714 again.
23714 is our target version

**Comment by brthor** [comment]
cc @anurse @ericstj

Hitting the following error here. Seems like it could be either NuGet or a packaging bug? any ideas here? 

16:37:34 error: System.IO.FileSystem 4.0.1-rc2-23714 provides a compile-time reference assembly for System.IO.FileSystem on .NETPlatform,Version=v5.4, but there is no run-time assembly compatible with osx.10.10-x64

**Comment by brthor** [comment]
Trying adding Microsoft.NETCore.Targets to see if it might help resolve these issues.

**Comment by brthor** [comment]
@dotnet-bot test this please

**Comment by anurse** [comment]
> Hitting the following error here. Seems like it could be either NuGet or a packaging bug? any ideas here?
> 
> 16:37:34 error: System.IO.FileSystem 4.0.1-rc2-23714 provides a compile-time reference assembly for System.IO.FileSystem on .NETPlatform,Version=v5.4, but there is no run-time assembly compatible with osx.10.10-x64

That's the problem #900 was supposed to fix. We're still seeing some issues. @davidfowl and I are on that.

**Comment by piotrpMSFT** [comment]
@brthor if this is intended to go into 1.0, please retarget the PR to rel/1.0.0.

**Pull request closed without merging**
