### PR TITLE
Insert NuGet Build 4.6.0-preview2-4706 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.6.0-preview2-4706 into cli master branch

### CODE REVIEW

**Comment by jainaashish** [comment]
@johnbeisner please merge this PR. and corresponding SDK PR.

**Review by rohit21agrawal — APPROVED** [review]

**Comment by johnbeisner** [comment]
@rohit21agrawal 
Please look at the PackagePath' for correctness.

**Comment by rohit21agrawal** [comment]
looks good @johnbeisner

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by emgarten** [comment]
It looks like `Microsoft.DotNet.Cli.Test.Tests.GivenDotnetTestBuildsAndRunsTestFromCsprojForMultipleTFM.MStestMultiTFM` is failing. Is this related to nuget?

**Comment by livarcocc** [comment]
@emgarten maybe, this change only contains a new NuGet and this has been failing consistently, so, right now, we have to assume that this is being caused by NuGet, though we don't understand why.

**Comment by johnbeisner** [comment]
@emgarten 
@livarcocc 
The working theory is that the CLI tests cannot run in parallel with the new NuGet version. We have detected an incorrect generation of a 'project.assets.json' for the failed test.

**Comment by emgarten** [comment]
@johnbeisner what was incorrect in the assets file? Restore in parallel should be safe, but if you aren't setting the packages directory and are re-using package ids between tests you could see some issues.

**Comment by johnbeisner** [comment]
@emgarten 
From an 'XunitCore.csproj' with 3 package references:
   "Microsoft.NET.Test.Sdk" Version="$(MicrosoftNETTestSdkPackageVersion)"
   "xunit" Version="2.2.0-beta4-build3444"
  "xunit.runner.visualstudio" Version="2.2.0-beta4-build1194"
The generated
xunitcore.csproj.nuget.g.props is missing the "xunit.runner.visualstudio" reference.

**Comment by johnbeisner** [comment]
@rohit21agrawal 
@emgarten
I will hold the local machine for reference.

**Comment by johnbeisner** [comment]
@emgarten
Additionally, the xunitcore.deps.json and the project.assets.json look to be incorrectly generated. Test = Microsoft.DotNet.Cli.Test.Tests.GivenDotnettestBuildsAndRunsTestfromCsproj.XunitSingleTFM

**Comment by emgarten** [comment]
I'll run these tests locally and try

**Comment by emgarten** [comment]
Closing this PR. I'll create another with the latest bits.

The PR for the fix blocking this one is here: https://github.com/NuGet/NuGet.Client/pull/1874

**Pull request closed without merging**
