### PR TITLE
bump f# sdk package version (rel/1.0.1)

### PR DESCRIPTION
**Pull request by enricosada**
This update the bundled F# Sdk to latest version

### CODE REVIEW

**Comment by enricosada** [comment]
the version `-bundled` of `FSharp.NET.Sdk` package contains only `Sdk` dir.

fix https://github.com/dotnet/cli/issues/4976

**Comment by livarcocc** [comment]
@enricosada did you manage to run validation (a full build of the CLI) before submitting these changes?

**Comment by enricosada** [comment]
@livarcocc of `release/2.0.0` yes. 
the branch `rel/1.0.1` doesnt build (is red, and locally too doesnt build).
The change is the same of rel/2.0.0.

Obv i tried locally manually changing the sdk targets, with latest `1.0.3-rc4-004973` binaries.

same targets on 1.0.1 works ok (i have the netcorecli-fsc test suite for that)

I'd like to test it, but build is red.

**Comment by livarcocc** [comment]
Can you try a build against rel/1.0.0?

**Comment by enricosada** [comment]
closed source bits cannot go on myget? stupid question i know but is annoying :(

**Comment by enricosada** [comment]
@livarcocc yes, sure, 1 minute, i'll try `rel/1.0.0`

**Comment by enricosada** [comment]
@livarcocc https://github.com/dotnet/cli/pull/6470 and building locally meanwhile (it take a bit on my notebook)

**Comment by livarcocc** [comment]
thanks @enricosada, let me know how it goes.

**Comment by enricosada** [comment]
@livarcocc so locally the build of f# sdks files to right place works.

but build fail later with

```
23:58:59.815     1>Target "SetupNuGetPackagesArchiveInputsOutputs: (TargetId:59)" in file "E:\github\cli\build\compile\Microsoft.DotNet.Cli.LzmaArchive.targets" from project "E:\github\cli\build.proj" (target "GetNuGetPackagesArchive" depends on it):
                   Using "GenerateNuGetPackagesArchiveVersion" task from assembly "E:\github\cli\/build_projects/dotnet-cli-build/bin/dotnet-cli-build.dll".
                   Task "GenerateNuGetPackagesArchiveVersion" (TaskId:39)
                     Task Parameter:ToolPath=E:\github\cli\/artifacts/win10-x64/stage2 (TaskId:39)
                     Task Parameter:SDKVersion=1.0.0-alpha-20170224-6 (TaskId:39)
                     > E:\github\cli\/artifacts/win10-x64/stage2\dotnet.exe new mvc -au Individual -f netcoreapp1.0 --no-tools --debug:ephemeral-hive -n TempProject -o "C:\Users\e.sada\AppData\Local\Temp\tmpEC5A.tmp\mvc"  (TaskId:39)
                     The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found. (TaskId:39)
                      (TaskId:39)
                       - Check application dependencies and target a framework version installed at: (TaskId:39)
                      (TaskId:39)
                           E:\github\cli\artifacts\win10-x64\stage2\shared\Microsoft.NETCore.App (TaskId:39)
                      (TaskId:39)
                       - The following versions are installed: (TaskId:39)
                      (TaskId:39)
                           1.0.4 (TaskId:39)
                      (TaskId:39)
                       - Alternatively, install the framework version '1.1.1'. (TaskId:39)
                      (TaskId:39)
23:59:04.087     1>E:\github\cli\build\compile\Microsoft.DotNet.Cli.LzmaArchive.targets(123,7): error MSB6006: "dotnet.exe" exited with code -2147450749. [E:\github\cli\build.proj]
23:59:04.564     1>C:\Users\e.sada\AppData\Local\Temp\tmpEC5A.tmp\mvc\TempProject.csproj : error MSB4025: The project file could not be loaded. Could not find file 'C:\Users\e.sada\AppData\Local\Temp\tmpEC5A.tmp\mvc\TempProject.csproj'.  C:\Users\e.sada\AppData\Local\Temp\tmpEC5A.tmp\mvc\TempProject.csproj [E:\github\cli\build.proj]
                   Done executing task "GenerateNuGetPackagesArchiveVersion" -- FAILED. (TaskId:39)
23:59:04.564     1>Done building target "SetupNuGetPackagesArchiveInputsOutputs" in project "build.proj" -- FAILED.: (TargetId:59)
23:59:04.564     1>Done Building Project "E:\github\cli\build.proj" (Compile target(s)) -- FAILED.
```

that's the closed bit?
but is different than ci error..

How we can proceed @livarcocc ?

**Comment by livarcocc** [comment]
That's not the closed bit. I am going to merge this and monitor VSO.

**Comment by enricosada** [comment]
Thx @livarcocc , doing a `git clean -xdf && build /t:Compile` (maybe i had some temp files, but i dont think so).

Please merge when necessary. these commit are good for both sdk 1.0 and sdk 2.0-preview1

**Comment by enricosada** [comment]
@livarcocc anyway as smoke test

```
dotnet new console -lang f#
dotnet restore
dotnet run
```

is enough

**Comment by livarcocc** [comment]
I kicked off a build without your changes, to make sure we have no other issues, then I will merge this one and monitor.

**Comment by enricosada** [comment]
After the clean, now locally build and works correctly (`1.0.0-rc4-004919`).
So works for me locally @livarcocc  :D

**Comment by cartermp** [comment]
Thanks, @enricosada!

**Pull request merged**
