### PR TITLE
Insert NuGet Build 4.7.0-rtm.5081 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.7.0-rtm.5081 into cli release/2.1.2xx branch

### CODE REVIEW

**Comment by livarcocc** [comment]
@rohit21agrawal what is the VS PR and bug number for this?

**Comment by livarcocc** [comment]
@mishra14 what is the VS PR and bug number for this?

**Comment by rohit21agrawal** [comment]
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/115738 
Bug linked in PR.

**Comment by rohit21agrawal** [comment]
@livarcocc PR is merged

**Pull request merged**
