### PR TITLE
Update dotnet manpages for Unix

### PR DESCRIPTION
**Pull request by kasper3**
skip ci please

Manual update, until https://github.com/dotnet/cli/issues/7291 is addressed.

Steps that I followed using Bash on Ubuntu 14:

```bash
# after cloning cli repo
cd cli/Documentation/manpages/sdk
dpkg -i https://github.com/jgm/pandoc/releases/download/2.1.3/pandoc-2.1.3-1-amd64.deb
sudo dpkg -i https://github.com/jgm/pandoc/releases/download/2.1.3/pandoc-2.1.3-1-amd64.deb
wget https://github.com/jgm/pandoc/releases/download/2.1.3/pandoc-2.1.3-1-amd64.deb
sudo apt install libgmp10
sudo dpkg -i pandoc-2.1.3-1-amd64.deb
wget https://github.com/dotnet/docs/archive/master.zip
unzip master.zip

ls docs-master/docs/core/tools/dotnet*.md | while read -r line; do pandoc -s -t man "$line" -o "$(basename ${line%.md}.1)"; done

# then only committed dotnet*.1 files
git add dotnet*1
git commit -m "Update dotnet manpages for Unix"
```

PowerShell solution is given here https://github.com/dotnet/docs/issues/2791#issuecomment-372707046. Either one of these scripts can be integrated to CI in such a way that when someone merges to master in dotnet/docs repo with changes in `dotnet-docs/docs/core/tools` directory, dotnet-bot creates a PR in this repo.

### CODE REVIEW

**Comment by nguerrera** [comment]
Thank you for providing the steps used.

**Comment by omajid** [comment]
This is awesome! :+1: 

I ran 

- `wget https://raw.githubusercontent.com/kasper3/cli/0177a2156cff54220aa5269bcd0a8cb891a35d5c/Documentation/manpages/sdk/dotnet.1`
- `man ./dotnet.1`

image


I think we need some [pre-processing of the .md files](https://github.com/dotnet/docs/issues/2791#issuecomment-319442451) or post-processing of man pages.

**Comment by kasper3** [comment]
@omajid fixed. I checked `man ./dotnet.1` and it looks fine.

**Comment by kasper3** [comment]
Pandoc seems to have extension points using custom filters http://pandoc.org/filters.html, written in ruby, perl or python and use it as `pandoc -F ./myhandler -t man dotnet.md -o dotnet.1`. .NET binding project seem quite old https://github.com/t0yv0/libpandoc-dotnet.

**Comment by nguerrera** [comment]
For 2.1, maybe we just fix up the formatting manually? Pains me to say that, but I don't want this to derail into getting nothing done for 2.1.

**Comment by omajid** [comment]
After playing around a bit, I think I have something decent working, without any manual modifications (but see the filter file below).

This what `man ./dotnet.1` now looks like:

image


This is the command I used to generate the man pages:

    ls docs-master/docs/core/tools/dotnet*.md | while read -r line; do pandoc -s -t man -V section=1 -V header=".NET Core" --column=500 --filter man-pandoc-filter "$line" -o "$(basename ${line%.md}.1)"; done

The filter file (a giant hack!) is: https://gist.github.com/omajid/22c4bbfdd6a8e235b2248f168f8523d0

This was done with:

$ pandoc --version
pandoc 1.19.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.1, highlighting-kate 0.6.4
Default user data directory: /home/omajid/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
$ rpm -q python3-pandocfilters 
python3-pandocfilters-1.4.1-2.fc27.noarch

**Comment by kasper3** [comment]
@nguerrera, my two cents: merge this PR as these files were last updated two years ago, so this changeset is already much better than what we have in master. Subsequent improvements can be done in follow up PRs and we can think of how to automate this process in #7291.

**Comment by nguerrera** [comment]
I might have been convinced but @omajid's pages look so nice. 😁

Here's what I'd like:

1. Commit that gist along with an update-man-pages.sh that repeats the whole generation.

2. Use update-man-pages.sh to regenerate the files.

3. Commit the updated files.

Can you do that? I'd say we can last several releases if we're down to one button to update the man pages with a script.

Thanks so much to both of you for pushing on this!

**Comment by omajid** [comment]
@kasper3 feel free to update this PR and include the filter file. Could you please add a .NET Foundation license header to it as well?

**Comment by kasper3** [comment]
@omajid, thanks for the filter script.

@nguerrera, I have added tool scripts in a separate directory and update the docs. There is a readme in tools dir with usage example https://github.com/dotnet/cli/blob/ee24d81648b6792c7249c5044f6218f59b89e49c/Documentation/manpages/tool

**Comment by kasper3** [comment]
> $ pandoc --version
> pandoc 1.19.1

@omajid, a lot has improved in their core since then. I have updated readme with note to promote using latest version of pandoc under Ubuntu example, how to quickly install it from packages available for different distros at https://github.com/jgm/pandoc/releases.

**Comment by omajid** [comment]
> a lot has improved in their core since then.

That's a good point. In fact, looking at the release notes, it seems like one of issues I was seeing (bad links) was fixed in 2.0.5: "omit internal links (#4136). That is, just print the link text without the URL.".

And thanks again everyone for getting this resolved before 2.1!

**Pull request merged**
