### PR TITLE
Update NuGet Version to 3.5.0-beta2-1451

### PR DESCRIPTION
**Pull request by zhili1208**

### CODE REVIEW

**Comment by rrelyea** [comment]
Addressing https://github.com/NuGet/Home/issues/2929
@piotrpMSFT  | @eerhardt - the CI seems messed up. My guess is that you folks will need to rerun and merge as appropriate. Perhaps it is failing due to the know CLI issue (to remove use of that API)?

**Comment by eerhardt** [comment]
Not sure if #3356 was merged before or after this was opened.  So let's run the whole thing again now just to be sure.

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Comment by eerhardt** [comment]
I'm seeing the following restore downgrade warnings:

```
19:52:22 warn : Detected package downgrade: NETStandard.Library from 1.6.0-rc3-24208-04 to 1.6.0-rc3-24207-03 
19:52:22 warn :  update-dependencies (>= 1.0.0) -> NuGet.Versioning (>= 3.5.0-beta2-1451) -> NETStandard.Library (>= 1.6.0-rc3-24208-04) 
19:52:22 warn :  update-dependencies (>= 1.0.0) -> NETStandard.Library (>= 1.6.0-rc3-24207-03)
```

But that package and version is definitely on the cli-deps feed:  https://dotnet.myget.org/feed/cli-deps/package/nuget/NETStandard.Library/1.6.0-rc3-24208-04

**Comment by zhili1208** [comment]
I think CLI should be updated to 1.6.0-rc3-24208-04, nuget is already using 24208-04, but update-dependencies is using 1.6.0-rc3-24207-03 here

**Comment by eerhardt** [comment]
Closing as this change went in with #3455

**Pull request closed without merging**
