### PR TITLE
Support overriding strong naming key path with environment variable.

### PR DESCRIPTION
**Pull request by cesarbs**
This is similar to what DNX_BUILD_KEY_FILE does in DNX.

cc @anurse @davidfowl

### CODE REVIEW

**Comment by weshaggard** [comment]
For my own curiosity what is the scenario you would need to use an environment variable to override this path?

**Comment by anurse** [comment]
Open source project wants to strong-name using a private key on the CI. This is for NuGet, specifically, since they use a Microsoft-internal key and have difficulties OSS signing. Regardless of that specific scenario, I think the use-case is valid.

**Comment by anurse** [comment]
Looks good. Builds are failing, not sure if that's directly related to you though. @brthor this seems related to the E2E test you added? Maybe some packages vanished from a feed?

**Comment by cesarbs** [comment]
@anurse Builds are failing due to missing packages. Is there a way I can restart them?

**Comment by anurse** [comment]
@dotnet-bot test this please

**Comment by anurse** [comment]
^-- that's how to restart a PR build btw @cesarbs  ;)

**Comment by cesarbs** [comment]
Thanks!

**Comment by anurse** [comment]
```
10:15:29 Restore failed
10:15:29 No space left on device
```

http://www.sadtrombone.com/

@Sridhar-MS

**Comment by cesarbs** [comment]
@dotnet-bot test this please

**Comment by anurse** [comment]
:shipit:

**Pull request closed without merging**
