### PR TITLE
First pass at cleaning up the global properties files

### PR DESCRIPTION
**Pull request by jgoshi**
If the global properties file had a clear purpose (like FileExtensions.props) I left it. Otherwise if a global property is only used in one file I moved it back to that file. This moves in the direction of a global props file only containing properties that are shared.

@piotrpMSFT @eerhardt @livarcocc @krwq @jonsequitur

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
I'll leave this open so others can take a look. My only concern was that `<channel>` is now pretty burried. We may want to extract out a `<branchinfo>` concept to ease the creation of new branches. However, this will impact branding and versioning as well so we can leave it to another change.

**Comment by eerhardt** [comment]
> We may want to extract out a <branchinfo> concept to ease the creation of new branches.

Agreed. We had BranchInfo.props now. Should we just leave channel and branch name in that file?

**Comment by jgoshi** [comment]
I'll put BranchInfo.props back

**Comment by jgoshi** [comment]
test Debian8.2 x64 Debug Build

**Pull request merged**
