### PR TITLE
Stop Skipping Dotnet pack

### PR DESCRIPTION
**Pull request by brthor**
Looks like this got resolved.

### CODE REVIEW

**Comment by krwq** [comment]
That's what I told you in one of the previous conversation :smile: Nobody remembers to remove skip so that's why I prefer when build is failing when something is broken and not pretending it's green by skipping - broken is broken (although if we split that image on the main page into each command and e2e separately then probably everyone would be happy)

**Comment by brthor** [comment]
Yeah we need that @krwq

**Comment by piotrpMSFT** [comment]
@krwq, the build must stay green because we can't have everyone have all the context in their heads. This skip should have referenced an issue and that issue should have been assigned to a milestone. The build is not our task tracking system.

**Comment by piotrpMSFT** [comment]
To be a bit more clear, it did not reference an issue that would have removed the skip. We should have had the skip point to this issue, and this one call out it's blocked by 333.

**Comment by brthor** [comment]
Thanks @piotrpMSFT, to be clear, you would like to see workarounds in general have a separate issue than the underlying issues?

**Comment by piotrpMSFT** [comment]
Yes.

**Pull request merged**
