### PR TITLE
Remove Path.Combine() from Directory.GetFiles

### PR DESCRIPTION
**Pull request by schellap**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2109)

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by schellap** [comment]
@dotnet-bot test this please

**Comment by schellap** [comment]
@piotrpMSFT, did you see this PR? Can you pls merge if it looks good?

**Comment by schellap** [comment]
Fixes #2110

**Pull request closed without merging**
