### PR TITLE
Update core-setup and re-enable all sdk resolver tests

### LINKED ISSUE #9851: Get hostfxr for msbuild resolver from 2.1.x branch
For 2.1.5xx / VS 15.9 preview, we are going to use a one-off build of hostfxr with https://github.com/dotnet/core-setup/pull/4301

For RTM, we should be getting the change to 2.1.x servicing.

### PR DESCRIPTION
**Pull request by nguerrera**
* Update core-setup to 2.1.5-servicing-26911-03
* Re-unify hostfxr.dll used by resolver and runtime
* Re-enable all sdk resolver tests on all platforms

Fix #9851

### CODE REVIEW

**Comment by nguerrera** [comment]
@Pilichie for approval for 2.1.500 / 15.9. This is just taking the resolver from the matching runtime that ships with 2.1.500.

**Comment by nguerrera** [comment]
@Pilchie

**Comment by Pilchie** [comment]
Approved for 15.9 - thanks @nguerrera .

**Comment by nguerrera** [comment]
Rebased since code review to resolve merge conflicts. Only impact on diff is that instead of replacing 2.1.3 with 2.1.5-servicing, we're replacing with 2.1.4 with 2.1.5-servcing.

I will merge this when green.

**Comment by nguerrera** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build 

Exit code 139 (segfault) on a handful of tests. Have we been seeing this?

**Pull request merged**
