### PR TITLE
Update our sln file to reference our csproj files

### PR DESCRIPTION
**Pull request by jgoshi**
@piotrpMSFT @livarcocc @krwq @blackdwarf

### CODE REVIEW

**Comment by jgoshi** [comment]
test Ubuntu x64 Release Build

**Comment by jgoshi** [comment]
test OSX x64 Release Build

**Comment by jgoshi** [comment]
@MattGertz Can I get approval for this one? This is something that shouldn’t affect us at all. I’m just changing our sln file to reference the csproj files now that we did the work to migrate all the project.json stuff to csproj in our repo.

**Comment by MattGertz** [comment]
Sounds good.

**Pull request merged**
