### PR TITLE
Revert "update NuGet to 4.0.0-rc2 build (#4802)"

### PR DESCRIPTION
**Pull request by livarcocc**
This reverts commit 0bafbd061ee622bd21c58964e79466f4aa845c91.

I will bring it back again soon, once I can work through all the breaking changes.

@piotrpMSFT @jgoshi @krwq @rrelyea @emgarten

### CODE REVIEW

**Comment by livarcocc** [comment]
@MattGertz can you approve? I would like to merge once it turns green to unblock our CI and builds. I will then working on bringing the change back in. I don't fully understand how it passed CI in the first place, but now I know what to look for regarding failures.

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by piotrpMSFT** [comment]
@mattgertz this is blocking all other CLI PRs at the moment. @srivatsn will be backing up @MattGertz for some time and may be able to help as well.

**Comment by srivatsn** [comment]
Approving for Matt.

**Pull request merged**
