### PR TITLE
Package bundled version props in to a VS insertion nupkg

### PR DESCRIPTION
**Pull request by nguerrera**
This puts Microsoft.NETCoreSdk.BundledVersions.props in to a .nupkg that VS can consume to augment its copy of MSBuild.

I also refactored a bit to isolate knowledge of the specific file to one target and have everything else operate on the directory. This would make it easier to add another such file and makes the code a little easier to follow.

@livarcocc @dsplaisted

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot test Fedora24 x64 Release Build

**Comment by nguerrera** [comment]
@dotnet-bot test Fedora24 x64 Release Build

**Comment by nguerrera** [comment]
@livarcocc @eerhardt Can we take Fedora24 out of CI? It's failing 95% of the time with that download issue.

**Comment by eerhardt** [comment]
Why isn't this added to our exsting nupkg that VS consumes?

**Comment by nguerrera** [comment]
I was going to do it that way, but there are two existing nupkgs, one for x86 and one for x64. I found it less confusing to put this architecture agnostic stuff in to a separate package.

**Comment by nguerrera** [comment]
If we stuff it in the architecture-specific package, the VS authoring side will be pulling non-x86/x64 specific assets out of a package/directory with x86/x64 in its name, which will look wrong and need a comment to explain why it's by design. This sets up MSBuildExtensions as a sibling of x86 and x64 which makes things more obviously correct IMHO.

**Comment by nguerrera** [comment]
New rule. When I see a test fail 3 times and all we do is, the test is getting disabled.

https://github.com/dotnet/cli/issues/6144

**Comment by nguerrera** [comment]
> As an administrator, you may still merge this pull request.

I will do this if I have sign-off and only Fedora24 fails with download error. I've submitted #6145 to turn Fedora24 off and filed #6146 to turn it back on.

**Comment by nguerrera** [comment]
@eerhardt Are you OK with the explanation on why I made a separate package? Anything else you'd like changed?

@livarcocc Please review.

**Comment by nguerrera** [comment]
@dotnet-bot Test Windows_NT x64 Release Build please

**Comment by eerhardt** [comment]
> @eerhardt Are you OK with the explanation on why I made a separate package? Anything else you'd like changed?

Sorry.  Yes, thank you for the good explanation. It makes sense to me.

**Pull request merged**
