### PR TITLE
Remove CommandResolutionStrategy

### PR DESCRIPTION
**Pull request by wli3**

### CODE REVIEW

**Comment by wli3** [comment]
@dotnet-bot test fedora.27 x64 Debug Build

**Comment by wli3** [comment]
@livarcocc @eerhardt do you have context why the field `CommandResolutionStrategy` is there? And it is passed down to the end but no one reads it and does anything using it.

I want to move CLI command resolution to dotnet.dll and this field made every coupled together.

I try to separate the concern of 
What to execute - command resolution, should be in dotnet.dll, it is very specific to dotnet CLI
How to execute - this is a util, it can be shared since it is just a wrapper around Processinfo 

The wall I hit of moving everything to dotnet.dll is we have some tests in net46 that rely on command.cs (how to execute) and net46 cannot reference netcoreapp3.0

**Comment by wli3** [comment]
@dotnet-bot test fedora.27 x64 Debug Build

**Comment by dsplaisted** [comment]
👍 for removing useless, confusing code :-)

**Pull request merged**
