### PR TITLE
Move Debian Package Tools to packaging folder

### PR DESCRIPTION
**Pull request by brthor**
Moved package_tool dir from the root to packaging/debian.

Changed the package script to account for this.

Fixes #267 
/cc @anurse @Sridhar-MS

### CODE REVIEW

**Comment by livarcocc** [comment]
LGTM

**Comment by brthor** [comment]
Thanks @livarcocc Just going to wait on the builds to make sure the package is still getting produced correctly.

**Comment by Sridhar-MS** [comment]
:shipit:

**Comment by brthor** [comment]
Looks like permissions on the files didn't get set right.

**Comment by davidfowl** [comment]
DO IT

**Comment by anurse** [comment]
@brthor It looks like the root `debian_config.json` didn't get removed in this PR. Assuming that's not needed any more, can you just remove that? (No PR needed IMHO)

**Comment by brthor** [comment]
Thanks for pointing this out @anurse, will delete!

**Pull request merged**
