### PR TITLE
Skip DefaultProxy resolution code if an exception is thrown

### PR DESCRIPTION
**Pull request by ghost**
Addresses: https://github.com/dotnet/cli/issues/6747

### CODE REVIEW

**Comment by johnbeisner** [comment]
@guardrex 
@artisticcheese
@scottaddie

**Comment by guardrex** [comment]
@artisticcheese Are u able? I don't have a Nano handy. If not, no worries, I'll spin one up and see what happens.

**Comment by artisticcheese** [comment]
@guardrex 
I don't understand how GitHub works, where is updated script which I can check?

**Comment by guardrex** [comment]
@artisticcheese Get it from his branch: https://github.com/johnbeisner/cli/blob/5c620978c124c928862f3221ad6be9bbf4eab802/scripts/obtain/dotnet-install.ps1

**Comment by artisticcheese** [comment]
Yes, this works

```
PS C:\> Invoke-WebRequest https://raw.githubusercontent.com/johnbeisner/cli/5c620978c124c928862f3221ad6be9bbf4eab802/scripts/obtain/dotnet-install.ps1 -OutFile a.ps1
PS C:\> .\a.ps1
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.4/dotnet-sdk-1.0.4-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.4/dotnet-sdk-1.0.4-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.4/dotnet-dev-win-x64.1.0.4.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.4/dotnet-dev-win-x64.1.0.4.zip
dotnet-install: Adding to current process PATH: "C:\Users\ContainerAdministrator\AppData\Local\Microsoft\dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
PS C:\>

```

**Comment by guardrex** [comment]
@johnbeisner Your commit is to *master*, so it will go live shortly, correct? I just need to know if we need to block the Nano Server tutorial topic update all the way to the 2.1 release.

**Comment by johnbeisner** [comment]
When it goes 'live' it will be updated at: 
* https://dot.net/v1/dotnet-install.sh (bash, UNIX)
* https://dot.net/v1/dotnet-install.ps1 (powershell, Windows)

**Comment by johnbeisner** [comment]
@dotnet/dotnet-cli 
Can someone approve these changes please.

**Comment by johnbeisner** [comment]
@dotnet/dotnet-cli
Can someone approve these changes please.

**Review by livarcocc — APPROVED** [review]

**Pull request merged**
