### PR TITLE
Mlorbetske dev/mlorbe/update template engine for1x

### PR DESCRIPTION
**Pull request by KevinRansom**
Set the unix permissions of the scripts.

### CODE REVIEW

**Comment by livarcocc** [comment]
@MattGertz This has already been approved. Just moved to a new PR.

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build
@dotnet-bot Test Windows_NT x64 Release Build
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu16.04 x64 Debug Build

**Comment by KevinRansom** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by livarcocc** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by livarcocc** [comment]
@dotnet-bot test Windows_NT x64 Release Build please

**Pull request merged**
