### PR TITLE
Run dotnet new to prime cache at the end of installer

### PR DESCRIPTION
**Pull request by wli3**
#6370
Windows installer will have cmd.exe windows pop up. Will fix it in an separate branch #6425

debian installer change will be a different pull request

### CODE REVIEW

**Comment by wli3** [comment]
#6425

**Comment by wli3** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build

**Comment by wli3** [comment]
@dotnet-bot test OSX10.12 x64 Release Build

**Comment by wli3** [comment]
@MattGertz Could you review this change?

**Comment by eerhardt** [comment]
How will customers get notice about telemetry opt out?

**Comment by wli3** [comment]
@eerhardt since currently "dotnet new" is "on your face". It is not a problem so far...

The cmd.exe window will popup in the middle of installation, and telemetry notification is there.
windows_pop_up

I will add telemetry notification somewhere after I fix the popup window

**Comment by eerhardt** [comment]
Does that popup window also come up for macOS?

**Comment by wli3** [comment]
@eerhardt no, I need to fix this.

It is require for preview-1? I can revert my mac change for now

**Comment by eerhardt** [comment]
> It is required for preview-1?

@livarcocc ?  

I'm not sure.  I'm no lawyer, and don't know when we do and when we don't have to ensure users know about the telemetry we are collecting from them.

**Comment by wli3** [comment]
@eerhardt Just removed mac change. Only Windows' installer change is there

**Comment by wli3** [comment]
@dotnet-bot test Linux x64 Release Build  OpenSUSE42.1 x64 Debug Build Ubuntu x64 Release Build

**Comment by wli3** [comment]
@dotnet-bot OpenSUSE42.1 x64 Debug Build 
@dotnet-bot Ubuntu x64 Release Build

**Comment by wli3** [comment]
@dotnet-bot test OpenSUSE42.1 x64 Debug Build
@dotnet-bot test Ubuntu x64 Release Build

**Pull request merged**
