### PR TITLE
Add more xlf files for new strings

### PR DESCRIPTION
**Pull request by livarcocc**
@piotrpMSFT @krwq @jgoshi @nguerrera

### CODE REVIEW

**Comment by krwq** [comment]
Are we gonna be updating xlf files by hand from now on? If yes should we also remove .cs files with localizable strings? If not should we check in the tool?

**Comment by livarcocc** [comment]
This is porting a change that went into rel when we branched for preview4, before rel became preview5.

**Comment by livarcocc** [comment]
@nguerrera Can you answer @krwq's questions?

**Comment by piotrpMSFT** [comment]
ignore the xlf files at the moment. We will be using the .cs files. These are part of the yet-to-be-built localization pipeline.

**Comment by piotrpMSFT** [comment]
@srivatsn @MattGertz

**Comment by nguerrera** [comment]
Just to expand on what @piotrpMSFT  said:

* The .cs files will be converted to .resx, which will generate new .cs files which will actually fetch strings from the right resource. 
* The .resx will be synced with the .xlf files automatically
* The dev team will edit the .resx files only
* The loc team will edit the. xlf files only
* Satellite assemblies will be built from .xlf files (via in-build conversion to translated resx).

**Comment by nguerrera** [comment]
But we don't have the pipeline yet, so we still need the current .cs files.

**Pull request merged**
