### PR TITLE
Add tests for RestoreUseStaticGraphEvaluation

### PR DESCRIPTION
**Pull request by wli3**
Part of https://github.com/dotnet/sdk/issues/11420
Wait after 5/26 need https://github.com/dotnet/toolset/pull/4583 get in first and then update stage 0

### CODE REVIEW

**Comment by wli3** [comment]
@joeloff could you review this? the branch is open right?

**Comment by joeloff** [comment]
Branch should be open.

Regarding the tests, it seems that regardless of the property, the results are expected to be the same. Are there situations where not using the static evaluation would produce different results, or is this purely for perf gains?

**Comment by wli3** [comment]
It is part of https://github.com/dotnet/toolset/pull/4583

It is porting https://github.com/dotnet/sdk/pull/10794

@ViktorHofer for the question

**Comment by ViktorHofer** [comment]
Purely perf gain. The NuGet cache, dgspec and other files should be the same with both modes. cc @jeffkl who wrote the static graph restore feature.

**Comment by wli3** [comment]
good to merge ? @joeloff

**Review by joeloff — APPROVED** [review]

**Pull request merged**
