### PR TITLE
Clean up product naming

### PR DESCRIPTION
**Pull request by richlander**
I'd like to adopt new naming for the product. This is the proposal.

- .NET Core - .NET Core runtime and framework
- .NET Core SDK - .NET Core + CLI tools

/cc @blackdwarf, @piotrpMSFT, @Petermarcu

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2147)

### CODE REVIEW

**Comment by blackdwarf** [comment]
Actually, I've made it similar as a proposal in: #2057. Here it is:

* .NET Core Runtime 
   * Shared runtime + host
* .NET Core Software Development Kit (SDK)
   * .NET Core Runtime vx.0.0.y
   * .NET Core CLI Tools va.0.0.b
   * In the future:
       * Docs
       * Samples

**Comment by richlander** [comment]
Yes, very similar. I'd like to stick to what I wrote.

I'm also going to try to remove "shared fx" from our vocab.

**Comment by blackdwarf** [comment]
@richlander any reason why yours is better? .NET Core on its own doesn't tell people what it is. .NET Core Runtime tells it cleanly.

**Comment by richlander** [comment]
Two reasons:

- I don't want to use "runtime" in the name.
- I don't want to talk about "Shared runtime + host" as top-level concerns.

**Comment by piotrpMSFT** [comment]
This should update installer branding as well

**Comment by richlander** [comment]
Yes. I thought we'd start with this and then move to the product as a second step. Doesn't need to all go into one PR.

**Comment by richlander** [comment]
I showed this to @coolcsh. I got the :+1: .

**Comment by blackdwarf** [comment]
@richlander the "shared runtime" above was just a pointer as to what it is in it. It is a singular unit. But ok.

**Comment by richlander** [comment]
@blackdwarf - I do want to stop using the term "shared runtime", so that's the other issue. I do like how you describe the SDK, however (minus the 'runtime' term).

**Comment by blackdwarf** [comment]
@richlander whatever makes people don't doubt which link to click to get bits.

**Comment by akoeplinger** [comment]
Hmm, using `.NET Core` as the moniker for the shared fx overloads an already overloaded term even more imho. 

I'd also add at least one sentence that tells people what they can actually _do_ with each package, e.g. run apps vs develop apps. Otherwise I'm left scratching my head which one I should pick. @blackdwarf's description is better in this case.

**Comment by blackdwarf** [comment]
@akoeplinger for sure, we need descs on these. But, as it used to be said *nomen est omen* thus I think  being explicit about the "runtime" bit is better.

**Comment by Petermarcu** [comment]
I'm going to commit this for now. We can update again if there are any more changes needed.

**Pull request merged**
