### PR TITLE
Update to no-timestamp packages and adjust feeds and cache accordingly

### PR DESCRIPTION
**Pull request by mlorbetske**
Switches to no-timestamp ASP.NET packages & aligns the templates, LZMA & package store

### CODE REVIEW

**Comment by livarcocc** [comment]
@MattGertz for approval. This will be blocking for ASP.NET as soon as we integrate the latest build from Core-Setup.

https://github.com/dotnet/cli/issues/6516

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by mlorbetske** [comment]
@dotnet-bot test OpenSUSE42.1 x64 Debug Build please

**Comment by mlorbetske** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by livarcocc** [comment]
@mlorbetske should we turn off telemetry from dotnet new? It has been extremely painful to get CI through due to this issue. Or maybe have new respect the telemetry flag to not even pass the delegate in that case? Meanwhile, we should file an issue about this in the runtime, about hitting a segfault problem when using delegates.

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build
@dotnet-bot Test Ubuntu16.04 x64 Debug Build

**Comment by mlorbetske** [comment]
Preparing a change that disables the telemetry. For clarity, the opt-out is honored, it's just checked inside the delegate.

**Comment by mlorbetske** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build please

**Comment by livarcocc** [comment]
I know, I was wondering if we can check the flag before we invoke the delegate. I suspect that would prevent the segfault.

**Comment by mlorbetske** [comment]
Let's chat more about it later today - from the issue on CoreFX, setting the env var unblocked the person who was hitting it, so I don't know that moving the check outside would really help.

**Pull request merged**
