### PR TITLE
Update branding to 2.1.200

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
@crummel Getting XliffTasks package not found suddenly. Related to cli-deps cleanup? I didn't think we would be getting it from there. cc @tannergooding

**Comment by nguerrera** [comment]
I think I see the issue. It's on dotnet-core and was also on cli-deps.  We removed dotnet-core feed and didn't notice until cli-deps went away

**Comment by nguerrera** [comment]
We need to be putting it on the blob feed.

**Comment by crummel** [comment]
Feeds should be updated now.
@dotnet-bot test this please

**Comment by crummel** [comment]
@nguerrera From the Windows builds, does `xunit.netcore.extensions` also need to be on the feed?

**Comment by nguerrera** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

(xunit.netcore.extensions should be restored)

**Comment by nguerrera** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build

**Pull request merged**
