### PR TITLE
Update known-issues.md

### PR DESCRIPTION
**Pull request by blackdwarf**
Add the section on Win7 timeout issue.

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/1862)

### CODE REVIEW

**Comment by blackdwarf** [comment]
@dotnet-bot test OSX x64 Release Build please

**Comment by blackdwarf** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please

**Comment by blackdwarf** [comment]
@dotnet-bot test Windows_2016 x86 Debug Build please

**Comment by anurse** [comment]
Still relevant?

**Comment by blackdwarf** [comment]
@anurse last I checked, it was.

**Comment by anurse** [comment]
So merge it :)

**Pull request merged**
