### PR TITLE
Upgrade stdlib and enable crossgen

### PR DESCRIPTION
**Pull request by davidfowl**

### CODE REVIEW

**Comment by davidfowl** [comment]
@dotnet-bot build Windows_NT Release

**Comment by davidfowl** [comment]
@dotnet-bot test Windows Release please

**Comment by davidfowl** [comment]
@dotnet-bot test Ubuntu Release please

**Comment by davidfowl** [comment]
@dotnet-bot test Ubuntu Release please

**Comment by davidfowl** [comment]
@dotnet-bot test this

**Comment by davidfowl** [comment]
@dotnet-bot test this please

**Comment by davidfowl** [comment]
@dotnet-bot test Ubuntu please

**Comment by davidfowl** [comment]
@dotnet-bot test Ubuntu Debug please

**Comment by anurse** [comment]
Does this supersede mine?

**Comment by davidfowl** [comment]
@anurse yes, but it's failing release builds on xplat or something.

**Pull request merged**
