### PR TITLE
Update to NuGet 517

### PR DESCRIPTION
**Pull request by anurse**
Fixes https://github.com/dotnet/cli/issues/964

/cc @schellap @Sridhar-MS @brthor @piotrpMSFT @davidfowl

### CODE REVIEW

**Comment by anurse** [comment]
FYI: I'm just going to merge this when the build finishes, since we're so short on time and this is so trivial.

**Comment by anurse** [comment]
@dotnet-bot test OSX Debug Build please

**Comment by anurse** [comment]
If the OSX Debug Build fails again, please wait for my confirmation before restarting it. I'm going to try taking a look at the Workspace and see why this failure is happening

**Comment by anurse** [comment]
@dotnet-bot test OSX Debug Build please

**Comment by anurse** [comment]
@dotnet-bot test CentOS7.1 Debug Build please

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX Debug Build please.

**Comment by anurse** [comment]
OSX Failure is the intermittent incremental publish bug again.

**Comment by anurse** [comment]
@dotnet-bot test OSX Debug Build please

**Comment by piotrpMSFT** [comment]
@cdmihai here's another one. Jenkins log link: http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/debug_osx_prtest/861/

@anurse shall we merge?

**Comment by anurse** [comment]
@piotrpMSFT absolutely!

**Comment by piotrpMSFT** [comment]
Merged despite CI failure tracked by #965

**Comment by schellap** [comment]
Thank you for the quick turnaround. This is also in the latest cli, right?

**Pull request merged**
