### PR TITLE
Fixed spelling mistakes in documentation

### PR DESCRIPTION
**Pull request by revlucio**
Found them while browsing the latest commits. Maybe Markdown files should be put through a spelling checker?

### CODE REVIEW

**Comment by revlucio** [comment]
@dotnet-bot test this please

**Comment by revlucio** [comment]
As this change is only to documentation does it matter that no test results were found in the builds?

**Comment by blackdwarf** [comment]
@dotnet-bot test this please

**Comment by blackdwarf** [comment]
@revlucio we like to keep even the docs "green" on build passes. :) Also, I've edited the canonical scenarios a lot, can you rebase and redo? Thanks for catching the errors, those things creep up pretty easily!

**Comment by revlucio** [comment]
@blackdwarf all done now

**Comment by piotrpMSFT** [comment]
@blackdwarf please verify the fixes and merge

**Comment by blackdwarf** [comment]
LGTM

**Pull request merged**
