### PR TITLE
Updating CoreFx, CoreClr, Roslyn, CoreSetup to rc3-24210-10, rc3-24210-10, beta1-20160610-04, rc3-3004459-00 respectively

### PR DESCRIPTION
**Pull request by eerhardt**

### CODE REVIEW

**Comment by eerhardt** [comment]
@joshfree

**Comment by eerhardt** [comment]
This also updates Microsoft.DiaSymReader to 1.0.8-rc2-60610-01.

That should be all of CLI's dependencies outside of NuGet.  We will bring in the new NuGet dependency separately when it is ready.

**Comment by eerhardt** [comment]
test Debian8.2 x64 Debug Build
test OpenSUSE13.2 x64 Debug Build
test RHEL7.2 x64 Release Build
test Ubuntu16.04 x64 Debug Build

MyGet doesn't have the new SharedFX ready to consume yet. Trying again and hoping its ready.

**Comment by eerhardt** [comment]
test Debian8.2 x64 Debug Build
test OpenSUSE13.2 x64 Debug Build
test RHEL7.2 x64 Release Build
test Ubuntu16.04 x64 Debug Build

**Comment by joshfree** [comment]
test Debian8.2 x64 Debug Build
test OpenSUSE13.2 x64 Debug Build
test RHEL7.2 x64 Release Build
test Ubuntu16.04 x64 Debug Build

**Comment by joshfree** [comment]
test OSX x64 Release Build

**Comment by joshfree** [comment]
OS X failed for the same issue; appears to be a os x test build issue.  looking.

**Comment by ellismg** [comment]
There are 9 failures in the build tests.

One example (looks like a project that was not expected to rebuild, rebuilt.):

```
    Microsoft.DotNet.Tools.Builder.Tests.ProjectToProjectDependenciesIncrementalTest.TestIncrementalBuildOfDependencyGraph(testIdentifer: "1", projectToTouch: "L0", expectedRebuiltProjects: ["L0"]) [FAIL]
      Expected string "Telemetry is: Enabled
Project L22 (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project L12 (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project L21 (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project L11 (.NETStandard,Version=v1.5) will be compiled because inputs were modified
	/Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/test/dotnet-build.Tests/bin/Release/netcoreapp1.0/TestIncrementalBuildOfDependencyGraph1/TestProjectToProjectDependencies/src/L21/bin/Debug/netstandard1.5/L21.dll
Compiling L11 for .NETStandard,Version=v1.5
Running /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/artifacts/osx.10.11-x64/stage2/dotnet /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/artifacts/osx.10.11-x64/stage2/sdk/1.0.0-preview2-003038/csc.dll -noconfig @/Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/test/dotnet-build.Tests/bin/Release/netcoreapp1.0/TestIncrementalBuildOfDependencyGraph1/TestProjectToProjectDependencies/src/L11/obj/Debug/netstandard1.5/dotnet-compile-csc.rsp
Process ID: 42496
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.7440629
Project L0 (.NETCoreApp,Version=v1.0) will be compiled because dependencies changed
Compiling L0 for .NETCoreApp,Version=v1.0
Running /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/artifacts/osx.10.11-x64/stage2/dotnet /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/artifacts/osx.10.11-x64/stage2/sdk/1.0.0-preview2-003038/csc.dll -noconfig @/Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/test/dotnet-build.Tests/bin/Release/netcoreapp1.0/TestIncrementalBuildOfDependencyGraph1/TestProjectToProjectDependencies/src/L0/obj/Debug/netcoreapp1.0/dotnet-compile-csc.rsp
Process ID: 42510
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:02.0761298
 
" to contain "Project L0 (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.".
```

**Comment by ellismg** [comment]
@brthor @eerhardt I'm not super familiar with the code here so I can't be of much help aside from looking at the build log and noting that yes, we do have real failures instead of just Jenkins issues.

**Comment by eerhardt** [comment]
test OSX x64 Release Build

**Comment by eerhardt** [comment]
test OSX x64 Release Build

**Comment by eerhardt** [comment]
test OSX x64 Release Build

Seriously - it is failing for a different flaky reason each time.  Sometimes it is failing exit code 138 during building the tests themselves.  This last time it failed with exit code 138 while building a project running a perf test.

**Comment by eerhardt** [comment]
Finally.

**Comment by joshfree** [comment]
Interesting.  I saw this fail for the same reason 2x in a row and assumed it was a CLI defect on mac.  Is there any tracking issues for this?

**Comment by eerhardt** [comment]
> I saw this fail for the same reason 2x in a row and assumed it was a CLI defect on mac. Is there any tracking issues for this?

Of the 5 times it failed, 3 of them were because `dotnet build` failed with `Exit Code 138`, which is tracked in https://github.com/dotnet/coreclr/issues/5672

132 - http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0-preview2/job/release_osx_x64_prtest/132/

```
Expected command to pass but it did not. File Name: /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/artifacts/osx.10.11-x64/stage2/dotnet Arguments: restore Exit Code: 138 StdOut: StdErr:
```

136 - http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0-preview2/job/release_osx_x64_prtest/136/console

```
07:39:52 info : Building tests: Microsoft.DotNet.Compiler.Common.Tests
07:39:52 EC       >]   /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/artifacts/osx.10.11-x64/stage2/dotnet "build" "--configuration" "Release"
07:39:52 EC       <] IL]  /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/test/Microsoft.DotNet.Compiler.Common.Tests> /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/artifacts/osx.10.11-x64/stage2/dotnet "build" "--configuration" "Release" exited with 138
```

137 - http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0-preview2/job/release_osx_x64_prtest/137/

```
Expected command to pass but it did not. File Name: /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/artifacts/osx.10.11-x64/stage2/dotnet Arguments: --verbose build "/Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0-preview2/release_osx_x64_prtest/test/Performance/bin/Release/netcoreapp1.0/IncrementalSkipAllNoDependenciesInGraph_TwoTargetGraphLarge/PerformanceTestProjects/TwoTargetGraphLarge/TwoTargetLargeP0" Exit Code: 138 StdOut: StdErr:
```

The two times last night it failed that you and @ellismg investigated was because of flaky incremental tests in `dotnet-build.Tests`. I thought we had an issue tracking it, but I can't seem to find it at the moment.  @cdmihai may know.

You could tell they were flaky because there was a different number that failed each time:

133 - http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0-preview2/job/release_osx_x64_prtest/133/console

```
21:42:40 === TEST EXECUTION SUMMARY ===
21:42:40    dotnet-build.Tests  Total: 70, Errors: 0, Failed: 7, Skipped: 1, Time: 64.643s
```

134 - http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0-preview2/job/release_osx_x64_prtest/134/console

```
22:04:12 === TEST EXECUTION SUMMARY ===
22:04:12    dotnet-build.Tests  Total: 70, Errors: 0, Failed: 9, Skipped: 1, Time: 59.848s
```

**Pull request merged**
