### PR TITLE
Update THIRD-PARTY-NOTICES

### LINKED ISSUE #4854: No mention of NuGet.Client in ThirdPartyNotices.txt
A built cli includes various dlls built from from NuGet.Client project. It also includes a LICENSE file and a ThirdPartyNotices.txt. There's no mention of NuGet.Client or its license (Apache 2.0) in either the main LICENSE file or in ThirdPartyNotices.txt.

### PR DESCRIPTION
**Pull request by blackdwarf**
Adding Nuget.Client notices.

Fixes #4854

### CODE REVIEW

**Comment by blackdwarf** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by leecow** [comment]
LGTM

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by piotrpMSFT** [comment]
@MattGertz FYI, approving this documentation-only change. It addresses the 3rd-party notices doc in the product, but does not have a behavioral impact.

**Comment by blackdwarf** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by blackdwarf** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by blackdwarf** [comment]
OK, I will merge this now since it is finally green.

**Pull request merged**
