### PR TITLE
MSBuild 15.8.108

### PR DESCRIPTION
**Pull request by AndyGerlicher**
This is the version currently in `lab/d15.8stg` for Preview 4.

### CODE REVIEW

**Comment by livarcocc** [comment]
CI failed to find the msbuild package. Kicking tests off again in case this was a timing issue.

@dotnet-bot Test this please.

**Comment by livarcocc** [comment]
@AndyGerlicher it is still failing to find packages. Can you take a look?

**Comment by livarcocc** [comment]
cc @rainersigwald as well

**Comment by rainersigwald** [comment]
I just released to myget, let's try again in half an hour or so.

**Comment by AndyGerlicher** [comment]
@dotnet-bot test this please

**Pull request closed without merging**
