### PR TITLE
Merge the JsonTextReader change from rel/1.0.0 to feature/msbuild

### PR DESCRIPTION
**Pull request by livarcocc**
Use JsonTextReader in DependencyContextJsonReader  (#3972)

Using low level JsonTextReader in DependencyContextJsonReader class for performance reasons

cc @piotrpMSFT @brthor @eerhardt

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build please.

**Comment by eerhardt** [comment]
:shipit:

**Comment by brthor** [comment]
:shipit:

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build please.
@dotnet-bot Test Ubuntu x64 Release Build please.

**Pull request merged**
