### PR TITLE
Re-enable solution building tests

### LINKED ISSUE #5205: Re-enable solution building tests
The solution building portion of these tests have been disabled
1. WhenValidProjectIsPassedTheSlnBuilds
2. MigrateAndBuild

Tracking an issue on the sdk
https://github.com/dotnet/sdk/issues/545

### PR DESCRIPTION
**Pull request by jgoshi**
@piotrpMSFT @livarcocc @eerhardt @krwq @jonsequitur 

Fixes #5205

### CODE REVIEW

**Comment by jgoshi** [comment]
test RHEL7.2 x64 Release Build

**Comment by eerhardt** [comment]
> RHEL7.2 x64 Release Build

What was the failure?  It wasn't that the test .sln failed to build, was it?

**Comment by jgoshi** [comment]
No, it was that intermittent failure with the CLI retrying stuff and it happened too fast or something like that. Unrelated to this.

**Comment by jgoshi** [comment]
This is a test only change. Can someone approve? Then I can merge it.

**Pull request merged**
