### PR TITLE
zh-Hans misspelling "推出" to "退出"

### PR DESCRIPTION
**Pull request by lenew**
fix misspelling "推出" to "退出"

### CODE REVIEW

**Comment by livarcocc** [comment]
@tmeschter what is the process here regarding loc?

**Comment by tmeschter** [comment]
Tagging @janbaltus for awareness of the translation issue.

@livarcocc @lenew We're not able to take direct community contributions to translations at this time--if we merge in this change it would likely be overwritten during the next translation pass.

**Comment by livarcocc** [comment]
I am closing this PR as we can't take it here, but @janbaltus should be able to absorb the change.

**Comment by livarcocc** [comment]
@lenew thanks for the PR and for bringing this to our attention.

**Comment by janbaltus** [comment]
Soource string got updated https://github.com/lenew/cli/commit/42f97b002b37488ae5f2a67925516d4cde249566
and target translation will be replaced by new translation

**Pull request closed without merging**
