### PR TITLE
Removing the code to generate the lzma archive

### PR DESCRIPTION
**Pull request by livarcocc**
Removing the code to generate the lzma archive and instead download it from the asp.net location.

This won't work until we have template updates, but a template update should be the only thing we need.

Fixes https://github.com/dotnet/cli/issues/6459.

@dotnet/dotnet-cli @mlorbetske

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE42.1 x64 Debug Build

**Comment by livarcocc** [comment]
@Pilchie @ManishJayaswal for approval.

**Comment by ManishJayaswal** [comment]
Approved pending one more CR and tests passing.

**Comment by livarcocc** [comment]
@dotnet-bot Test Debian8.2 x64 Debug Build
@dotnet-bot Test OpenSUSE42.1 x64 Debug Build
@dotnet-bot Test Ubuntu16.04 x64 Debug Build

**Pull request merged**
