### PR TITLE
Updating dependencies from last known good builds

### PR DESCRIPTION
**Pull request by eerhardt**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2162)

### CODE REVIEW

**Comment by joshfree** [comment]
/cc @leecow @Petermarcu 

this is our rc2 'escrow build'; we'll want to send this to partner teams to consume once a CLI/SharedFX is built.

**Comment by davidfowl** [comment]
So 931 now?

**Comment by joshfree** [comment]
@davidfowl 23930.00 is _so yesterday_ :)

**Comment by eerhardt** [comment]
> So 931 now?

@davidfowl - taking these new CoreFX builds is mostly-automated using https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/update-dependencies.ps1.  The script needs some enhancements, especially putting the new build # in the PR title and commit message. Those changes will be coming...

**Comment by dagood** [comment]
Status note: I'm waiting for a build to show up that has clients for all platforms then I'm going to be making PRs for corefx/coreclr/wcf/buildtools to take it up.

**Comment by eerhardt** [comment]
@dagood - just an FYI.  -beta-002173+ will have this change in it.

**Comment by dagood** [comment]
Thanks. Looks like 002173 is a complete set now, so those PRs will be up shortly.

**Pull request merged**
