### PR TITLE
Reverse installation order of shared frameworks

### PR DESCRIPTION
**Pull request by piotrpMSFT**
@livarcocc @jinujoseph

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@MattGertz this was approved over email due to cascading effects. We'll merge once validated.

**Comment by MattGertz** [comment]
Yep, understood.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu16.04 x64 Debug Build

**Pull request merged**
