### PR TITLE
Update to new msbuild

### PR DESCRIPTION
**Pull request by nguerrera**
Update to version of msbuild that includes microsoft/msbuild#935

@eerhardt

### CODE REVIEW

**Comment by eerhardt** [comment]
Looks like crossgen is failing.

```
CROSSGEN : error : Could not load file or assembly 'System.Runtime.Serialization.Xml, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/mnt/resource/j/workspace/dotnet_cli/feature_msbuild/debug_debian8.2_x64_prtest/build.proj]
10:13:27          CROSSGEN : error : compilation failed for "/mnt/resource/j/workspace/dotnet_cli/feature_msbuild/debug_debian8.2_x64_prtest/artifacts/debian.8-x64/stage1/sdk/1.0.0-featmsbuild-003465/Microsoft.Build.Tasks.Core.dll" (0x80131621) [/mnt/resource/j/workspace/dotnet_cli/feature_msbuild/debug_debian8.2_x64_prtest/build.proj]
```

@rainersigwald @jeffkl - did you guys recently add a dependency to 'System.Runtime.Serialization.Xml'?

@nguerrera - we will have to add this dependency to `src\redist` for now, until MSBuild's dependencies are specified correctly in their nupkgs.

**Comment by nguerrera** [comment]
@eerhardt TFW someone answers your question before you finished typing it. Thanks. ;)

**Comment by jeffkl** [comment]
@eerhardt yes https://github.com/Microsoft/msbuild/commit/968209a4663869c1568c5c66dc25676ce7a174fa#diff-759f47333f5676b6ec0bfa21d2e9edf0R32

We used to have a tool running that generated the dependencies automatically in our NUSPECs but I'm told it stopped working for us.  Do you just need a new NuGet package with this dependency?

**Comment by eerhardt** [comment]
> We used to have a tool running that generated the dependencies automatically in our NUSPECs but I'm told it stopped working for us. Do you just need a new NuGet package with this dependency?

Yes, that would help!  Nick should be able to workaround it, as specified above.  But we wouldn't need the workaround if the dependencies were correct in the .nupkg.

**Comment by nguerrera** [comment]
@eerhardt @jeffkl I pushed the workaround with 2accc15. I can revert it if we get a new build that specifies the dep.

**Comment by jeffkl** [comment]
Okay I'll be working on the MSBuild 15.1 packages after I finish the 14.0 packages...

**Comment by nguerrera** [comment]
@eerhardt Green now. Good to merge?

**Comment by nguerrera** [comment]
I've filed tracking bugs to get the nupkg fixed (Microsoft/msbuild#942) and the workaround reverted (#4084).

**Comment by eerhardt** [comment]
:shipit:

**Pull request merged**
