### PR TITLE
Publishing a single project to avoid recompiling

### PR DESCRIPTION
**Pull request by davidfowl**
- Let nuget deal with unifying versions across differnet projects.

### CODE REVIEW

**Comment by davidfowl** [comment]
@dotnet-bot test this please

**Comment by davidfowl** [comment]
This needs more changes to publish to work.

**Comment by schellap** [comment]
@davidfowl I am seeing the same error in our Ubuntu Release CI as well in . Is this a known issue?

09:07:02 error: Could not find file '/tmp/NuGet/TempCache/78945f8e-ed97-4522-b91a-b2ac5b252de7/ny4gq2yc.cz3'.
09:07:03 Build step 'Execute shell' marked build as failure

See CI job for this  PR https://github.com/dotnet/corert/pull/717
http://dotnet-ci.cloudapp.net/job/dotnet_corert/job/release_prtest_ubuntu/795/console

**Comment by davidfowl** [comment]
No idea. Might be a nuget cache thing...

**Pull request closed without merging**
