### PR TITLE
Insert NuGet Build 4.3.1-rtm-5850 into cli 1.1

### PR DESCRIPTION
**Pull request by zivkan**

### CODE REVIEW

**Comment by peterhuene** [comment]
@zivkan it looks like this failed CI because we can't find NuGet packages with `4.3.1-rtm-5850`.  Have all of them been published?

**Comment by zivkan** [comment]
MyGet has some inconsistencies. Their website says the 4.3.1-rtm-5850 version exists on their website, but their v3 feed does not, which is why restore fails. I'll see what I can do to fix it.

**Comment by zivkan** [comment]
I was looking in the wrong place. Problem actually appears to be that this old branch didn't add the nuget-build myget feed as a package source. I added it to nuget.config, so we'll see if the builds are more successful this time.

**Comment by peterhuene** [comment]
Ignore the RHEL failure for now; there's a known infrastructure problem that's preventing that leg from running.

**Pull request merged**
