### PR TITLE
Dev/merge internal 05142020/release/3.1.2xx

### PR DESCRIPTION
**Pull request by wli3**

### CODE REVIEW

**Comment by wli3** [comment]
@wtgodbe a package is not published?
```
error NU1603: sdks depends on Microsoft.NET.Build.Extensions (>= 3.1.202-servicing.20223.9) but Microsoft.NET.Build.Extensions 3.1.202-servicing.20223.9 was not found. An approximate best match of Microsoft.NET.Build.Extensions 3.1.300-preview.20160.11 was resolved.
```

**Comment by wtgodbe** [comment]
Ah, it's because we only pushed all the 3.1.104 nonshipping packages to the public transport feed, but not the 3.1.202 nonshipping packages. The missing package here is from dotnet/sdk, which explains why we can't find it. I'll push the stuff now, then we can hit retry and everything should work.

**Comment by wtgodbe** [comment]
CC @mmitche about the above

**Comment by wtgodbe** [comment]
@wli3 why did you undo my branding change? It needs to be part of this PR. Branding and code merge need to be done concurrently

**Pull request merged**
