### PR TITLE
MSBuild 15.7.124 for 2.1.3xx

### PR DESCRIPTION
**Pull request by rainersigwald**
Supersedes #8854.

This version has https://github.com/Microsoft/msbuild/pull/3126, which should resolve the TF problems from #8854.

### CODE REVIEW

**Comment by livarcocc** [comment]
Should this go in 15.7 (release/2.1.2xx) as well? Or there we should maintain 108?

**Comment by rainersigwald** [comment]
@dotnet-bot test this please

(Forgot to make sure our packages were pushed to MyGet before starting this, sorry)

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build

**Comment by livarcocc** [comment]
@rainersigwald @dsplaisted there is some regression here affecting windows only. There are two tests who have been failing complaining about a direct reference to M.NC.App. Can you guys check? It is happening on the other msbuild insertion on 2.1.2xx as well.

**Comment by dsplaisted** [comment]
The actual test failure is that the output doesn't contain strings such as `Total tests: 3. Passed: 2. Failed: 1. Skipped: 0.`.  I'm not sure if the warning about the direct reference is related.

**Comment by rainersigwald** [comment]
The failure is due to https://github.com/Microsoft/vstest/issues/1503. Basically, the test infrastructure assumed that writes to stdout from the test-runner process would be piped all the way out through the top-level `dotnet` invocation, but that's not true any more--because the process may have been launched by a long-lived worker node that has no stdout.

There's a workaround: set `MSBUILDNODEWINDOW`, which keeps MSBuild from starting the worker nodes disconnected, and use `/nr:false` to ensure that tests never connect to a preexisting worker node. I propose to apply that now and take vstest fix before release.

**Comment by rainersigwald** [comment]
I see a couple of options:
* just break test :disappointed:
* revert node reuse :disappointed:
* figure out a smaller change msbuild-side to plumb stdout through again (not sure how easy this would be)
* just fix VSTest (they're saying they did this on purpose to colorize output, which isn't good)

**Comment by rainersigwald** [comment]
Just pushed a change that goes with option 3: a new escape hatch + opting into it here. It won't work until https://github.com/Microsoft/msbuild/pull/3130 is merged + packaged, but is that something you're amenable to @livarcocc?

**Comment by rainersigwald** [comment]
this does work e2e, by the way (manually injected new MSBuild into CLI built from this CL):

```
s:\work\vstestmulti>dotnet msbuild /version
Microsoft (R) Build Engine version 15.7.123.48545 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

15.7.123.48545
s:\work\vstestmulti>dotnet test
s:\work\vstestmulti\VSTestDesktopAndNetCore.csproj : warning NU1604: Project dependency Microsoft.NET.Test.Sdk does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
Build started, please wait...
s:\work\vstestmulti\VSTestDesktopAndNetCore.csproj : warning NU1604: Project dependency Microsoft.NET.Test.Sdk does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
s:\work\vstestmulti\VSTestDesktopAndNetCore.csproj : warning NU1604: Project dependency Microsoft.NET.Test.Sdk does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
Build completed.

Test run for s:\work\vstestmulti\bin\Debug\net46\VSTestDesktopAndNetCore.dll(.NETFramework,Version=v4.6)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0-preview-20180221-13
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   VSTestFailTest
Error Message:
 Assert.Fail failed.
Stack Trace:
   at TestNamespace.VSTestTests.VSTestFailTest() in s:\work\vstestmulti\Tests.cs:line 19


Total tests: 3. Passed: 2. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 1.7360 Seconds
Test run for s:\work\vstestmulti\bin\Debug\netcoreapp2.1\VSTestDesktopAndNetCore.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0-preview-20180221-13
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   VSTestFailTest
Error Message:
 Assert.Fail failed.
Stack Trace:
   at TestNamespace.VSTestTests.VSTestFailTest() in s:\work\vstestmulti\Tests.cs:line 19

Failed   VSTestFailTestNetCoreApp
Error Message:
 Assert.Fail failed.
Stack Trace:
   at TestNamespace.VSTestTests.VSTestFailTestNetCoreApp() in s:\work\vstestmulti\Tests.cs:line 31


Total tests: 3. Passed: 1. Failed: 2. Skipped: 0.
Test Run Failed.
Test execution time: 1.6528 Seconds
```

**Comment by AndyGerlicher** [comment]
The updated MSBuild has an updated NuGet reference in the resolver. Had to pull in the NuGet insertion that went into 2.1.2xx to match MSBuild's assembly version to avoid a crossgen failure.

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Windows_NT_ES x64 Debug Build please

**Pull request merged**
