### PR TITLE
Update to SetupCrossgen 186 - Coherence 25661

### PR DESCRIPTION
**Pull request by mlorbetske**
@mikeharder 

@SteveSandersonMS this does not update to `-final` packages yet, the next build will

### CODE REVIEW

**Comment by mlorbetske** [comment]
@dotnet-bot test OpenSUSE42.1 x64 Debug Build please
@dotnet-bot test Windows_NT x64 Release Build please
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please

**Comment by livarcocc** [comment]
@MattGertz Flow of dependencies into the CLI.

**Pull request merged**
