### PR TITLE
Add null check for Environment.GetEnvironmentVariable

### PR DESCRIPTION
**Pull request by wli3**

### CODE REVIEW

**Comment by wli3** [comment]
Other than put a stick on my screen "CHECK NULL on GetEnvironmentVariable", what do you think is a better way to prevent it in the future? Will C#8 null check detect that?

**Comment by wli3** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by wli3** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build

**Comment by wli3** [comment]
@livarcocc 

the socket issue is still happening

https://ci.dot.net/job/dotnet_cli/job/release_2.1.3xx/job/release_rhel7.2_x64_prtest/187/testReport/junit/(root)/(empty)/Microsoft_DotNet_New_Tests_GivenThatIWantANewAppWithSpecifiedType_TemplateRestoresAndBuildsWithoutWarnings_language___C____projectType___mvc___skipSpaWebpackSteps__False_/

https://ci.dot.net/job/dotnet_cli/job/release_2.1.3xx/job/debug_centos7.1_x64_prtest/195/testReport/junit/(root)/(empty)/Microsoft_DotNet_New_Tests_GivenThatIWantANewAppWithSpecifiedType_TemplateRestoresAndBuildsWithoutWarnings_language___C____projectType___mvc___skipSpaWebpackSteps__False_/

**Comment by wli3** [comment]
I have a rhel7 machine. Let me keep running until i get binlog with the error

**Comment by wli3** [comment]
@dotnet-bot test OSX10.12 x64 Release Build

**Comment by wli3** [comment]
track the CI failure separately https://github.com/dotnet/cli/issues/8972

**Comment by wli3** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT x64 Release Build

**Comment by wli3** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build

**Comment by wli3** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by livarcocc** [comment]
Attempt turn 99

@dotnet-bot Test CentOS7.1 x64 Debug Build
@dotnet-bot Test RHEL7.2 x64 Release Build

**Comment by wli3** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build
@dotnet-bot Test RHEL7.2 x64 Release Build

**Comment by wli3** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build  same here

**Pull request merged**
