### PR TITLE
Update 3.1.1xx stage0

### PR DESCRIPTION
**Pull request by wli3**

### CODE REVIEW

**Comment by nguerrera** [comment]
Might pass now with re

**Comment by nguerrera** [comment]
Might pass now, I did merge 3.0 -> 3.1

**Comment by nguerrera** [comment]
Looks like some issues with templates targeting 3.1. Need this update to unblock the insertion of dotnet/sdk.

**Comment by wli3** [comment]
One problem is easy fix. Another looks like an actual bug in vstest, i filed it here https://github.com/microsoft/vstest/issues/2202 

Is this PR blocking the insertion to VS? If so I think we should skip the test (it flows to core-sdk already)

**Comment by nguerrera** [comment]
Let’s skip the test. We should get this in.

**Comment by nguerrera** [comment]
The 3.0 -> 3.1 merge is blocked on new stage 0. I had forgotten cli repo in that until Friday :(

**Comment by nguerrera** [comment]
(Ignore previous deleted message.)

The sdk -> cli flow needs a new stage 0

**Comment by nguerrera** [comment]
Thanks

**Pull request merged**
