### PR TITLE
Updating SDK to 2.0.0-preview3-20170721-5

### PR DESCRIPTION
**Pull request by wli3**
@dotnet/dotnet-cli

@srivatsn Flow of dependencies into the CLI

### CODE REVIEW

**Comment by livarcocc** [comment]
This will not have to be inserted into VS. Only rel/1.1.0 gets inserted.

**Comment by wli3** [comment]
@livarcocc sorry copy paste without reading..

**Comment by wli3** [comment]
@livarcocc could you approve this change?

**Comment by wli3** [comment]
@livarcocc the green button

**Pull request merged**
