### PR TITLE
Bump fsharp sdk (rel/1.0.0)

### PR DESCRIPTION
**Pull request by enricosada**
This update the bundled F# Sdk to latest version

### CODE REVIEW

**Comment by livarcocc** [comment]
@enricosada we currently have the F# tests disabled because the fsharp tool requires a 1.0 shared framework to run, which the 2.0 CLI does not carry with.

Does this PR fix this problem? If so, can you re-enable the tests to guarantee that?

**Comment by enricosada** [comment]
@livarcocc no, 2.0 require 2.0 fsc, and is not there yet. Working on it.
Will be fixed with an update who doesnt require changes there or in sdk (just a new `FSharp.NET.Sdk` package on nuget.org), but when is done, i'll send a PR to reenable tests (i remember the pain of beta/rc/preview :D)

**Comment by enricosada** [comment]
But this PR add everything is needed to be bundled in `Sdks`, so f# will work if we publish later the package (i designed exactly to be possible to update it so we can fix stuff), so please merge it if possibile.
Also it add bits needed for VS2017 /cc @cartermp

**Comment by livarcocc** [comment]
Can we we please turn the test back on then? And confirm it actually works?

**Pull request closed without merging**
