### PR TITLE
Merge rel/1.0.0 into master

### PR DESCRIPTION
**Pull request by eerhardt**
This includes all changes in rel/1.0.0 just before the "dotnet new3" integration into "dotnet new".

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
looks like run-build.sh needs to be `chmod +x`'d. Curious that Fedora didn't mind...

**Comment by eerhardt** [comment]
:rage:

**Comment by eerhardt** [comment]
@piotrpMSFT - can you check out what I did here:  https://github.com/eerhardt/cli/commit/a2c1a39d07a7f83957ba7eaf44619a162620910e And let me know what you think?

**Comment by eerhardt** [comment]
Test Ubuntu x64 Release Build

**Comment by eerhardt** [comment]
@livarcocc @piotrpMSFT  PTAL.  I'll merge this soon.

Here are the two commits of interest:

https://github.com/dotnet/cli/pull/5552/commits/a2c1a39d07a7f83957ba7eaf44619a162620910e
https://github.com/dotnet/cli/pull/5552/commits/3f3443d2dfbda5e3540d4f4518bddde2db18d684

**Pull request merged**
