### PR TITLE
restore the NoPackage switch for VSO signing build

### PR DESCRIPTION
**Pull request by anurse**
Not the prettiest. Ideally, the VSO build would just call a different target so we could have a consistent interface, but I didn't have time to hack that about. This is easier :).

/cc @livarcocc @Sridhar-MS @davidfowl

### CODE REVIEW

**Comment by anurse** [comment]
Talked to @Sridhar-MS. We're going to just remove ci_build.cmd/sh and have the VSO/Jenkins builds use command line args to the build scripts.

**Comment by livarcocc** [comment]
:shipit:

**Comment by anurse** [comment]
@Sridhar-MS do you know if I need to do anything to have Jenkins pick up the groovy changes? Do we need to wait until the changes reach `rel/1.0.0` (or worse `master`)? It's still trying to launch ci_build.cmd. I think I'll add those scripts back as a simple emulation of the old behavior until Jenkins is calling the right thing.

**Comment by Sridhar-MS** [comment]
It should be picked up once it reaches the rel/1.0.0 branch.

cc: @mmitche

**Comment by anurse** [comment]
Ok. Then I think I'd like to avoid hacking up an emulation of ci_build.sh. If it's OK with everyone else, I can merge it and be extra vigilant on the CI after merging to make sure I didn't mess anything up.

**Comment by anurse** [comment]
Fortunately, once merged it will be extremely clear where the builds are failing because they will try to invoke ci_build.cmd/sh and it won't exist :)

**Comment by Sridhar-MS** [comment]
:shipit:

**Comment by anurse** [comment]
I added help to the build scripts `./build.sh --help` and `.\build.cmd -Help` so it should be straight forward how to convert the CI definitions.

**Comment by anurse** [comment]
I'm going to merge it. It'll probably break Jenkins slightly, but who knows, maybe I'll luck out. @Sridhar-MS are you going to update the VSO definitions?

**Comment by mmitche** [comment]
Yes, your job are now based out of the rel/1.0.0 branch.  Master is not longer built.  When you decide to reenable master, we simply add that branch to a file.

**Pull request merged**
