### PR TITLE
dotnet-install should identify all RHEL 7.x as RHEL

### PR DESCRIPTION
**Pull request by omajid**
New RHEL minor versions are compatible with previous RHEL minor versions. They also replace them: all users using RHEL 7.n are migrated to RHEL 7.(n+1) by a simple yum upgrade. So just treat all RHEL 7.x version as RHEL.

This only holds true for minor versions. RHEL 7 is not compatible with RHEL 6. But since .NET Core only supports RHEL 7, this shouldn't matter.

This PR is a subset of #5255. In my tests, it is enough to build CLI on RHEL 7.3. I haven't run the tests (and I doubt they will pass), but the generated .NET Core dev image (`dotnet-dev-*.tar.gz`) can run `dotnet net && dotnet restore && dotnet run` just fine on RHEL 7.3

See also https://github.com/dotnet/core-setup/issues/1217.

I am hoping that this might be deemed suitable for inclusion for 1.0.0 given that it's a very small change compared to #5255.

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@Petermarcu who can help with issues like this one? RID compatibility is something CLI inherits from CoreCLR and we need someone more familiar with variations across OS flavors to review.

**Comment by Petermarcu** [comment]
@ellismg , You were talking to me about this. Can you take a look?

**Comment by Petermarcu** [comment]
If this is the way we want to treat RHEL we probable also make sure we have the RID graph definitions correct. We could just create a RHEL7 RID package in future releases.

@piotrpMSFT , if we have someone confirm our compatibility across these OS's, is this the right change in the CLI?

**Comment by piotrpMSFT** [comment]
@petermarcu we're pretty focused on 1.0 at the moment so we haven't had a chance to review this change. We should have some cycles to look at post-1.0 changes soon and I wanted to be sure this is one we're going to take before looking at the code delta.

**Comment by Petermarcu** [comment]
Looks like a small change and we need to accurately model Rhel. @omajid is from Redhat so I believe the statements he is making about RHEL :) It would be good if our RTM tooling accurately models RHEL but I don't know where you guys are in you lock down.

**Comment by omajid** [comment]
@Petermarcu, Hi!

> We could just create a RHEL7 RID package in future releases.

That would be perfect for us! A generic RHEL 7 RID already exists: https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md and we would really like to have be used whenever possible. @ellismg was telling me that most of .NET Core already targets the generic RHEL 7 RID (apologies if I misunderstood that).

Some other discussions on generic RHEL 7 RID include https://github.com/dotnet/corefx/issues/14089 and https://github.com/dotnet/core-setup/issues/1217. They might provide more background information on this.

**Comment by ellismg** [comment]
As @omajid says, we already have a generic rhel.7 rid and we actually use that as the rid we package all our RHEL bits for.  The runtime graph handles providing the fallback.  If we do dotnet/core-setup#1217, then we could remove the minor version rids (rhel.7.0, rhel.7.1, etc) at some point (we'd maintain them only so old tooling could consume the new packages and do the correct fallback, but maybe for 2.0.0 we aren't concerned with a 1.0.0 SDK consuming 2.0.0 bits?)

This change LGTM.  It enables pulling down the correct assets when you are on newer RHEL versions.  Since RHEL has binary compatibility, this just works.  It's identical to taking a RHEL 7.2 machine, running dotnet-install and then doing a yum update, which happens to move you to RHEL 7.3.  At that point the bits you got with dotnet-install would continue to work, you just can't use dotnet-install to get a newer version of the bits, which is frustrating.

**Comment by omajid** [comment]
Also, this issue ends up being a blocker for building almost any project that uses the `dotnet-install.sh` script from `cli`. I believe these include `cli` iteself, `NuGet.Client`, `core-setup`, and `roslyn`. All of them use this `dotnet-install` script and abort because it doesn't recognize `rhel.7.3` rid.

**Comment by omajid** [comment]
Anyone have further thoughts on this? Any chance this could be accepted into 1.0? Are there still any outstanding concerns that I can help address?

**Comment by omajid** [comment]
Hey folks. Any updates on this? Can we at least get this into master? As I said earlier, this is blocking building cli (and other projects) on RHEL 7.

**Comment by ellismg** [comment]
If we can put this in rel/1.0.0 could we at least land it in master for vNext?  @pitorpMSFT

**Comment by omajid** [comment]
I think the last message was meant to ping @piotrpMSFT

**Comment by omajid** [comment]
Thank you!

**Pull request merged**
