### PR TITLE
Fix build badges for master branch

### PR DESCRIPTION
**Pull request by krwq**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2290)

### CODE REVIEW

**Comment by krwq** [comment]
@mmitche, should the CI pick this up or is it auto ignoring non source code changes?

**Comment by mmitche** [comment]
looks like it picked up

**Comment by krwq** [comment]
sounds good :) probably lagged few minutes

**Comment by krwq** [comment]
Merging this since it is hard to break build by changing README.md but broken badges give a false feeling of "everything is ok"

**Comment by mmitche** [comment]
@krwq Looks like github was giving 503s for a bit.

**Pull request merged**
