### PR TITLE
Use the latest nuget.exe in generatenupkg script

### PR DESCRIPTION
**Pull request by kasper3**
Instead of v3.5.0-rc1, use the `v4.7.0`

### CODE REVIEW

**Comment by kasper3** [comment]
Was trying to figure out how to install 2.1 rc1 using dotnet-install, and found this low hanging fruit. Is 3.5.0-rc1 intentional?

**Comment by livarcocc** [comment]
It was the minimum/latest at the time we made that change. I was just trying to figure out if you were aware of any particular issue that this would address.

**Comment by kasper3** [comment]
It uses release version of nuget.exe instead of an old release candidate. If this is not worth updating, feel free to close the request.

**Comment by livarcocc** [comment]
Any chance you could update it to be a specific released version instead of latest? Using latest has broken us in the past, which is why we pinned to this rc one. I am fine with switching to a released version, I think that's a good change. However, I don't want the roll forward to latest.

**Pull request merged**
