### PR TITLE
Add hyphen in Welcome to .NET Core Telemetry paragraph - commandline

### PR DESCRIPTION
**Pull request by scottaddie**
Add a hyphen in "commandline" within the **Welcome to .NET Core!** --> **Telemetry** paragraph. This makes it 2 distinct words, instead of 1.

### CODE REVIEW

**Comment by GuardRex** [comment]
Should be hyphenated as a adjective. https://github.com/aspnet/Docs/issues/2248#issuecomment-263354652

**Comment by scottaddie** [comment]
@GuardRex Thank you for the link and for pointing this out!

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
cc @piotrpMSFT Just to be sure you capture this string in your loc pass.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
@scottaddie I'm picking up this change in https://github.com/dotnet/cli/pull/5067. It's cherrypicked.

**Comment by scottaddie** [comment]
@piotrpMSFT Thank you!

**Pull request closed without merging**
