### PR TITLE
Read rid from build prop

### PR DESCRIPTION
**Pull request by wli3**
issue: https://github.com/dotnet/cli/issues/6375

Read rid from BuildInfoProps to make it more reliable

### CODE REVIEW

**Comment by wli3** [comment]
@livarcocc  @eerhardt I am not very confident about this change. 
BuildInfoProps is a generated file. That means, signing must run after compile. There is implicit dependency. 

On another side:
(1) it does need to run after compile, it needs something to sign on anyway
2) to make it explicit, signing need to dependency on CLI build framework which dependent on platform abstraction and to make it work, signing basically need to import everything.

Any better solution?

**Comment by livarcocc** [comment]
Can you push this to a branch under dotnet, instead of your own fork? This way we can kick a build in VSO to see if signing will work with your changes. Be careful when you kick off a build to cancel it as soon as the first signing step completes (so that nothing gets published out of your build).

Also, I am not concerned about the dependencies on build. This seems fair, the whole compile depends on it, I see no problem with signing depending on it either. But please try the VSO build first.

**Comment by wli3** [comment]
@livarcocc glad you let me run it on build machine. VSO build are using an old version of Msbuild. I changed the files to use old version(we have several msbuild files that are 14) in the repo.

Do you think that solution is good? I should use stage0 to run signing?

**Comment by livarcocc** [comment]
@MattGertz This is an infra-structure only change.

@wli3, feel free to merge.

**Pull request merged**
