### PR TITLE
Update NuGet to 3.5.0-beta-1130

### PR DESCRIPTION
**Pull request by eerhardt**
@davidfowl @pranavkm @piotrpMSFT @emgarten

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2283)

### CODE REVIEW

**Comment by eerhardt** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build

I pushed this too soon and our myget cli-deps feed wasn't ready for it

**Comment by pranavkm** [comment]
:shipit:

**Comment by davidfowl** [comment]
:shipit:

**Comment by emgarten** [comment]
:shipit:

**Comment by pranavkm** [comment]
Looks like this is done testing.

**Comment by eerhardt** [comment]
Sending ship room email now

**Pull request merged**
