### PR TITLE
Fixing 'Channel' and 'BranchName': "release/2.1.4xx" to "master"

### PR DESCRIPTION
**Pull request by ghost**
Fixing 'Channel' and 'BranchName': "release/2.1.4xx" to "master" - also the readme

### CODE REVIEW

**Review by peterhuene — APPROVED** [review]

**Review by dsplaisted — APPROVED** [review]
We should really be calculating the information in BranchInfo.props dynamically, otherwise we will continue to get this wrong.

We can't do that for the README.md file, but if we were calculating the `Channel` and `BranchName` dynamically, then we could have a test that ensured that README.md was up-to-date.

**Comment by tannergooding** [comment]
We should probably have a validation job (possibly a MicroBuild job, to parity what Roslyn has).

That job can trivially validate things like that publish branch or created packages matching the branch that GitHub pulls down. It also avoids the problem of building from sources that don't have branch info or that weren't checked out via Git.

**Comment by dsplaisted** [comment]
@tannergooding @johnbeisner Can one of you file an issue to improve things here?  IE either calculating these properties dynamically, or validating that they are correct in a validation job.

**Comment by johnbeisner** [comment]
git rev-parse --abbrev-ref HEAD

**Pull request merged**
