### PR TITLE
Create beta-install-experience.md

### LINKED ISSUE #506: Document install experience for Beta
- Document the dependencies for the zip install.

### PR DESCRIPTION
**Pull request by blackdwarf**
Add a document outlining the install experiences that will exist in the Beta timeframe (January). This document also outlines the way to update and remove the bits for Beta.

Fix #506 

/cc @brthor @Sridhar-MS @piotrpMSFT

### CODE REVIEW

**Comment by blackdwarf** [comment]
Windows build failing due to Roslyn AV error (known).

**Comment by piotrpMSFT** [comment]
@jaredpar we're getting more AVs... can you guys take a look?

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT Debug Build please

**Comment by jaredpar** [comment]
@piotrpMSFT is there a dump available for us to investigate?  The stack traces don't help in tracking down these AVs because they are on code paths which run on virtually every compilation.

Curious: why are we immediately pointing to Roslyn here instead of CoreCLR?  Roslyn runs fine in our lab, on desktop and CoreCLR, thousands of times a day.  These AVs are only showing up on CoreCLR runs that are different than the CoreCLR we use in our labs (at least the earlier ones).

**Pull request merged**
