### PR TITLE
Insert NuGet Build 4.9.0-preview2.5430 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.9.0-preview2.5430 into cli release/2.1.5xx branch

### CODE REVIEW

**Comment by livarcocc** [comment]
@rohit21agrawal @nkolev92 has this been merged to VS?

**Comment by nkolev92** [comment]
Not yet. 
We'll ping you when it's merged.

**Comment by livarcocc** [comment]
Is this in now?

**Comment by PatoBeltran** [comment]
Close this in favor of https://github.com/dotnet/cli/pull/9951

**Pull request closed without merging**
