### PR TITLE
remove test skips introduced to workaround #2536

### LINKED ISSUE #2536: Libraries targetting netstandard1.5 cannot be restored for RIDs
This is a current problem in NuGet which prevents libraries from having rid specific assets if published. 

Being tracked here:
https://github.com/NuGet/Home/issues/2553
This issue will be used for tracking test skips.

### PR DESCRIPTION
**Pull request by brthor**
Fixes #2536

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2685)

### CODE REVIEW

**Comment by brthor** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by piotrpMSFT** [comment]
@brthor his is pretty odd. It seems like the test is failing due to Console StdOut stream state:

> MESSAGE:
System.InvalidOperationException : The collection has been marked as complete with regards to additions.
+++++++++++++++++++
STACK TRACE:
at System.Collections.Concurrent.BlockingCollection`1.TryAddWithNoTimeValidation(T item, Int32 millisecondsTimeout, CancellationToken cancellationToken) at System.Collections.Concurrent.BlockingCollection`1.Add(T item) at Microsoft.DotNet.Cli.Utils.BlockingMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count) in D:\j\workspace\debug_windows---54dcb9ec\src\Microsoft.DotNet.Cli.Utils\BlockingMemoryStream.cs:line 23 at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder) at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count) at System.IO.TextWriter.WriteLine(String value) at System.IO.SyncTextWriter.WriteLine(String value) at System.Console.WriteLine(String value) at Microsoft.DotNet.Tools.Test.Utilities.TestCommand.ExecuteWithCapturedOutput(String args) in D:\j\workspace\debug_windows---54dcb9ec\test\Microsoft.DotNet.Tools.Tests.Utilities\Commands\TestCommand.cs:line 75 at Microsoft.DotNet.Tools.Test.Utilities.BuildCommand.ExecuteWithCapturedOutput(String args) in D:\j\workspace\debug_windows---54dcb9ec\test\Microsoft.DotNet.Tools.Tests.Utilities\Commands\BuildCommand.cs:line 254 at Microsoft.DotNet.Cli.Utils.Tests.GivenAProjectDependenciesCommandFactory.It_resolves_desktop_apps_defaulting_to_Debug_Configuration() in D:\j\workspace\debug_windows---54dcb9ec\test\Microsoft.DotNet.Cli.Utils.Tests\GivenAProjectDependenciesCommandFactory.cs:line 36

And only on x86 Windows. I'll kick the build once more to see if this is transient. Otherwise we'll need to understand how an unrelated test is affecting the console for this test...

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by brthor** [comment]
Well this is super weird. I'll debug.

**Comment by brthor** [comment]
Actually @piotrpMSFT I am not seeing that here. 

```
19:58:29 Listening on port 49873
19:58:29 RECEIVING MESSAGE:
19:58:29 {"MessageType":"TestSession.Connected","Payload":null}
19:58:29 ==============================
21:33:09 
Build timed out (after 120 minutes). Marking the build as aborted.
21:33:09 
Build was aborted
```

Seems like the kestrel tests are flaky on x86

**Comment by brthor** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Pull request merged**
