### PR TITLE
Updating the CLI version to preview4.

### PR DESCRIPTION
**Pull request by livarcocc**
@piotrpMSFT @jgoshi @krwq @blackdwarf

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by livarcocc** [comment]
@mmitche This failed twice because it failed to reach docker. Is the machine busted or something:

Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by mmitche** [comment]
@livarcocc It's not.  Trying to figure out why.

**Comment by mmitche** [comment]
@livarcocc The issue here is that the user name changed and there were docker settings based on the username baked into the image.  I updated the startup scripts.

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by naamunds** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Pull request merged**
