### PR TITLE
Newline before "For OS X"

### PR DESCRIPTION
**Pull request by dlech**
Markdown does not render properly without it.

### CODE REVIEW

**Comment by livarcocc** [comment]
LGTM

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT Debug please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test "Windows_NT Debug" please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT Debug Build please.

**Pull request merged**
