### PR TITLE
Upgrade Corefx and coreclr references

### PR DESCRIPTION
**Pull request by Sridhar-MS**
Microsoft.NetCore.App 1.0.0 => 1.0.1
Microsoft.NETCore.Runtime.CoreCLR 1.0.2 => 1.0.4
CLI Branding "Microsoft .NET Core 1.0.0 - SDK Preview" => "Microsoft .NET Core 1.0.1 - SDK 1.0.0 Preview 2-003122"

List of changes
- all project.jsons
- dotnet new templates
- and build projects files
   - shared-build-targets-utils\DependencyVersions.cs
   - CliDependencyVersions.cs

cc: @eerhardt @Petermarcu @piotrpMSFT 

SDK Branding changes

image

### CODE REVIEW

**Comment by livarcocc** [comment]
:shipit:

**Comment by eerhardt** [comment]
:shipit: - I'm not certain of all the places that have our "release moniker".  Do we have any other places hard-coded for the OSX and Ubuntu native installers?  @brthor ?

**Comment by brthor** [comment]
I don't think so @eerhardt but worth a quick verification pass.

:shipit:

**Comment by dasMulli** [comment]
#NamingThings: Shouldn't it be `Microsoft .NET Core 1.0.1 - SDK Preview 2.0.1`? Or is it a `.NET Core SDK 1.0.0 - Preview 2.0.1` that ships with a `.NET Core 1.0.1` (or at least `Microsoft.NETCore.App/1.0.1` directory).. 
My point is: How do i know that i will get a `.NET Core 1.0.1` when the installer says `1.0.0 - SDK Preview 2.0.1`?
Thinking further: What will happen at `.NET Core 1.1`? `.NET Core 1.0.0 - SDK`, dropping the `Preview` part and including a `Microsoft.NETCore.App` at `1.1.0` - or just `.NET Core 1.1 with SDK` (whatever the actual sdk / cli version actually is).

**Comment by Sridhar-MS** [comment]
@dasMulli Yes. Thats a bug I am going to fix.

**Comment by Sridhar-MS** [comment]
Cherry picked the following commits
https://github.com/dotnet/cli/pull/3950
https://github.com/dotnet/cli/pull/3948
https://github.com/dotnet/cli/pull/3789

cc @piotrpMSFT @leecow

**Comment by Sridhar-MS** [comment]
@rynowak and @cartermp Can you make sure that all your commits are in? For example I missed a bug fix (https://github.com/dotnet/cli/pull/4119/commits/07b581f0913e0ae25712bb1908ef8a9f8fe2f328) from @cartermp which I had to cherry-pick.

**Comment by rynowak** [comment]
@Sridhar-MS - there should be another change coming from @muratg

**Comment by livarcocc** [comment]
@rynowak what is this change from @muratg?

We are supposed to do three things with this release: CoreCLR update, ASP.NET web template update and F# template update.

**Comment by rynowak** [comment]
@livarcocc we haven't made all of the necessary changes to update the web template.

This is another part https://github.com/dotnet/cli/pull/4130

**Comment by livarcocc** [comment]
@rynowak @Sridhar-MS: Just want to remind you guys of our timeline on this. We need this build out today so that other can party on it and validate it.

It is all right that that is what we needed. We should probably have just pushed that change on Sridhar's branch, but ok. He will pull it in.

**Comment by rynowak** [comment]
It looks like we're also need to update package versions for EntityFramework as well. I'll be working this afternoon to identify the right set of changes and that to you ASAP

**Comment by brthor** [comment]
Looked over this change, and currently LGTM 

For the additional changes coming in it would make sense to me to get them all pushed to this branch (it is not in a private fork).

**Comment by rynowak** [comment]
Ok @brthor when I get the final set of changes for the web template I will push those to this branch.

**Comment by rynowak** [comment]
I have added the updates for Kestrel, Routing, EF and scaffolding. This includes everything AFAIK @muratg  @pranavkm. 

Note that the scaffolding packages aren't on our test feed yet, @pranavkm is on it.

**Comment by Sridhar-MS** [comment]
The build is green. I am merging this branch.

**Comment by livarcocc** [comment]
:shipit:

**Comment by pranavkm** [comment]
Scaffolding ones are up on https://dotnet.myget.org/feed/Packages/aspnetcore-patch.

**Pull request merged**
