### PR TITLE
Move FSharpTestProjects to the TestAssets folder.

### PR DESCRIPTION
**Pull request by eerhardt**
@brthor @Sridhar-MS @enricosada

### CODE REVIEW

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Comment by enricosada** [comment]
:+1: thx

**Comment by eerhardt** [comment]
> better leave only working tests in TestAssets i think. 

We are trying to clean up our "test" directory at the moment.  See #1250. When I spoke with @piotrpMSFT, he said to move these. But I can easily just delete them now, and they can be re-added as appropriate when they get used.

I'll let you guys decide.

**Comment by piotrpMSFT** [comment]
Let's merge this. I don't want to split efforts. For now let's put the test assets in one place. How we manage F# specifically is a sepearate issue :)

**Pull request merged**
