### PR TITLE
Update CoreSetup to preview2-25319-07

### PR DESCRIPTION
**Pull request by eerhardt**
/cc @dotnet/dotnet-cli

### CODE REVIEW

**Comment by eerhardt** [comment]
test CentOS7.1 x64 Debug Build
test Linux x64 Release Build
test RHEL7.2 x64 Release Build

**Comment by livarcocc** [comment]
@MattGertz flow of dependencies into the CLI.

**Comment by wli3** [comment]
relate issue https://github.com/dotnet/core-setup/pull/2474#event-1092607767
I did see some new build in [apt-get feed](https://apt-mo.trafficmanager.net/repos/dotnet/dists/trusty/main/binary-amd64/Packages) but I cannot find 2.0.0-preview2-25319-07, it is still in CI pipeline?

@karajas

**Comment by eerhardt** [comment]
Closing old PR.  We will update core-setup in the release/2.0.0 branch.

**Pull request closed without merging**
