### PR TITLE
LOC CHECKIN | cli-master | 20170529

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by nguerrera** [comment]
Test Ubuntu16.04 x64 Debug Build

**Comment by nguerrera** [comment]
I will merge this to master when green, cherry-pick to 2.0 and start new PR.

**Comment by livarcocc** [comment]
@mattger this is loc insertion. Can you please approve?

**Comment by nguerrera** [comment]
This one targets master (2.1). Merging and will send new PR with cherry pick to 2.0

**Pull request merged**
