### PR TITLE
MSBuild 15.7.127.34537 for 3xx

### PR DESCRIPTION
**Pull request by rainersigwald**
Internal PR (escrow approved): https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/113318

### CODE REVIEW

**Comment by rainersigwald** [comment]
@livarcocc Not sure if this is as important since prodcon will pick it up; could wait for #8915 to merge to 3xx.

**Comment by livarcocc** [comment]
If this is for 15.7, you need to target release/2.1.2xx. Duo check-in makes it flow into 3xx faster, otherwise our nightly merges should pick it up.

**Comment by AndyGerlicher** [comment]
Prodcon will pick it up since it went into our release branch, but does it update the dependency so cloning CLI and building will use it? And if not is that coming at some point?

**Comment by livarcocc** [comment]
@AndyGerlicher it does not update the dependency. I believe this is coming in V2.

**Pull request merged**
