### PR TITLE
Added a dotnet test, adapters and runners document

### PR DESCRIPTION
**Pull request by livarcocc**
It details the interactions between dotnet test, adapters and runners by describing the communication protocol between these pieces and the parameters that they support.

cc @piotrpMSFT @blackdwarf

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2069)

### CODE REVIEW

**Comment by blackdwarf** [comment]
:lgtm: modulo comments

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Documentation/DotnetTestAdaptersAndRunners.md, line 7 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjqiO2c5QZQEyqQTr1:-KDjqiO2c5QZQEyqQTr2:-877682530) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/Documentation/DotnetTestAdaptersAndRunners.md#L7)):*
Double describes

---

*[Documentation/DotnetTestAdaptersAndRunners.md, line 22 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjt1p0C370lo18aho5:-KDjt1p0C370lo18aho6:906509094) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/Documentation/DotnetTestAdaptersAndRunners.md#L22)):*
An example of the data on wire would be helpful

---

*[Documentation/DotnetTestAdaptersAndRunners.md, line 48 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjt5uNspd4blgICLqD:-KDjt5uNspd4blgICLqE:1221033681) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/Documentation/DotnetTestAdaptersAndRunners.md#L48)):*
We have the README.md for the dotnet-test command. To not duplicate work, can you link to this document? I can update that doc with this content. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dotnet/cli/2069#-:-KDjsweNat6v7OUPVCxd:-546044657)*

**Comment by livarcocc** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/dotnet/commands/dotnet-test/readme.md, line 7 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjqiO2c5QZQEyqQTr1:-KDk4FGZa7SI44-vwHrd:-709678398) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/src/dotnet/commands/dotnet-test/readme.md#L7)):*
Will fix.

---

*[src/dotnet/commands/dotnet-test/readme.md, line 48 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjt5uNspd4blgICLqD:-KDk42YftvDay3LfjmRV:-920253896) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/src/dotnet/commands/dotnet-test/readme.md#L48)):*
Moved it to readme.md under dotnet-test

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dotnet/cli/2069)*

**Comment by livarcocc** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/dotnet/commands/dotnet-test/readme.md, line 22 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjt1p0C370lo18aho5:-KDk7A2H7ago5_HRGxxh:-1497928151) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/src/dotnet/commands/dotnet-test/readme.md#L22)):*
Added links to each class that describes the payload. It will be more accurate then actually pasting some JSON here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dotnet/cli/2069)*

**Comment by livarcocc** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/dotnet/commands/dotnet-test/readme.md, line 7 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjqiO2c5QZQEyqQTr1:-KDk7aIbFMs6MPbOuSC2:-499146009) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/src/dotnet/commands/dotnet-test/readme.md#L7)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dotnet/cli/2069)*

**Comment by livarcocc** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/dotnet/commands/dotnet-test/readme.md, line 7 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjqiO2c5QZQEyqQTr1:-KDk7fw7JCk-5mvnIml7:-499146009) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/src/dotnet/commands/dotnet-test/readme.md#L7)):*
Done.

---

*[src/dotnet/commands/dotnet-test/readme.md, line 22 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjt1p0C370lo18aho5:-KDk7hRLvgnGRJduokwm:-499146009) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/src/dotnet/commands/dotnet-test/readme.md#L22)):*
Done.

---

*[src/dotnet/commands/dotnet-test/readme.md, line 48 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjt5uNspd4blgICLqD:-KDk7iD0MsHx7LMnRQkI:-499146009) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/src/dotnet/commands/dotnet-test/readme.md#L48)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dotnet/cli/2069)*

**Comment by livarcocc** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/dotnet/commands/dotnet-test/readme.md, line 7 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjqiO2c5QZQEyqQTr1:-KDk7qUG3DcDK4tbAKIh:-499146009) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/src/dotnet/commands/dotnet-test/readme.md#L7)):*
Done.

---

*[src/dotnet/commands/dotnet-test/readme.md, line 22 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjt1p0C370lo18aho5:-KDk7qvW8gXD28MLzEYo:-499146009) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/src/dotnet/commands/dotnet-test/readme.md#L22)):*
Done.

---

*[src/dotnet/commands/dotnet-test/readme.md, line 48 \[r1\]](https://reviewable.io:443/reviews/dotnet/cli/2069#-KDjt5uNspd4blgICLqD:-KDk7rZu55MbN1IuNk_v:-499146009) ([raw file](https://github.com/dotnet/cli/blob/e865f430fc6d9c57d12ae3cb62a1a1da9a120ce2/src/dotnet/commands/dotnet-test/readme.md#L48)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dotnet/cli/2069)*

**Comment by blackdwarf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dotnet/cli/2069#-:-KDk81N-zPY6yeV0UuqG:1417088721)*

**Pull request merged**
