### PR TITLE
MSBuild 15.7.179

### PR DESCRIPTION
**Pull request by rainersigwald**
Shiproom approved; should have no .NET Core impact.

### CODE REVIEW

**Comment by rainersigwald** [comment]
I'll add our myget feed.

**Comment by rainersigwald** [comment]
Did I do something to hork Jenkins? It doesn't seem like this change could cause this symptom . . .

**Comment by livarcocc** [comment]
Seems to be turning green now.

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Ubuntu x64 Release Build please
Timeout: https://ci.dot.net/job/dotnet_cli/job/release_2.1.3xx/job/release_ubuntu_x64_prtest/365/

**Comment by AndyGerlicher** [comment]
@mmitche can we turn off prodcon for MSBuild and use the version here for 2.1? We no longer have any upstream dependencies and shouldn't be updating again.

**Comment by mmitche** [comment]
@AndyGerlicher already off :)

**Pull request merged**
