### PR TITLE
Update message sequences of ProjectModel server

### PR DESCRIPTION
**Pull request by troydai**
Send References ahead of Dependencies

Address #857 

/cc @abpiskunov 
/review @davidfowl @anurse

### CODE REVIEW

**Comment by anurse** [comment]
@dotnet-bot test this please

**Comment by troydai** [comment]
@dotnet-bot test this please

**Comment by troydai** [comment]
Ping @davidfowl @anurse

**Comment by anurse** [comment]
:shipit:

**Comment by troydai** [comment]
@dotnet-bot test this please

**Comment by troydai** [comment]
For Ubuntu build disk has run out of space.

**Comment by troydai** [comment]
@dotnet-bot build CentOS Release please

**Comment by troydai** [comment]
@dotnet-bot test this please

**Pull request merged**
