### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Potapy4**
- Rename from `.Net` to `.NET`

### CODE REVIEW

**Comment by livarcocc** [comment]
@Potapy4 thanks for the PR, we appreciate it.

@nguerrera is it ok to modify the translations here directly?

cc @peterhuene

**Comment by peterhuene** [comment]
The `.Net` -> `.NET` change in the localized files seem appropriate to me, fwiw.

**Comment by nguerrera** [comment]
> The .Net -> .NET change in the localized files seem appropriate to me, fwiw.

It does. @tmeschter @janbaltus can we make sure this change is done on the backend so that next handback doesn't revert.

**Comment by nguerrera** [comment]
Thanks, @Potapy4 

Let's just wait for confirmation that the loc changes are applied on the backend too and then we can merge.

**Comment by lukaschal** [comment]
Fixed in a MLCP platform.

**Comment by livarcocc** [comment]
This is good to merge now?

**Comment by nguerrera** [comment]
Thanks again, @Potapy4

**Pull request merged**
