### PR TITLE
General cleanup of the solution.

### PR DESCRIPTION
**Pull request by MichaelSimons**
Removed non-existent projects, fixed paths, removed invalid projects, etc. 

The TestProjectToProjectDependencies.xproj was removed because there isn't a corresponding project.json file for it, rather there are 5 various subprojects.  The xproj was therefore invalid.

cc @eerhardt @anurse

### CODE REVIEW

**Comment by eerhardt** [comment]
:shipit:

**Comment by piotrpMSFT** [comment]
Thanks! :shipit:

**Comment by davidfowl** [comment]
This PR won't merge :sob:

**Comment by MichaelSimons** [comment]
I manually merged the changes.  It should be up to date now.

**Pull request merged**
