### PR TITLE
Fix a typo skip ci please

### PR DESCRIPTION
**Pull request by MattGal**
I keep seeing this typo, may as well fix it.

### CODE REVIEW

**Comment by livarcocc** [comment]
@Pilchie @ManishJayaswal This is a documentation only change.

**Comment by mairaw** [comment]
I thought xliff files were auto-generated based on the current source?

**Comment by MattGal** [comment]
I just searched the repo for "dependented" and only found xliff's.   Either way, would be nice to fix even if this needs to be fixed elsewhere.

**Comment by mairaw** [comment]
Sure. I've fixed that in the source back in Feb: https://github.com/dotnet/cli/commit/b6053811653b0e63777be5a856fe448e30c8538b#diff-25cf71eb3cc84f71b57ea7db048a33a3

So the product would have to be re-localized because that string doesn't even exist anymore in the product.

**Comment by Pilchie** [comment]
Where does this appear to the user. Based on @mairaw's comments, I can't tell whether this is necessary or not?

**Comment by mairaw** [comment]
I think it shows in older versions of the SDK.

**Comment by MattGal** [comment]
Feel free to close it out, if I fixed it in the wrong place it would be cool to fix it, if it's unnecessary then no worries.

**Pull request closed without merging**
