### PR TITLE
Send an empty error message after global error is cleared

### PR DESCRIPTION
**Pull request by troydai**

### CODE REVIEW

**Comment by davidfowl** [comment]
What bug is this fixing

**Comment by troydai** [comment]
Issue #1569 is reopened. It is regressed in https://github.com/dotnet/cli/commit/81baacd64128f00f87ad5304fab9f490fb88ea24

**Comment by troydai** [comment]
@dotnet-bot test OSX Debug Build please

**Comment by troydai** [comment]
@eerhardt is there known issue regarding dotnet restore on Mac?

**Comment by eerhardt** [comment]
> @eerhardt is there known issue regarding dotnet restore on Mac?

Not that I know of. I'll investigate...

**Comment by troydai** [comment]
Can I reset these two build now?

**Comment by troydai** [comment]
@davidfowl sign off? since I cleared your concern.

**Comment by troydai** [comment]
@eerhardt @anurse is it ok if I merge without clear the OSX build?

**Pull request merged**
