### PR TITLE
Update version of xunit adapter in test assets and xunit template

### PR DESCRIPTION
**Pull request by Faizan2304**

### CODE REVIEW

**Comment by Faizan2304** [comment]
@dotnet-bot test OSX x64 Release Build

**Comment by Faizan2304** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by Faizan2304** [comment]
@dotnet-bot test Fedora23 x64 Debug Build

**Comment by Faizan2304** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by Faizan2304** [comment]
@dotnet-bot test Windows_NT x86 Debug Build

**Comment by codito** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by codito** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by Faizan2304** [comment]
@dotnet-bot test Windows_NT x64 Release Build
@dotnet-bot test Ubuntu16.04 x64 Debug Build
@dotnet-bot test Ubuntu x64 Release Build
@dotnet-bot test Debian8.2 x64 Debug Build
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by codito** [comment]
The build failure seem unrelated to the change.

```
06:47:32 + ./build.sh --skip-prereqs --configuration Debug --targets Default
06:47:46 Failed to create prime the NuGet cache. restore3 failed with: 1
06:47:46 Build step 'Execute shell' marked build as failure
```

**Comment by Faizan2304** [comment]
@dotnet-bot test Ubuntu x64 Release Build
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by codito** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by livarcocc** [comment]
Can you change it here as well: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectJsonMigration/ConstantPackageVersions.cs#L11? Otherwise, the versions will diverge, between the template and the migrated one.

**Comment by livarcocc** [comment]
I will merge once it is green.

**Comment by Faizan2304** [comment]
@dotnet-bot test OSX x64 Release Build

**Pull request merged**
