### PR TITLE
Insert NuGet Build 4.6.0-rtm-4825 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.6.0-rtm-4825 into cli release/2.1.1xx branch

### CODE REVIEW

**Comment by livarcocc** [comment]
@rohit21agrawal can you confirm that this has been approved/inserted into VS already?

**Comment by rohit21agrawal** [comment]
not yet, we have a PR out for it
@patobeltran will follow up when it's been inserted

**Comment by livarcocc** [comment]
Ok, I will hold off on merging this until that happens.

**Comment by PatoBeltran** [comment]
@livarcocc the PR was just merged into VS

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Pull request merged**
