### PR TITLE
Update templates to add missing BrowserLink package

### PR DESCRIPTION
**Pull request by mlorbetske**
We should hold off on merging this one until we get an understanding of why the previous fix for the warnings for Microsoft.Composition didn't work.

### CODE REVIEW

**Comment by livarcocc** [comment]
@mlorbetske Let me know when it is ok to merge this.

**Comment by mlorbetske** [comment]
@livarcocc after this build is green, we should be OK. Unless we need to suppress that warning globally whatever change we end up taking shouldn't impact templates

**Comment by mlorbetske** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build please
@dotnet-bot test OpenSUSE42.1 x64 Debug Build please

**Comment by livarcocc** [comment]
@MattGertz Flow of dependencies into the CLI.

**Pull request merged**
