### PR TITLE
Update to ASP.NET 1.0.6 and 1.1.4

### PR DESCRIPTION
**Pull request by mlorbetske**

### CODE REVIEW

**Comment by livarcocc** [comment]
@mlorbetske 
```
10:45:20.383 3>D:\j\workspace\debug_windows---23e7412e\.dotnet_stage0\x86\sdk\1.0.4\NuGet.targets(97,5): error : Unable to resolve 'Microsoft.DotNet.Common.ItemTemplates (>= 1.0.0-beta2-20170907-306)' for '.NETCoreApp,Version=v1.0'. [D:\j\workspace\debug_windows---23e7412e\build\templates\templates.csproj] [D:\j\workspace\debug_windows---23e7412e\build\Microsoft.DotNet.Cli.BundledTemplates.proj]
```

**Comment by mlorbetske** [comment]
@livarcocc  Yep, packages apparently hadn't propagated on MyGet by that time

@dotnet-bot test Ubuntu x64 Release Build please
@dotnet-bot test Windows_NT x64 Release Build please
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by nguerrera** [comment]
Merging without waiting for Jenkins queue to unblock on that final leg (it's been such for hours) so that the official build can start.

**Comment by nguerrera** [comment]
@MattGertz FYI. Ingestion of ASP.NET for 1.1 servicing.

**Pull request merged**
