### PR TITLE
Sepeters 286351 update template sdk version

### PR DESCRIPTION
**Pull request by seancpeters**
Updating the Microsoft.Net.Sdk version tpo 20161031-2
Updating the Microsoft.Net.Sdk.Web version to 20161031-2-97

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@livarcocc @nguerrera it looks like the sdk version bump is failing because a task cannot be found in the sdk payload. Any ideas?

**Comment by nguerrera** [comment]
Investigating

**Comment by nguerrera** [comment]
@piotrpMSFT I believe the problem is that the dotnet_stage0 still has nuget 3.6 which causes assembly load conflicts with SDK. What controls the stage0 version?

**Comment by nguerrera** [comment]
I'm told stage0 can't be updated until all PJ's are converted to csproj. That is blocking updating the SDK to latest.

**Comment by piotrpMSFT** [comment]
@nguerrera we'll add a 2nd stage 0. We'll use one for the pj work and another for msbuild work... migration is hard...

**Comment by nguerrera** [comment]
Hard indeed, i'm now investigating an issue where some projects were already held back to an earlier SDK. You probably want to leave those held back here so as not to get hit by the same issue and we can make progress in parallel.

**Comment by piotrpMSFT** [comment]
@seancpeters the Stage0 change is merged. Feel free to rebase or resolve merge conflicts and push up a new commit.

**Comment by livarcocc** [comment]
Closing this one in favor of https://github.com/dotnet/cli/pull/4585

**Pull request closed without merging**
