### PR TITLE
remove dotnet-build.tests

### PR DESCRIPTION
**Pull request by piotrpMSFT**
This capability is being replaced by MSBuild, and the project.json build tests are very long running. We still get coverage from the CLI build itself so long as we need this capability.

/cc @brthor @eerhardt @livarcocc @cdmihai

### CODE REVIEW

**Comment by livarcocc** [comment]
:shipit:

**Comment by eerhardt** [comment]
:shipit:   One random question - are there any "TestAssets" that are only used by these tests?  It may be good to delete them as well, if they are easy to spot.

**Comment by piotrpMSFT** [comment]
@eerhardt I'll do a pass through testassets to see what is still being used independently of this change. There is not much management of these thus far.

**Comment by brthor** [comment]
:shipit: @eerhardt @piotrpMSFT I think it may be valuable to keep the test assets around, unless the scenarios they are mocking will also be going away.

**Comment by piotrpMSFT** [comment]
@brthor, the responsibility of incremental, p2p, etc. is moving into shared targets in another repo. CLI shouldn't be re-testing those capabilities.

**Pull request merged**
