### PR TITLE
Use the portable `linux-x64` runtime when building on Linux.

### PR DESCRIPTION
**Pull request by eerhardt**
In order to get more coverage on the portable `linux-x64` runtime, we should always install the portable linux runtime when building on linux.  This will help us ensure the .NET Core SDK works on the portable linux runtime on all the distros we support.

@livarcocc @nguerrera 

/cc @Petermarcu @gkhanna79

### CODE REVIEW

**Comment by eerhardt** [comment]
FYI - the BundledRuntimes.props file was in `Western European` encoding and also had inconsistent whitespace, which was making my editor very angry.  So I reformatted that file in a separate commit.  Please review commit-by-commit for easy reviewing.

**Comment by nguerrera** [comment]
@mmitche Neither of these are expected to run anymore, but they still show with 'waiting for status to be reported':
```
Fedora24 x64 Release Build — Waiting for status to be reported
OSX x64 Release Build — Waiting for status to be reported
```

**Comment by mmitche** [comment]
@nguerrera The GitHub settings have protected branches on including those checks.  Github pre-populates the list with what it expects to see.  You need to remove those expected checks.

Btw, did you figure out the F24 issue?

**Comment by eerhardt** [comment]
Thanks, @mmitche.  I've updated the repo's settings to have the correct legs be marked as "required".

**Pull request merged**
