### PR TITLE
Remove NuGet.Config files for test projects.

### LINKED ISSUE #1316: Test projects using custom NuGet.Config
Is this intentional? Why do our tests use custom NuGet.configs?

````
    /Users/piotrp/code/github/piotrpMSFT/cli2/NuGet.Config
    /Users/piotrp/.nuget/NuGet/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/E2E/bin/Debug/dnxcore50/osx.10.11-x64/bin/e2etestroot/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/E2E/bin/Debug/dnxcore50/bin/e2etestroot/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-compile.Tests/bin/Debug/dnxcore50/TestProjects/TestLibraryWithAnalyzer/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-compile.Tests/bin/Debug/dnxcore50/TestAssets/TestProjects/TestLibraryWithAnalyzer/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-compile.Tests/bin/Debug/dnxcore50/osx.10.11-x64/TestAssets/TestProjects/TestLibraryWithAnalyzer/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/TestProjects/TestSimpleIncrementalApp/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/TestProjects/TestProjectToProjectDependencies/src/L22/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/TestProjects/TestProjectToProjectDependencies/src/L21/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/TestProjects/TestProjectToProjectDependencies/src/L12/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/TestProjects/TestProjectToProjectDependencies/src/L11/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/TestProjects/TestProjectToProjectDependencies/src/L0/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/TestAssets/TestProjects/TestSimpleIncrementalApp/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/TestAssets/TestProjects/TestProjectToProjectDependencies/src/L22/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/TestAssets/TestProjects/TestProjectToProjectDependencies/src/L21/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/TestAssets/TestProjects/TestProjectToProjectDependencies/src/L12/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/TestAssets/TestProjects/TestProjectToProjectDependencies/src/L11/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/TestAssets/TestProjects/TestProjectToProjectDependencies/src/L0/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/osx.10.11-x64/TestAssets/TestProjects/TestSimpleIncrementalApp/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/osx.10.11-x64/TestAssets/TestProjects/TestProjectToProjectDependencies/src/L22/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/osx.10.11-x64/TestAssets/TestProjects/TestProjectToProjectDependencies/src/L21/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/osx.10.11-x64/TestAssets/TestProjects/TestProjectToProjectDependencies/src/L12/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/osx.10.11-x64/TestAssets/TestProjects/TestProjectToProjectDependencies/src/L11/NuGet.Config
    /Users/piotrp/code/github/piotrpMSFT/cli2/test/dotnet-build.Tests/bin/Debug/dnxcore50/osx.10.11-x64/TestAssets/TestProjects/TestProjectToProjectDependencies/src/L0/NuGet.Config
````

### PR DESCRIPTION
**Pull request by eerhardt**
Fix #1316 

@Sridhar-MS @brthor

### CODE REVIEW

**Comment by brthor** [comment]
The change which recently went in to set `TEST_ARTIFACTS` was regressed by the new build scripts.

For this reason, some of the tests will still use a random temp directory and a random NuGet.config in a parent directory may get picked up (that was the purpose of these files originally).

Might you be able to set the `TEST_ARTIFACTS` environment variable somewhere in the build prior to running the tests as part of this PR?

**Comment by eerhardt** [comment]
> Would you consider setting the TEST_ARTIFACTS environment variable somewhere in the build as a part of this PR?

@brthor - I added a new commit that sets the TEST_ARTIFACTS environment variable in the new build scripts.  PTAL

**Comment by eerhardt** [comment]
cc: @anurse to look over the script change.

**Comment by anurse** [comment]
:shipit:

**Comment by piotrpMSFT** [comment]
@eerhardt please merge if this is ready!

**Comment by eerhardt** [comment]
> @eerhardt please merge if this is ready!

Done.  I was giving @brthor a chance to look it over, but he still can I guess...

**Comment by brthor** [comment]
LGTM :+1:

**Pull request merged**
