### PR TITLE
Updating the MSI Installation Note message.

### PR DESCRIPTION
**Pull request by livarcocc**
Updating the MSI Installation Note message. Also had to shift components around slightly to make it fit.

capture

### CODE REVIEW

**Comment by livarcocc** [comment]
Fixes https://github.com/dotnet/cli/issues/8459

**Comment by livarcocc** [comment]
@MattGertz for approval.

**Comment by MattGertz** [comment]
@livarcocc I'm curious about the one character offset on the left margin of SDK, Privacy, and MIT links as compared to the Core link.  Is that intentional?  It looks like a mistake to my eyes.

**Comment by johnbeisner** [comment]
@MattGertz 
@livarcocc 

Name="CoreDocumentationLink" X="180"

I think it should be "185"

**Comment by MattGertz** [comment]
Good, I'm not just seeing thing then.  Let's fix that. 

(I'll just assume that this was deliberately done so that I could add value to the PR. ;-))

**Comment by livarcocc** [comment]
@MattGertz you passed the test.

capture2

**Comment by MattGertz** [comment]
Approved.  I feel worthy now.

**Pull request merged**
