### PR TITLE
MSBuild 15.8.160-preview

### PR DESCRIPTION
**Pull request by AndyGerlicher**
We may have 1 more insertion for Preview 5 before tomorrow night's cutoff, but I wanted to get this started to make sure there are no issues.

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build please

**Comment by AndyGerlicher** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build please
Hrm, different failures this time: https://ci.dot.net/job/dotnet_cli/job/release_2.1.4xx/job/debug_debian8.2_x64_prtest/249/

**Comment by AndyGerlicher** [comment]
@livarcocc any idea on this? I was getting that test failure in Debian only before, now it's all of them. I don't think it's us?

**Comment by AndyGerlicher** [comment]
This is ready and is in VS for 15.8 P5. Looks like other insertions to this branch are failing as well, so I'm going to assume it's not an issue with our insertion.

**Comment by AndyGerlicher** [comment]
@dotnet-bot test this please

**Comment by AndyGerlicher** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by nguerrera** [comment]
@dsplaisted OK to merge?

**Comment by nguerrera** [comment]
(again, ok to merge since this is in VS)

**Pull request merged**
