### PR TITLE
Merge rel/1.0.0 into master

### PR DESCRIPTION
**Pull request by krwq**
testing in progress.

Please review README.md changes - there was a merge conflict which I resolved by taking rel/1.0.0 which seemed more complete and replacing /beta/ with /dev/

WARNING: watch out the fix to unblock the build (commits after merge)

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2259)

### CODE REVIEW

**Comment by krwq** [comment]
This is building without problems on my local box but seems that CI is not working. @mmitche, could you take a look if there is something I should change or not merge?

**Comment by mmitche** [comment]
This is because the CI is not set up to build PRs against the master branch (only against release/1.0.0 right now).  So my first question is...is this the right target branch?

If it is, then we should enable the CI against this branch.

**Comment by krwq** [comment]
Yes, this is the right branch. I believe CI should be checking both branches.

**Comment by mmitche** [comment]
@krwq It's explicitly set not to right now, but no worries, we can fix that NBD.  I assume the jobs should be exactly the same between the two branches?

**Comment by krwq** [comment]
They should be the same, Thanks!

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by brthor** [comment]
Nice, thanks for re-enabling that @mmitche !

**Comment by krwq** [comment]
I'm merging this since rhel was never built on master. @livarcocc is working on the issue.

**Pull request merged**
