### PR TITLE
MSBuildSDKsPath

### LINKED ISSUE #4822: Add MSBuildSDKsPath to MSBuild invocations
CLI portion of https://gist.github.com/piotrpMSFT/9ab355cd48a5539c9fc31bafd98df5aa

### PR DESCRIPTION
**Pull request by piotrpMSFT**
Fixes #4822 by exposing MSBuildSDKsPath to MSBuild when invoked from CLI.
Adds stub SDKs to enable end-to-end testing.

@mlorbetske @srivatsn can you link issues tracking adding `real` updated SDKs to CLI?

@livarcocc @krwq can you review?

@AndyGerlicher @kieranmo FYI 

@MattGertz this will need your approval to merge

@enricosada note that #4822 introduces an additional model for referencing SDKs in .NET Core. For RC2 we're implementing the model but not an extensibility model. Your existing integration via NuPkg will continue to work. We are looking into the benefit of extensibility for this model and will share with you once we have some kind of plan. For the time being we'll test it with the in-box SDKs but will reach out asap.

### CODE REVIEW

**Comment by enricosada** [comment]
thx for ping @piotrpMSFT , i'll read the docs later (nice! 👍 for using f# as example 😄 )

**Comment by livarcocc** [comment]
@dotnet-bot Test this please

**Comment by srivatsn** [comment]
For net.sdk https://github.com/dotnet/sdk/issues/415 tracks doing the work.

**Comment by MattGertz** [comment]
Approved pending tests passing.

**Pull request merged**
