### PR TITLE
Add switch to enable searching global path for existing SDK version

### PR DESCRIPTION
**Pull request by flcdrg**
Implements #11058

### CODE REVIEW

**Comment by johnbeisner** [comment]
@flcdrg 
"ProgramFiles" is not necessary the global location. The global location is defined on the "PATH" environmental variable - on Windows x64 OSs this could one of 2 values. Moreover, our plans for the global location include Visual Studio being able to install .NET Core to other volumes - in that scenario the global location could be "E:\dotnet\x64"

**Comment by flcdrg** [comment]
@johnbeisner So checking PATH locations would cover the other volumes scenario?

**Comment by johnbeisner** [comment]
@flcdrg 
As long as you use the first dotnet 'hit' on the PATH

**Comment by flcdrg** [comment]
No worries. I'll update the PR to reflect that advice.

**Comment by wli3** [comment]
@flcdrg I am sorry but please expect long delay for this review. We temporarily don't have enough people in the team

**Comment by marcpopMSFT** [comment]
CLI repo has been archived and merged with https://github.com/dotnet/sdk/tree/master/src/Cli.  Closing all old PRs in the cli repo to master.

**Pull request closed without merging**
