### PR TITLE
Fix yum package conflict in Docker image

### PR DESCRIPTION
**Pull request by naamunds**
When running the CLI builds on the new build agents, the CentOS
build failed with the following error:

2017-01-26T20:39:30.0800810Z Step 4 : RUN yum -q -y install unzip libunwind gettext libcurl-devel openssl-devel zlib libicu-devel
2017-01-26T20:39:30.3020500Z  ---> Running in 97affb106685
2017-01-26T20:39:40.3872390Z [91mError: libselinux conflicts with fakesystemd-1-17.el7.centos.noarch

Swapping the "fakesystemd" package with the real "systemd" package
fixed the issue, which was recommended in http://stackoverflow.com/a/36632668.

This issue hasn't been seen on the official builds because the build
agents in that pool have the Docker image cached, and they are using an
older version of the centos:7.1.1503 image which appears not to have
this issue.

This same change was made in https://github.com/dotnet/core-setup/pull/1149

### CODE REVIEW

**Comment by livarcocc** [comment]
Will this work with the cached images and old build agents as well?

**Comment by naamunds** [comment]
@livarcocc Core-Setup hasn't had any issues with it on the old build agents.  It causes the CentOS image to be rebuilt starting with this "swap" step the first time a build with these changes is run on a build agent.  After a build agent has run a build with these changes, it uses the cache for every Dockerfile step like before.

**Comment by livarcocc** [comment]
@MattGertz FYI, this is a build only change.

**Comment by piotrpMSFT** [comment]
@MattGertz approving this infra change

**Comment by MattGertz** [comment]
Make it so!

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Pull request merged**
