### PR TITLE
Change ASP.NET tool version to reflect project format.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
/cc @Eilon @muratg @DamianEdwards @Peter-Schneider @livarcocc

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by NTaylorMullen** [comment]
Assuming the failure from the build is not due to my change 😄

**Comment by livarcocc** [comment]
It isn't. We hit a CI issue. FIxing it. Will re-spin the windows failure once we have the fix.

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Pull request merged**
