### PR TITLE
Update Roslyn to 1.3.0-beta1-20160406-08

### PR DESCRIPTION
**Pull request by eerhardt**
@Petermarcu @piotrpMSFT @tmat

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2376)

### CODE REVIEW

**Comment by tmat** [comment]
@jaredpar @agocke

**Comment by eerhardt** [comment]
@Petermarcu - after talking with @tmat, it appears this isn't the final Roslyn version.  They need to take the new CoreFX version from last night and get a build with that out.

Let me know if you still want me to take this change, or wait for the new Roslyn build.

**Comment by eerhardt** [comment]
I talked with Eilon, and we are going to take this change as soon as we can.  We will update Roslyn again, when the new build comes out.

**Comment by Petermarcu** [comment]
Yes, we'll take two updates, this one and then the one when Roslyn updates their dependency on CoreFX.

**Pull request merged**
