### PR TITLE
Update f# templates for preview2.1 

### PR DESCRIPTION
**Pull request by enricosada**
- add missing templates (`web`, `xunit`)
- add tests (may fail becase `dotnet-compile-fsc` `-preview2.1` package is not released yet, working on it)
  - i hope to release it asap before this is merged, otherwise just ignore test is ok

### CODE REVIEW

**Comment by enricosada** [comment]
@piotrpMSFT i added templates, and disabled test until new `dotnet-compile-fsc` is published.
i tested locally and `dotnet-new` create templates for all, and work with my local `dotnet-compile-fsc` 
can be merged like that?

**Comment by enricosada** [comment]
btw @piotrpMSFT the `web` template also for c# has a wrong netcoreapp package version, but it's restored as 1.1.0 anyway with an upgrade warning
i added the f# web like c# one, so project file is the same and easy to align. For code i just used a simplifed website (it's like `preview3` web template)

**Comment by cartermp** [comment]
LGTM.

**Comment by piotrpMSFT** [comment]
@srivatsn @MattGertz for approval. Thanks @enricosada!!

**Comment by piotrpMSFT** [comment]
@srivatsn @mattgertz

**Pull request merged**
