### PR TITLE
Add overload to LockFileReader.Read

### PR DESCRIPTION
**Pull request by troydai**
Address issue #2206 

/cc @davidfowl

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2208)

### CODE REVIEW

**Comment by davidfowl** [comment]
:shipit:

**Comment by eerhardt** [comment]
@troydai - this has merge conflicts.  If you still interested in making this change, can you resolve the conflicts?  If not, please close.

**Comment by troydai** [comment]
I want to merge to this. What's the branch I can merge to for rtm now. I can rebase on it.

**Comment by eerhardt** [comment]
rel/1.0.0 is open for "Preview2" work.

**Comment by livarcocc** [comment]
No tests?

**Comment by troydai** [comment]
why do we need test for this?

**Comment by livarcocc** [comment]
@troydai I honestly don't understand the question. To me, every piece of code needs a test.

**Comment by troydai** [comment]
@livarcocc I understand your point. But there is no prove 100% code coverage means good test. On the other hand, more automation means more maintenance cost. I'll close this PR for now, to me it doesn't worth to have add 10 more lines of test to cover a simple overload.

**Comment by troydai** [comment]
@davidfowl I close this issue since I don't think this feature worth the effort since CLI team's strong opinion on 100% code coverage. We have no rtm feature relies on this. Please let me know otherwise.

**Pull request closed without merging**
