### PR TITLE
LOC CHECKIN | cli master | 20180315

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by peterhuene** [comment]
Unfortunately it looks like the `list tool` command tests are making some string length assumptions that are violated when the table header is localized.  I'll see if I can create a fix for the failing tests.

**Comment by nguerrera** [comment]
For things where testing the visual against an English rendering (help message) seemed most effective, I sacrificed the loc coverage.

**Comment by nguerrera** [comment]
There is also a BeVisuallyEquivalentIfNotLocalized helper I used in places.

**Comment by nguerrera** [comment]
Nevermind, I see you did the work to fix it and not lose coverage. :)

**Comment by peterhuene** [comment]
@v-zbsail If you rebase this PR off of master it should resolve hopefully resolve the test failures.

**Comment by nguerrera** [comment]
Shouldn't be necessary to rebase. Jenkins uses merge head.

**Comment by nguerrera** [comment]
@dotnet-bot test this please

**Comment by peterhuene** [comment]
That's good to know, thanks.  I'm used to Travis for public repos.

**Comment by peterhuene** [comment]
@v-zbsail Unfortunately it looks like this needs to be rebased with changes that went into master recently.  Will changed a few of the resource strings to make them clearer for users.

**Comment by nguerrera** [comment]
@peterhuene you can resolve this for him. That's the usual process. Accept conflicts in entirely in his favor then build to change things to needs-review etc. Push a commit.

**Comment by nguerrera** [comment]
Thanks

**Comment by peterhuene** [comment]
For strings being translated that have been modified in master, should I treat them still as `new`?

**Comment by nguerrera** [comment]
No accept his side of the conflict entirely (whole file) with "translated" then update xlf as usual and tooling will change to "needs-review-translation" which is correct.

**Comment by peterhuene** [comment]
Sorry I had asked the question without fully reading your comment.  Pushed up the rebase.

**Pull request merged**
