### PR TITLE
Update command description

### LINKED ISSUE #10744: dotnet clean also supports solution files
## Steps to reproduce
`dotnet clean --help` says that the argument is a project but it seems that the command accepts solution as well.
Running on a folder with no solution or project gives the following error message:
`MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.`

## Expected  behavior
`dotnet clean --help` would say it supports solution files as well.

## Actual behavior
`dotnet clean --help` says it supports project files.

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010184\

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.300-preview1-008174 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

### PR DESCRIPTION
**Pull request by Potapy4**
I've updated `dotnet clean`, `dotnet restore`, `dotnet build`, `dotnet publish`, and `dotnet test` commands description.

Fixes #10744

### CODE REVIEW

**Comment by KathleenDollard** [comment]
@peterhuene I just see parameter name changes, not changes to the actual strings. Where do I look for that?

**Comment by peterhuene** [comment]
In this case, the strings already exist since other commands already use them.

Without this change, a command like `dotnet build` will display the following for its argument:

```
$ dotnet build --help
Usage: dotnet build [options] <PROJECT>

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.
...
```

With this change:

```
$ dotnet build --help
Usage: dotnet build [options] <PROJECT | SOLUTION>

Arguments:
  <PROJECT | SOLUTION>   The project or solution file to operate on. If a file is not specified, the command will search the current directory for one.
...
```

**Comment by peterhuene** [comment]
@KathleenDollard are you good with the above change before I merge?

**Comment by Potapy4** [comment]
@KathleenDollard just ping 🔔

**Comment by KathleenDollard** [comment]
Yes, this looks good. Sorry I was slow on this :(

Thanks for the fix :)

**Comment by peterhuene** [comment]
@Potapy4 Thanks for taking the time to fix this!  We appreciate it.

**Pull request merged**
