### PR TITLE
Piotrp msft/3628 rebase

### PR DESCRIPTION
**Pull request by piotrpMSFT**
Rebase of @enricosada's work in #3628 onto rel/1.0.0

### CODE REVIEW

**Comment by enricosada** [comment]
Sry for delay @piotrpMSFT , I have time for oss and rebase in the weekend, like for `dotnet new` f# pr. 
Sry for the waiting, arm zero time. 
Thx for taking care of this one

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX x64 Release Build please.

**Comment by piotrpMSFT** [comment]
@enricosada np. Just want to make sure stuff gets merged before any future release :)

**Comment by eerhardt** [comment]
:shipit:

**Comment by brthor** [comment]
:shipit:

**Pull request merged**
