### PR TITLE
[NO MERGE] TEST CI

### PR DESCRIPTION
**Pull request by eerhardt**
Testing Fedora 24 CI on rel/1.0.1.  Please don't merge.

### CODE REVIEW

**Comment by eerhardt** [comment]
test Fedora24 x64 Release Build

**Comment by livarcocc** [comment]
This does look like an infra-structure problem, since it is happening for 1.0.1 as well.

**Comment by eerhardt** [comment]
test Fedora24 x64 Release Build

**Comment by eerhardt** [comment]
@livarcocc - it hasn't happened on 1.0.1 yet.

**Comment by eerhardt** [comment]
Nevermind. It just happened

**Comment by eerhardt** [comment]
Closing.  This proves that there is something really wrong with the Fedora24 machines we are using.

/cc @nguerrera

**Pull request closed without merging**
