### PR TITLE
Update badges to align with linux build definition

### PR DESCRIPTION
**Pull request by wli3**

### CODE REVIEW

**Comment by wli3** [comment]
@dotnet-bot  test this please

**Comment by wli3** [comment]
@dotnet-bot test this please

**Comment by livarcocc** [comment]
@wli3 how does this fix the issue again? Why is latest being updated now before linux succeeds? Is there any other leg claiming to be linux-x64?

**Comment by wli3** [comment]
Ubuntu and Debian are producing Linux-x64 badge, which is wrong. So when the last build sees the wrong badge of Linux-x64(actually Ubuntu) it think this is done and moved the latest forward.

This fix will correct Ubuntu and Debian build to produce say Ubuntu_14_04 . Also, it will wait for all machine to finish to move to latest

**Comment by wli3** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by wli3** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by livarcocc** [comment]
Got it. Thanks.

**Pull request merged**
