### PR TITLE
Add PowerShell script to update manpage

### PR DESCRIPTION
**Pull request by kasper3**
@nguerrera, added PowerShell script which on Windows does the same thing.

### CODE REVIEW

**Comment by livarcocc** [comment]
Flaky test. Filed https://github.com/dotnet/cli/issues/8959 for it.

@dotnet-bot Test Windows_NT x64 Release Build

**Comment by kasper3** [comment]
@dotnet-bot Test Windows_NT x64 Release Build please

**Comment by nguerrera** [comment]
I really appreciate the effort here, but I'm not sure that we need to have both PowerShell and Bash versions of this. At present, we need to run it manually, and it doesn't really matter much to me if we need to grab a linux box or WSL to do it. I'm not sure if having to make any improvements to this process in two places is a worthwhile sacrifice. At some point, we'll hopefully have it fully automated so that PRs are sent automatically with updated man pages and I would hope that whatever is driving that won't need two parallel scripts.

**Comment by kasper3** [comment]
Appreciate your feedback @nguerrera. I agree that automating this in CI in such a way that whenever someone updates this directory https://github.com/dotnet/docs/tree/master/docs/core/tools, @dotnet-bot sends a PR to this repo. I couldn't figure out the configurations at https://github.com/dotnet/dotnet-ci, otherwise would have sent a PR there to that effect. :)

**Pull request closed without merging**
