### PR TITLE
Localize CLI command line parser

### PR DESCRIPTION
**Pull request by piotrpMSFT**
@srivatsn @nguerrera I found a bunch of non-localized strings in our command line parser. Since these generate our help text, I think we must merge this tonight. I'm finishing the PR now. 

@livarcocc @jgoshi @krwq @jonsequitur @blackdwarf

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
Working on wrapping up build issues. Wanted to make sure people knew this was coming first.

**Comment by piotrpMSFT** [comment]
This PR was significantly slowed by https://github.com/dotnet/cli/issues/5070

**Comment by piotrpMSFT** [comment]
Hacks lead to hacks... opened https://github.com/dotnet/cli/issues/5071 to track having to make LocalizableStrings `public` on account of https://github.com/dotnet/cli/issues/5070. @krwq.

**Comment by livarcocc** [comment]
@dotnet-bot Test RHEL7.2 x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test  Fedora23 x64 Debug Build

**Comment by livarcocc** [comment]
@srivatsn can you approve? Would like to merge once it turns green.

**Comment by srivatsn** [comment]
Approved

**Pull request merged**
