### PR TITLE
Better sdk resolver test

### PR DESCRIPTION
**Pull request by nguerrera**
@livarcocc More coverage is still needed, but this at least adds the InternalsVisibleTo.cs you needed as well as one proper test.

@MattGertz FYI. Test-only change.

### CODE REVIEW

**Comment by nguerrera** [comment]
@livarcocc @jaredpar What is the process/cadence for updating roslyn in the CLI? I did my testing in a VS 2017 dogfooding build and the compilation error in CI is because the CLI doesn't have this 15.1 fix yet: https://github.com/dotnet/roslyn/issues/16935 !

**Comment by nguerrera** [comment]
I see that change was backed out of 15.1 and is slated for 15.3. Still, we need to make sure the compiler lines up between VS and CLI for preview1. Is there a bug tracking that already or is there just a step that's always done to sync up around a release?

**Comment by nguerrera** [comment]
@dotnet-bot Test Debian8.2 x64 Debug Build
@dotnet-bot Test OpenSUSE42.1 x64 Debug Build
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test RHEL7.2 x64 Release Build

**Comment by livarcocc** [comment]
@MattGertz Test change only.

**Pull request merged**
