### PR TITLE
Fixed relative path handling for pack and publish command

### LINKED ISSUE #6700: Dotnet publish output parameter doesn't work
## Steps to reproduce
```
C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox [master +2 ~5 -0 !]> dotnet publish .\Sandbox.sln -c Release -o .\output\
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\docker-compose.dcproj : error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.4\Sdks\Microsoft.Docker.Sdk\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
  Sandbox.Web -> C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\Sandbox.Web\bin\Release\netcoreapp1.1\Sandbox.Web.dll
  Sandbox.Api -> C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\Sandbox.Api\bin\Release\netcoreapp1.1\Sandbox.Api.dll
C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox [master +2 ~5 -0 !]> ls -l .\output\
```

Files are available in `C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\Sandbox.Api\bin\Release\netcoreapp1.1` and `C:\Users\user\Documents\Visual Studio 2017\Projects\Sandbox\Sandbox.Web\bin\Release\netcoreapp1.1`, which is not what I need. `output` folder remains empty.

## Expected  behavior
Compiled dlls in output folder, in the above example in `.\output`. I would expect dlls in output folder as specified by output argument.

## Actual behavior
There is no actual difference running with or without -o parameter.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

I get the same behavior in container from image `aspnetcore:1.1.2-jessie`.

### PR DESCRIPTION
**Pull request by dasMulli**
... when invoked outside the project directory.

This changes the output directory for `pack` and `publish` to be expanded to a full path based on the current working directory. (This is probably most useful when invoking the `pack` command on a solution to generate multiple nupkg files into a single output directory).

The original behaviour was introduced with the move to MSBuild since it treats relative paths as relative to the project being built.

⚠️  **This is a breaking change** ⚠️ 

Pros of taking it:
* Introduce a breaking change only for a major version increment. (fixing this bug would probably have to wait for a 3.0 release)
* People aware of this issue are either using the commands from a project directory or pass absolute paths (did a quick search on GitHub).
* This issue has been reported a number of times and seems to be agreed on to be a buggy behaviour in discussions. (#5996, #6700, #4765, #6063)

Cons of taking it:
* It is a breaking change.

cc @piotrpMSFT @livarcocc @eerhardt @nguerrera (don't really know who to tag)

Fixes #6700, #4765

### CODE REVIEW

**Comment by nguerrera** [comment]
I am supportive of this change. We have gotten *a lot* of feedback about the current behavior being wrong. I think we should take the break.

**Comment by livarcocc** [comment]
I am supportive of this change as well. I just wonder if this is enough or if we should do this in other places as well. Like, in all outputs or maybe all the places where we can specify paths.

**Comment by wli3** [comment]
I changed the base to master, release/2.0.0 is stabilizing

**Comment by dasMulli** [comment]
I just wonder if a change like this should even be made for a minor version increment (2.1). It is breaking, but it really is generally agreed to be a bug.
If so, I think I found additional places where this is needed. I'll rework the PR over the weekend.

**Comment by wli3** [comment]
@dotnet-bot test OpenSUSE42.1 x64 Debug Build

**Comment by wli3** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by wli3** [comment]
@dasMulli we cannot decide if this can go to 2.1 yet, since this is a breaking change. This change will need to hold off for a while. Also we also need to make sure this behavior, not relevant to current directory, is the same across the board.

**Comment by dasMulli** [comment]
@livarcocc @wli3 can we close this against a single issue (and close the other ones as duplicate)? this one would need an overhaul anyway to check for any new possibly project relative paths.
If a 3.* version ever comes along, I'll surely remember this anyway 🤞 
But until then, I don't think there's a point in keeping this open for years.

**Comment by wli3** [comment]
@dasMulli agree, closing :)

**Pull request closed without merging**
