### PR TITLE
Revert "Merge pull request #5529 from piotrpMSFT/piotrpMSFT/merge/1.0.0-rc3"

### PR DESCRIPTION
**Pull request by eerhardt**
I made a mistake merging the 1.0.0-rc3 integration into rel/1.0.0.

This change reverts #5529, if we want to revert this merge.

This reverts commit 41330f072ffc7dc9e5f5accfc34704e87e925f7b, reversing
changes made to 3eee54e4f9985f76f769d4a494a396c16944d4bb.

@livarcocc @piotrpMSFT

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build

**Comment by piotrpMSFT** [comment]
The merge PR was approved by shiproom. Since we haven't merged the revert yet, I'm closing this PR.

**Comment by eerhardt** [comment]
Thanks, @piotrpMSFT.  Sorry for the trouble.  I'll go back to my cave now and get out of your guys' way.  😄

**Comment by piotrpMSFT** [comment]
let's ship this thing! I miss the days when @livarcocc being unhappy about YOLOs was our biggest merge concern 💂

**Pull request closed without merging**
