### PR TITLE
Fix dotnet/templating#1206

### PR DESCRIPTION
**Pull request by mlorbetske**
Fixes dotnet/templating#1206

Description of all of the included changes at the linked issue

### CODE REVIEW

**Comment by mlorbetske** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please

**Comment by nguerrera** [comment]
@leecow @mlorbetske Has this been approved for 2.0.1?

**Comment by leecow** [comment]
Approved

**Comment by nguerrera** [comment]
@MattGertz FYI. Approved dependency flow for 2.0.1

**Pull request merged**
