### PR TITLE
Hoisting FrameworkAssemblies for desktop frameworks during migration.

### PR DESCRIPTION
**Pull request by livarcocc**
@piotrpMSFT @jgoshi @krwq @NTaylorMullen 

Fixes https://github.com/dotnet/cli/issues/4595

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build
@dotnet-bot Test Windows_NT x64 Release Build
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by NTaylorMullen** [comment]
@livarcocc quick question: Does this mark the hoisted framework refs with anything that indicates it can be ripped out later?

**Comment by livarcocc** [comment]
Yeap, the same FromP2P we use for hoisted projectdependencies.

**Pull request merged**
