### PR TITLE
RID specific and app local loads

### PR DESCRIPTION
**Pull request by schellap**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2064)

### CODE REVIEW

**Comment by schellap** [comment]
Cc @gkhanna79

**Comment by schellap** [comment]
@pakrym, @anurse

**Comment by schellap** [comment]
@anurse, could give a look and if you can pass on the test case, I can add one or if you are close go ahead.

**Comment by anurse** [comment]
:shipit:

It fixes the bug we found. Hopefully it doesn't regress anything else... but I guess the best way to find out right now is to merge :).

**Comment by piotrpMSFT** [comment]
:shipit:

**Pull request merged**
