### PR TITLE
Updating NuGet references from beta to rc.

### PR DESCRIPTION
**Pull request by eerhardt**
@emgarten @davidfowl

### CODE REVIEW

**Comment by eerhardt** [comment]
test Debian8.2 x64 Debug Build

**Comment by emgarten** [comment]
I've verified that 3.5.0-rc-1233 is on the nugetbuild feed. :shipit:

**Comment by piotrpMSFT** [comment]
:shipit:

**Comment by piotrpMSFT** [comment]
@eerhardt I just sent mail regarding this change. Merging.

**Pull request merged**
