### PR TITLE
Remove use of Microsoft.Extensions.PlatformAbstractions

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@pranavkm thanks for fixing https://github.com/dotnet/cli/pull/3443!

**Comment by eerhardt** [comment]
:shipit: :shipit: :shipit: :shipit: 

Thanks for the help!

**Comment by pranavkm** [comment]
Do I need to merge this back to rel/1.0.0?

**Comment by eerhardt** [comment]
> Do I need to merge this back to rel/1.0.0?

No, we will take care of merging `rel/1.0.0-preview2` into `rel/1.0.0`.  No need for dual checkins.

**Pull request merged**
