### PR TITLE
Eliminate response waiting period

### PR DESCRIPTION
**Pull request by troydai**
Issue #2996 

Per discussion with @piotrpMSFT we decide to eliminate all the response waiting period by reading fixed number of response to speed up test and avoid race condition.

### CODE REVIEW

**Comment by troydai** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please

**Comment by eerhardt** [comment]
> @dotnet-bot test RHEL7.2 x64 Release Build please

@troydai - what was the failure? it wasn't a projectmodel failure was it?

**Comment by troydai** [comment]
It is. it looks like a flip.

**Comment by troydai** [comment]
sign off?

**Comment by troydai** [comment]
@piotrpMSFT can you sign off this?

**Comment by troydai** [comment]
ping @piotrpMSFT

**Comment by troydai** [comment]
ping @piotrpMSFT

**Comment by piotrpMSFT** [comment]
:shipit:

**Pull request merged**
