### PR TITLE
Use latest command line parser

### PR DESCRIPTION
**Pull request by nguerrera**
@livarcocc @dotnet/dotnet-cli

### CODE REVIEW

**Comment by nguerrera** [comment]
Test Windows_NT x64 Release Build
Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@MattGertz Flow of dependencies into the CLI. We need to do a slight update on our tests to reflect the fact that we removed the basic description from the help. We had agreed to do that at the beginning of 2.0 and finally pulled the dependency to do that.

**Comment by nguerrera** [comment]
Rebased to resolve merge conflict. No changes since review.

**Comment by nguerrera** [comment]
Test Windows_NT x64 Release Build

**Comment by nguerrera** [comment]
Test Ubuntu16.10 x64 Debug Build

**Pull request merged**
