### PR TITLE
Update compiler

### PR DESCRIPTION
**Pull request by KevinRansom**
Update compiler to include default properties for project system property pages.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot test OSX10.12 x64 Release Build  please.

**Comment by KevinRansom** [comment]
@dotnet-bot test Windows_NT x64 Release Build  please

**Comment by KevinRansom** [comment]
Tagging @MattGertz for approval pending CI tests.

**Customer scenario:** 
This upgrades the F# compiler to the latest build.  It contains fixes that enable Property pages for dotnet SDK project to edit a number of properties that are not editable without this change.

**Workarounds, if any:**
A developer can edit the project file to Manually set these values

**Performance impact : **
None

**Root cause analysis :** Not yet implemented.  This is the first release to support dotnet sdk projects.
**How was this bug found?:** Adhoc testing

**Comment by livarcocc** [comment]
@MattGertz Flow of dependencies into the CLI. No VS insertion required.

**Pull request merged**
