### PR TITLE
Add markdown verison of en-EULA

### PR DESCRIPTION
**Pull request by jasonwilliams200OK**
Contributes to #2731.

cc: @Elion

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2738)

### CODE REVIEW

**Comment by blowdart** [comment]
This appears to be for the ".NET Library". It's frankly not clear what that covers, is the cli? the framework? something else entirely?

**Comment by jasonwilliams200OK** [comment]
@blowdart, this is just a markdown variant of https://github.com/dotnet/cli/blob/13817c7/packaging/osx/sharedframework/resources/en.lproj/eula.rtf
See https://github.com/dotnet/cli/tree/13817c7/packaging/osx/sharedframework/resources/en.lproj

**Comment by blowdart** [comment]
Yes .. so I'd posit that's wrong there too.

**Comment by blackdwarf** [comment]
@jasonwilliams200OK let's hold off on this one for a while, there are talks about whether the EULA is the right one or not for the CLI we should figure it out this week.

**Pull request closed without merging**
