### PR TITLE
Revert "Add performance tests"

### PR DESCRIPTION
**Pull request by piotrpMSFT**
Reverts dotnet/cli#2663

This got merged a bit early. @brianrob @pakrym can you guys close on any remaining open issues?

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2787)

### CODE REVIEW

**Comment by brianrob** [comment]
Yes.  I am fine with @pakrym's change as long as it runs under the harness and produces data.  @dpodder was looking into the issue that @pakrym saw.  @dpodder, were you able to determine what happened?

**Comment by dpodder** [comment]
@brianrob The last issue I'm aware of should now be resolved in the current iteration of PR #2746.

**Comment by brianrob** [comment]
Thanks @dpodder.  @pakrym, can you please try the latest iteration in #2746 and see if your tests run and you get results?

**Comment by pakrym** [comment]
I took latest script but still see:
```
# xunit-performance repo was detected at 'd:\temp\xperf', skipping git clone
# xunit-performance at 'd:\temp\xperf' was already built, skipping CiBuild. Use --rebuild to force rebuild.
# Prepending D:\github\dotnet\cli\artifacts\win10-x64\stage2 to PATH
# Deleting D:\github\dotnet\cli\test\Performance\project.lock.json
# Dotnet restore using "D:\github\dotnet\cli\artifacts\win10-x64\stage2\dotnet.exe"...
  $ cd "D:\github\dotnet\cli\test\Performance"
  $ D:\github\dotnet\cli\artifacts\win10-x64\stage2\dotnet.exe restore > "D:\github\dotnet\cli\test\Performance\logs\run-perftests\dotnet-restore-using-d-github-dotnet-cli-artifacts-win10-x64-stage2-dotnet-exe.log"
# Run runid.test...
  $ cd "D:\github\dotnet\cli\test\Performance"
  $ d:\temp\xperf\tools\bin\dotnet run -p d:\temp\xperf\src\cli\Microsoft.DotNet.xunit.performance.runner.cli -c Release -- -runner D:\github\dotnet\cli\artifacts\win10-x64\stage2\dotnet.exe -runid runid.test -runnerargs "test D:\github\dotnet\cli\test\Performance\project.json -c Release" > "D:\github\dotnet\cli\test\Performance\logs\run-perftests\run-runid-test.log"
# Reverting PATH
! ERROR: Command `d:\temp\xperf\tools\bin\dotnet run -p d:\temp\xperf\src\cli\Microsoft.DotNet.xunit.performance.runner.cli -c Release -- -runner D:\github\dotnet\cli\artifacts\win10-x64\stage2\dotnet.exe -runid runid.test -runnerargs "test D:\github\dotnet\cli\test\Performance\project.json -c Release" > "D:\github\dotnet\cli\test\Performance\logs\run-perftests\run-runid-test.log"` returned with error code 2147516547. See 'D:\github\dotnet\cli\test\Performance\logs\run-perftests\run-runid-test.log' for details.
```

```
Project Microsoft.DotNet.xunit.performance.runner.cli (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
The targeted framework { "Microsoft.NETCore.App": "1.0.0-rc2-3002545" } was not found.
  - Check application dependencies and target a framework version installed at:
      d:\temp\xperf\tools\bin\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0-rc2-3002543

```

**Comment by brianrob** [comment]
@pakrym can you please delete your d:\temp\xperf directory and try again?  We took a change to xunit-performance to fix this issue.  Thanks!

**Comment by pakrym** [comment]
@brianrob ran fine, got `.xml` and `.csv` with data.

**Comment by brianrob** [comment]
Excellent.  That's great!

**Pull request merged**
