### PR TITLE
make dotnet-build show build summary

### PR DESCRIPTION
**Pull request by krwq**
Fixes https://github.com/dotnet/cli/issues/5110
If going into RC3 it requires https://github.com/dotnet/cli/commit/0be2f7c1fad52e2bb11bcd792dd880ec1ffa4135

### CODE REVIEW

**Comment by livarcocc** [comment]
I think you should target RC3 with this. It is simple enough, we should try to take it to shiproom.

**Comment by krwq** [comment]
@livarcocc, it also requires https://github.com/dotnet/cli/commit/0be2f7c1fad52e2bb11bcd792dd880ec1ffa4135 for RC3. I do not have preference for RC3 vs RTM

**Comment by livarcocc** [comment]
We have 15.1.0-preview-000509-03 in rc3 as well, for the msbuild version.

**Comment by krwq** [comment]
@dotnet-bot test OpenSUSE13.2 x64 Debug Build please

**Comment by krwq** [comment]
@MattGertz can I get approval for this?

**Comment by piotrpMSFT** [comment]
@MattGertz this was approved in shiproom today, adding the flag and merging.

**Pull request merged**
