### PR TITLE
Insert NuGet Build 4.6.2-rtm-5055 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.6.2-rtm-5055 into cli release/2.1.1xx branch

### CODE REVIEW

**Comment by livarcocc** [comment]
@rohit21agrawal what is the bug or PR for this insertion in VS? I need to guarantee this has been merged in VS before merging it here.

**Comment by livarcocc** [comment]
@leecow as this will require yet another release of the CLI.

**Comment by livarcocc** [comment]
I see the VS insertion hasn't been merged yet, so I will hold off on merging this one until then. Please, comment in here when the VS merge goes through.

cc @MattGertz this is the one that @rrelyea gave us a heads up for.

**Comment by jainaashish** [comment]
yeah, I'll let you know once we merge the VS insertion PR.

**Pull request merged**
