### PR TITLE
Added triage helpers badge

### PR DESCRIPTION
**Pull request by aawadall**
skip ci please

Added triage helpers badge to README.md file

### CODE REVIEW

**Comment by livarcocc** [comment]
@aawadall what is this?

**Comment by aawadall** [comment]
This is the badge proposed by Code Triage to triage issues posted to this repo.

**Comment by livarcocc** [comment]
I am sorry, I am not sure what that is. Do you have links to more information?

@terrajobst @richlander you folks aware of this?

**Comment by nguerrera** [comment]
Since we have not heard back and I don't see this in other dotnet repos, I am closing.

**Pull request closed without merging**
