### PR TITLE
Moves version suffix from beta to rc2

### PR DESCRIPTION
**Pull request by piotrpMSFT**
/cc @Sridhar-MS @brthor @Petermarcu @muratg @danroth27 @blackdwarf @gkhanna79 @schellap 

Changes our version suffix from beta to rc2

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2325)

### CODE REVIEW

**Comment by brthor** [comment]
:shipit: :shipit: :shipit:

**Comment by Sridhar-MS** [comment]
:shipit:

**Comment by muratg** [comment]
@pranavkm Do we need to change anything in our CI for this?

**Comment by pranavkm** [comment]
Yup - we need to update our build quality.

**Comment by piotrpMSFT** [comment]
@Petermarcu this change is confirmed to update installer strings as well.

**Comment by pranavkm** [comment]
Does this also affect the channel to pick up new CLI builds from? We currently default to beta.

**Comment by Sridhar-MS** [comment]
The channel remains as beta.

**Comment by pranavkm** [comment]
Thanks!

**Pull request merged**
