### PR TITLE
Fixed dictionary key conflict on binding redirects generation

### LINKED ISSUE #865: Error on dotnet run
Guys,

I'm getting an error when running dotnet run or dotnet build:
_An item with the same key has already been added. Key: (log4net, neutral, 669e0ddf0bb1aa2a)_

Not sure how to proceed.

Thank you!

A bit more context:
My project.lock.json contains the following bits:

```
"Log4Net/2.0.5": {
        "type": "package",
        "compile": {
          "lib/net45-full/log4net.dll": {}
        },
        "runtime": {
          "lib/net45-full/log4net.dll": {}
        }
      },
      "log4net.Ext.Json.1.2.13/1.2.13.20140804": {
        "type": "package",
        "dependencies": {
        "log4net": "2.0.3"
        },
        "compile": {
          "lib/net35-full/log4net.Ext.Json.dll": {}
        },
        "runtime": {
          "lib/net35-full/log4net.Ext.Json.dll": {}
        }
      }
```

Notice the log4net dependency of log4net.Ext.Json has different casing than the root Log4Net dependency. Could this be the issue?

UPDATE2:
Changed the cached nuspec file for log4net.Ext.Json to say Log4Net and it made the error go away. At this point I think this is a bug. I'll try and have a look at the code.

### PR DESCRIPTION
**Pull request by marono**
Due to packages including assemblies other than their primary output,
under some circumstances, the same assembly may be considered multiple
times for bindign redirect generation, which would cause the build to
fail because of dictionary key collisions. Fixed the issue by filtering
the assemblies considered for binding redirects to only include
exports in the runtime list only when the same export is not already
published via a compilation list of another dependency.

Fix #865

### CODE REVIEW

**Comment by davidfowl** [comment]
This needs a test

**Comment by marono** [comment]
Is that something I've messed up? When building it locally it seems to succeed...

**Comment by shahid-pk** [comment]
@marono all work is done in the rel/1.0.0 branch may be master was broken before your patch.

**Comment by marono** [comment]
Do you need me to rebase it, or will you do it ?

**Comment by davidfowl** [comment]
@maririos 2 things:
- Send the pull request to rel/1.0.0
- Write a test that verifies the problem is fixed.

**Comment by marono** [comment]
Ok, will do, thanks!

**Pull request closed without merging**
