### PR TITLE
Updating dependencies from last known good builds

### PR DESCRIPTION
**Pull request by eerhardt**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/1978)

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@eerhardt any ideas on this one?

**Comment by eerhardt** [comment]
There are a couple breaking changes in CoreFX again that I'm working through.  Most notably, I'm blocked by the System.Threading.Tasks assembly version was downgraded from 4.0.11 to 4.0.10, which is causing crossgen to fail for csc.dll. @ericstj is working on rolling this change back until all the teams can get on the latest builds.

**Comment by ericstj** [comment]
Today's builds have the workaround

**Comment by eerhardt** [comment]
This is being replaced by https://github.com/dotnet/cli/pull/1990

**Pull request closed without merging**
