### PR TITLE
Insert NuGet Build 4.8.0-preview5.5328 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.8.0-preview5.5328 into cli release/2.1.4xx branch

### CODE REVIEW

**Comment by PatoBeltran** [comment]
@livarcocc the PR for this insertion was merged yesterday to VS.

**Comment by PatoBeltran** [comment]
@nguerrera @dsplaisted since @livarcocc is OOF

**Comment by dsplaisted** [comment]
@dotnet-bot test this please

**Comment by nguerrera** [comment]
Once this is merged, we have to to the dance back and forth with https://github.com/dotnet/sdk/pull/2391

**Pull request merged**
