### PR TITLE
Extract localizable strings from dotnet-publish

### PR DESCRIPTION
**Pull request by vsccarl**
Extracted localizable strings from the dotnet-publish command into LocalizableStrings.cs

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
Noted flaky test here: https://github.com/dotnet/cli/issues/4660#issuecomment-262083208

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please.

**Comment by MattGertz** [comment]
Approved pending successful tests.

**Comment by vsccarl** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please.

**Comment by vsccarl** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build

**Comment by nguerrera** [comment]
@piotrpMSFT Can this be merged? Is this the last of the strings?

**Comment by piotrpMSFT** [comment]
@vsccarl is this the last of them?

**Comment by vsccarl** [comment]
@nguerrera @piotrpMSFT There are a few more that I should be able to finish up this week.

**Pull request merged**
