### PR TITLE
Update Template Engine and templates for 1.x

### PR DESCRIPTION
**Pull request by mlorbetske**
@KevinRansom

### CODE REVIEW

**Comment by mlorbetske** [comment]
It looks like these are all failing for the F# templates due to duplicate compile items (from the implicit globs in the SDK & the explicit ones that specify the ordered items for compile).

@KevinRansom should the templates not have the compile items to get the `fs` files in some order or should the implicit globs for F# be removed?

```
19:36:38                      /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.1.0/release_osx_x64_prtest/artifacts/osx.10.11-x64/stage2/sdk/1.1.0-preview1-005066/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.DefaultItems.targets(165,5): error : Duplicate 'Compile' items were included. The .NET SDK includes 'Compile' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultCompileItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'Program.fs' [/Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.1.0/release_osx_x64_prtest/test/dotnet-new.Tests/bin/Release/netcoreapp1.1/TemplateRestoresAndBuildsWithoutWarningsF#_console/TemplateRestoresAndBuildsWithoutWarningsF#_console.fsproj] [/Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.1.0/release_osx_x64_prtest/build/test/RunTest.proj]
```

**Comment by KevinRansom** [comment]
@mlorbetske I expect you are suffering from 1.1 not having the F# dotnet sdk updates.  

@livarcocc  ... I pulled the PR with the F# sdk updates just now.  The dependency needs to be updated, before Mike can pull this.  Or Mike can disable the f# tests, and we re-enable them as soon as the sdk is updated.

Kevin

**Comment by livarcocc** [comment]
@KevinRansom @mlorbetske I have updated this PR with the new SDK.

**Comment by livarcocc** [comment]
@MattGertz This will require an insertion into VS and this will enable the F# scenarios with the CLI in the box with VS.

**Comment by MattGertz** [comment]
Approved per JoC's F# approval yesterday.

**Comment by livarcocc** [comment]
Closing this one in favor of https://github.com/dotnet/cli/pull/7046.

**Pull request closed without merging**
