### PR TITLE
Re-enable solution building tests

### PR DESCRIPTION
**Pull request by jgoshi**

### CODE REVIEW

**Comment by jgoshi** [comment]
This doesn't seem to have the fix either.

**Comment by livarcocc** [comment]
@rainersigwald Can you help us figure out which version of the SDK contains this build fix?

We have SDK 1.0.0-alpha-20170217-2 and MSBuild 15.1.548.

If these are supposed to contain the fix, then maybe there was a missing case or maybe we are doing something wrong in the CLI.

**Comment by jgoshi** [comment]
Looks like we can wait until next week. See this PR for comments:
https://github.com/dotnet/cli/pull/5690

**Comment by rainersigwald** [comment]
In rel-1.0.0 land, things should be fixed. MSBuild 15.1.548 should have the MSBuild side of the change, and I'd expect that version of the SDK to have its side but haven't confirmed yet. Looking at that . . .

**Comment by rainersigwald** [comment]
SDK 1.0.0-alpha-20170217-2 appears to have its side of the fix, too. @jgoshi can you reopen this? I think it deserves investigation.

**Comment by jgoshi** [comment]
I already deleted the branch. Will recreate it.

**Comment by jgoshi** [comment]
The fix is in and works for us. The failure I was seeing was due to the file path being too long (on Windows when builds result in paths longer than 256 characters we start seeing errors). Once I shorted the test asset directory name the tests now pass.

**Comment by jgoshi** [comment]
@livarcocc Since this is a test only change can we just merge it? Also I can discard the similar change I was going to make in the master branch right? Since this change will move over the next time we merge rel/1.0.0 into master?

**Comment by rainersigwald** [comment]
`MAX_PATH` strikes again :( https://github.com/Microsoft/msbuild/issues/53 . . . someday.

**Comment by jgoshi** [comment]
test Fedora24 x64 Release Build

**Comment by eerhardt** [comment]
@jgoshi - you can ignore the Fedora24, OpenSUSE42 and Ubuntu16.10 failures.  They aren't supposed to be there.  I think I've fixed it so you shouldn't see those 3 legs anymore on new runs.

**Comment by jgoshi** [comment]
test Windows_NT x86 Debug Build

**Comment by jgoshi** [comment]
Fixes #5205

**Comment by piotrpMSFT** [comment]
@MattGertz merging test-only change, re-enabling tests that were blocked by upstream issues.

**Pull request merged**
