### PR TITLE
Add help job

### PR DESCRIPTION
**Pull request by jyoungyun**
The help job is not implemented in the cli project.
Add help job.

### CODE REVIEW

**Comment by jyoungyun** [comment]
@dotnet-bot Please test Ubuntu x64 Release Build

**Comment by jyoungyun** [comment]
Can anyone review it? Or is it a problem to merge this patch?

**Comment by livarcocc** [comment]
I am not sure what this is and what it does, can you clarify? Why do we want/need this?

**Comment by jyoungyun** [comment]
@livarcocc This patch will help to print out help message from dotnet-bot when you comment `@dotnet-bot help`. You can see the same code in coreclr, corefx and core-setup.
core-setup: https://github.com/dotnet/core-setup/blob/master/netci.groovy#L152~L154
coreclr:https://github.com/dotnet/coreclr/blob/master/netci.groovy#L2662-L2664
corefx:https://github.com/dotnet/corefx/blob/master/netci.groovy#L562-L564
This is the same patch: https://github.com/dotnet/corefx/commit/86810135282a8a912195fac36b52c8d976a529d3

**Comment by jyoungyun** [comment]
@dotnet-bot help

**Pull request merged**
