### PR TITLE
Set Docker Internal UID to Host UID, Remove Postbuild step

### LINKED ISSUE #205: Jenkins cannot access dotnet-linux-x64...tar.gz
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_cli_debug_ubuntu_prtest/265/console

java.io.IOException: remote file operation failed: /mnt/j/workspace/Private/dotnet_cli_debug_ubuntu_prtest at hudson.remoting.Channel@68a5c403:dci-ub-bld-12: java.nio.file.AccessDeniedException: /mnt/j/workspace/Private/dotnet_cli_debug_ubuntu_prtest/artifacts/packages/dnvm/dotnet-linux-x64.0.0.1-alpha-20151116-174400.tar.gz

### PR DESCRIPTION
**Pull request by brthor**
These changes will use docker's new Dockerfile Arguments to
pass the Host User ID to the docker container at build time.
This allows the docker container to set it's internal user
to match that of the host. When using shared volumes between
the host and container, this prevents files created in the
container from being owned by root.

This will solve our problem of needing a cleanup step after
every ubuntu CI run.

NOTE: These changes require docker 1.9 (which our CI machines are using)

Fixes #205 

/cc @piotrpMSFT @Sridhar-MS @glennc @anurse

### CODE REVIEW

**Comment by brthor** [comment]
OSX Failure: ./scripts/ci_postbuild.sh: No such file or directory

This is expected, this step is removed. After merge updates to netci.groovy will take effect and the CI jobs will not try to execute this job.

**Comment by brthor** [comment]
@dotnet-bot test this please

Unexpected weird lintian bug on one of the Ubuntu runs, doesn't break anything but want to see if it happens again.

**Comment by brthor** [comment]
All failures here seem to be from the removal of the postbuild step, or unrelated CI issues. This is expected. 

@Sridhar-MS mind taking a look to confirm?

**Comment by Sridhar-MS** [comment]
:shipit:

**Comment by brthor** [comment]
Want to get this merged by 1 today, if anyone else was wanting to take a look

**Pull request merged**
