### PR TITLE
Update NuGet to 3.5.0-beta-1246

### PR DESCRIPTION
**Pull request by alpaix**
Updating NuGet packages version to 3.5.0-beta-1246.

//cc @emgarten @Petermarcu

### CODE REVIEW

**Comment by weshaggard** [comment]
Is this a downgrade? At least from a semantic versioning prospective isn't `beta-1246` less then `rc-1233`?

**Comment by eerhardt** [comment]
From semantic versioning, yes it is a downgrade.  But changing it from beta to rc was a mistake in the first place.  This is correcting that mistake.

@yishaigalatzer

**Comment by yishaigalatzer** [comment]
@eerhardt is right

**Comment by weshaggard** [comment]
Sounds good I just wanted to make sure it was intentional and that we don't expect it to impact any scenarios.

**Pull request merged**
