### PR TITLE
Upgrade StdLib References to rc2-23614, Upgrade Runtime Version

### PR DESCRIPTION
**Pull request by brthor**
Changed `dotnet new` template as well as a part of these changes to reference only `NETStandard.Library`. 

@Sridhar-MS This version of stdlib includes the runtime as well. 

cc @davidfowl Will these changes alleviate the issues with shims you were referring to?

### CODE REVIEW

**Comment by brthor** [comment]
Seeing `Segmentation fault  (core dumped)` with the upgraded runtime again.

Last diagnosis was a bug in CoreHost not catching an initialization failure.

Made changes in pal.h to change hresult_t to int instead of long per @sergiy-k 's suggestion.

@anurse PTAL at this commit (https://github.com/dotnet/cli/commit/efa484d8c4f4edf3b58eeaa4421bb4467a169299)

**Comment by anurse** [comment]
Sure, that looks like C++ code to me. :trollface: 

Seriously though, seems fine to me and if @sergiy-k says it's better, I'd be inclined to believe him given I have almost no C/C++ experience ;P

**Comment by brthor** [comment]
Yeah it was a small change :smile: Just wanted to make sure you were aware of that.

**Comment by brthor** [comment]
On Ubuntu/Mac:
failed to initialize CoreCLR, HRESULT: 0x80131500

Followed up via email w/ @kouvel

**Comment by davidfowl** [comment]
It's amazing that updating these packages is so hard...

**Comment by brthor** [comment]
@dotnet-bot test this please

**Comment by brthor** [comment]
Looks like crossgen may be causing this issue. Deleting "mscorlib.ni.dll" makes it go away.

**Comment by anurse** [comment]
Given the crossgen issues, can we just update stdlib (leave Runtime as-is) and push this ASAP? @ericstj was saying this should work in our scenarios (based on my understanding of what we use today). It will have issues, but this is really blocking a lot of ASP.NET work that we want to get in before the holidays.

**Comment by brthor** [comment]
@anurse difficulty is 23614 includes the runtime as a dependency. We can try it though.

**Comment by anurse** [comment]
The runtime is listed explicitly in our "Microsoft.DotNet.Runtime" project, so the older version should eclipse the newer one.

**Comment by brthor** [comment]
@anurse that's right. Looks like crossgen issues are resolved here. 

Fixed merge conflicts, if builds pass let's merge this.

If we see issues, downgrade runtime and go with that.

**Comment by brthor** [comment]
This looks like a failure in ILC:

malloc(): smallbin double linked list corrupted: 0x0000000000c67ef0 

@schellap

**Comment by brthor** [comment]
@anurse Even if we downgrade the runtime in the runtime project, that only publishes to `runtimes/coreclr` 

The tool runtime would still be coming from stdlib unless we overwrite it.

**Comment by gkhanna79** [comment]
@brthor Can you please share a repro? We dont see this in the CoreRT CI.

**Comment by brthor** [comment]
@gkhanna79 I'll put a zip together with these bits

**Comment by anurse** [comment]
@brthor I'm pretty sure the build script copies `runtime/coreclr` into `bin`.

How soon can we get this in? Could we just skip the failing test for now? We really need to unblock ASP.NET work.

**Comment by schellap** [comment]
I think you might need a new ILC. We discovered an issue with a PInvoke signature missing the this pointer. This has existed for a while but I think it is showing itself up now. I will upload a new ILC for you.

**Comment by brthor** [comment]
@schellap We need to get this checked in ASAP. I am going to need to skip this test until we get the new ILC

**Comment by anurse** [comment]
:+1: Thanks!

**Comment by brthor** [comment]
OSX Release failure is unrelated.

**Pull request merged**
