### PR TITLE
Update templates to carry test SDK 15.8.0-preview-20180610-02

### PR DESCRIPTION
**Pull request by mlorbetske**
cc @smadala

### CODE REVIEW

**Comment by mlorbetske** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please

**Comment by mlorbetske** [comment]
I believe we're having the same issue as in #9492, I'll add the templating MyGet feed back to the NuGet.targets for the time being

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build

**Comment by smadala** [comment]
@mlorbetske @livarcocc Thanks! I hope this will land in 15.8 preview 4.

**Pull request merged**
