### PR TITLE
update nuget and sdk to 3.6.0-rc-1954 and 1.0.0-alpha-20161006-3

### PR DESCRIPTION
**Pull request by rohit21agrawal**
@livarcocc @eerhardt @rrelyea

### CODE REVIEW

**Comment by eerhardt** [comment]
:shipit: when green

**Comment by rohit21agrawal** [comment]
@dotnet-bot test this please

**Comment by rohit21agrawal** [comment]
@dotnet-bot test OSX x64 Release Build please

**Comment by livarcocc** [comment]
You also need to update NuGet at the Compiler.Common project and the ProjectModel.Tests and Utils.Tests projects.

**Comment by rohit21agrawal** [comment]
@livarcocc yeah figured that out..have updated them now.

**Comment by rohit21agrawal** [comment]
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by livarcocc** [comment]
@dotnet-bot Test OSX x64 Release Build

**Pull request merged**
