### PR TITLE
move all version suffixes to preview3 and rc4

### PR DESCRIPTION
**Pull request by brthor**
PTAL @eerhardt @piotrpMSFT @livarcocc

### CODE REVIEW

**Comment by brthor** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by brthor** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by brthor** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by brthor** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by livarcocc** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build

**Comment by eerhardt** [comment]
We should sit down and discuss our plans here before moving forward with this. Questions I have:

- Does preview3 start consuming builds from "master" of corefx?
- If so, does preview3+ support 1.0.0 of .NET Core?  Does it support multiple versions of the runtime?
- What are our plans for versioning ProjectModel and friends going forward?

@blackdwarf

**Comment by brthor** [comment]
> We should sit down and discuss our plans here before moving forward with this. Questions I have:

We need to do this quickly then because we can't merge anything into `rel/1.0.0` before this is merged or our versions are messed up.

I agree those points need discussion, but should they block this PR going in?

**Comment by eerhardt** [comment]
:shipit:

**Pull request merged**
