### PR TITLE
Minor text fixes for ko

### PR DESCRIPTION
**Pull request by Mardoxx**
"NET Core" -> ".NET Core" for in Korean translation

skipciplease

### CODE REVIEW

**Comment by Mardoxx** [comment]
Why are these building when CI is meant to be skipped?

**Comment by livarcocc** [comment]
it is not all one word. It is three separate words.

**Comment by livarcocc** [comment]
@dotnet-bot Test RHEL7.2 x64 Release Build
@dotnet-bot Test OpenSUSE42.1 x64 Debug Build

**Comment by Mardoxx** [comment]
Ah right, may be more clear to have it say "skip_ci_please" replace _ for spaces or something!

**Comment by livarcocc** [comment]
@MattGertz for approval. Just is just adding a . to .NET that we were missing in the korean strings. Do you need the template for this?

**Comment by MattGertz** [comment]
Approved & thanks!

**Pull request merged**
