### PR TITLE
Insert NuGet Build 4.6.0-rtm-4918 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.6.0-rtm-4918 into cli release/2.1.1xx branch

### CODE REVIEW

**Comment by livarcocc** [comment]
@MattGertz Another one that will require a VS insertion.

**Comment by MattGertz** [comment]
@livarcocc OK.

**Comment by livarcocc** [comment]
@rohit21agrawal has this been approved and inserted into VS?

**Comment by rohit21agrawal** [comment]
@livarcocc it's underway. @emgarten can link to the VS PR.

**Comment by emgarten** [comment]
VS PR is here: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/105895

**Comment by livarcocc** [comment]
I see the VS PR was merged. Merging this one as well.

**Pull request merged**
