### PR TITLE
Added dotnet list package command

### PR DESCRIPTION
**Pull request by jp2masa**
Added `dotnet list package` command.
Related to #4746

### CODE REVIEW

**Comment by jp2masa** [comment]
@dotnet-bot
test CentOS7.1 x64 Debug Build please
test Debian8.2 x64 Debug Build please

**Comment by livarcocc** [comment]
@KathleenDollard This is an awesome contribution, can you take a look at it to make sure it aligns with the other commands? I would love to take this.

@jp2masa Can you just revert your changes to the xlf files? We will have them translated, you don't need to worry about it. Just re-run the build with the /p:UpdateXlfOnBuild=true. It will override the xlf files and then you can push again.

Once again, thanks for this PR, it looks great.

**Comment by jp2masa** [comment]
I ran `build.cmd /p:UpdateXlfOnBuild=true` and nothing changed. Should I delete the xlf files before running the command?

**Comment by wli3** [comment]
Hi @jp2masa sorry for the delay. yes, you will need to revert all change in .xlf files (including new xlf)

These xlf file will have right "need translate here" and be hand over to localisation team later. (Just curious you translated to all these language yourself?)

**Comment by jp2masa** [comment]
@dotnet-bot
test Windows_NT x64 Release Build please
test Windows_NT x86 Debug Build please
test Windows_NT_ES x64 Debug Build please

**Comment by spboyer** [comment]
This is a big gap in the CLI for listing packages within a project and has been sitting unmerged for a long time. Can we get this looked at? @KathleenDollard @livarcocc

**Comment by livarcocc** [comment]
Closing this one in favor of https://github.com/dotnet/cli/pull/9935.

**Pull request closed without merging**
