### PR TITLE
bump nuget version to 3.6.0-beta.1.msbuild.15

### PR DESCRIPTION
**Pull request by rohit21agrawal**
- If this PR should not run tests please add text "skip[REMOVE_THIS]ci[REMOVE_THIS]please" (remove the marked text, no quotes).
- Please add description for changes you are making.
- If there is an issue related to this PR, please add the reference.

CC: @emgarten @rrelyea @livarcocc @eerhardt

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
@dotnet-bot test this please.

**Comment by rohit21agrawal** [comment]
@dotnet-bot test Fedora23 x64 Debug Build please.

**Comment by rohit21agrawal** [comment]
@dotnet-bot test OpenSUSE13.2 x64 Debug Build please.

**Comment by rohit21agrawal** [comment]
@eerhardt @rrelyea @livarcocc @joelverhagen @emgarten  all checks passed - can i get an approval to merge this in?

**Comment by eerhardt** [comment]
:shipit:  go for it

**Pull request merged**
