### PR TITLE
Fix function error not found

### LINKED ISSUE #1689: Ubuntu initial experience
## Steps to reproduce
clean ubuntu server 14.04
./build.sh

## Expected  behavior
Expected error: Unable to find Clang Compiler

## Actual behavior
line 67: error: command not found

Seems that command "error" is not recognized and thus I'm not seeing an actual error.

### PR DESCRIPTION
**Pull request by brthor**
Fixes #1689 

cc @krwq @piotrpMSFT @Sridhar-MS

### CODE REVIEW

**Comment by brthor** [comment]
@dotnet-bot test Windows_2016 Debug Build please

**Comment by krwq** [comment]
:shipit: btw what's the windows failure?

**Comment by brthor** [comment]
Started a thread for the windows failure, think you're on it.

It's unrelated so going to merge this.

**Comment by brthor** [comment]
@dotnet-bot test Windows_2016 Debug Build please

**Comment by brthor** [comment]
@dotnet-bot test this please

**Pull request merged**
