### PR TITLE
WIP no merge, for investigation - ingest runtime Rpm agnostic and produce Rpm agnostic packages

### PR DESCRIPTION
**Pull request by wli3**
this RP is built on top of https://github.com/dotnet/cli/pull/8625. I think it is better to create a different PR

The above insertion failed due to CLI cannot ingest runtime RPM agnostic packages. After this change, CLI will **produce** RPM agnostic packages as well. 

example file name `dotnet-sdk-2.1.300-preview2-008268-x64.rpm`
cc @leecow 
cc @dagood after this change version page need to change as well. Basically, cli rpm will look the same as cli deb

### CODE REVIEW

**Comment by wli3** [comment]
@danmosemsft after making the change of rpm package. It still fail with the test in the original insertion.

Any idea?
Microsoft.DotNet.Tests.GivenAProjectToolsCommandResolver.ItAddsFxVersionAsAParamWhenTheToolHasThePrefercliruntimeFile

**Comment by wli3** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build

**Comment by wli3** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build

**Comment by wli3** [comment]
Sorry the original failing test is "Microsoft.DotNet.Tests.GivenAProjectToolsCommandResolver.**ItReturnsNullWhenProjectDirectoryDoesNotContainAProjectFile**" The above is not the same. And it disappeared after rerun

**Comment by wli3** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build

**Comment by wli3** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build i cannot repo it on my rehl7 machine

**Comment by wli3** [comment]
GivenAnInstalledPackageUninstallRollsbackWhenTransactionAborts(testMockBehaviorIsInSync: False)

it fails on test set up. And other tests has the same call. Let alone there is not shared folders. Let me rename that test to see that happened

**Comment by wli3** [comment]
> GivenAnInstalledPackageUninstallRollsbackWhenTransactionAborts(testMockBehaviorIsInSync: False)

looks like a strange issue. rename the test fixed it

**Comment by nguerrera** [comment]
> looks like a strange issue. rename the test fixed it

That is mortifying.

**Comment by nguerrera** [comment]
Why did you have a hunch it would?

**Comment by wli3** [comment]
Let's revert the rename, and see, if it fails, at least we can get a steady repro

**Comment by wli3** [comment]
@nguerrera well we get a steady repro.

**Comment by wli3** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by danmosemsft** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please (myget timeout)

**Comment by wli3** [comment]
Here is the log result

```
00:51:13     14>Done Building Project "/mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/build/test/RunTest.proj" (default targets).
00:51:14     14>RunTest:
00:51:14          ####packageId='global.tool.console.demo'
00:51:14          ####stageDirectory='"/mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/bin/3/linux-x64/bin/Microsoft.DotNet.ToolPackage.Tests/Release/netcoreapp2.1/kisckzw0.amo/.stage/y3lvcxuc.yzr"'
00:51:14          ####stageDirectory.WithSubDirectories(packageId).Value='/mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/bin/3/linux-x64/bin/Microsoft.DotNet.ToolPackage.Tests/Release/netcoreapp2.1/kisckzw0.amo/.stage/y3lvcxuc.yzr/global.tool.console.demo'
00:51:14          ####Directory.GetDirectories(stageDirectory.WithSubDirectories(packageId).Value).Count()='1'
00:51:14          ####Directory.EnumerateDirectories(stageDirectory.WithSubDirectories(packageId).Value).Count()='1'
00:51:15          ####packageId='global.tool.console.demo'
00:51:15          ####stageDirectory='"/mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/bin/3/linux-x64/bin/Microsoft.DotNet.ToolPackage.Tests/Release/netcoreapp2.1/yf4hmh1i.h4e/.stage/wvvuiukj.c4e"'
00:51:15          ####stageDirectory.WithSubDirectories(packageId).Value='/mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/bin/3/linux-x64/bin/Microsoft.DotNet.ToolPackage.Tests/Release/netcoreapp2.1/yf4hmh1i.h4e/.stage/wvvuiukj.c4e/global.tool.console.demo'
00:51:15          ####Directory.GetDirectories(stageDirectory.WithSubDirectories(packageId).Value).Count()='1'
00:51:15          ####Directory.EnumerateDirectories(stageDirectory.WithSubDirectories(packageId).Value).Count()='1'
00:51:17          ####packageId='global.tool.console.demo'
00:51:17          ####stageDirectory='"/mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/bin/3/linux-x64/bin/Microsoft.DotNet.ToolPackage.Tests/Release/netcoreapp2.1/dy1qg4to.3l4/.stage/kryeacc0.pv1"'
00:51:17          ####stageDirectory.WithSubDirectories(packageId).Value='/mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/bin/3/linux-x64/bin/Microsoft.DotNet.ToolPackage.Tests/Release/netcoreapp2.1/dy1qg4to.3l4/.stage/kryeacc0.pv1/global.tool.console.demo'
00:51:17          ####Directory.GetDirectories(stageDirectory.WithSubDirectories(packageId).Value).Count()='1'
00:51:17          ####Directory.EnumerateDirectories(stageDirectory.WithSubDirectories(packageId).Value).Count()='1'
00:51:19          ####packageId='global.tool.console.demo'
00:51:19          ####stageDirectory='"/mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/bin/3/linux-x64/bin/Microsoft.DotNet.ToolPackage.Tests/Release/netcoreapp2.1/naqmbecr.3zo/.stage/u2c2phoz.2iw"'
00:51:19          ####stageDirectory.WithSubDirectories(packageId).Value='/mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/bin/3/linux-x64/bin/Microsoft.DotNet.ToolPackage.Tests/Release/netcoreapp2.1/naqmbecr.3zo/.stage/u2c2phoz.2iw/global.tool.console.demo'
00:51:19          ####Directory.GetDirectories(stageDirectory.WithSubDirectories(packageId).Value).Count()='1'
00:51:19          ####Directory.EnumerateDirectories(stageDirectory.WithSubDirectories(packageId).Value).Count()='1'
00:51:20          ####packageId='global.tool.console.demo'
00:51:20          ####stageDirectory='"/tmp/csa1wyb4.2aa 0cf0nrhm.hnu/odr551wm.uro/.stage/ie2icz4c.qef"'
00:51:20          ####stageDirectory.WithSubDirectories(packageId).Value='/tmp/csa1wyb4.2aa 0cf0nrhm.hnu/odr551wm.uro/.stage/ie2icz4c.qef/global.tool.console.demo'
00:51:20          ####Directory.GetDirectories(stageDirectory.WithSubDirectories(packageId).Value).Count()='0'
00:51:20          ####Directory.EnumerateDirectories(stageDirectory.WithSubDirectories(packageId).Value).Count()='0'
00:51:20          [xUnit.net 00:00:36.5199293]       System.InvalidOperationException : Sequence contains no elements
00:51:20 
         [xUnit.net 00:00:36.5185287]     Microsoft.DotNet.ToolPackage.Tests.ToolPackageInstallerTests.GivenAnInstalledPackageUninstallRollsbackWhenTransactionAborts(testMockBehaviorIsInSync: False) [FAIL]
00:51:20          [xUnit.net 00:00:36.5212395]       Stack Trace:
00:51:20          [xUnit.net 00:00:36.5225935]            at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
00:51:20          [xUnit.net 00:00:36.5226848]         /mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/src/dotnet/ToolPackage/ToolPackageInstaller.cs(85,0): at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.<>c__DisplayClass6_0.<InstallPackage>b__0()
00:51:20          [xUnit.net 00:00:36.5227490]         /mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/src/dotnet/TransactionalAction.cs(76,0): at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback)
00:51:20          [xUnit.net 00:00:36.5228046]         /mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/src/dotnet/ToolPackage/ToolPackageInstaller.cs(50,0): at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackage(String packageId, String packageVersion, String targetFramework, Nullable`1 nugetConfig, String source, String verbosity)
00:51:20          [xUnit.net 00:00:36.5228678]         /mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/test/Microsoft.DotNet.ToolPackage.Tests/ToolPackageInstallerTests.cs(427,0): at Microsoft.DotNet.ToolPackage.Tests.ToolPackageInstallerTests.GivenAnInstalledPackageUninstallRollsbackWhenTransactionAborts(Boolean testMockBehaviorIsInSync)
00:51:20          [xUnit.net 00:00:36.5276016]   Finished:    Microsoft.DotNet.ToolPackage.Tests
00:51:20          Failed   Microsoft.DotNet.ToolPackage.Tests.ToolPackageInstallerTests.GivenAnInstalledPackageUninstallRollsbackWhenTransactionAborts(testMockBehaviorIsInSync: False)
00:51:20     14>DOTNETTEST : error Message:  [/mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/build/test/RunTest.proj]
00:51:20           System.InvalidOperationException : Sequence contains no elements
00:51:20          Stack Trace:
00:51:20             at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
00:51:20             at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.<>c__DisplayClass6_0.<InstallPackage>b__0() in /mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/src/dotnet/ToolPackage/ToolPackageInstaller.cs:line 85
00:51:20             at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback) in /mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/src/dotnet/TransactionalAction.cs:line 76
00:51:20             at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackage(String packageId, String packageVersion, String targetFramework, Nullable`1 nugetConfig, String source, String verbosity) in /mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/src/dotnet/ToolPackage/ToolPackageInstaller.cs:line 50
00:51:20             at Microsoft.DotNet.ToolPackage.Tests.ToolPackageInstallerTests.GivenAnInstalledPackageUninstallRollsbackWhenTransactionAborts(Boolean testMockBehaviorIsInSync) in /mnt/resource/j/workspace/dotnet_cli/master/release_rhel7.2_x64_prtest/test/Microsoft.DotNet.ToolPackage.Tests/ToolPackageInstallerTests.cs:line 427
00:51:20          
00:51:20 
```

**Comment by wli3** [comment]
Stage directory suddenly change from test to test

Stage directory is eventually from here

var root = new DirectoryPath(Path.Combine(Directory.GetCurrentDirectory(), Path.GetRandomFileName()));

That means Directory.GetCurrentDirectory changed. But even when it is changed, root is the same for the following calls

**Comment by danmosemsft** [comment]
Do your tests run concurrently in a single process, as CoreFX's xunit ones do? If so Directory.GetCurrentDirectory() is best avoided because it's so easy for another test to affect it. Same for any other process wide state.

**Comment by peterhuene** [comment]
Apparently there is a test in the same test class that is modifying the CWD too.  While it may not be the underlying issue here, modifying global state from tests can certainly contribute to such problematic heisenbugs.

@wli3 is there a reason the tool package root is CWD for these tests? I understand what the test that is modifying the CWD is trying to accomplish, but perhaps we need to pass through an argument on install that, if not passed, defaults to CWD?  Tests modifying CWD should be avoided at all cost.

**Comment by danmosemsft** [comment]
cc @JeremyKuhne to see discussion above fyi.

**Comment by peterhuene** [comment]
Another possibility: the path with a space in it it's causing the expected directory to be created at a different location for the restore, thus corefx is working correctly.

**Comment by wli3** [comment]
> 1. Test [GivenAConfigFileInCurrentDirectoryPackageInstallSucceeds](https://github.com/dotnet/cli/blob/master/test/Microsoft.DotNet.ToolPackage.Tests/ToolPackageInstallerTests.cs#L156-L175) is modifying CWD.  This should never happen in a test because this is process-global state.  **Proposal: pass the directory through as an argument to `InstallPackage` to allow the test to override the default-if-not-passed of CWD.**

This test is essentially testing a nuget flag. And make sure nuget targets will do the right action. If there is a regression on the feature we depend on we can caught it. Further tweak of the test will make it useless. I would just delete the test.

This is a trade off. CLI has several tests changing CWD already and it has been stable for a long time. Also, the design of the test and production code should not care where the folder lives.

> 2. Tool package installer tests that run after `GivenAConfigFileInCurrentDirectoryPackageInstallSucceeds` now use the directory it created the `NuGet.config` in (note the space in the temp path for the failure test case in CI; this is the format used for the config file paths) as the basis for their tool package roots.  While each test should be isolated from the others using a random sub-directory, this order-dependent behavior should be fixed.  **Proposal: use temp instead of CWD for the path basis.**

I did another PR. And note, it does not point to mock file system in that tests. Also, as I stated before. I cannot repo it, that's why it is strange.

Also I was surprised the root is using CWD as well. So I agree it should be somewhere stable.

**Comment by peterhuene** [comment]
I fully understand what the test is doing; regardless, modifying the CWD should only occur if we absolutely have to and in this instance we absolutely do not have to.

From what I can determine, the **only** place we would set the CWD is testing `DotnetNewRedirector`.  Unless my grep powers have failed me, that is the only place a built-in command is being used with `WorkingDirectory` called from the entirety of the CLI source base.

**Comment by nguerrera** [comment]
> CLI has several tests changing CWD already

We should be disabling test paralellism if we are certain we need to do this. Some assemblies have done this with the assembly level xunit attribute. Maybe this one should too. But, yes, this should be a last resort.

**Comment by danmosemsft** [comment]
@peterhuene I mentioned in another issue, but CoreFX has a way for tests to run code in a child process in an easy and seamless manner. You would be welcome to clone it.

eg 
https://github.com/dotnet/corefx/blob/ebbe93932733dafbd687e60db3b5443ebcf36001/src/System.Console/tests/ConsoleEncoding.Windows.cs#L17

impl
https://github.com/dotnet/corefx/blob/master/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs

**Comment by peterhuene** [comment]
@danmosemsft That's useful, thanks!

In this instance, I think the test implementation is wrong and should be using another, local mechanism for conveying this information to the class under test, even if it's purely an internal call only used by the test.

**Comment by wli3** [comment]
Agree with above, and we can always improve our tests. But, an insertion will constantly break a test is worrisome.

**Comment by nguerrera** [comment]
>But, an insertion will constantly break a test is worrisome.

Yes, see https://github.com/dotnet/cli/pull/8689#issuecomment-369701453

I want us to know conclusively why this only broke (from 0% repro to 100% repro) when we got the insertion. There needs to be enough data to understand if the only risk of breaking is when doing bad things (as in our tests) or if there is a more legitimately breaking change that happened in corefx.

**Comment by peterhuene** [comment]
I agreed; the insertion causing this failure is worrisome.  I think we should investigate if RHEL fails consistently with a similiar path (space in name in /tmp) for tool package root.  We should verify that the restore operation actually created the files where we expect them to be before we consider the problem to be corefx.

**Pull request closed without merging**
