### PR TITLE
Updating 2.2 test templates

### PR DESCRIPTION
**Pull request by singhsarab**
Updating the test templates for net 2.2x with precendence fix.

### CODE REVIEW

**Comment by jamshedd** [comment]
Approved for 2.2.2xx

**Comment by singhsarab** [comment]
@livarcocc What dotnet cli version is this part of ? Also, good to know what version of VS is this available in ?

**Comment by livarcocc** [comment]
SDK 2.2.2xx and it ships with VS 2016.

**Comment by singhsarab** [comment]
@livarcocc  What version ships with VS 2019 ?

**Comment by livarcocc** [comment]
2.2.200 and 2.1.600.

**Pull request merged**
