### PR TITLE
update nuget to 4.3.0-preview4-4258

### PR DESCRIPTION
**Pull request by zhili1208**

### CODE REVIEW

**Comment by livarcocc** [comment]
@MattGertz this will require a CLI insertion into VS. But this version of NuGet has already been inserted there. So, this should be ok?

**Comment by MattGertz** [comment]
@livarcocc Starting a few hours ago, we need to track anything VS insertion-related in a VSO bug & it will need approval from Dir/QB.

**Comment by livarcocc** [comment]
@zhili1208 can you point us to the bug that you used to make the NuGet insertion to VS? Or create one if there isn't one already?

**Comment by zhili1208** [comment]
@livarcocc bug number is 458078

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by livarcocc** [comment]
@MattGertz Can you approve this? It is a dependency flowing into the CLI and the CLI into VS.

Bug is here: https://devdiv.visualstudio.com/DevDiv/_workitems?id=452135&_a=edit&triage=true.

**Pull request merged**
