### PR TITLE
ingest runtime Rpm agnostic and produce Rpm agnostic packages

### PR DESCRIPTION
**Pull request by wli3**
The previous PR https://github.com/dotnet/cli/pull/8689 is having strange test failure. We decide to check in with the walkaround and create a separate issue to investigate. The previous branch has investigation logging logic. So I branched out a clean one

-------------
this RP is built on top of #8625. I think it is better to create a different PR

The above insertion failed due to CLI cannot ingest runtime RPM agnostic packages. After this change, CLI will produce RPM agnostic packages as well.

example file name dotnet-sdk-2.1.300-preview2-008268-x64.rpm
cc @leecow
cc @dagood after this change version page need to change as well. Basically, cli rpm will look the same as cli deb

### CODE REVIEW

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT x64 Release Build

**Comment by wli3** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build

**Comment by wli3** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by wli3** [comment]
@dotnet-bot test RHEL6 x64 Debug Build

**Comment by wli3** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by wli3** [comment]
@danmosemsft

**Comment by danmosemsft** [comment]
@wli3 why was it necesary to rename the test? I do'nt feel comfortable doing that if we have no idea why it helps.

**Comment by danmosemsft** [comment]
How did you even guess to do it?

**Comment by wli3** [comment]
@nguerrera @livarcocc we decide to not block insertion any longer. Especially considering prod con. However, we do want to get to the bottom of this issue with a separate thread

**Comment by danmosemsft** [comment]
Fair enough. Go for it.

**Comment by wli3** [comment]
filed https://github.com/dotnet/corefx/issues/27588

**Pull request merged**
