### PR TITLE
TestPlatform insertion 16.1.1

### PR DESCRIPTION
**Pull request by jayaranigarg**
Release : https://github.com/Microsoft/vstest/releases/tag/v16.1.1

### CODE REVIEW

**Comment by jayaranigarg** [comment]
@dotnet-bot Test this please

**Comment by jayaranigarg** [comment]
Can somebody help to push this PR in?

**Comment by peterhuene** [comment]
@jayaranigarg to be clear, 2.1.8xx is a 16.2 targeting branch.  Is this update intended as a servicing fix for 16.1 and should be made to a 16.1 servicing branch (2.1.7xx)?  If not, then is there a 16.2 version of test tools to insert?

**Comment by jayaranigarg** [comment]
@peterhuene : Thank you for letting me know. This insertion was intended for 16.1 servicing branch.
Here is the PR for that : https://github.com/dotnet/cli/pull/11498

**Comment by peterhuene** [comment]
Do you have a 16.2 insertion to make for the 2.1.8xx/2.2.4xx branches or should I close this PR?

One last question, has .NET Core shiproom approved this fix for servicing?  Once merged, we will handle merging the changes from the servicing branches to the current preview branches.

**Comment by peterhuene** [comment]
Closing this PR in favor of letting the 2.2.3xx change merge up.

**Pull request closed without merging**
