### PR TITLE
Insert NuGet Build 4.9.0-preview5.5621 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.9.0-preview5.5621 into cli release/2.1.5xx branch

### CODE REVIEW

**Comment by jainaashish** [comment]
there is compilation error for windows build:

error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [D:\j\workspace\release_windo---316d249c\src\Microsoft.DotNet.MSBuildSdkResolver\Microsoft.DotNet.MSBuildSdkResolver.csproj] [D:\j\workspace\release_windo---316d249c\build.proj]

@livarcocc

**Comment by livarcocc** [comment]
Jenkins outage, I imagine.
@dotnet-bot Linux arm Debug Build
@dotnet-bot Linux x64 Release Build
@dotnet-bot Linux-musl x64 Debug Build
@dotnet-bot OSX10.12 x64 Release Build
@dotnet-bot RHEL6 x64 Debug Build
@dotnet-bot Ubuntu x64 Release Build
@dotnet-bot Ubuntu16.04 x64 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Linux arm Debug Build
@dotnet-bot Test Linux x64 Release Build
@dotnet-bot Test Linux-musl x64 Debug Build
@dotnet-bot Test OSX10.12 x64 Release Build
@dotnet-bot Test RHEL6 x64 Debug Build
@dotnet-bot Test Ubuntu x64 Release Build
@dotnet-bot Test Ubuntu16.04 x64 Debug Build

**Comment by jainaashish** [comment]
Raised another PR to insert 4.9.0.5630 so please ignore this.

**Pull request closed without merging**
