### PR TITLE
Updating the websdk version for 1.0

### PR DESCRIPTION
**Pull request by vijayrkn**
Updating the websdk version for 1.1.0 cli
https://dotnet.myget.org/feed/dotnet-web/package/nuget/Microsoft.NET.Sdk.Web/1.0.0-alpha-20170516-2-509 

@mlorbetske @livarcocc

### CODE REVIEW

**Comment by vijayrkn** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by livarcocc** [comment]
This should match what will go into VS. Is this true?

**Comment by livarcocc** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by vijayrkn** [comment]
@livarcocc  yes, this is the cli version we want to ship in VS.

**Comment by vijayrkn** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by mlorbetske** [comment]
@livarcocc for some reason, the NT x86 build is failing to restore packages for dotnet-dependency-tool-invoker (System.Threading.Thread 4.3.0, System.Linq.Parallel 4.3.0, etc) - but these pass in every other configuration. Any ideas what could cause that?

**Comment by livarcocc** [comment]
@mlorbetske Not really. Not sure what would cause that.

**Comment by livarcocc** [comment]
But I think I am hitting this in my other PR as well.

**Comment by vijayrkn** [comment]
Looks like this PR is also hitting the same issue - https://github.com/dotnet/cli/pull/6633 is also hitting the same issue.

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by vijayrkn** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by vijayrkn** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@MattGertz flowing of dependencies into the CLI.

**Pull request merged**
