### PR TITLE
Remove duplicated install scripts.

### PR DESCRIPTION
**Pull request by eerhardt**
Please use `dotnet-install` instead.

### CODE REVIEW

**Comment by eerhardt** [comment]
@piotrpMSFT @krwq

**Comment by piotrpMSFT** [comment]
Thanks!

**Comment by krwq** [comment]
should we replace that with some script which displays a message where is the actual script instead?

**Comment by piotrpMSFT** [comment]
This is already preview2 work. Let's just rip the bandage

**Comment by eerhardt** [comment]
test CentOS7.1 x64 Debug Build

**Comment by eerhardt** [comment]
test Debian8.2 x64 Debug Build

**Comment by eerhardt** [comment]
test OSX x64 Release Build

**Pull request merged**
