### PR TITLE
Fix fedora.23 dockerfile

### PR DESCRIPTION
**Pull request by wli3**
Use existing docker image to reduce error from extra dependency.

Append CLI specific packages

### CODE REVIEW

**Comment by wli3** [comment]
@livarcocc  should I also cherry pick this change to branch 1.0 and 1.0.1 ?

**Comment by wli3** [comment]
Tested on VSTS

**Comment by livarcocc** [comment]
Let's wait for this to pass through VSO and then cherry pick to rel/1.0.1. No need to do it for rel/1.0.0.

**Comment by livarcocc** [comment]
@MattGertz Infra-structure only change.

**Pull request merged**
