### PR TITLE
Updating the websdk version to 2.1.500

### PR DESCRIPTION
**Pull request by vijayrkn**
Issue - https://github.com/aspnet/Home/issues/3437
PR- https://github.com/aspnet/websdk/pull/397
Package - https://dotnet.myget.org/feed/dotnet-web/package/nuget/Microsoft.NET.Sdk.Web/2.1.500

### CODE REVIEW

**Comment by livarcocc** [comment]
What happens if you need to re-spin?

**Comment by vijayrkn** [comment]
The package is only in myget. If absolutely needed, we can remove them and re-publish.

**Comment by vijayrkn** [comment]
@livarcocc - Is it okay to merge this?

**Comment by livarcocc** [comment]
I think so, go ahead.

**Pull request merged**
