### PR TITLE
[DO NOT MERGE] updated to coherence 26448 & templating build 298

### PR DESCRIPTION
**Pull request by seancpeters**

### CODE REVIEW

**Comment by seancpeters** [comment]
Mike, Bala, & I went back n forth on doing this one. We wanted to get a newer version out tonight, for CTI to test. Then we'll get the 26452 insertion done tomorrow

**Comment by seancpeters** [comment]
Looks like we don't yet have no-timestamp versions of:
- Microsoft.AspNetCore.All
- Microsoft.VisualStudio.Web.CodeGeneration.Tools

**Comment by mikeharder** [comment]
Good catch.  @JunTaoLuo, do you know the status of the non-timestamped versions of these packages?

**Comment by mikeharder** [comment]
@seancpeters: I do see non-timestamped versions of these packages in the output of CoherenceSigned.  Where do you see they are missing?

**Comment by seancpeters** [comment]
Mike H. & I talked about this offline, but for others following along: the errors with the package versions are in the failed builds, for example:
https://ci.dot.net/job/dotnet_cli/job/release_2.0.0/job/debug_windows_nt_x86_prtest/668/
https://ci.dot.net/job/dotnet_cli/job/release_2.0.0/job/debug_ubuntu16.10_x64_prtest/641/

**Comment by mikeharder** [comment]
I believe the issue is the non-timestamped packages have not been published to https://dotnet.myget.org/gallery/aspnetcore-ci-release, and the test is expecting this feed to contain them.  The fix is to either publish the non-timestamped packages to this feed, or publish them to another feed (i.e. a verification feed) and update the test to include this feed.

**Comment by mlorbetske** [comment]
There's a verification feed that Pranav and Eilon have for uploading the no-timestamp packages to & the NuGet.config needs to be updated to point at it.

**Comment by mlorbetske** [comment]
From NuGet.config

    <add key="aspnet" value="https://dotnet.myget.org/F/aspnetcore-release/api/v3/index.json" />
    
    
    <add key="websdkfeed" value="https://dotnet.myget.org/F/dotnet-web/api/v3/index.json" />

**Comment by JunTaoLuo** [comment]
Unfortunately we don't build the no-timestamp version of the .All metapackage until Conherence-Signed so it is only available on the aspnetcore-release and aspnetcore-dev (i.e. signed) feeds. Not sure about the .Tools packages though. I'm assuming those should be on the aspnetcore-ci-dev and aspnetcore-ci-release feeds so it might be a problem somewhere in our build.

**Comment by seancpeters** [comment]
@dotnet-bot test this please

**Comment by mikeharder** [comment]
@seancpeters, @mlorbetske: Can you please update this PR to use ASP.NET build `26452`?  This is our target final build.

**Comment by nguerrera** [comment]
Superseded by #7262

**Pull request closed without merging**
