### PR TITLE
Fix crossgen step on win10 box

### PR DESCRIPTION
**Pull request by nguerrera**
See https://github.com/dotnet/cli/pull/6094#issuecomment-288278480

@ellismg @eerhardt @gkhanna79 @livarcocc

### CODE REVIEW

**Comment by ellismg** [comment]
LGTM

**Comment by nguerrera** [comment]
@ellismg Was [this](https://github.com/dotnet/cli/pull/6094#issuecomment-288280020) before or after LGTM?

**Comment by ellismg** [comment]
Sorry about that, Nick.  I'm guessing we don't have CI coverage on Windows 10?

**Comment by nguerrera** [comment]
No problem. Even after this, current status on my machine with no other changes:

```

                   "D:\Src\cli\build.proj" (default target) (1) ->
                   "D:\Src\cli\build\test\RunTest.proj" (default target) (2:2) ->
                   (RunTest target) ->
                     DOTNETTEST : error Message:  [D:\Src\cli\build\test\RunTest.proj]
```

**Comment by nguerrera** [comment]
Better error digging in the logs:

Failed   Microsoft.DotNet.Migration.Tests.GivenThatIWantToMigrateSolutions.WhenDirectoryAlreadyContainsCsprojFileItMigratesAndBuildsSln (TaskId:74)

**Comment by ellismg** [comment]
It was before I looked at the diff.  I think what Nick did will work.

**Comment by nguerrera** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please

Looks like there are some flaky tests. A different set failed for me on re-run and a handful just failed on CentOS, which I don't think are related to this change.

**Comment by nguerrera** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please

**Pull request merged**
