### PR TITLE
Help message for dotnet

### LINKED ISSUE #2697: dotnet --help is not functional when only installing .Net Core
## Steps to reproduce
1. Install the .Net Core your favorite Linux distro.  Note this is **not **installing the .Net Core SDK
2. Run `dotnet`
3. Observe the output `Usage: dotnet [--help | app.dll]`
4. Run `dotnet --help`

## Expected  behavior
I would not expect the Usage to display commands that are invalid.

## Actual behavior
`Could not resolve SDK directory from [/usr/share/dotnet]`

## Environment data
.Net Core 1.0.0-rc2-3002485 on Debian Jessie.

### PR DESCRIPTION
**Pull request by schellap**
Fixes #2697 

@blackdwarf @piotrpMSFT @gkhanna79 PTAL. Contains user facing strings about the muxer help message.

@blackdwarf One concern I have is about putting URLs in the binary. As URLs can go dead or moved to different domains. Is there a place we ask users to pick the dotnet SDK from?

### CODE REVIEW

**Comment by schellap** [comment]
Here is what it looks like:
```
Microsoft .NET Core Shared Framework Host

  Version  : 1.0.1-rc3-002724-00
  Build    : 5fe36b07675f56a05f5822f454ca8190afae3cd5

Usage: dotnet [common-options] [[options] path-to-application]

Common Options:
  --help                           Display .NET Core Shared Framework Host help.
  --version                        Display .NET Core Shared Framework version.

Options:
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.

Path to Application:
  The path to a .NET Core managed application, dll or exe file to execute.

If you are debugging the Shared Framework Host, set 'COREHOST_TRACE' to '1' in your environment.

Install .NET SDK from https://github.com/dotnet/cli to build .NET Core applications.
```

**Comment by blackdwarf** [comment]
@schellap you're right, we shouldn't point people to the CLI repo. Here is the fwlink for the getting started page: http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409. This is the new GS page so its now live yet but it will be for RC2.

**Comment by gkhanna79** [comment]
LGTM module other comments.

**Comment by schellap** [comment]
Yo @blackdwarf link hits 404.

**Comment by schellap** [comment]
Oh thanks. This PR is for Preview 2. Will it be the same or do you expect that to change or this link would auto redirect?

**Comment by blackdwarf** [comment]
@schellap yeah, the link will go live on Mon. :) So by the time this hits Preview 2, it will be long up and running.

**Pull request merged**
