### PR TITLE
LOC CHECKIN | dotnet/cli master | 20200403

### PR DESCRIPTION
**Pull request by v-chmart**
Localization update.

### CODE REVIEW

**Comment by sfoslund** [comment]
@wli3 do we need this change in master?

**Comment by wli3** [comment]
@sfoslund not have to. But it is good to have a round of loc pass

**Review by wli3 — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
CLI repo has been archived and merged with https://github.com/dotnet/sdk/tree/master/src/Cli.  Closing all old PRs in the cli repo to master.  I double checked a couple of files and they appear to be translated in sdk so we should be fine.

**Pull request closed without merging**
