### PR TITLE
Updating netci.groovy to archive test results on failure.

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
test ci please

**Comment by tannergooding** [comment]
test ci please

**Comment by tannergooding** [comment]
FYI. @livarcocc, @dotnet/cli-contrib 

I forced it to collect on success to validate things were working: https://ci.dot.net/job/dotnet_cli/job/release_2.1/job/GenPRTest/job/release_windows_nt_x64_prtest/1/artifact/

**Comment by livarcocc** [comment]
I would actually target 2.1.2xx at this point, since that's the minimum one we will be servicing until 4xx comes along and gets inserted into VS.

**Comment by tannergooding** [comment]
Updated to target 2.1.2xx

**Pull request merged**
