### PR TITLE
Fixing wrong output path passed to pre/post publish scripts

### LINKED ISSUE #1014: dotnet publish no longer forwards the path the project it being published to (regression)
The publish command used to pass the path the project was published to in the %publish:OutputPath% parameter. After this commit https://github.com/dotnet/cli/commit/ac2d0e36a9b1353f3461c01f60567d9dc541e0eb#diff-06bec5144cd01c123b4fd6d6c7f4c027R92 it no longer does. As a result pre/post publish scripts are useless since it they don't know where the project was published.

Note it is impossible to figure out the path where the project is - `%publish.OutputPath%/%publish:Configuration%/%publish:Framework%` results in `C:\Temp\WebApp6IIS/Debug/DNXCore` but the project was actually published to `C:\Temp\WebApp6IIS\Debug\dnxcore50`

### PR DESCRIPTION
**Pull request by moozzyk**
Fixes #1014

### CODE REVIEW

**Comment by livarcocc** [comment]
LGTM.

**Comment by piotrpMSFT** [comment]
@moozzyk I assume you want this in rel/1.0.0 and not master?

**Comment by moozzyk** [comment]
I don't know the branching story :) - I will rebase on rel/1.0.0 if you say this is where I want it

**Comment by livarcocc** [comment]
@moozzyk rel/1.0.0 is where you want it.

**Comment by moozzyk** [comment]
@livarcocc - Thanks. I will rebase and push tomorrow.

**Comment by moozzyk** [comment]
Closing this PR. I will open a new one based on rel/1.0.0 branch.

**Pull request closed without merging**
