### PR TITLE
Upgrade all Roslyn references to -20160108-01

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by agocke** [comment]
Has anyone seen the CentOS failure before? Segfault?

**Comment by Sridhar-MS** [comment]
Jenkins currently down for maintenance. Was the SegFault in `dotnet restore` because I have seen this before but have investigated yet.

**Comment by Sridhar-MS** [comment]
@dotnet-bot test CentOS7.1 Debug Build please

**Comment by agocke** [comment]
test CentOS7.1 Debug Build please

**Comment by agocke** [comment]
@Sridhar-MS Yup, it was the restore. It looks like things went through this time.

**Comment by Sridhar-MS** [comment]
Yeah the restore crash is intermittent. I will investigate that.

**Comment by Sridhar-MS** [comment]
:shipit:

**Pull request merged**
