### PR TITLE
Insert NuGet Build 4.4.0-preview3-4475 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.4.0-preview3-4475 into cli release/2.0-vs branch

### CODE REVIEW

**Comment by livarcocc** [comment]
Has this been inserted into VS already?

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by zhili1208** [comment]
Yes, it's ready inserted to VS

**Comment by livarcocc** [comment]
@MattGertz Flow of dependencies into VS.

**Pull request merged**
