### PR TITLE
Fix library suffux usage for coreclr library name construction

### PR DESCRIPTION
**Pull request by alexanderkozlenko**

### CODE REVIEW

**Comment by alexanderkozlenko** [comment]
@dotnet-bot test OSX Debug Build

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX Debug Build please.

**Comment by Sridhar-MS** [comment]
@piotrpMSFT The hard drive on dci-mac-bld-3 is dead. Hence the OSX failures. It has been taken offline now.

**Comment by Sridhar-MS** [comment]
@dotnet-bot test OSX Debug Build please.

**Comment by blackdwarf** [comment]
Thanks!

**Pull request merged**
