### PR TITLE
Add error message when runtime target is not found

### PR DESCRIPTION
**Pull request by pakrym**
https://github.com/dotnet/cli/issues/1497

@davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
Test failure..

**Comment by pakrym** [comment]
Fixed

**Comment by pakrym** [comment]
@dotnet-bot CentOS7.1 Release Build

**Comment by pakrym** [comment]
@dotnet-bot Tets CentOS7.1 Release Build please

**Comment by anurse** [comment]
:shipit: assuming builds fixed or unrelated failures.

**Comment by livarcocc** [comment]
@pakrym Did you merge without waiting for CI? Please, let's not get in the habit of doing that. I am sure it is fine, but in one case it isn't, it may end up costing a bunch of people a lot of time.

**Comment by pakrym** [comment]
Nope, I merged with cent os fail, which looked hardly related, everything else was green, I'm not sure why it says in progress now.

**Pull request merged**
