### PR TITLE
Use StringComparison.Ordinal with IndexOf in AnsiConsole

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes #https://github.com/dotnet/cli/issues/2042
cc: @ellismg, @brthor 

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2096)

### CODE REVIEW

**Comment by ellismg** [comment]
LGTM.  I wonder if we should be more aggressive around turning on the FxCop rules around having to specify this stuff.  Having folks be explicit may help them do the right thing more often.

**Comment by brthor** [comment]
LGTM :shipit:

**Comment by stephentoub** [comment]
test OSX x64 Release Build please
test Windows_NT x64 Release Build please
test Windows_NT x86 Debug Build please

**Comment by davidfowl** [comment]
:shipit:

**Pull request merged**
