### PR TITLE
Insert NuGet Build 4.9.0-preview2.5428 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.9.0-preview2.5428 into cli release/2.1.5xx branch

### CODE REVIEW

**Comment by nkolev92** [comment]
@livarcocc @nguerrera @dsplaisted 

Is there no SDK branch yet? 
Our automation failed because it could not find the correct branch.

**Comment by livarcocc** [comment]
What do you mean? 2.1.5xx is a branch 😄

**Comment by nkolev92** [comment]
@livarcocc I'm referring to https://github.com/dotnet/sdk. 

There's no `release/2.1.5xx` equivalent branch there. 

https://github.com/dotnet/sdk/tree/release/2.1.5xx does not exist.

**Comment by livarcocc** [comment]
The branch is created on SDK. Can you please get a PR there as well.

**Comment by nkolev92** [comment]
I have created the SDK PR
https://github.com/dotnet/sdk/pull/2502

The VS PR has already been merged, https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/138942?_a=overview

**Pull request merged**
