### PR TITLE
Insert NuGet Build 5.0.0-rtm.5821 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 5.0.0-rtm.5821 into cli release/2.2.2xx branch

### CODE REVIEW

**Comment by wli3** [comment]
```
     2>/mnt/resource/j/workspace/dotnet_cli/release_2.2.2xx/debug_centos7.1_x64_prtest/src/redist/redist.csproj(346,5): error : Error: Could not load file or assembly 'NuGet.Packaging.Core, Version=5.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
10:54:42          Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
10:54:42          Copyright (c) Microsoft Corporation.  All rights reserved.
10:54:42          
10:54:42      2>/mnt/resource/j/workspace/dotnet_cli/release_2.2.2xx/debug_centos7.1_x64_prtest/src/redist/redist.csproj(346,5): error : Error compiling /mnt/resource/j/workspace/dotnet_cli/release_2.2.2xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.2.200-preview-009807/Sdks/Microsoft.NET.Sdk/tools/netcoreapp2.0/Microsoft.NET.Build.Tasks.dll: Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
10:54:42      2>/mnt/resource/j/workspace/dotnet_cli/release_2.2.2xx/debug_centos7.1_x64_prtest/src/redist/redist.csproj(346,5): error : Error: compilation failed for "/mnt/resource/j/workspace/dotnet_cli/release_2.2.2xx/debug_centos7.1_x64_prtest/bin/2/linux-x64/dotnet/sdk/2.2.200-preview-009807/Sdks/Microsoft.NET.Sdk/tools/netcoreapp2.0/Microsoft.NET.Build.Tasks.dll
```

**Comment by wli3** [comment]
dup of #10726

**Comment by nkolev92** [comment]
@wli3 
At some point in the last few months, it was decided that NuGet should do insertions against both 2.1 and 2.2 branches directly. 

We can revisit that if needed, but that is the reason for this PR.

**Comment by wli3** [comment]
sorry i did not see the branch is different

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Pull request merged**
