### PR TITLE
Update branding string to 1.0.3

### PR DESCRIPTION
**Pull request by piotrpMSFT**
Update branding string to 1.0.3

/cc @leecow

### CODE REVIEW

**Comment by leecow** [comment]
:shipit:

**Comment by piotrpMSFT** [comment]
@mattgertz this change is going to the rel/1.0.0-preview2 branch which will create the .NET Core 1.0.3 project.json-based CLI packages. Can you take a look and approve?

**Comment by MattGertz** [comment]
Approved.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Fedora23 x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
Fedora had a network issue downloading the Stage0 .tar.gz. I validated that I can manually download the requested URL.

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Pull request merged**
