### PR TITLE
Implement support for Embedded PDB

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@livarcocc

**Comment by tmat** [comment]
test Windows_NT x64 Release Build please

**Comment by livarcocc** [comment]
:shipit:

**Comment by livarcocc** [comment]
Actually, can you please move this to rel/1.0.0? We have a PR out to merge feature/msbuild to that branch and we will stop using feature/msbuild. If you don't move it there now, you will have to after the merge PR is checked in.

**Comment by tmat** [comment]
OK, I'll wait for the merge to happen since I need some of the changes you made in the build.

**Comment by livarcocc** [comment]
@tmat We have merged the msbuild work into rel/1.0.0, please rebase there.

**Comment by tmat** [comment]
Rebased: https://github.com/dotnet/cli/pull/4137

**Pull request closed without merging**
