### PR TITLE
Update templates and add 'baseline' feature

### PR DESCRIPTION
**Pull request by mlorbetske**

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test this please

**Comment by livarcocc** [comment]
@mlorbetske did the packages change under us again:

/mnt/resource/j/workspace/dotnet_cli/release_2.0.0/debug_debian8.2_x64_prtest/artifacts/debian.8-x64/stage2/sdk/2.0.0-preview1-005848/NuGet.targets(97,5): error : Package Microsoft.Extensions.SecretManager.Tools 2.0.0-preview1-24639 is not compatible with netcoreapp1.0

**Comment by mlorbetske** [comment]
Kicked off the build too early, packages hadn't fully propagated through MyGet

@dotnet-bot test CentOS7.1 x64 Debug Build please
@dotnet-bot test Windows_NT x86 Debug Build please
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build please

**Pull request merged**
