### PR TITLE
remove unnecessary NuGet.Config that was causing problems

### PR DESCRIPTION
**Pull request by anurse**
This should fix the resolution failure.

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2354)

### CODE REVIEW

**Comment by pranavkm** [comment]
Nice. You could potentially try updating the project,json for this project since it has super old DNX references

**Comment by pranavkm** [comment]
:shipit:

**Comment by piotrpMSFT** [comment]
@dotnet-bot test this please

**Comment by anurse** [comment]
@dotnet-bot test OSX x64 Release Build please
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by anurse** [comment]
@dotnet-bot test Ubuntu x64 Debug Build please

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu x64 Debug Build please

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX x64 Release Build please.

**Comment by piotrpMSFT** [comment]
I'm looking at these test failures locally, they seem like flaky failures, so I hope CI passes without change to get us unblocked.

**Comment by piotrpMSFT** [comment]
@anurse @pakrym FYI, the Kestrel tests thus far have been sending GET requests to the Kestrel server in a spinlock without any delay. In this configuration, Kestrel sporatically failed to respond. I added a delay of 100ms between requests and, on my local box, this seems to have eliminated the flakiness. Since tests are now successfully communicating with Kestrel I'm going to assume that this is a stress issue somewhere on the server stack. You may want to have someone test this scenario on OS X 64 bit to see if there is a product issue.

/cc @Sridhar-MS

**Comment by Sridhar-MS** [comment]
Thanks a lot @piotrpMSFT for fixing the flakiness in the Kestrel Tests.

**Comment by anurse** [comment]
If there's a Kestrel issue, can you report it to aspnet/KestrelHttpServer? We do some stress runs so it might be known and someone there could comment.

**Pull request merged**
