### PR TITLE
Updating NuGet to 3.6.0-rc-1979

### PR DESCRIPTION
**Pull request by emgarten**
Adding support for single $(TargetFramework)

### CODE REVIEW

**Comment by emgarten** [comment]
test Windows_NT x64 Release Build

**Comment by emgarten** [comment]
Here is my output from ``dotnet new -t msbuild`` and ``dotnet restore3`` for single vs multiple frameworks.

``<TargetFramework>netcoreapp1.0</TargetFramework>``
```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(NuGetPackageRoot)' == ''">
    <NuGetPackageRoot>$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
  </PropertyGroup>
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)microsoft.net.sdk\1.0.0-alpha-20161010-1\build\netstandard1.0\Microsoft.NET.Sdk.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.net.sdk\1.0.0-alpha-20161010-1\build\netstandard1.0\Microsoft.NET.Sdk.targets')" />
  </ImportGroup>
</Project>
```

``<TargetFrameworks>netcoreapp1.0</TargetFrameworks>``
```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(NuGetPackageRoot)' == ''">
    <NuGetPackageRoot>$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
  </PropertyGroup>
  <ImportGroup Condition=" '$(IsCrossTargetingBuild)' == 'true' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)nuget.build.tasks.pack\3.6.0-rc-1954\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets" Condition="Exists('$(NuGetPackageRoot)nuget.build.tasks.pack\3.6.0-rc-1954\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets')" />
    <Import Project="$(NuGetPackageRoot)microsoft.net.sdk\1.0.0-alpha-20161010-1\buildCrossTargeting\Microsoft.NET.Sdk.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.net.sdk\1.0.0-alpha-20161010-1\buildCrossTargeting\Microsoft.NET.Sdk.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.0' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)microsoft.net.sdk\1.0.0-alpha-20161010-1\build\netstandard1.0\Microsoft.NET.Sdk.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.net.sdk\1.0.0-alpha-20161010-1\build\netstandard1.0\Microsoft.NET.Sdk.targets')" />
  </ImportGroup>
</Project>
```

No target framework conditions are added for a single framework.

**Comment by emgarten** [comment]
//cc @eerhardt @brthor @livarcocc @rohit21agrawal @rrelyea

**Comment by eerhardt** [comment]
:shipit:

**Pull request merged**
