### PR TITLE
Fixes #2987

### LINKED ISSUE #2987: Update EULAs for new privacy policy links
There are pending changes to the EULA in https://github.com/dotnet/cli/pull/2478 which are associated with previously merged telemetry changes (from a few different PRs). This issue simply tracks merging that PR.

### PR DESCRIPTION
**Pull request by piotrpMSFT**
Update EULA for new privacy policy link

Fixes #2987

### CODE REVIEW

**Comment by livarcocc** [comment]
:shipit:

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
Slave went offline during the build

**Comment by piotrpMSFT** [comment]
@mmitche is something up with infra?

**Comment by piotrpMSFT** [comment]
These changes are text only, and the failures we see are due to flaky tests/infra. I'm going to merge to keep the product unblocked. I'm opening preview2 issue for the flaky test.

**Comment by mmitche** [comment]
@piotrpMSFT I'll contact DDIT again for the network failures.

FYI your Debian failure is because of:

/mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_debian8.2_x64_prtest/test/dotnet-publish.Tests/bin/Debug/netcoreapp1.0/CompilationFailedTest/CompileFail/Program.cs(12,18): error CS1002: ; expected
13:08:07 /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_debian8.2_x64_prtest/test/dotnet-publish.Tests/bin/Debug/netcoreapp1.0/CompilationFailedTest/CompileFail/Program.cs(12,27): error CS1002: ; expected
13:08:07 /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_debian8.2_x64_prtest/test/dotnet-publish.Tests/bin/Debug/netcoreapp1.0/CompilationFailedTest/CompileFail/Program.cs(12,34): error CS1002: ; expected
13:08:07 /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_debian8.2_x64_prtest/test/dotnet-publish.Tests/bin/Debug/netcoreapp1.0/CompilationFailedTest/CompileFail/Program.cs(12,35): error CS1525: Invalid expression term '}'
13:08:07 /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_debian8.2_x64_prtest/test/dotnet-publish.Tests/bin/Debug/netcoreapp1.0/CompilationFailedTest/CompileFail/Program.cs(12,35): error CS1002: ; expected

**Comment by piotrpMSFT** [comment]
@mmitche those are false alarms. These are tests that intentionally try to compile stuff that won't compile. The real issue is we have a test for the projectmodelserver which tries to do some socket IO and that test failed. I'm opening an issue to track.

**Comment by mmitche** [comment]
@piotrpMSFT The failures on the connection issues are only between DTAP and Azure.

**Pull request merged**
