### PR TITLE
Update Core-setup to 2.0.0-preview1-002061-00

### PR DESCRIPTION
**Pull request by eerhardt**
@livarcocc

### CODE REVIEW

**Comment by eerhardt** [comment]
This fixes the signing issue with the shared framework.

**Comment by eerhardt** [comment]
test OSX10.12 x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by eerhardt** [comment]
Merging to unblock the signing issue blocking CLI going into VS.

**Pull request merged**
