### PR TITLE
Update AppDep SDK version

### PR DESCRIPTION
**Pull request by schellap**
Added System.Threading.Overlapped.dll

### CODE REVIEW

**Comment by schellap** [comment]
@dotnet-bot test this please

**Comment by davidfowl** [comment]
Don't you need to update the package dependency? I think we should just generate that thing at build time @brthor

**Comment by schellap** [comment]
Yes, fixing it in a branch from cmd line. Tried to edit from browser...

**Comment by davidfowl** [comment]
Ahaha

**Comment by schellap** [comment]
@davidfowl notice this in your builds? Same problem you are discussing with ericstj?

```
01:24:47 warn : Detected package downgrade: System.CommandLine from 0.1.0-e160208-1 to 0.1.0-e160119-1 
01:24:47 warn :  dotnet (>= 1.0.0) -> Microsoft.DotNet.ILCompiler.SDK (>= 1.0.6-prerelease-00003) -> Microsoft.DotNet.ILCompiler (>= 1.0.6-prerelease-00003) -> System.CommandLine (>= 0.1.0-e160208-1) 
01:24:47 warn :  dotnet (>= 1.0.0) -> System.CommandLine (>= 0.1.0-e160119-1)
01:24:47 warn : Detected package downgrade: System.CommandLine from 0.1.0-e160208-1 to 0.1.0-e160119-1 
01:24:47 warn :  dotnet (>= 1.0.0) -> Microsoft.DotNet.ILCompiler.SDK (>= 1.0.6-prerelease-00003) -> Microsoft.DotNet.ILCompiler (>= 1.0.6-prerelease-00003) -> System.CommandLine (>= 0.1.0-e160208-1) 
01:24:47 warn :  dotnet (>= 1.0.0) -> System.CommandLine (>= 0.1.0-e160119-1)
```

**Comment by davidfowl** [comment]
The version of System.CommandLine in the CLI is downgrading the one used by the ILCompiler.SDK. You can just upgrade the one in the CLI and see if it works, it should.

**Comment by schellap** [comment]
Yeah. That is clear from the log. But the ref-def mismatch issue... if a downgrade can happen due to a dependency of the original project... anyway this shouldn't affect CLI.

**Comment by davidfowl** [comment]
There's no ref def mismatch here, this is just a downgrade of a pure IL package.

**Comment by schellap** [comment]
I'll probably talk to you or eric to understand this issue... thanks.

**Pull request merged**
