### PR TITLE
TestPLatform insertion 16.1.1

### PR DESCRIPTION
**Pull request by jayaranigarg**
Release : https://github.com/Microsoft/vstest/releases/tag/v16.1.1

### CODE REVIEW

**Comment by jayaranigarg** [comment]
Can somebody help to push this PR in?

**Comment by peterhuene** [comment]
@jayaranigarg to be clear, 2.2.4xx is a 16.2 targeting branch.  Is this update intended as a servicing fix for 16.1 and should be made to a 16.1 servicing branch (2.2.3xx)?  If not, then is there a 16.2 version of test tools to insert?

**Comment by jayaranigarg** [comment]
@peterhuene : Yes, we would like to take a servicing fix for 16.1. And then ofcourse, port to 16.2 branch as well. Assuming porting to future branches is something you already take care of, I will go ahaead and create a PR for 2.2.3xx branch.

**Comment by jayaranigarg** [comment]
Here you go: https://github.com/dotnet/cli/pull/11497

**Comment by peterhuene** [comment]
Closing this PR in favor of letting the 2.2.3xx change merge up.

**Pull request closed without merging**
