### PR TITLE
Using low level JsonTextReader in DependencyContextJsonReader class.

### PR DESCRIPTION
**Pull request by Yves57**
See aspnet/MVC#5060

/cc @pakrym @rynowak 

Replace the high Json.Net concept of `JObject.Load()` by using the `JsonTextReader` class.

### CODE REVIEW

**Comment by eerhardt** [comment]
@Yves57, there are failing tests. These need to be fixed before this PR can be merged.

**Comment by pakrym** [comment]
@eerhardt @Yves57 I am going to take a look and fix it.

**Comment by Yves57** [comment]
@pakrym If you don't want to waste your time, you can send me the problematic "deps.json" files, I can look at the problems.

**Comment by pakrym** [comment]
Superseded by https://github.com/dotnet/cli/pull/3972

**Pull request closed without merging**
