### PR TITLE
Inserting dotnet/templating rel/2.1.0-preview1 into cli master

### PR DESCRIPTION
**Pull request by seancpeters**
dotnet/templating build 1.0.0-beta3-20171109-311

### CODE REVIEW

**Comment by seancpeters** [comment]
WIP because I want to do a bit more testing with my local build.

**Comment by seancpeters** [comment]
Removed the WIP tag. 
dotnet new testing complete, updated to newest templating build. 
Also updated the web sdk version per @vijayrkn

**Comment by seancpeters** [comment]
There was a little confusion with what all needed to be updated. I've resolved the merge conflicts and gotten the versions right. I'm not pushing anything more here unless there's issues with the builds.

**Comment by livarcocc** [comment]
@seancpeters is there anything missing for this PR or can it be merged?

**Comment by seancpeters** [comment]
@livarcocc it is complete and can be merged.

**Pull request merged**
