### PR TITLE
Update web template for Web SDK 154

### PR DESCRIPTION
**Pull request by mlorbetske**
@piotrpMSFT

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@MattGertz this update to preview4/RC2 will need approval from you

**Comment by MattGertz** [comment]
Approved (pending tests), let's take it to Shiproom.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test this please.

**Comment by enricosada** [comment]
@mlorbetske @piotrpMSFT pls update F# templates too, that's going to make f# web fail the `dotnet publish`.
F# fsproj are aligned with csproj, line by line, so is easy to do same changes (versions/deletions)

**Pull request merged**
