### PR TITLE
LOC CHECKIN | dotnet/cli release/3.0.1xx | 20190621

### PR DESCRIPTION
**Pull request by v-zbsail**
- If this PR should not run tests add text "skip[REMOVE_THIS]ci[REMOVE_THIS]please" (remove the marked text, no quotes).
- Add description for changes you are making.
- If there is an issue related to this PR, add the reference.

### CODE REVIEW

**Comment by tmeschter** [comment]
@livarcocc OK to merge this?

**Comment by peterhuene** [comment]
@tmeschter should this merge down from master to release/3.0.1xx?  I don't think we've snapped yet for preview 7.

**Comment by tmeschter** [comment]
Cut-off for loc changes for the VS 16.2 time frame was the 15th, so this is the final translation pass--assuming release/3.0.1xx is aligned with 16.2, which I was told it was.

**Comment by peterhuene** [comment]
We don't install a 3.0 SDK with 16.2, so I'm confused by this.  @livarcocc?

**Comment by livarcocc** [comment]
This should target master.

Even though we are not inserting for 16.2, my understanding is that the translators follow the VS schedule.

**Comment by livarcocc** [comment]
@v-zbsail can you please re-target this to master?

**Comment by nguerrera** [comment]
Hmm, I closed the equivalent on SDK, assuming we had everything translated on master and the merge would take care of it. Looking closer, it seems master is a bit behind on both repos vs. these prs on translation.

Nevertheless, we have time for translation in 3.0. The only hard requirement is that we meet the 16.3 loc deadline. 

@tmeschter We have no string changes in 16.2 branches so no problem there. I think the simplest course of action here is to close this and let the translations come to master on whatever schedule falls out. Does that work for you? At this time, master is our 16.3 branch. Reach out to us to check if that remains the case when 16.3 hand-offs are happening.

**Comment by nguerrera** [comment]
If not, I can reopen sdk and retarget both to master, resolve conflicts, etc. This would give us more translation in previews, but I'm not sure if it's worth the work...

**Comment by nguerrera** [comment]
Tom is OOF. I'll go ahead and redirect this to master. It's a bit of work but we'll get the translations in preview users hands sooner.

**Comment by nguerrera** [comment]
OK, rebased and retargeted to master.

**Pull request merged**
