### PR TITLE
Update Microsoft.DiaSymReader reference to 1.0.8

### PR DESCRIPTION
**Pull request by eerhardt**
~~I forgot to update this reference in our last PR. I'm tired of updating this version for this one reference.  Removing it as a test to see if we don't even need it.~~

Updating reference to stable version.

@livarcocc @piotrpMSFT @brthor

### CODE REVIEW

**Comment by brthor** [comment]
```
12:49:52 Failed to resolve library symbol hostfxr_main, error: dotnet: undefined symbol: hostfxr_main
12:49:52 /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0-preview2/debug_centos7.1_x64_prtest/build_projects/dotnet-cli-build/build.sh: line 117: 17499 Segmentation fault      dotnet restore
12:49:52 
```

This is non-ideal @schellap !

**Comment by eerhardt** [comment]
Ouch

**Comment by eerhardt** [comment]
so Stage0 is broke now?

**Comment by eerhardt** [comment]
Doing some code analysis, I see we are using this reference in order for https://github.com/dotnet/cli/blob/rel/1.0.0-preview2/src/Microsoft.Extensions.Testing.Abstractions/SourceInformationProvider.cs to do its job.

Updating the version now.

**Comment by eerhardt** [comment]
ok - PTAL.  I just updated the version number to the stable version. This dependency can't be removed.

**Comment by eerhardt** [comment]
test Debian8.2 x64 Debug Build
test RHEL7.2 x64 Release Build

**Comment by eerhardt** [comment]
The CentOS build passed, Jenkins just didn't update the badge correctly:

http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0-preview2/job/debug_centos7.1_x64_prtest/194/console

```
14:14:08 Using context: CentOS7.1 x64 Debug Build
14:14:08 Could not update commit status of the Pull Request on GitHub.
14:14:08 java.io.IOException: {
14:14:08   "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
14:14:08   "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
14:14:08 }
14:14:08 
14:14:08 	at org.kohsuke.github.Requester.handleApiError(Requester.java:561)
14:14:08 	at org.kohsuke.github.Requester._to(Requester.java:266)
14:14:08 	at org.kohsuke.github.Requester.to(Requester.java:206)
14:14:08 	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:871)
14:14:08 	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:248)
14:14:08 	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:208)
14:14:08 	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:192)
14:14:08 	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:32)
14:14:08 	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:17)
14:14:08 
```

**Pull request merged**
