### PR TITLE
AllowTrailingCommas and JsonCommentHandling.Skip for RuntimeConfig

### PR DESCRIPTION
**Pull request by wli3**
Fix https://github.com/dotnet/cli/issues/11918

### CODE REVIEW

**Comment by nguerrera** [comment]
I know it's not a breaking change issue there, but can we allow both in Tools manifest? I think it would be friendlier to allow this in a source file that might need a comment, and allow a user to use trailing commas to minimize diffs.

**Comment by wli3** [comment]
@nguerrera although comment and tailing comma is not in the spec, so it is technically invalid. It will be flagged by vscode and github view. I think it is less headache to stick to the spec than add an additional feature.

**Comment by nguerrera** [comment]
I think comments should be allowed in any config file, I'm not as passionate about trailing commas. In my mind, sticking to the spec of no comments, means that JSON should not be used for config files.

**Comment by wli3** [comment]
I would agree json is not ideal comment. However unfortunately that is the defacto "modern" config file (maybe another is yaml) that people would expect.

Also intentionally go off the spec and essentially made up our own format is not very maintainable

**Comment by livarcocc** [comment]
I don't really see strong harm in allowing comments in these files. We do allow them in other .net stack json files.

**Comment by wli3** [comment]
@livarcocc until other stack adopt s.t.json and did not enable it

**Comment by livarcocc** [comment]
So, you are ok with this being in the runtime config, which is actually a machine generated file and never checked-in but feel like doing it in the manifest is crossing a line? I fear we are leaning towards purity here at the cost of potentially harming our customers.

**Comment by wli3** [comment]
per harming the customer -- what if other languages want to read json-withcomment format and it doesn't tolerate it? 

stick to a standard does have benefit

**Comment by wli3** [comment]
runtime config is in the wild already, i agree to reduce the initial impact of the migration

**Comment by livarcocc** [comment]
Other languages reading our manifest file for tools? Then they need to figure out how to ignore or work around it. Seems super corner case and far fetched. Again, I agree in principle, but I don't see strong reasons on this case.

**Comment by wli3** [comment]
another side. Potentially we need to explain to our customer. A file allows comment, B file allows comments also tailing comma, C file owned by another level of the stack cannot for both --- instead we should just suggest the customer to write the most strict json. if we encourage them to write comment. they will hit a wall somewhere else

**Comment by wli3** [comment]
i believe consistency can help the customer better in the long run

**Comment by livarcocc** [comment]
I believe this will likely go the other way around, where they will ask for the comments from other files in the stack, I believe that comments in config files have real value and that if we don't allow them now it may come across as a limitation on our side. If someone does not want to have comments on theirs, they can simply disallow it.

**Comment by wli3** [comment]
@livarcocc if so we should push it to be the default of s.t.json and ask teams to adapt it, instead of waiting for the users to ask. @terrajobst @ahsonkhan

**Comment by livarcocc** [comment]
I don't get it why we are putting all of these in the same bucket. I don't understand why turning comments by default to our tool manifest file (which is a configuration file) needs to imply that this should be the default for all conceivable json files produced/consumed with s.t.json.

**Comment by wli3** [comment]
We had a meeting offline.

The conclusion of the meeting is: 
When there is new further json files or when s.t.json adds more feature to make reading less strict available. In general, we want to be as permissive as possible for config files.

That means for tool manifest file, we will enable all available options  -- comment and trailing commas. Although it will cause a bug to surface. I will file it separately.

**Comment by wli3** [comment]
Merge this change. Continue discuss should go to https://github.com/dotnet/cli/issues/11952

**Pull request merged**
