### PR TITLE
Adding a TestRunner.TestCompleted message to the test sinks.

### PR DESCRIPTION
**Pull request by livarcocc**
Adding a TestRunner.TestCompleted message that the runner can send to dotnet test.

cc @piotrpMSFT

### CODE REVIEW

**Comment by livarcocc** [comment]
cc @brthor @Sridhar-MS

**Comment by piotrpMSFT** [comment]
:shipit:

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT Release Build please

**Comment by livarcocc** [comment]
@mmitche This is failing because it can't find CMake in the machine. Is it missing VS?

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT Release Build please

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT Debug Build please

**Pull request merged**
