### PR TITLE
NuGet 607

### PR DESCRIPTION
**Pull request by piotrpMSFT**
@Sridhar-MS @emgarten

### CODE REVIEW

**Comment by emgarten** [comment]
:+1:

**Comment by piotrpMSFT** [comment]
@dotnet-bot test this please

**Comment by emgarten** [comment]
@piotrpMSFT  The failure here looks like an issue with the project model. NuGet 607 does not flow build only dependencies to parent projects, publish should not either.

**Comment by davidfowl** [comment]
Why is this a build dependency... https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/project.json#L27 wtf

**Comment by emgarten** [comment]
Looking at this further I see that NuGet is leaving build type dependencies in as dependency entries on the parent target entries. This ends up looking the same as an unresolved package to the project model.

I have a fix here: https://github.com/NuGet/NuGet.Client/pull/269

**Comment by piotrpMSFT** [comment]
@davidfowl just changed the dependency

**Comment by emgarten** [comment]
The dependency fix isn't in NuGet 612 yet, I'll provide the number once this finishes building.

**Comment by piotrpMSFT** [comment]
Thanks @emgarten. I just updated my PR to drop the latent "build" dependencies as well.

**Comment by emgarten** [comment]
@piotrpMSFT NuGet 613 contains the fix for removing build type dependencies.

**Comment by SajayAntony** [comment]
This pretty much blocks our cross plat pert runs. At this point .

**Comment by piotrpMSFT** [comment]
rebasing now.

**Comment by piotrpMSFT** [comment]
we're seeing a bunch of version hoisting... I'm investigating if it repros on 583...

**Comment by davidfowl** [comment]
I'll take over this change. I have another branch that I'm working on

**Pull request closed without merging**
