### PR TITLE
Add F# EndToEnd tests

### PR DESCRIPTION
**Pull request by enricosada**
a `dotnet new` an f# console app who reference an `dotnet new` F# lib, `restore` => `build` => `run`

### CODE REVIEW

**Comment by enricosada** [comment]
Ok got it, fails if lib is `netstandard` instead of `netcoreapp`.

```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void Lib.Say.hello(System.String)'.
   at Program.main(String[] argv)
```

this is the repro case of error https://github.com/dotnet/cli/issues/6912 and https://github.com/dotnet/cli/issues/6863
and anyway a good scenario to test

/cc @dsyme @cartermp @KevinRansom @ncave

**Comment by dsyme** [comment]
@enricosada Thanks!

**Comment by wli3** [comment]
Failed with 
```
Stacktrace

                                        MESSAGE:
                                        Expected command to pass but it did not.
File Name: /mnt/j/workspace/dotnet_cli/release_2.0.0/release_linux_x64_prtest/artifacts/linux-x64/stage2/dotnet
Arguments: run -p app
WorkingDir:: /mnt/j/workspace/dotnet_cli/release_2.0.0/release_linux_x64_prtest/artifacts/testpackages/artifacts/9acc2935-7089-484d-8e42-340608edf6fe
Exit Code: 134
StdOut:

StdErr:

Unhandled Exception: System.MissingMethodException: Method not found: 'Void Lib.Say.hello(System.String)'.

                                        +++++++++++++++++++
                                        STACK TRACE:
                                           at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at Microsoft.DotNet.Tools.Test.Utilities.CommandResultAssertions.Pass() in /mnt/j/workspace/dotnet_cli/release_2.0.0/release_linux_x64_prtest/test/Microsoft.DotNet.Tools.Tests.Utilities/Assertions/CommandResultAssertions.cs:line 32
   at Microsoft.DotNet.Tests.EndToEnd.GivenFSharpShouldWork.AppWithLib() in /mnt/j/workspace/dotnet_cli/release_2.0.0/release_linux_x64_prtest/test/EndToEnd/GivenFSharpShouldWork.cs:line 61
```

**Comment by cartermp** [comment]
@wli3 Looks like this is pending #6935, otherwise the test will always fail to compile.

**Comment by wli3** [comment]
@dotnet-bot test this please

**Comment by enricosada** [comment]
closing in favor of https://github.com/dotnet/cli/pull/6975 who target `release/2.0.0-preview2` branch

**Pull request closed without merging**
