### PR TITLE
Perform test platform insertion for 15.8

### PR DESCRIPTION
**Pull request by mlorbetske**
@singhsarab @abhishkk

### CODE REVIEW

**Comment by nguerrera** [comment]
@mlorbetske Does this have a corresponding change in VS? Is that VS change approved?

**Comment by mlorbetske** [comment]
@singhsarab @abhishkk could you answer Nick’s question about any approvals?

I’m not aware of any independent VS insertion for these

**Comment by nguerrera** [comment]
Hmm, the diff shows templates changing but the title says "Test platform" and there are separate entries for test platform in dependency version. What is the actual payload here? template changes?

**Comment by abhishkk** [comment]
@nguerrera @mlorbetske 
Release notes [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/releases.md#1580).
VS insertion PR [here](https://devdiv.visualstudio.com/DevDiv/Automated%20Testing/_git/VS/pullrequest/131563?_a=overview).

**Pull request merged**
