### PR TITLE
Building CLI is incremental

### PR DESCRIPTION
**Pull request by cdmihai**
This PR depends on previous PR #676.

Compiling stage 1 and stage 2 is incremental.

- removed all the place-binary scripts. They did not seem to be doing anything, and were preventing incremental compilation
- modified the compile-stage scripts to not clean the directory and to prevent copying some items if they are already there

Here are some run times for compile-stage2.ps1 (measured on windows, on one run, stage 1 compiler is crossgened). Stage 1 should have the same times when stage0 is incremental. Incremental stage 2 still takes 53 seconds due to published being called multiple times on the same projects.

========master stage 2 clean========
4 minutes

========This PR stage 2 clean========
2 minutes

========This PR stage 2 incremental second run========
53 seconds

The cool thing is that even if we clean stage 2 every time, it's still 4 minutes vs 2 minutes. This is because on pre-incremental compilation, the same dependency is compiled as many times as publish is invoked on a root project. With incremental compilation, that compilation happens only once.

### CODE REVIEW

**Comment by davidfowl** [comment]
> removed all the place-binary scripts. They did not seem to be doing anything, and were preventing incremental compilation

They are used for the dev experience of the CLI. When you build, it updates stage 2 so you can just build a single component and see the changes immediately.

**Comment by cdmihai** [comment]
@dotnet-bot test this please

**Comment by cdmihai** [comment]
@davidfowl

The `place-binary` script is an implementation to the use case of "users wants to compile a single project in place in a multi-project system".

For tackling this use case, I suggest moving away from the place-binary post-compile script because:
- It is specific to CLI development only, whereas we should design a more generic user experience for all users that have a multi-project system and want to compile only one project, in place. I don't think it's a good idea to force every user to come up with their own unique approach to `place-binary`
- It forces all user scenarios for compile to take a dependency hit on place-binary logic. For example, when stage 1 is built, its output is copied by `place-binary` into stage 2. When tests with dependencies to CLI are built, the re-building of the CLI dependencies triggers yet another copying of files into stage 2 by place-binary. This behaviour is erroneous. The place-binary logic should be executed only when the user wants to compile a single project, in place.
- Now that we have incremental compilation

There are several options to replace `place-binary` inside the CLI project:
- now that we have incremental compilation, we can take advantage of it. We can add a `--compile-only` switch to the CLI `build.[ps1|sh]` script so it only runs stage0 -> stage1 and stage1 -> stage2 compilations. Incrementality would ensure that projects that did not change do not get rebuilt.
- call dotnet-build on a project and manually specify the `--output` argument to point to stage2, thus causing overwriting the old binaries. Devs can put this in a script to not type the path every time.

However, long term, we should define a more generic user experience for this use case. It is related to the unsolved problem of how users can hook up custom logic into the CLI workflow: #510

**Comment by piotrpMSFT** [comment]
@cdmihai @davidfowl let's get incremental working first and then add back copy to output. the scripts, as they stand today, are only occasionally working since Stage2 is typically in use when updating Stage2, so there are access violations. https://github.com/dotnet/cli/issues/790

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test CentOS7.1 Release Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test CentOS7.1 Release Build please.

**Comment by mmitche** [comment]
@piotrpMSFT I'm going to shut this down in a few for maintenance (plugin updates, etc.) so your build wont' complete for a while.  I added new machines and a build got picked up before the machine was ready which is why the last one failed.

**Comment by piotrpMSFT** [comment]
Thanks @mmitche I just wanted to get this back in the queue before I forget. We'd really like to get this merged tonight.

/cc @cdmihai

**Comment by piotrpMSFT** [comment]
@dotnet-bot test CentOS7.1 Release Build please.

**Comment by mmitche** [comment]
@piotrpMSFT Jenkins is still down due to the VM not booting correctly upon a reboot.  This is being worked on right now.

**Pull request merged**
