### PR TITLE
use Sdks attribute in `dotnet new` templates

### PR DESCRIPTION
**Pull request by piotrpMSFT**
This:

```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">

  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NETStandard.Library" Version="1.6" />
  </ItemGroup>

</Project>
```

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
Also fixes #4906 since `PrivateAssets` is no longer in these templates.

**Comment by piotrpMSFT** [comment]
@rainersigwald thanks for the fast turnaround! This PR is now passing localy. @MattGertz can you take a look? @livarcocc @krwq @jgoshi ?

**Comment by piotrpMSFT** [comment]
Opened https://github.com/Microsoft/msbuild/issues/1433 to track ignoring casing for Sdk's

**Comment by piotrpMSFT** [comment]
Opened Issue https://github.com/dotnet/sdk/pull/454 and PR https://github.com/dotnet/sdk/pull/455 to fix SDK templates.

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build
@dotnet-bot Test Debian8.2 x64 Debug Build
@dotnet-bot Test RHEL7.2 x64 Release Build

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu x64 Release Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OpenSUSE13.2 x64 Debug Build please.

**Pull request merged**
