### PR TITLE
preserve whitespace

### LINKED ISSUE #4314: dotnet migrate should add trailing new line at the end of generated proj file
Currently:
```
...
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" /> 
</Project>
 \ No newline at end of file 
```

### PR DESCRIPTION
**Pull request by brthor**
Should fix #4314 

@rainersigwald I am seeing the preserveFormatting approach is eating the newline though. Do you see something I may be doing wrong here?

/cc @piotrpMSFT

### CODE REVIEW

**Comment by rainersigwald** [comment]
@brthor eating which newline, the final one?

**Comment by brthor** [comment]
Yeah the final one.

**Comment by rainersigwald** [comment]
@brthor I tried adding a trailing newline to our preserve-formatting tests and it seems to work. I'm not sure what might be going on here . . .

**Comment by brthor** [comment]
In your formatting tests, do you mutate the project between loading and saving? 

i.e. creating/deleting all of item groups, property groups, items, properties, targets

**Comment by rainersigwald** [comment]
Yes, I can mutate + save to a file and get trailing whitespace back.

I tried to check out your fork at this commit and `build.cmd`, but it failed--are there special build instructions I should use? I'm trying now with the exact command the CI build used `\build.cmd -Configuration Debug -Architecture x86 -Targets Default`

**Comment by brthor** [comment]
A regular build should be succeeding here (might just do build.cmd /t:Compile though)

**Comment by brthor** [comment]
Note that the tests will fail, because of the newline issue.

**Comment by livarcocc** [comment]
I will re-base and re-submit once the msbuild issue is fixed.

**Pull request closed without merging**
