### PR TITLE
Make deb package has linux-x64 content

### PR DESCRIPTION
**Pull request by wli3**
By build using RID -- linux-x64 and
package publish use HostRID ubuntu etc

**Customer scenario**

Ubuntu/Debian user install CLI/SDK via apt-get

```
sudo apt-get install dotnet-sdk-2.0.0-preview2-0060XX
```

The binary file installed on user machine are not Linux generic but specific to RID

**Bugs this fixes**

https://github.com/dotnet/cli/issues/6809

**Workarounds, if any**

Install CLI/SDK via install script

**Risk**

The Ubuntu/Debian users will get different binary file when install via apt-get and it will potentially out of support

**Performance impact**

no

**Root cause analysis**

N/A

**How was the bug found?**

N/A

### CODE REVIEW

**Comment by wli3** [comment]
@dotnet-bot test OSX10.12 x64 Release Build

**Comment by wli3** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by wli3** [comment]
@livarcocc  @johnbeisner  the change is good now

**Comment by wli3** [comment]
@MattGertz Could you review this change?

**Comment by eerhardt** [comment]
@ellismg - can you take a look at this change?  I'm wondering if it is going to affect build from source.

**Comment by ellismg** [comment]
Thanks for pointing this out @eerhardt, I'll look in more depth later today.

**Pull request merged**
