### PR TITLE
WIP: MSBuild 15.7.52

### PR DESCRIPTION
**Pull request by AndyGerlicher**
Just testing the output of the new build (SDK build targeting netcoreapp2.1 and netstandard2.0).

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
Uhg, package dependency versions are slightly wrong.

**Comment by livarcocc** [comment]
Very happy to see this.

**Comment by AndyGerlicher** [comment]
Any idea on this? @emgarten or @livarcocc 
```
1>D:\j\workspace\release_windo---f861f43b\src\Microsoft.DotNet.Cli.Utils\Microsoft.DotNet.Cli.Utils.csproj : error NU1102: Unable to find package Microsoft.Build with version (>= 15.7.0-preview-000059) [D:\j\workspace\release_windo---f861f43b\src\dotnet\dotnet.csproj] [D:\j\workspace\release_windo---f861f43b\build.proj]
22:14:30      1>D:\j\workspace\release_windo---f861f43b\src\Microsoft.DotNet.Cli.Utils\Microsoft.DotNet.Cli.Utils.csproj : error NU1102: - Found 175 version(s) in cli-deps [ Nearest version: 15.7.0-preview-000011-1378327 ] [D:\j\workspace\release_windo---f861f43b\src\dotnet\dotnet.csproj] [D:\j\workspace\release_windo---f861f43b\build.proj]
22:14:30      1>D:\j\workspace\release_windo---f861f43b\src\Microsoft.DotNet.Cli.Utils\Microsoft.DotNet.Cli.Utils.csproj : error NU1102: - Found 21 version(s) in BlobFeed [ Nearest version: 15.7.0-preview-000011-1397096 ] [D:\j\workspace\release_windo---f861f43b\src\dotnet\dotnet.csproj] [D:\j\workspace\release_windo---f861f43b\build.proj]
22:14:30      1>D:\j\workspace\release_windo---f861f43b\src\Microsoft.DotNet.Cli.Utils\Microsoft.DotNet.Cli.Utils.csproj : error NU1102: - Found 16 version(s) in nuget.org [ Nearest version: 15.5.180 ] [D:\j\workspace\release_windo---f861f43b\src\dotnet\dotnet.csproj] [D:\j\workspace\release_windo---f861f43b\build.proj]
```

It looks like it's looking for version >= `15.7.0-preview-000059`, which is right:
https://dotnet.myget.org/feed/msbuild/package/nuget/Microsoft.Build/15.7.0-preview-000059

And I think our dependency versions between packages are good. It doesn't seem to like that version though? Before we had something like `15.7.0-preview-000059-1343104` where that last part was some generated number. Could removing that be causing the issue? Let me know if you have any ideas.

**Comment by livarcocc** [comment]
I don't believe we have that msbuild feed in the list of CLI feeds. We can easily add it, but shouldn't you be publishing to the blob feed?

**Pull request closed without merging**
