### PR TITLE
Pay for play loc

### PR DESCRIPTION
**Pull request by livarcocc**
- [x] I want to try this out on Windows. Only tried on OSX so far.
- [x] I want to do a binary diff of the langpack files. If they are identical across distros, I will produce only one language pack for all distros, which will require a small tweak to this code.

Once the items above are done, I will remove the WIP.

@dotnet/dotnet-cli

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
I check that this is not working on Windows. Had to make a little play with the RegEx passed to Zip versus the tar task, as they differ slightly.
Also, diffed the localized assemblies between OSX and Windows, and turns out they are different. So, at this point, I will just generate one language pack per distro: windows x86, windows x64, linux and OSX.
I believe this is ready to be reviewed at this point. @wli3 @nguerrera

**Comment by nguerrera** [comment]
Looks good. We need https://github.com/dotnet/core-setup/pull/2717 to be merged first.

I suspect the only difference between satellites on different platforms is public-signed vs. not, but it's not urgent to have just one zip.

**Comment by livarcocc** [comment]
@MattGertz for approval

**Customer scenario**

Satellite assemblies are increasing the size of the SDK by 21mb, without considering the Nuget satellite assemblies. As such, we decided to create language packs for them when the SDK is being installed by zip/tarball. This means that native installers will be fully localized and archives will be english only with the option of overlaying the language pack archive to get additional languages. This PR, removes satellites assemblies from archives and creates a separate language pack archive to contain them.

**Bugs this fixes:** 

https://github.com/dotnet/cli/issues/6877

**Workarounds, if any**

Ship everything in the CLI with the satellite assemblies.

**Risk**

Small. In the worst cases, users will either have english only or all satellite assemblies in their SDK.

**Performance impact**

None.

**Is this a regression from a previous update?**

N/A

**Root cause analysis:**

N/A

**How was the bug found?**

Planned feature.

**Comment by livarcocc** [comment]
Like @nguerrera said, we need to wait for dotnet/core-setup#2717. I am aware of it. Go ahead and approve. I will only merge this once the core-setup change has made into the CLI. I will also validate that before merging.

**Comment by steveharter** [comment]
Note the PR for the core-setup change is https://github.com/dotnet/core-setup/pull/2731 (release/2.0.0) which is ready to go pending approval.

**Pull request merged**
