### PR TITLE
Add version suffix to build cache to ensure incremental builds are reset when it changes

### LINKED ISSUE #2687: Changing --version-suffix should trigger a new build
## Steps to reproduce

* Having a `project.json` with `"version": "1.0.0-*"`.
* Run `dotnet build --version-suffix 1`
* Run `dotnet build --version-suffix 2`

## Expected  behavior

To build twice and have a `.dll` with version 1.0.0-2

## Actual behavior

The build is not triggered and the message `Project MyProject (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.` is shown. The generated `.dll` version is 1.0.0-1.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc2-002426)

Product Information:
 Version:     1.0.0-rc2-002426
 Commit Sha:  08ee6dedd9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

### PR DESCRIPTION
**Pull request by anurse**
Fixes #2687 

This adds a mechanism to store build arguments in the incremental cache and compare them when deciding if existing build artifacts can be used. It also adds `version-suffix` as the first (and only) of these arguments.

/cc @davidfowl @pakrym @cdmihai

### CODE REVIEW

**Comment by anurse** [comment]
@dotnet-bot test OSX x64 Release Build please

**Comment by anurse** [comment]
```
16:33:20 The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc3-004306' was not found.
16:33:20   - Check application dependencies and target a framework version installed at:
16:33:20       /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.0.0/release_osx_x64_prtest/artifacts/osx.10.11-x64/stage1/shared/Microsoft.NETCore.App
16:33:20   - The following versions are installed:
16:33:20       1.0.0-rc3-002862
16:33:20   - Alternatively, install the framework version '1.0.0-rc3-004306'.
```

I'm seeing this locally now as well but it seems unrelated. @piotrpMSFT @eerhardt is this something you guys are aware of? Something wrong with the packages on the feed?

**Comment by pakrym** [comment]
LGTM, figure out build issues and :shipit:

**Comment by cdmihai** [comment]
LGTM

**Comment by eerhardt** [comment]
> I'm seeing this locally now as well but it seems unrelated. @piotrpMSFT @eerhardt is this something you guys are aware of? Something wrong with the packages on the feed?

The branch was broken yesterday afternoon for a while. We split the shared framework out into the core-setup repo, and since we were using `rc3-*` versions in our project.jsons, it was picking up different versions between your NuGet package and the shared framework that was installed on disk.

This is now fixed, and rebasing your change on the latest is the right thing.

**Comment by anurse** [comment]
Yeah, I was just going to say that it seems to be working locally again after rebase. I've pushed the update to the server

**Pull request merged**
