### PR TITLE
Add NuGet version to DependencyVersions.props.

### PR DESCRIPTION
**Pull request by eerhardt**
I moved all usages of `4.0.0-rc3` that refer to the NuGet version into the DependencyVersions.props file.

Note: The line endings of DependencyVersions.props were all changed in the previous commit to that file.  This change is correcting that.

@livarcocc

### CODE REVIEW

**Comment by livarcocc** [comment]
@MattGertz Do we need shiproom approval for just build script changes?

**Comment by MattGertz** [comment]
No, I can approve that (and just did).  Pending successful checks, of course... ;-)

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Comment by eerhardt** [comment]
test Ubuntu x64 Release Build

**Comment by eerhardt** [comment]
Test Windows_NT x64 Release Build

**Comment by eerhardt** [comment]
Test OSX x64 Release Build

**Pull request merged**
