### PR TITLE
Update ASP.NET to 24801 - SetupCrossgen build 56

### PR DESCRIPTION
**Pull request by mlorbetske**
Related to #6462 and and #6460 

This aligns with SetupCrossgen build 56 with timestamps

### CODE REVIEW

**Comment by livarcocc** [comment]
@Pilchie @ManishJayaswal for approval.

**Comment by ManishJayaswal** [comment]
@mlorbetske - what is the customer scenario here?

**Comment by mlorbetske** [comment]
This updates to the latest ASP.NET templates and brings the referenced set of packages in to alignment with the runtime package store. The customer scenario is to allow for the creation of ASP.NET Core 2.0 web applications at the command line and in visual studio

**Comment by livarcocc** [comment]
@dotnet-bot Test Debian8.2 x64 Debug Build

**Pull request merged**
