### PR TITLE
Test platform insertion 15.8 RTM

### PR DESCRIPTION
**Pull request by abhishkk**
TestPlatform insertion for 15.8.0

VS insertion PR [link](https://devdiv.visualstudio.com/DevDiv/Automated%20Testing/_git/VS/pullrequest/131563?_a=overview)

### CODE REVIEW

**Comment by abhishkk** [comment]
@livarcocc Is release/2.1.4xx correct branch for 15.8 RTM?

**Comment by abhishkk** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by nguerrera** [comment]
@Pilchie dependency flow still auto approved or now that we're in QB mode, do we need a VSO bug for each one?

@dsplaisted Is everyone else up to date: fsharp? roslyn? I have been seeing insertions for nuget, msbuild, web sdk, but I don't recall F# and roslyn recently.

**Comment by nguerrera** [comment]
@abhishkk Yes, this is the correct branch.

**Comment by nguerrera** [comment]
Spoke to @dsplaisted and he said we can merge these.

**Comment by nguerrera** [comment]
(since they are merged to VS)

**Pull request merged**
