### PR TITLE
Update stage 0

### PR DESCRIPTION
**Pull request by dsplaisted**
Includes NuGet update which should unblock #11366

### CODE REVIEW

**Comment by dsplaisted** [comment]
@wli3 It looks like the Json APIs changed and this is failing to compile since JsonReaderException no longer exists.  Can you take a look?

**Comment by wli3** [comment]
@ahsonkhan do you know what is the replacement for JsonReaderException?

**Comment by ahsonkhan** [comment]
> do you know what is the replacement for JsonReaderException?

`JsonException`

**Comment by wli3** [comment]
just pushed the fix https://github.com/dotnet/corefx/issues/37272

**Comment by wli3** [comment]
thanks @ahsonkhan !

**Comment by wli3** [comment]
/opt/code/artifacts/tmp/Debug/dotnet/sdk/3.0.100-preview6-012021/NuGet.targets(292,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Common, Version=5.2.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified. [/opt/code/artifacts/tmp/Debug/test/dotnet-

**Comment by wli3** [comment]
need to update nuget?

**Pull request merged**
