### PR TITLE
Update NuGet Version to 3.5.0-beta2-1451

### PR DESCRIPTION
**Pull request by zhili1208**

### CODE REVIEW

**Comment by rrelyea** [comment]
@piotrpMSFT @eerhardt @joshfree @rohit21agrawal

**Comment by rrelyea** [comment]
@piotrpMSFT - believe this will fail, until you fix https://github.com/dotnet/cli/issues/3356 
The updated nuget build is mentioned in this PR.
How should we coordinate?
/cc: @eerhardt

**Comment by pranavkm** [comment]
The build is oddly passing so far.

**Comment by pranavkm** [comment]
Although I think it needs to submitted against the rel/1.0.0-preview2 branch. @eerhardt \ @livarcocc should be able to confirm.

**Comment by eerhardt** [comment]
> Although I think it needs to submitted against the rel/1.0.0-preview2 branch. @eerhardt \ @livarcocc should be able to confirm.

Yes, for the CLI, all "preview2" changes need to go into the `rel/1.0.0-preview2` branch.

**Comment by eerhardt** [comment]
I'm closing this PR out since rel/1.0.0-preview2 is on the latest NuGet version (beta2-1484).  We will RI rel/1.0.0-preview2 into rel/1.0.0, so this change is no longer needed.

**Pull request closed without merging**
