### PR TITLE
Fix restore for appdepsdk

### PR DESCRIPTION
**Pull request by davidfowl**
Added `Microsoft.NETCore.Platforms` to get the correct appsdk. I'm going to merge this since it's blocking the build.

/cc @schellap @piotrpMSFT @anurse

### CODE REVIEW

**Comment by davidfowl** [comment]
I believe the supposed compile error is by design. Not sure why ubuntu doesn't like it

**Comment by davidfowl** [comment]
@dotnet-bot Test Ubuntu Debug Build please

**Comment by davidfowl** [comment]
Test Ubuntu Release Build please

**Comment by anurse** [comment]
Looks fine to me. The Ubuntu failures still seem unrelated so I'm not sure how to unblock the merge button...

**Comment by anurse** [comment]
@dotnet-bot Test Ubuntu Debug Build please

**Comment by anurse** [comment]
@dotnet-bot Test Ubuntu Release Build please

**Comment by schellap** [comment]
LGTM /Cc @gkhanna79

**Pull request closed without merging**
