### PR TITLE
Fix fsharp targetfw rel1.0.0

### PR DESCRIPTION
**Pull request by piotrpMSFT**
@enricosada this is a rebase of #1023

### CODE REVIEW

**Comment by enricosada** [comment]
I'll update this tomorrow

**Comment by enricosada** [comment]
working on it

**Comment by enricosada** [comment]
done in #1180

**Comment by enricosada** [comment]
this pr fix #692

**Comment by piotrpMSFT** [comment]
Looks like this is failing CI

**Comment by enricosada** [comment]
@piotrpMSFT you need to merge #1180 in `fix_fsharp_targetfw_rel1.0.0`, after that this pr see the new commits.
I can only send pr to `fix_fsharp_targetfw_rel1.0.0` or `rel/1.0.0`

**Comment by enricosada** [comment]
I cannot directly push to `fix_fsharp_targetfw_rel1.0.0` branch to update this pr, i have no push permission, i can only send pr

**Pull request closed without merging**
