### PR TITLE
Update the Sdk version to the latest build.

### PR DESCRIPTION
**Pull request by eerhardt**
@brthor @livarcocc @Sridhar-MS @piotrpMSFT

### CODE REVIEW

**Comment by brthor** [comment]
:shipit:

**Comment by brthor** [comment]
Actually should we just wait on the rename to bump this version?

**Comment by eerhardt** [comment]
> Actually should we just wait on the rename to bump this version?

Doesn't hurt to do it again... does it?

I mostly wanted to ensure nothing was broken with the latest.  So getting the latest in earlier seems better to me.

**Comment by brthor** [comment]
sounds good

**Pull request merged**
