### PR TITLE
Show help info when no or wrong arguments are given

### LINKED ISSUE #5383: 'dotnet add' with no arguments should probably show output of `dotnet add --help`
This would be consistent with the behavior of `dotnet add package` and `dotnet add reference` when called with no other args.

## Steps to reproduce
```
dotnet add
```

## Expected  behavior
```
Required command was not provided.

.NET Add Command

Usage: dotnet add [arguments] [options] [command]

Arguments:
  <PROJECT>  The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h|--help  Show help information

Commands:
  package    Command to add package reference
  reference  Command to add project to project reference

Use "dotnet add [command] --help" for more information about a command.
```

## Actual behavior
```
Required command was not provided.
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc4-004530)

Product Information:
 Version:            1.0.0-rc4-004530
 Commit SHA-1 hash:  4f0b7bd58c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15007
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004530

### LINKED ISSUE #5384: 'dotnet sln' with no arguments should probably show output of `dotnet sln --help`
This would be consistent with the behavior of `dotnet sln add` and `dotnet sln remove` when called with no other args.

## Steps to reproduce
```
dotnet add
```

## Expected  behavior
```
Required command was not provided.

.NET modify solution file command

Usage: dotnet sln [arguments] [options] [command]

Arguments:
  <SLN_FILE>  Solution file to operate on. If not specified, the command will search the current directory for one.

Options:
  -h|--help  Show help information

Commands:
  add     Add a specified project(s) to the solution.
  list    List all projects in the solution.
  remove  Remove the specified project(s) from the solution. The project is not impacted.

Use "dotnet sln [command] --help" for more information about a command.
```

## Actual behavior
```
Required command was not provided.
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc4-004530)

Product Information:
 Version:            1.0.0-rc4-004530
 Commit SHA-1 hash:  4f0b7bd58c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15007
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004530

### PR DESCRIPTION
**Pull request by mikkelbu**
When no arguments (or wrong arguments) are given to the following
commands then we also show the help for the command
* dotnet add
* dotnet list
* dotnet remove
* dotnet sln

Fixes #5383, fixes #5384

### CODE REVIEW

**Comment by livarcocc** [comment]
@MattGertz for approval.

**Comment by livarcocc** [comment]
@wli3 please take a look

**Comment by MattGertz** [comment]
Approved & thank you!

**Comment by livarcocc** [comment]
Thanks for the PR @mikkelbu

**Pull request merged**
