### PR TITLE
Fix for issue #1656

### PR DESCRIPTION
**Pull request by Peter-Schneider**

### CODE REVIEW

**Comment by brthor** [comment]
If bold recursion is > 0, we are inside a bold tag and the color should be dark, why change it this way?

**Comment by brthor** [comment]
@Peter-Schneider this does not fix the issue of bold bleeding like in #1656 but I still think it's a valuable fix.

Please open an issue for the bold colors being darker and let's get this merged :smile:

**Comment by Peter-Schneider** [comment]
@brthor I've submitted issue #1686 :wink:

**Comment by brthor** [comment]
:shipit:

**Comment by piotrpMSFT** [comment]
Thanks for the contribution, @Peter-Schneider

**Comment by Peter-Schneider** [comment]
:+1: Thanks for merging, @piotrpMSFT - I think issue #1686 can be closed then...

**Pull request merged**
