### PR TITLE
[WIP: Do not merge]Add kestrel tests.

### PR DESCRIPTION
**Pull request by Sridhar-MS**
Tests will 'build', 'run', 'publish' and 'execute' a Kestrel Hello World server as a PortableFatApp and as a Standalone app.

This PR is built on top of https://github.com/dotnet/cli/pull/2156 to test host changes.

cc @schellap @gkhanna79

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2187)

### CODE REVIEW

**Comment by schellap** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@schellap Are you not planning to merge https://github.com/dotnet/cli/pull/2156?

**Comment by schellap** [comment]
I merged because kestrel seems to have run in some of them.

**Comment by Sridhar-MS** [comment]
I fixed some issues regarding running tests inside a docker.

**Comment by Sridhar-MS** [comment]
@schellap only one Windows test is failing which I suspect is because of file paths exceeding max limit. I will take a look at it tomorrow.

**Comment by schellap** [comment]
@Sridhar-MS thank you so much for helping out. I have validated by hand on Windows, so we should be good. It helped me find an usage of an uninitialized variable. Cc @piotrpMSFT @gkhanna79

**Comment by gkhanna79** [comment]
Very cool @Sridhar-MS and @schellap!

**Comment by muratg** [comment]
:bow:

**Comment by Sridhar-MS** [comment]
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by Sridhar-MS** [comment]
Closing this PR. Tracked in #2269

**Pull request closed without merging**
