### PR TITLE
Update branding and branch info for release/2.1.5xx

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
@mmitche This doesn't seem to be picking up the change to dotnet-ci for release/2.1.5xx

**Comment by mmitche** [comment]
test this please

**Comment by nguerrera** [comment]
@mmitche Thanks. For my education, did you do something elsewhere to awaken this, or is that incantation required instead of close/reopen for new branch?

**Comment by mmitche** [comment]
I ran the generator.  It's only triggered by a new commit in the branch, so if no commits had happened the jobs don't exist: https://ci.dot.net/job/dotnet_cli/job/release_2.1.5xx/job/generator/build?delay=0sec

**Pull request merged**
