### PR TITLE
typo

### PR DESCRIPTION
**Pull request by github-john-doe**

### CODE REVIEW

**Comment by github-john-doe** [comment]
@nguerrera

**Comment by wli3** [comment]
Hi @github-john-doe, 
Thank you!

Did you edit .xlf file by hand? You should edit LocalizableStrings.resx first and run _./build.cmd /p:UpdateXlfOnBuild=true_ to update the localization file properly.

**Comment by github-john-doe** [comment]
Got it, will do.

**Comment by github-john-doe** [comment]
Fixed.

**Comment by nguerrera** [comment]
Thanks!

**Comment by github-john-doe** [comment]
Please merge the change?

**Comment by github-john-doe** [comment]
Thanks!

**Pull request merged**
