### PR TITLE
Updating the Sdk to one that includes the error surfacing work.

### PR DESCRIPTION
**Pull request by livarcocc**
@dotnet/dotnet-cli 

@MattGertz this is dependency update in the CLI. Just bringing over the changes already approved in the SDK.

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE42.1 x64 Debug Build

**Comment by livarcocc** [comment]
@mmitche Are we having issues with our Fedora24 machines? This PR has been on the queue for it in the same position for a while now.

**Comment by mmitche** [comment]
@livarcocc We are switching around our subscriptions.  I'll check on this one

**Comment by livarcocc** [comment]
@mmitche do we know when we will be able to have this leg working again? I am waiting for this build to finish to do a VS insertion.

**Comment by mmitche** [comment]
@dotnet-bot test Fedora24 x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Fedora24 x64 Release Build

**Comment by mmitche** [comment]
@dotnet-bot test Fedora24 x64 Release Build

**Pull request merged**
