### PR TITLE
Remove csv deps file generation

### PR DESCRIPTION
**Pull request by pakrym**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2118)

### CODE REVIEW

**Comment by pakrym** [comment]
@dotnet-bot test this please

**Comment by pakrym** [comment]
@dotnet-bot test this please

**Comment by anurse** [comment]
:shipit:

**Comment by pakrym** [comment]
@dotnet-bot test this please

**Comment by pakrym** [comment]
@dotnet-bot test this please

**Comment by pakrym** [comment]
@dotnet-bot test this please

**Comment by pakrym** [comment]
@dotnet-bot test Ubuntu x64 Release Build please
@dotnet-bot test Ubuntu x64 Debug Build please
@dotnet-bot test  OSX x64 Release Build please

**Comment by pakrym** [comment]
@dotnet-bot test this please

**Comment by pakrym** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please

**Pull request merged**
