### PR TITLE
project json migration nuget package

### PR DESCRIPTION
**Pull request by brthor**
@333fred @eerhardt

### CODE REVIEW

**Comment by 333fred** [comment]
I'm assuming this is part of a nuproj that will generate the nupkg for you? If so, 👍

**Comment by brthor** [comment]
Not quite, since the projects are still project.json based, this itemgroup just tells the build system which projects to go build for packaging, sign, and eventually `dotnet pack`.  It's going that direction though

**Comment by brthor** [comment]
dotnet test this please

**Comment by eerhardt** [comment]
@dotnet-bot test Windows_NT x64 Release Build please
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by eerhardt** [comment]
:shipit:

**Pull request merged**
