### PR TITLE
Update 1.x templates for 1.1.6

### PR DESCRIPTION
**Pull request by JunTaoLuo**
These are the latest templates built for 1.1.6. I'm still figuring out which feed this package needs to be on.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
this template update contains the changes in https://github.com/aspnet/templating/pull/160

**Comment by JunTaoLuo** [comment]
Okay it seems like we push our package to aspnetcore-master. @pranavkm has volunteered to push the package manually. Once done this PR is ready to be merged.

**Comment by livarcocc** [comment]
@dotnet-bot Test this please.

**Comment by JunTaoLuo** [comment]
@dotnet-bot Test this please

**Comment by JunTaoLuo** [comment]
@dotnet-bot Test this please.

**Comment by pranavkm** [comment]
Looks like a test failure:

```
DOTNETTEST : error Message:  [/Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.1.0/release_osx_x64_prtest/build/test/RunTest.proj]
                      Expected directory "1.1.4" cannot be found inside directory "/Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.1.0/release_osx_x64_prtest/test/dotnet.Tests/bin/Release/netcoreapp1.1/Dotnet_first_time_experience_tests/nuget_cache/microsoft.aspnetcore.mvc". (TaskId:8)
                     Stack Trace: (TaskId:8)
                        at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) (TaskId:8)
                        at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) (TaskId:8)
                        at Microsoft.DotNet.Tools.Test.Utilities.DirectoryInfoAssertions.HaveDirectory(String expectedDir) in /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.1.0/release_osx_x64_prtest/test/Microsoft.DotNet.Tools.Tests.Utilities/Assertions/DirectoryInfoAssertions.cs:line 146 (TaskId:8)
                        at Microsoft.DotNet.Tools.Test.Utilities.DirectoryInfoAssertions.HaveDirectories(IEnumerable`1 expectedDirs) in /Users/dotnet-bot/j/workspace/dotnet_cli/rel_1.1.0/release_osx_x64_prtest/test/Microsoft.DotNet.Tools.Tests.Utilities/Assertions/DirectoryInfoAssertions.cs:line 151 (TaskId:8)
```

Do we need to change versions in more places?

**Comment by livarcocc** [comment]
Yes. We need to update some tests as well it seems.

**Comment by pranavkm** [comment]
@JunTaoLuo got the test updated. Third time's the charm!

**Comment by JunTaoLuo** [comment]
01:03:30.181  4:25>DOTNETTEST : error Message:  [/mnt/resource/j/workspace/dotnet_cli/rel_1.1.0/debug_centos7.1_x64_prtest/build/test/RunTest.proj]
                      System.IO.IOException : The process cannot access the file '/mnt/resource/j/workspace/dotnet_cli/rel_1.1.0/debug_centos7.1_x64_prtest/.nuget/packages/.tools/dotnet-portable/1.0.0/netcoreapp1.1/project.assets.json' because it is being used by another process. (TaskId:7)
                     Stack Trace: (TaskId:7)
                        at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent) (TaskId:7)
                        at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent) (TaskId:7)
                        at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) (TaskId:7)
                        at NuGet.ProjectModel.LockFileFormat.Read(String filePath, ILogger log) (TaskId:7)
                        at Microsoft.DotNet.Tests.GivenAProjectToolsCommandResolver.GenerateDepsJsonMethodDoesntOverwriteWhenDepsFileAlreadyExists() in /mnt/resource/j/workspace/dotnet_cli/rel_1.1.0/debug_centos7.1_x64_prtest/test/Microsoft.DotNet.Cli.Utils.Tests/GivenAProjectToolsCommandResolver.cs:line 267 (TaskId:7)

This doesn't seem to be related to this change.

**Comment by livarcocc** [comment]
This is our 1.0 branch and it has some test intermittent failures that we have since fixed. Kicking that leg again.

@dotnet-bot Test CentOS7.1 x64 Debug Build

**Pull request merged**
