### PR TITLE
Insert NuGet Build 4.8.0-rtm.5374 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.8.0-rtm.5374 into cli release/2.1.4xx branch

### CODE REVIEW

**Comment by nguerrera** [comment]
@mishra14 This build will NOT make it in to 2.1.400, an maybe not  2.1.40 either.

What is in here? Did this get inserted into VS?

cc @livarcocc

**Comment by mishra14** [comment]
@nguerrera This is a 4.8 escrow fix that we are trying to insert into VS. You can read more about it [here](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/135213?_a=overview).

cc: @jainaashish

**Comment by livarcocc** [comment]
We will not be able to absolve this for 15.8 at this point. We cut our final build and are now working on 401 for servicing.

**Comment by nguerrera** [comment]
@livarcocc @mishra14 Should we be taking this into 2.1.4xx now for the next servicing train that comes along?

**Comment by mishra14** [comment]
🔔  @jainaashish @rrelyea  Can you comment on this not making into 15.8 cli/sdk?

**Comment by nguerrera** [comment]
I think we already resolved that it won't be in 15.8 CLI. The question is do we want it in 2.1.402+, and I believe the answer is yes,

**Comment by livarcocc** [comment]
There will be a new PR for this soon.

**Pull request closed without merging**
