### PR TITLE
Fix installer issues

### LINKED ISSUE #2100: .NET Core Installer still claims it is the CLI installer:
Running https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-win-x64.latest.exe, this is what the installer dialog looks like:

image

### LINKED ISSUE #2161: .NET Core Mac pkg Installer missing default strings
screen shot 2016-03-31 at 8 37 07 am

Resources {SharedFrameworkNugetName} and {SharedFrameworkNugetVersion} are not filled in properly 

.NET Core Installer version 1.0.0-rc2-23930

### PR DESCRIPTION
**Pull request by Sridhar-MS**
- Sign the Sharedfx bundle correctly.
- Fix the installer title for SharedFx bundle. Fixes #2100
- Fix the installer title for SharedFx pkg. Fixes #2161

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2163)

### CODE REVIEW

**Comment by Sridhar-MS** [comment]
@piotrpMSFT @Petermarcu Can we get this in?

**Comment by Sridhar-MS** [comment]
The signed sharedfx bundle is uninstallable today. We need this change to fix it.

**Comment by Petermarcu** [comment]
What do you mean by uninstallable? Don't we want it to be uninstallable?

**Comment by Sridhar-MS** [comment]
Oh Sorry.. a typo. I meant to say The signed sharedfx bundle is *not installable* today.

**Comment by Petermarcu** [comment]
Ok, that is definitely something we need.

**Comment by Petermarcu** [comment]
@Sridhar-MS , is this ready to merge?

**Comment by Sridhar-MS** [comment]
yup

**Pull request merged**
