### PR TITLE
Update f# preview2 templates

### PR DESCRIPTION
**Pull request by enricosada**
- add `xunit` template
- add `web` template
- add tests

### CODE REVIEW

**Comment by enricosada** [comment]
@piotrpMSFT i added templates, dunno why fails on ubuntu/opensuse. 
Is possibile to merge anyway? or i need to disable tests?

**Comment by enricosada** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by cartermp** [comment]
LGTM.  I like keeping the project.json files as similar as possible.

**Comment by piotrpMSFT** [comment]
@srivatsn @MattGertz for approval

Note that this PR affects preview2 [PJ] only.

**Comment by piotrpMSFT** [comment]
@srivatsn @mattgertz

**Pull request merged**
