### PR TITLE
LOC CHECKIN | cli | HB 20161216

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by nguerrera** [comment]
@srivatsn @piotrpMSFT

**Comment by nguerrera** [comment]
@dotnet-bot Test Debian8.2 x64 Debug Build please

**Comment by nguerrera** [comment]
@dotnet-bot Test Debian8.2 x64 Debug Build please

**Comment by nguerrera** [comment]
Looks like https://github.com/dotnet/cli/pull/5056 would fix CI.

**Comment by livarcocc** [comment]
@dotnet-bot Test Debian8.2 x64 Debug Build

**Pull request merged**
