### PR TITLE
fixes #1858

### LINKED ISSUE #1858: No executable found matching command "dotnet-publish-iis" etc.
## Steps to reproduce

   "tools": {
        "dotnet-publish-iis": "1.0.0-*",
        "dotnet-razor-tooling": "1.0.0-*",
        "dotnet-ef": "1.0.0-*"
    },

>dotnet restore
>dotnet ef
>dotnet publish-iis
## Actual behavior

No executable found matching command "dotnet-ef"
No executable found matching command "dotnet-publish-iis"

## Environment data
`dotnet --version` output:
.NET Command Line Tools (1.0.0-beta-001741)

Product Information:
 Version:     1.0.0-beta-001741
 Commit Sha:  622cb17d7c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
[zaxitech_core_demo.zip](https://github.com/dotnet/cli/files/173349/zaxitech_core_demo.zip)

### PR DESCRIPTION
**Pull request by brthor**
cc @moozzyk

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2011)

### CODE REVIEW

**Comment by moozzyk** [comment]
This looks good to me but I am not extremely familiar with the code...

**Comment by brthor** [comment]
The issue was the project Context of the consumer app was being resolved always against netstandardapp1.5, which doesn't work if it's not using that tfm :smile: 

This change just takes whatever tfm/rid is there and takes the tools node out of that context.

**Comment by moozzyk** [comment]
Yes. This I got from the change. I am just not sure if there isn't any other code that assumes that tools are always netstandardapp1.5

**Comment by bricelam** [comment]
LGTM

**Comment by eerhardt** [comment]
@brthor - your windows test failure:  http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0/job/debug_windows_2016_x86_prtest/377/

```
13:33:24       File Name: D:\j\workspace\debug_windows---06508db9\artifacts\win10-x86\stage2\dotnet.exe
13:33:24       Arguments: portable 
13:33:24       Exit Code: 131
13:33:24       StdOut:
13:33:24       
13:33:24       StdErr:
13:33:24       Could not load host policy library []
```

looks like the same problem I fixed with https://github.com/dotnet/cli/pull/1990/commits/f6335b536d9c31a5a42acab0abb4983b08899418.  Haven't merged that PR yet.  Looks like we'll need a new CoreFX build before I can merge my PR. Maybe taking that fix separately might be a good idea...

**Comment by piotrpMSFT** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_2016 x86 Debug Build please.

**Comment by brthor** [comment]
Cherry picked @eerhardt 's fix for the `could not load host policy` issue

**Comment by brthor** [comment]
rebased on @Sridhar-MS to fix the test failures

**Comment by brthor** [comment]
@mmitche something up with 2016?

**Comment by brthor** [comment]
ubuntu debug has passed, don't know why it's showing as in progress

**Comment by brthor** [comment]
2016 not even started, :frowning: 

Should we just merge this?

**Pull request merged**
