### PR TITLE
Enable Jenkins to parse trx file

### PR DESCRIPTION
**Pull request by piotrpMSFT**

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
test ci please

**Comment by piotrpMSFT** [comment]
dotnet test CentOS7.1 x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x64 Release Build please.

**Comment by livarcocc** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please.
@dotnet-bot test Windows_NT x64 Release Build please.

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Pull request merged**
