### PR TITLE
Add license text to LZMA SDK license notice

### PR DESCRIPTION
**Pull request by richlander**
- Added full license to LZMA SDK entry in the 3PN file.

### CODE REVIEW

**Comment by livarcocc** [comment]
@MattGertz Marking this as approved as this is a documentation only change.

**Comment by livarcocc** [comment]
@dotnet-bot Test Fedora23 x64 Debug Build

**Comment by piotrpMSFT** [comment]
Is this a 1.0.0 ship blocker?

**Comment by Petermarcu** [comment]
I don't think so but @richlander can confirm.

**Comment by richlander** [comment]
Not a ship blocker, as this is just improving the LZMA entry not creating it from scratch.

**Pull request merged**
