### PR TITLE
Backport upgrade behavior to 2.1.8xx

### PR DESCRIPTION
**Pull request by joeloff**
Backport upgrade behavior to 2.1.8xx

### CODE REVIEW

**Comment by joeloff** [comment]
cc @jamshedd

**Comment by wli3** [comment]
This is a cherry-pick? Did you test it locally?

**Comment by joeloff** [comment]
@wli3 not cherry pick, we have a tool that scraped all the official installers and then generate the WiX authoring so we can just paste it in, or were you referring to something else?

**Comment by wli3** [comment]
Just test locally with the build and see if it actually update an existing installation

**Comment by joeloff** [comment]
yeah, that's what I'm doing. I've built a few installers to run through upgrade/downgrade/SxS/uninstall scenarios

**Review by wli3 — APPROVED** [review]

**Comment by joeloff** [comment]
Detection is working, here's a log example from a fake 812 to 814 upgrade:

[21A0:3420][2020-10-23T15:10:46]i102: Detected related bundle: {211c7ea8-de3c-4415-8031-85d5eb25dc01}, type: Upgrade, scope: PerMachine, version: 2.1.812.9913, operation: MajorUpgrade

Below is from SxS upgrade (2.1.805+2.1.809 upgrading to 2.1.814)

[1984:23A8][2020-10-23T15:30:28]i102: Detected related bundle: {8b78fabb-be69-4a68-810c-46ac7f5d2585}, type: Upgrade, scope: PerMachine, version: 2.1.809.0, operation: MajorUpgrade
[1984:23A8][2020-10-23T15:30:28]i102: Detected related bundle: {9d8b88f3-2932-4566-ba6b-0bd4edd2fe95}, type: Upgrade, scope: PerMachine, version: 2.1.805.0, operation: MajorUpgrade

**Pull request merged**
