### PR TITLE
Add hyphen between Download Checksums

### PR DESCRIPTION
**Pull request by jchannon**
It appears to be 1 link but its 2, 1 for the download and 1 for the checksums

skipciplease

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@blackdwarf can you review?

**Comment by blackdwarf** [comment]
LGTM

**Comment by eerhardt** [comment]
@jchannon - what browser are you using?  On Chrome on Windows, and on Safari on Mac, the two hyperlinks are on separate lines

screen shot 2017-02-23 at 10 20 58 pm

Note: this is fixed in the master branch:  https://github.com/dotnet/cli/tree/master#installers-and-binaries

**Comment by jchannon** [comment]
OSX & Chrome

**Comment by jchannon** [comment]
screen shot 2017-02-24 at 08 08 21

**Comment by eerhardt** [comment]
:+1:

**Comment by eerhardt** [comment]
@jchannon - I decided to back port the master branch format into rel/1.0.0 with #5838.  I needed to do that for the new distro work that I need to add into the README.

I think this PR can now be closed in favor of #5838.  That PR will fix this problem.

Let me know if you think that is not the case.

**Pull request closed without merging**
