### PR TITLE
Fix the CI legs; CLI:release/2.1.3xx

### PR DESCRIPTION
**Pull request by ghost**
The Linux-musl command-line should be derived from "baseShellBuildCommand" not "buildCommand"

Follow-up to PR: https://github.com/dotnet/cli/pull/9502

### CODE REVIEW

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
_Successful CI runs from the newer netci.groovy:_
**Linux-musl x64 Debug**
https://ci.dot.net/job/dotnet_cli/job/release_2.1.3xx/job/GenPRTest/job/debug_linux-musl_x64_prtest/1/
**Linux_NoSuffix arm Release**
https://ci.dot.net/job/dotnet_cli/job/release_2.1.3xx/job/GenPRTest/job/release_linux_nosuffix_arm_prtest/1/
**Linux_NoSuffix x64 Release**
https://ci.dot.net/job/dotnet_cli/job/release_2.1.3xx/job/GenPRTest/job/release_linux_nosuffix_x64_prtest/1/
**Windows_NT_NoSuffix x64 Release**
https://ci.dot.net/job/dotnet_cli/job/release_2.1.3xx/job/GenPRTest/job/release_windows_nt_nosuffix_x64_prtest/1/

**Review by nguerrera — APPROVED** [review]

**Comment by nguerrera** [comment]
Please squash and clean up the commit description when merging.

**Pull request merged**
