### PR TITLE
Don't try to uplift when we find a * version in a dependency.

### PR DESCRIPTION
**Pull request by livarcocc**
Fixes https://github.com/dotnet/cli/issues/5890

@piotrpMSFT @jgoshi @jonsequitur

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@mattgettz this is a migration issue we'd like to take for 1.0.1. It was reported by someone migrating with RC. There is a workaround but it is quite involved. We don't have a sense that this is pervasive, but want to have a fix available in case the pattern is popular.

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test this please

**Pull request closed without merging**
