### PR TITLE
Merge internal and update 2.1.8xx branding

### PR DESCRIPTION
**Pull request by sfoslund**

### CODE REVIEW

**Comment by sfoslund** [comment]
> Expected File 2.1.807-preview-009872.aspNetCertificateSentinel cannot be found in directory /opt/code/bin/3/rhel.6-x64/test/dotnet.Tests/.cctor/Dotnet_first_time_experience_tests/nuget_home/.dotnet.

@wli3 it looks like bumping the branding broke something, do you recognize this error?

**Comment by wli3** [comment]
Nothing to merge from internal?

That error message looks like one of the famous flaky test

**Review by wli3 — APPROVED** [review]

**Comment by wli3** [comment]
CI get stuck again. Try run git commit --amend. And git push --force to reset the commit hash and kick the CI

**Comment by sfoslund** [comment]
@wli3 yes, there was only one commit to merge from internal. It looks like the error is persistent.

**Comment by wli3** [comment]
Let's disable this test. It is disabled in other branches 
https://github.com/dotnet/cli/blob/release/3.1.4xx/test/dotnet-new.Tests/NewCommandTests.cs

It is likely out of date here. @donJoseLuis

**Comment by wli3** [comment]
Or even worse, flaky

**Comment by sfoslund** [comment]
@wli3 [GivenSecurityExceptionItPrintsWarning](https://github.com/dotnet/cli/blob/release/2.1.8xx/test/Microsoft.DotNet.ShellShim.Tests/WindowsEnvironmentPathTests.cs#L146) is failing now and it doesn't look like this one is disabled in other branches. Is this a known flaky test?

**Comment by wli3** [comment]
The assertion is failing on loc

**Comment by wli3** [comment]
It is a Spanish leg

Expected collection to be equal to {"\u001b[33mNo se pudo agregar "C:\Tools" a la variable de entorno PATH. Agregue este directorio a PATH para usar las herramientas instaladas con "dotnet tool install".\u001b[39m"}, but {"\u001b[33mFailed to add 'C:\Tools' to the PATH environment variable. Please add this directory to your PATH to use tools installed with 'dotnet tool install'.\u001b[39m"} differs at index 0.

**Comment by wli3** [comment]
This is so weird. They expect and actual are both in the same process. But get 2 different result

**Comment by wli3** [comment]
@dsplaisted you probably will also need to cherry pick all above changes

**Comment by wli3** [comment]
@sfoslund thanks for investigate into this!

**Comment by dsplaisted** [comment]
@wli3 cherry pick to which branch?

**Comment by wli3** [comment]
@dsplaisted for 2.1.5xx, you need a similar merge from internal branch and then update the branding

**Pull request merged**
