### PR TITLE
Msbuild 15.7.0-preview-000108

### PR DESCRIPTION
**Pull request by livarcocc**
Replaces https://github.com/dotnet/cli/pull/8855

@AndyGerlicher

### CODE REVIEW

**Comment by AndyGerlicher** [comment]
Looks like this is getting closer, thanks!. Also please move from 108 -> 120 :)

**Comment by rainersigwald** [comment]
I think this will be broken on update to 120 until https://github.com/Microsoft/msbuild/pull/3126, sorry :(

**Comment by rainersigwald** [comment]
(could do 108 as an intermediate if that's helpful)

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by rainersigwald** [comment]
@livarcocc can you update this to 122? It should be as easy as cherry-picking d87accad6

**Comment by rainersigwald** [comment]
The plot thickens: the node-reuse changes break this, as I suspected. But https://github.com/Microsoft/msbuild/pull/3052 also, independently, breaks it. I have NO IDEA HOW. That's why my attempts to build a simple escape hatch didn't work.

**Pull request closed without merging**
