### PR TITLE
Fixed a missing interpolation operator

### LINKED ISSUE #4939: Malformatted help output for `dotnet restore`
## Steps to reproduce
run `dotnet help`

## Expected  behavior
{LocalizableStrings... does not show up.

## Actual behavior
```
Usage: restore [arguments] [options] [[--] <arg>...]]

Arguments:
  [{LocalizableStrings.CmdArgument}]  Optional path to a project file or MSBuild arguments.

Options:
  -h|--help                       Show help information
  -s|--source <source>            Specifies a NuGet package source to use during the restore.
  --packages <packagesDirectory>  Directory to install packages in.
  --disable-parallel              Disables restoring multiple projects in parallel.
  --configfile <file>             The NuGet configuration file to use.
  --no-cache                      Do not cache packages and http requests.
  --ignore-failed-sources         Treat package source failures as warnings.
  --no-dependencies               Set this flag to ignore project to project references and only restore the root project
  -v|--verbosity                  Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]

Args:
  Any extra options that should be passed to MSBuild. See 'dotnet msbuild -h' for available options.
```

## Environment data
.NET Command Line Tools (1.0.0-preview5-004228)

Product Information:
 Version:            1.0.0-preview5-004228
 Commit SHA-1 hash:  1484b1b70b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /Users/piotrp/code/github/piotrpMSFT/cli/artifacts/osx.10.11-x64/stage2/sdk/1.0.0-preview5-004228

### PR DESCRIPTION
**Pull request by vsccarl**
Fixes #4939

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build
@dotnet-bot Test Ubuntu16.04 x64 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build
@dotnet-bot Test Ubuntu16.04 x64 Debug Build

**Comment by piotrpMSFT** [comment]
I'm merging this. It looks like CI did not send build success replies to GitHub @mmitche. All builds are green.

**Comment by piotrpMSFT** [comment]
Once approved by @mattGertz, of course :)

**Comment by mmitche** [comment]
@piotrpMSFT I see failures.  What failed to send?

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build
@dotnet-bot Test RHEL7.2 x64 Release Build

**Pull request merged**
