### PR TITLE
fix dotnet pack help

### PR DESCRIPTION
**Pull request by mairaw**
Related to https://github.com/dotnet/docs/issues/8860

### CODE REVIEW

**Comment by peterhuene** [comment]
@livarcocc would this meet 3.0 bar?

**Comment by livarcocc** [comment]
I doubt it. I would put in 3.1 for 16.4 though. @wli3 are the branches ready?

**Comment by peterhuene** [comment]
Ugh, I really wish you could preview target base changes before the PR is updated.  Let me rebase this quickly.

**Comment by peterhuene** [comment]
@mairaw I force updated your branch to rebase on 3.1 as that's what we'll target with this PR.

**Comment by mairaw** [comment]
Thanks @peterhuene!

**Comment by wli3** [comment]
@livarcocc I did make 3.1.1xx branch. I believe have set up everything. But I didn't get a chance to review with you today

**Pull request merged**
