### PR TITLE
Adding logging based on levels (Error only to Debug)

### PR DESCRIPTION
**Pull request by ahsonkhan**
Issue #13

### CODE REVIEW

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by krwq** [comment]
@anurse, @ahsonkhan  Is this PR still valid? Please close it or fix conflicts

**Comment by anurse** [comment]
Sounds like it's quite out of date now.

**Pull request closed without merging**
