### PR TITLE
Updating CoreFx, CoreSetup to rc3-24131-00, rc3-004363 respectively

### PR DESCRIPTION
**Pull request by eerhardt**

### CODE REVIEW

**Comment by eerhardt** [comment]
@joshfree @schellap - this should get CLI back up to 'latest' of everything.

**Comment by schellap** [comment]
Do you mean to say this includes the `__LINUX__` fox as well that went in this morning?

**Comment by eerhardt** [comment]
> Do you mean to say this includes the __LINUX__ fox as well that went in this morning?

This includes `rc3-004363` of core-setup, which has hash `ce6aaef52b8f1761625b74ffb0985c8abc817ae8`, which has commit https://github.com/dotnet/core-setup/commit/ce6aaef52b8f1761625b74ffb0985c8abc817ae8

**Comment by schellap** [comment]
@eerhardt thank you!

**Pull request merged**
