### PR TITLE
suppress adding project output to export when there is no output

### LINKED ISSUE #1093: Build fails for build time dependencies
Clone the aspnet/common repo and build `Microsoft.Extensions.Primitives`. 

That repo has a dependency on `Microsoft.Extensions.HashCodeCombiner.Sources` which is a build time dependency. `HashCodeCombiner` is also a sources packages so it shouldn't produce any binaries.

However, `build` expect a dll from it:

```
D:\aspnet\common\src\Microsoft.Extensions.Primitives>dotnet build
Compiling Microsoft.Extensions.Primitives for .NETFramework,Version=v4.5.1
C:\Users\victorhu\AppData\Local\Microsoft\dotnet\cli\bin\dotnet-compile-csc.exe "@D:\aspnet\common\src\Microsoft.Extensions.Primitives\obj\Debug\net451\dotnet-compile.rsp" returned Exit Code 1
D:\aspnet\common\src\Microsoft.Extensions.Primitives\error CS0006: Metadata file 'D:\aspnet\common\src\Microsoft.Extensions.HashCodeCombiner.Sources\bin\Debug\net451\Microsoft.Extensions.HashCodeCombi
ner.Sources.dll' could not be found
```

Side note, probably related:

If you run `dotnet pack` on a sources package you get the correct nupkg but if you run `dotnet build` you get binaries. In the case of source packages, there should be no binaries.

### PR DESCRIPTION
**Pull request by anurse**
fixes #1093

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
Looks good

**Comment by davidfowl** [comment]
Stuff broke

**Comment by anurse** [comment]
Looks like the test was assuming that an empty project would still produce a DLL. I think the right approach is to make the test project non-empty, so I added a simple source code file.

**Comment by anurse** [comment]
@dotnet-bot test Ubuntu Debug Build please

**Comment by anurse** [comment]
@dotnet-bot test Ubuntu Release Build please

**Comment by anurse** [comment]
@dotnet-bot test Ubuntu Debug Build please

**Comment by anurse** [comment]
@dotnet-bot test Ubuntu Release Build please

**Comment by robmen** [comment]
Maybe ask with, "pretty please", @anurse? :smile_cat:

**Comment by anurse** [comment]
@robmen sigh... yeah, it seems the Ubuntu agents are just in a weird state. @piotrpMSFT I'm pretty sure this is just the transient issue we're seeing with Ubuntu agents. Can we merge this? /cc @davidfowl @victorhurdugaci

**Comment by anurse** [comment]
@dotnet-bot test Ubuntu Release Build please

**Comment by anurse** [comment]
@dotnet-bot test Ubuntu Release Build please

**Comment by victorhurdugaci** [comment]
@dotnet-bot test Ubuntu Release Build please

**Comment by victorhurdugaci** [comment]
The failure seems to to a myget timeout

**Comment by anurse** [comment]
@dotnet-bot test Ubuntu Release Build please

**Pull request merged**
