### PR TITLE
Make portable PDB default again

### PR DESCRIPTION
**Pull request by jaredpar**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2356)

### CODE REVIEW

**Comment by jaredpar** [comment]
Do not merge this PR until we have sign off.  This change is being considered for RC2 but by no means approved.  This PR is being done to have everything ready to go if the decision is made to take this route.

**Comment by livarcocc** [comment]
We still need to update the runner to consume the new API from TestingAbstractions

**Comment by livarcocc** [comment]
@jaredpar Actually, never mind. I checked the code (that I wrote) and it will do the right thing already. I even tried it out and compiled something with full pdbs and it managed to load the tests in VS. We should be good.

:shipit:

**Comment by eerhardt** [comment]
@jaredpar - Should we take this for Preview2?  If not, let's close this PR.  If yes, can we add a test?

**Comment by MichaelSimons** [comment]
@jaredpar, @piotrpMSFT, @blackdwarf - what is the status of this?  Are we going to change the default or not?  If so what is the time frame?

**Comment by eerhardt** [comment]
Closing, as this appears to have zero traction.

**Pull request closed without merging**
