### PR TITLE
debian deb packages

### PR DESCRIPTION
**Pull request by brthor**
This is blocked on https://github.com/dotnet/core-setup/pull/227 going in
and will fail until then

@MichaelSimons @naamunds @eerhardt

### CODE REVIEW

**Comment by eerhardt** [comment]
Wow - is this seriously that easy?

**Comment by MichaelSimons** [comment]
>         public static BuildTargetResult CheckUbuntuDebianPackageBuildDependencies(BuildTargetContext c)

Can you explain why this is only done for Ubuntu 14.04 rather than all configurations we are building Debian packages for?

---
Refers to: build_projects/dotnet-cli-build/PrepareTargets.cs:349 in 97f2fa2. [](commit_id = 97f2fa22e762c405a9f6c7188acd1ff0914742ed, deletion_comment = False)

**Comment by naamunds** [comment]
Do we need to update scripts/docker/debian/Dockerfile to add liblldb like in https://github.com/dotnet/core-setup/pull/227?

**Comment by brthor** [comment]
> Do we need to update scripts/docker/debian/Dockerfile to add liblldb like in dotnet/core-setup#227?

Should be unnecessary but for consistency's sake yes.

**Comment by brthor** [comment]
> Can you explain why this is only done for Ubuntu 14.04 rather than all configurations we are building Debian packages for?

Ubuntu 14.04 is the only place where jenkins has docker AFAIK

**Comment by brthor** [comment]
test this please

**Comment by brthor** [comment]
test this please

**Comment by MichaelSimons** [comment]
@brthor, Any update on this?  What is the current plan?  Is CLI going to pickup the latest runtime?

**Comment by Daniel15** [comment]
For what it's worth, the Ubuntu 16.04 packages install fine for me on Debian "testing". It looks like `liblldb` is available in testing and experimental: https://packages.debian.org/stretch/liblldb-3.6

**Comment by brthor** [comment]
I don't know what the plan is to pick up the 1.1.0 runtime in the cli. @livarcocc will have more info

This change could either be ported over to the preview 2.1 branch or reworked for the new build system. But requires getting the 1.1.0 runtime. Closing for now.

**Pull request closed without merging**
