### PR TITLE
Update test templates to use the 15.7.0 test SDK

### PR DESCRIPTION
**Pull request by mlorbetske**
cc @mayankbansal018

### CODE REVIEW

**Comment by livarcocc** [comment]
@mlorbetske it can't find the template packages. Can you investigate?

**Comment by mlorbetske** [comment]
I've uploaded these to the MyGet feed, will kick off a new PR build after giving it a bit for propagation.

**Comment by mlorbetske** [comment]
@dotnet-bot test this please

**Comment by livarcocc** [comment]
Do we have a VSO bug for these? Did it get approved through escrow?

**Comment by mlorbetske** [comment]
@mayankbansal018 - can you answer the question from @livarcocc ?

**Comment by mayankbansal018** [comment]
@livarcocc when I created the pull request, we were in ask mode, so did not need the escrow mode approval, I can create a bug if need be.

**Comment by mayankbansal018** [comment]
@mlorbetske I'm assuming this PR is for inserting latest dotnet templates in VS, can you please create a bug in VSO, & get it approved

**Comment by mlorbetske** [comment]
@mayankbansal018 the templates in VS are delivered via the CLI, so yes, this would insert them into VS. Ensuring that the appropriate approvals are in place to have your content inserted has traditionally been a thing your team has owned and would be better suited to explain the value in as part of the ask mode template.

**Comment by livarcocc** [comment]
We need a bug and approval to merge this.

**Comment by cltshivash** [comment]
@livarcocc We will not take this for escrow as there's no blocking issue or big value add. 
@mlorbetske @mayankbansal018 had completed the PR in ask mode in this repo but the insertion to VS didn't happen. We will explicitly call it out the next time (for the followup VS insertion which is handled by today by the dotnet core team)

**Comment by livarcocc** [comment]
I have filled https://devdiv.visualstudio.com/DevDiv/_workitems/edit/602822 for this and will take it to shiproom.

**Pull request merged**
