### PR TITLE
Fixes issue #1415

### PR DESCRIPTION
**Pull request by piotrpMSFT**

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
Fixes #1415

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT Release Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT Debug Build please.

**Comment by davidfowl** [comment]
I'm seeing nuget badness on my machine as well.

**Comment by piotrpMSFT** [comment]
@davidfowl accessing the Web portal is also not working.

**Comment by davidfowl** [comment]
http://status.myget.org/ US West down

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT Debug Build please.

**Comment by piotrpMSFT** [comment]
Portal seems to have come back up. Going to try again.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test this please.

**Pull request merged**
