### PR TITLE
Enable HighEntropyVA in our builds by default.

### PR DESCRIPTION
**Pull request by livarcocc**
@dotnet/dotnet-cli @morganbr

### CODE REVIEW

**Comment by krwq** [comment]
LGTM For sanity please verify HighEntropyVA is being passed to the compiler

**Comment by livarcocc** [comment]
I ran biskim again and didn't get the error.

**Comment by livarcocc** [comment]
@dotnet-bot Test this please.

**Comment by livarcocc** [comment]
@dotnet-bot Test OSX10.12 x64 Release Build

**Pull request merged**
