### PR TITLE
Updating SDk to 20170414

### PR DESCRIPTION
**Pull request by ramarag**
this is a followup of https://github.com/dotnet/sdk/pull/1119

@livarcocc @eerhardt PTAL

### CODE REVIEW

**Comment by eerhardt** [comment]
Can we also fix https://github.com/dotnet/cli/pull/6300#discussion_r111017441 now as well?

**Comment by ramarag** [comment]
I think we should keep a distinction between packages used to build the product including what is used to bootstrap it and what goes into the product itself. I would decouple the fix

**Comment by eerhardt** [comment]
I'll let @livarcocc make the final call, since he owns this code.  But in general, we shouldn't have multiple versions duplicated in various projects.  They should all be consolidated into DependencyVersions.props.

**Comment by livarcocc** [comment]
I agree with @eerhardt. I don't see what is the reason to not update the build now that we have fixed the issue that was blocking it.

**Comment by ramarag** [comment]
@eerhardt @livarcocc fixed https://github.com/dotnet/cli/pull/6300#discussion_r111017441

**Pull request merged**
