### PR TITLE
Made dotnet new templates generate portable pdbs

### PR DESCRIPTION
**Pull request by ajaybhargavb**
#3421 

@eerhardt

### CODE REVIEW

**Comment by eerhardt** [comment]
Does F# want this as well?

@enricosada

**Comment by eerhardt** [comment]
:shipit: pending ask mode approval and the answer to the F# question.

**Comment by piotrpMSFT** [comment]
I don't see approval mail on this one. Was it sent?

**Comment by ajaybhargavb** [comment]
Just sent one

**Comment by joshfree** [comment]
Approved; merging

**Comment by eerhardt** [comment]
F# can fend for themselves.  If they want it turned on, they can do it.

**Comment by shanselman** [comment]
Someone should mention this to F# folks. @enricosada @piotrpMSFT

**Comment by enricosada** [comment]
thx @shanselman , that was already in `F# for preview2 list1 #3631 
But really thx for ping. it's easy to miss notification, lots of activity in this repo

**Pull request merged**
