### PR TITLE
Including unresolved library in LibraryExporter.GetAllExports result

### PR DESCRIPTION
**Pull request by troydai**
/cc @davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
Don't filter on unresolved, just return an unresolved library export with no assemblies

**Comment by Sridhar-MS** [comment]
OSX builds are failing due to a dead hard drive on one of the mac machines. It has been taken offline now.

**Comment by Sridhar-MS** [comment]
@dotnet-bot test OSX Debug Build please.

**Comment by Sridhar-MS** [comment]
@dotnet-bot test OSX Release Build please.

**Comment by troydai** [comment]
@Sridhar-MS do you know the reason of failure on Ubuntu build? Those builds failed immediately after started for file operation exception.

**Comment by Sridhar-MS** [comment]
@troydai The failure is due to low disk space on the Ubuntu machine. @mmitche is taking a look.

**Comment by davidfowl** [comment]
:shipit:

**Comment by troydai** [comment]
Thanks @Sridhar-MS .

I'll therefore ignore the failure on the Ubuntu Release Build and merge the change once other builds pass.

**Pull request merged**
