### PR TITLE
MSBuild 15.3.406

### PR DESCRIPTION
**Pull request by rainersigwald**
Internal VS PR (shiproom approved but not yet merged): https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/76591

### CODE REVIEW

**Comment by nguerrera** [comment]
@MattGertz @srivatsn FYI, flow of shiproom-approved dependencies in to 1.1. CLI.

**Comment by nguerrera** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

Appears to be network flakiness

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build
@dotnet-bot Test Debian8.2 x64 Debug Build
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by nguerrera** [comment]
@dotnet-bot Test Fedora24 x64 Release Build

More network flakiness :(

**Comment by nguerrera** [comment]
@dotnet-bot Test Fedora24 x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build

**Pull request merged**
