### PR TITLE
Insert localize testplatform 

### PR DESCRIPTION
**Pull request by Faizan2304**
Inserting localized nugget packages of testplatform.

Testing: Did bug bash in windows, Linux, Japanese windows machine

### CODE REVIEW

**Comment by Faizan2304** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by Faizan2304** [comment]
@dotnet-bot test Windows_NT x64 Release Build please
@dotnet-bot test Ubuntu16.04 x64 Debug Build please

**Comment by livarcocc** [comment]
@Faizan2304 Why do we have all these commits in this PR?

**Comment by piotrpMSFT** [comment]
This seems to be merging `master` into `rel/1.0.0`. Closing so we don't accidentally merge. Please cherrypick the changes onto `rel/1.0.0` then re-open the PR.

**Pull request closed without merging**
