### PR TITLE
Updated ASP.NET 5 to ASP.NET Core in readme

### PR DESCRIPTION
**Pull request by revlucio**

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@blackdwarf @davidfowl @DamianEdwards can one of you please validate this?

**Comment by blackdwarf** [comment]
I think it needs to be ASP.NET Core 1. Otherwise, looks good.

**Comment by piotrpMSFT** [comment]
@blackdwarf is that confirmed?

**Comment by blackdwarf** [comment]
I'm pretty sure that's the new name. Actually, it's ASP.NET Core 1.0 (http://www.hanselman.com/blog/ASPNET5IsDeadIntroducingASPNETCore10AndNETCore10.aspx).

**Comment by blackdwarf** [comment]
Yup, this needs to be ASP.NET Core 1.0. The latest commit looks right.

**Comment by blackdwarf** [comment]
@dotnet-bot test CentOS7.1 Debug Build please

**Comment by blackdwarf** [comment]
@dotnet-bot test Ubuntu Debug Build please

**Comment by blackdwarf** [comment]
@dotnet-bot test Ubuntu Release Build please

**Comment by blackdwarf** [comment]
@dotnet-bot test CentOS7.1 Release Build please

**Comment by revlucio** [comment]
@dotnet-bot test CentOS7.1 Debug Build please

**Comment by piotrpMSFT** [comment]
@dotnet-bot test this please

**Comment by revlucio** [comment]
The change seems to have been made anyway

**Pull request closed without merging**
