### PR TITLE
preview3 updates for new build definitions

### PR DESCRIPTION
**Pull request by naamunds**
These changes are required for building in the new VSTS pool.

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test this please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test this please.

**Comment by ravimeda** [comment]
This PR is blocked due to the failing tests, which have been in the same state for past couple days ([dashboard](https://ci.dot.net/job/dotnet_cli/job/rel_1.0.0-preview3/)). 
@piotrpMSFT @livarcocc  please could you clarify if this (failing tests) issue is being worked on.

**Comment by ravimeda** [comment]
@dotnet-bot test this please.

**Comment by ravimeda** [comment]
@livarcocc @piotrpMSFT any update on the test failure fix up, please?

**Comment by livarcocc** [comment]
Do we really need this for rel/1.0.0-preview3? I believe these changes already went in for master, rel/1.0.0 and rel/1.0.1.

We have no plans to service 1.0.0-preview3 at this point.

Do you have a reason to take this in preview3?

**Comment by ravimeda** [comment]
Yes, these changes are in master, rel/1.0.0 and rel/1.0.1. Let's close the PR.
Cc @naamunds

**Pull request closed without merging**
