### PR TITLE
preview4 updates for new build definitions

### PR DESCRIPTION
**Pull request by naamunds**
These changes are required for building in the new VSTS pool.

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test this please.

**Comment by naamunds** [comment]
@dotnet-bot test OSX please

**Comment by naamunds** [comment]
@dotnet-bot Test OSX x64 Release Build please

**Comment by naamunds** [comment]
@dotnet-bot Test OSX x64 Release Build please

**Pull request merged**
