### PR TITLE
Insert NuGet Build 4.7.0-preview3.5038 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.7.0-preview3.5038 into cli master branch

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test this please

**Comment by rohit21agrawal** [comment]
for 15.7, should we target release/2.1.2xx or master?

**Comment by livarcocc** [comment]
15.7 goes into release/2.1.2xx. We need to retarget this PR.

**Comment by rohit21agrawal** [comment]
@zhili1208 please retarget the PR to release/2.1.2xx

**Pull request closed without merging**
