### PR TITLE
Adds Microsoft.Docker.Sdk to CLI

### PR DESCRIPTION
**Pull request by yanchenw**
This change is to add Sdk.props and Sdk.targets of Microsoft.Docker.Sdk
into CLI. This unblocks the scenario where a VS solution contains a few
.NET Core projects as well as a docker-compose.dcproj project and people
want to build the solution from command line with .NET Core CLI. With
the Sdk.props and Sdk.targets being present in CLI, building
docker-compose.dcproj becomes no-op so it won't block building the other
.NET Core projects.

The SDK files are open-sourced under MIT license here:
https://github.com/Microsoft/DockerTools

#6178

### CODE REVIEW

**Comment by yanchenw** [comment]
#6178

**Comment by philcontrolf1** [comment]
@livarcocc / @MattGertz / anyone else: is there anything blocking this one being merged? Getting #6178 fixed would be wonderful.

**Comment by dasMulli** [comment]
Btw since VS 15.6 is going to introduce SDKs as NuGet packages, would it be possible to upload the sdk package to NuGet?
That way the projects could be changed to `Sdk=".../1.0.0"` or a global.json with the msbuild-sdks version can be added to make this work. this may need a migration on the VS side but would never need any update to the CLI distribution regardless of what license is used or what changes may be necessary (since it can be done out-of-band as a new nuget package + project migration)

**Comment by MattGertz** [comment]
@livarcocc You & I haven't discussed this one.  This change seems rational to me, can you let me know your thoughts here?

**Comment by livarcocc** [comment]
@MattGertz this will enable folks to build solutions that contain dcproj files in them. It is something people have been asking for for a while. This change currently targets .NET Core 2.1 Preview2. I will merge if you are ok with it.

**Comment by MattGertz** [comment]
So mote it be.

**Comment by Pzixel** [comment]
Does it works with custom projects? I have custom project in `$(CustomProjectExtensionsPath)`, is dontent CLI aware of it?

**Pull request merged**
