### PR TITLE
Remove NuGet.config from the default dotnet new drop.

### LINKED ISSUE #656: Remove Nuget.Config from `dotnet new` drop for release
The nuget.config drop was added as a temporary step until the StdLib is available on nuget.org.

When this is true, we should remove the nuget.config drop.

### PR DESCRIPTION
**Pull request by brthor**
Fixes #656 

@weshaggard @Petermarcu @piotrpMSFT @Sridhar-MS

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2319)

### CODE REVIEW

**Comment by Sridhar-MS** [comment]
LGTM

**Comment by weshaggard** [comment]
LGTM

**Comment by brthor** [comment]
@dotnet-bot test OSX x64 Release Build

**Comment by brthor** [comment]
@dotnet-bot test OSX x64 Release Build please

**Pull request merged**
