### PR TITLE
Add netcoreapp as default tfm to run

### PR DESCRIPTION
**Pull request by pakrym**
Fixes: https://github.com/dotnet/cli/issues/2218
@anurse @davidfowl

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2342)

### CODE REVIEW

**Comment by anurse** [comment]
:shipit:

**Comment by pakrym** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build  please

**Comment by pakrym** [comment]
@dotnet-bot test Windows_NT x64 Release Build please
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by pakrym** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by pakrym** [comment]
@dotnet-bot tests CentOS7.1 x64 Debug Build please
@dotnet-bot tests OSX x64 Release Build please

**Comment by pakrym** [comment]
@dotnet-bot tests CentOS7.1 x64 Debug Build please
@dotnet-bot tests OSX x64 Release Build please

**Comment by pakrym** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please
@dotnet-bot test OSX x64 Release Build please

**Pull request merged**
