### PR TITLE
Adding openSUSE 13.2, Fedora 23 and Ubuntu 16.04 links to the README page

### PR DESCRIPTION
**Pull request by livarcocc**
cc @joshfree @eerhardt @brthor

### CODE REVIEW

**Comment by mellinoe** [comment]
Should the Ubuntu 16.04 links be next to the Ubuntu 14.04 (in the downloads section)?

**Comment by brthor** [comment]
agree with @mellinoe to group the ubuntu sections.

**Comment by livarcocc** [comment]
Sure.

**Comment by mellinoe** [comment]
LGTM

**Comment by piotrpMSFT** [comment]
@dotnet-bot test  OSX x64 Release Build please.

**Comment by eerhardt** [comment]
LGTM

**Comment by brthor** [comment]
test this please

**Comment by livarcocc** [comment]
@dotnet-bot Test Debian8.2 x64 Debug Build
@dotnet-bot Test RHEL7.2 x64 Release Build

**Comment by mellinoe** [comment]
Is this ready to go in? I was going to make a dummy change to kick off a build to consume core-setup changes, but this one looks good to go. The official core-setup build will be done in the next 30-40 mins.

**Comment by joshfree** [comment]
nit: "CentOS 7.1 / Oracle Linux 7" should be "CentOS 7.1 / Oracle Linux 7.1".  otherwise LGTM.  Thanks for making this update

**Pull request merged**
