### PR TITLE
Bumping the SDK version to 1.0.0-alpha-20170123-1.

### PR DESCRIPTION
**Pull request by livarcocc**
@piotroko @piotrpMSFT @jonsequitur @krwq @jgoshi

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build
@dotnet-bot Test RHEL7.2 x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@MattGertz for approval.

**Comment by livarcocc** [comment]
This is just bringing the SDK version in RC3 to rel/1.0.0.

**Comment by livarcocc** [comment]
@piotrpMSFT this one next.

**Pull request merged**
