### PR TITLE
Updating the CLI branding to 2.1.3 and ingesting the 2.0.4 runtime.

### PR DESCRIPTION
**Pull request by livarcocc**

### CODE REVIEW

**Comment by livarcocc** [comment]
@mmitche these are not getting kicked off. Is that because we just merged the dotnet-ci change?

**Comment by mmitche** [comment]
Appears  to be because release/2.1 isn't tracked, just dev/release/2.1

https://github.com/dotnet/dotnet-ci/blob/master/data/repolist.txt#L27

**Comment by livarcocc** [comment]
My bad. I put the wrong branch in it.

@dotnet-bot Test this please

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Pull request merged**
