### PR TITLE
Putting back the valuable one-line installation script examples.

### PR DESCRIPTION
**Pull request by ghost**
Putting back the valuable one-line installation script examples.

@dotnet/dotnet-cli

### CODE REVIEW

**Comment by johnbeisner** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by johnbeisner** [comment]
@dotnet-bot test CROSS Check

**Comment by johnbeisner** [comment]
@dotnet-bot test OSX10.12 x64 Release Build

**Comment by johnbeisner** [comment]
@dotnet-bot test Windows_NT_ES x64 Debug Build

**Comment by johnbeisner** [comment]
@dotnet-bot test Windows_NT x86 Debug Build

**Comment by johnbeisner** [comment]
@dotnet-bot test Windows_NT x64 Release Build

**Comment by johnbeisner** [comment]
@dotnet-bot test CROSS Check

**Comment by johnbeisner** [comment]
@piotrpMSFT 
Can you bless this please...

**Review by TheRealPiotrP — APPROVED** [review]
Glad to have these back!

**Pull request merged**
