### PR TITLE
Update Roslyn to 1.3.0-beta1-20160429-01

### PR DESCRIPTION
**Pull request by eerhardt**
@agocke @piotrpMSFT

### CODE REVIEW

**Comment by agocke** [comment]
What's up with Jenkins?

Assuming tests pass, LGTM.

**Comment by eerhardt** [comment]
Not sure - looking now.  I may have missed a test referencing Roslyn.

**Comment by eerhardt** [comment]
Yup that was the problem, there was a new TestAsset that is referencing roslyn.  I fixed it.  We should be good now.

**Comment by eerhardt** [comment]
test Windows_NT x86 Debug Build

**Pull request merged**
