### PR TITLE
Just moved the file check to after we have created the item.

### PR DESCRIPTION
**Pull request by livarcocc**
Fixes https://github.com/dotnet/cli/issues/4712

@piotrpMSFT @krwq @jgoshi

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build

**Comment by rs38** [comment]
thanks for fixing my bug 👍

**Comment by piotrpMSFT** [comment]
Now to add some tests... :)

**Comment by rs38** [comment]
I will, but need some time as I need still to learn Pester and not to break sth. again.

**Comment by piotrpMSFT** [comment]
Wow, I haven't seen Pester yet. Looks interesting.

I've also spent some time posting [MockService](https://github.com/piotrpMSFT/Microsoft.Owin.MockService) to ASP.NET Core 1.1. This is a nice little tool that lets us simulate web services in the context of unit tests so we can do full validation of how the scripts interact with Azure!

**Pull request merged**
