### PR TITLE
Rename test templates for casing consistency

### PR DESCRIPTION
**Pull request by jgoshi**
@piotrpMSFT @livarcocc @krwq

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build please

**Comment by jgoshi** [comment]
test Windows_NT x64 Release Build
Windows_NT x86 Debug Build

**Comment by jgoshi** [comment]
test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build please

**Comment by jgoshi** [comment]
test CentOS7.1 x64 Debug Build

**Pull request merged**
