### PR TITLE
Update NET.Sdk to 1.1.0-alpha-20170217-4

### PR DESCRIPTION
**Pull request by eerhardt**
@ericstj @livarcocc @piotrPMSFT

### CODE REVIEW

**Comment by eerhardt** [comment]
test Ubuntu x64 Release Build
test Windows_NT x64 Release Build
test Windows_NT x86 Debug Build

**Comment by eerhardt** [comment]
@piotrpMSFT @livarcocc - can someone take a look at these windows test failures?

**Comment by piotrpMSFT** [comment]
I just confirmed that this is [at least in part] the same root cause as https://github.com/dotnet/cli/pull/5813. Once that turns green, we'll want to merge rel/1.0.0 into master before we can merge this new SDK.

**Comment by eerhardt** [comment]
@piotrpMSFT - that wasn't enough to fix the problem.  There are still test failures in Windows.

**Comment by eerhardt** [comment]
Test Windows_NT x64 Release Build
Test Windows_NT x86 Debug Build

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x64 Release Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x64 Release Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x64 Release Build please.

**Comment by eerhardt** [comment]
I think we might need a new MSBuild version. But we are currently blocked on taking a new one waiting for https://github.com/Microsoft/msbuild/pull/1762#issuecomment-282906268

**Comment by eerhardt** [comment]
Oh, we are using Stage0 to build the tests. This isn't going to get fixed unless we turn parallel build off first. Merge the new SDK.  Then turn parallel build back on.

**Comment by piotrpMSFT** [comment]
why is it passing except windows?

**Comment by piotrpMSFT** [comment]
This next issue looks like a bug in the actual SDK. I won't know more until in the office tomorrow, but  here are some details that may help @nguerrera or @dsplaisted tell us what's going on:

The test is performing a migration of a project.json

The resultant csproj includes this propertygroup:

```
  <PropertyGroup>
    <TargetFrameworks>net20;net35;net40;net461</TargetFrameworks>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
    <AssemblyName>TestAppWithMultipleFullFrameworksOnly</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>TestAppWithMultipleFullFrameworksOnly</PackageId>
  </PropertyGroup>
```

The error message from CI passes through the following from our Build target:
```
error MSB3030: Could not copy the file "obj\Debug\net461\win7-x86\TestAppWithMultipleFullFrameworksOnly.exe" because it was not found. [D:\j\workspace\debug_windows---8a02d2bd\test\dotnet-migrate.Tests\bin\Debug\netcoreapp2.0\ItMigratesAppsWithFullFrameworkTestAppWithMultipleFullFrameworksOnly\TestAppWithMultipleFullFrameworksOnly\TestAppWithMultipleFullFrameworksOnly.csproj] 
```

If I'm reading this right, the SDK expected to find the project's output in a RID-specific directory. This makes since, since a RuntimeIdentifier is defined in the PropertyGroup. However, I suspect that a path calculation is occurring based on inferred RID rules and outputing the project to a RID-less sub-directory. I won't know more until I can do a full local build tomorrow.

I recall @livarcocc doing some work in migration to help with a related scenario. Adding him, as there may be a bad merge somewhere.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please.

**Comment by nguerrera** [comment]
Where is the full project and what commands is the test executing. Is it possible to isolate a repro?

**Comment by eerhardt** [comment]
I'm building locally now, and will have more info in 30-40 minutes.

My guess is that we are missing bugs that were fixed in MSBuild, but we are blocked getting a new one by https://github.com/Microsoft/msbuild/pull/1762.

@nguerrera - did you have to make any changes to MSBuild when you did any of the RID work at the end of VS 2017?

**Comment by nguerrera** [comment]
@eerhardt No, but the version in rel/1.0.0 has all of my changes so I don't understand why tests would fail only in master.

**Comment by nguerrera** [comment]
There were msbuild changes in support of Peter's change though.

**Comment by eerhardt** [comment]
hmm, those 2 tests passed locally.  👎

**Comment by nguerrera** [comment]
@eerhardt On Windows, synced exactly to this PR?

**Comment by nguerrera** [comment]
Is the build in question a parallel sln build by chance? That might need msbuild changes to fix a race issue.

**Comment by eerhardt** [comment]
Oh, are we missing [@livarcocc's rel/1.0.0 change](https://github.com/dotnet/cli/pull/5758)?  This project.json doesn't have a RID defined, but then the migrated project DOES have a RID defined.

**Comment by nguerrera** [comment]
But the project should build with or without that change. And I assume tests were passing in 1.0.0 before and after the change, right?

**Comment by eerhardt** [comment]
I just rebuilt on this exact branch, and the tests passed locally for me:

```
Passed   Microsoft.DotNet.Migration.Tests.GivenThatIWantToMigrateTestApps.ItMigratesAppsWithFullFramework(projectName: "TestAppMultipleFrameworksNoRuntimes", framework: null)
Passed   Microsoft.DotNet.Migration.Tests.GivenThatIWantToMigrateTestApps.ItMigratesAppsWithFullFramework(projectName: "TestAppWithMultipleFullFrameworksOnly", framework: "net461")
```

**Comment by eerhardt** [comment]
test Windows_NT x64 Release Build
test Windows_NT x86 Debug Build

**Comment by nguerrera** [comment]
Is there anything in master that's not in e685a808a19c12b69af3012321718686afec0a4a? CI builds the merge result, right?

**Comment by nguerrera** [comment]
Answering my own question: looks like this is rebased over top of master, so that's not it.

**Comment by piotrpMSFT** [comment]
I regretted that rebase as soon as I finished it :(

**Comment by nguerrera** [comment]
New theory from @jgoshi via @eerhardt : long path issue with RID now in path for this project. Explains local passes and CI (longer root path) failure. Discussing offline on how to confirm and fix.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please.

**Comment by eerhardt** [comment]
test Windows_NT x64 Release Build

**Pull request merged**
