### PR TITLE
Don't require all dotnet tools to be on the path

### PR DESCRIPTION
**Pull request by davidfowl**
- Try resolving full path to executable in the local directory first.

#186

### CODE REVIEW

**Comment by jaredpar** [comment]
:+1: 

Wanted this exact behavior today when working in the repo.

**Comment by anurse** [comment]
:shipit:

**Comment by livarcocc** [comment]
LGTM. I think this will also help me use the custom csc compiler for UTF8 strings.

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by krwq** [comment]
LGTM :+1:  please resolve merge conflict, make sure it passes CI and good to go

**Comment by davidfowl** [comment]
This was merged a while ago

**Pull request closed without merging**
