### PR TITLE
Removed link to preview4 page

### PR DESCRIPTION
**Pull request by jchannon**
This removes a link to a preview4 download page. This is confusing as it clicking the link appears to point to an older version of preview4 than what is actually shown further down in the README under ` Installers and Binaries`

skipci

### CODE REVIEW

**Comment by eerhardt** [comment]
@blackdwarf @livarcocc please take a look

**Comment by livarcocc** [comment]
@blackdwarf Since he initially added the version there. I think the intention was to have a link to the latest officially released version of the CLI. If that's the case, I would argue that we should clarify that and updated it.

**Comment by blackdwarf** [comment]
Thanks @livarcocc. This was added intentionally. It should be updated to point to RC3 release notes that are on https://github.com/dotnet/core/blob/master/release-notes/rc3-download.md. 

@jchannon can you modify the PR to leave the paragraph in and change the title and the link?

**Comment by jchannon** [comment]
@blackdwarf done!

**Comment by blackdwarf** [comment]
Thanks @jchannon !

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build
@dotnet-bot Test CentOS7.1 x64 Debug Build

**Comment by blackdwarf** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build

**Comment by piotrpMSFT** [comment]
@MattGertz approving this doc-only Readme.md change

**Comment by MattGertz** [comment]
@piotrpMSFT I recall JoC telling you yesterday at Shiproom that doc fixes no longer met the bar for a build... ;-)

**Comment by piotrpMSFT** [comment]
@MattGertz per earlier conversation, this is a non-product doc change so we'll merge once it's green.

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build

**Pull request merged**
