### PR TITLE
port @ellismg's dockerfile cleanup

### PR DESCRIPTION
**Pull request by brthor**
cc @livarcocc @eerhardt @ellismg 

this is a straight copy of https://github.com/dotnet/core-setup/pull/58

The Ubuntu errors are driving me nuts here

### CODE REVIEW

**Comment by brthor** [comment]
https://github.com/dotnet/cli/pull/3332 this has to go in first here.

**Comment by brthor** [comment]
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by livarcocc** [comment]
:shipit:

**Comment by brthor** [comment]
@troydai Any idea why these tests are timing out on OpenSUSE?

**Comment by brthor** [comment]
@dotnet-bot test OpenSUSE13.2 x64 Debug Build please

**Comment by brthor** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by brthor** [comment]
This PR is showing some issues, but ubuntu is passing, to get ubuntu unblocked I am going to reduce the scope here only to include ubuntu dockerfiles.

**Comment by brthor** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please
@dotnet-bot test CentOS7.1 x64 Debug Build please
@dotnet-bot test CentOS7.1 x64 Debug Build please
@dotnet-bot test CentOS7.1 x64 Debug Build please

**Comment by brthor** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build please

**Comment by brthor** [comment]
@dotnet-bot test Fedora23 x64 Debug Build please

**Comment by brthor** [comment]
@dotnet-bot test OpenSUSE13.2 x64 Debug Build please

**Comment by brthor** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please

**Comment by brthor** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please

**Comment by brthor** [comment]
Merging this to unblock ubuntu builds, which are the only builds this change affects.

We'll deal with the timeout issues separately.

**Pull request merged**
