### PR TITLE
Removing the nuspec schema change used for adding the serviceable tag.

### PR DESCRIPTION
**Pull request by toddm**
Removing the schema change made with the addition of the serviceable pack option.
Fixes https://github.com/NuGet/Home/issues/2938

@rohit21agrawal @eerhardt @rrelyea

### CODE REVIEW

**Comment by toddm** [comment]
test Windows_NT x64 Release Build

**Comment by eerhardt** [comment]
The error I see is:

```
File "System.Linq.dll" should not be found in directory "/opt/code/test/dotnet-publish.Tests/bin/Release/netcoreapp1.0/PortableAppWithRuntimeTargetsIsPublishedCorrectly/PortableTests/PortableAppWithNative/bin/Debug/netcoreapp1.0/publish".
```

That test ensures when a project is referencing System.Linq that is not in the Shared Framework, it doesn't get published

```C#
            // Prior to `type:platform` trimming, this would have been published.
            publishDir.Should().NotHaveFile("System.Linq.dll");
```

I'm not sure what caused this, it doesn't look like your change.  The new NuGet version could have...  It needs more investigation.

**Comment by rohit21agrawal** [comment]
LGTM
:shipit:

**Comment by eerhardt** [comment]
@toddm - I am seeing passing tests on other PRs.  Let's try this again now that myget appears to be back.

@dotnet-bot test this please

**Comment by toddm** [comment]
@dotnet-bot test this please

**Comment by toddm** [comment]
@dotnet-bot test this please

**Comment by eerhardt** [comment]
Can you try rebasing on the latest code?

**Comment by toddm** [comment]
It's already based on the latest.  I don't see any commits not included in my branch.

**Comment by toddm** [comment]
@dotnet-bot test this please

**Comment by eerhardt** [comment]
This change is in rel/1.0.0-preview2.  This PR is for rel/1.0.0.  All of rel/1.0.0-preview2 will RI into rel/1.0.0 when preview2 ships, so this PR is no longer needed closing.

Also - it appears that rel/1.0.0 is broken right now with that failing test, which is why rel/1.0.0 PRs are failing.  That should be fixed with the RI as well.

**Pull request closed without merging**
