### PR TITLE
Adding support for fedora27,opensuse42.3 and ubuntu18.04 in dotnet-install

### PR DESCRIPTION
**Pull request by rakeshsinghranchi**
core-setup build process download cli using this file.

### CODE REVIEW

**Comment by rakeshsinghranchi** [comment]
cc @janvorli

**Comment by wtgodbe** [comment]
I'm not familiar with the cli repo, but from what I can tell it looks good.

**Comment by rakeshsinghranchi** [comment]
@wli3  can you please look at PR failures. Seems unrelated to my changes.

**Comment by wli3** [comment]
@mmitche Looks like something with Jenkins  java.net.MalformedURLException: no protocol: helix-int-notification-url

**Comment by livarcocc** [comment]
rel/1.0.0 is not an active branch anymore. If you want to target 1.0, you need to target rel/1.0.1. Though while this will unblock builds on this branch, we ship this script currently out of release/2.1.3xx. I also think we should update the title of this PR. It is not really adding these distros to the CLI, but enabling them in the install script.

**Comment by rakeshsinghranchi** [comment]
@livarcocc , I will create a separate PR for release/2.1.3xx branch. Closing this now.

**Pull request closed without merging**
