### PR TITLE
Insert NuGet Build 4.4.0-preview1-4365 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.4.0-preview1-4365 into cli release/2.0.0 branch

### CODE REVIEW

**Comment by nkolev92** [comment]
//cc
@nguerrera @livarcocc

**Comment by dsplaisted** [comment]
@dotnet-bot test OpenSUSE42.1 x64 Debug Build
test Ubuntu16.04 x64 Debug Build

**Comment by dsplaisted** [comment]
@dotnet-bot test OpenSUSE42.1 x64 Debug Build

**Comment by nguerrera** [comment]
Replaced by #7459

**Pull request closed without merging**
