### PR TITLE
Update the installation scripts in release/2.0.0 branch.

### PR DESCRIPTION
**Pull request by ghost**
dotnet/cli - master has the most current scripts - updating release/2.0.0 branch.

### CODE REVIEW

**Review by wli3 — APPROVED** [review]

**Comment by livarcocc** [comment]
I think what you should do here, instead of copying the code changes, just cherry-picking the commits over from the master branch into the release/2.0.0 branch. If that's what you did already, perfect, otherwise, I think that's what we should do.

**Review by livarcocc — CHANGES_REQUESTED** [review]
Se my other comment.

**Review by livarcocc — APPROVED** [review]

**Comment by johnbeisner** [comment]
Addressing: https://github.com/dotnet/cli/issues/7392

**Comment by johnbeisner** [comment]
https://github.com/dotnet/cli/issues/6747

**Pull request merged**
