### PR TITLE
updating to coherence 26452 & templating build 300

### PR DESCRIPTION
**Pull request by seancpeters**

### CODE REVIEW

**Comment by seancpeters** [comment]
Sorry, this is merging to master, need to merge against release/2.0.0 - closing.

**Comment by seancpeters** [comment]
Changed the base branch, re-opening this one, instead of creating a new PR.

**Comment by nguerrera** [comment]
@MattGertz FYI. ASP.NET code flow to CLI 2.0

**Comment by livarcocc** [comment]
@dotnet-bot Test Debian8.2 x64 Debug Build

**Pull request merged**
