### PR TITLE
Fix version displayed after install, provide information on more installed packeges

### LINKED ISSUE #8042: .NET Core SDK 2.0.3 has hard-coded version string in bundle UI
@barnson commented on [Thu Nov 16 2017](https://github.com/dotnet/core-setup/issues/3427)

## Steps to reproduce

* Install dotnet-sdk-2.0.3-win-x64.exe, downloaded from https://www.microsoft.com/net/download/windows.

## Expected  behavior

The `Success` page tells me I installed version 2.0.3.

## Actual behavior

image

The loc string `FirstTimeWelcomeMessage` used on the `Success` page in the bundle has hard-coded `2.0.0` strings.

## Environment data

n/a

### PR DESCRIPTION
**Pull request by 4creators**
Partially fixes #8042 

PR adds information about versions of runtime, packages and tools installed with bundle installer
displaying them at the last successful install view. Version data are read from src/DependencyVersions.deps
file what allows for automatic updates to installer UI keeping it in sync with changing source.

### CODE REVIEW

**Comment by 4creators** [comment]
PTAL
@livarcocc @wli3

**Comment by 4creators** [comment]
Pls find below current screenshots of installer - obviously final design decisions are in hands of mainatiners 😃  

dotnetsdk-installer-03-01


dotnetsdk-installer-03-02


dotnetsdk-installer-03-03

**Comment by 4creators** [comment]
@livarcocc 
I have not received any feedback after more than 8 weeks. Should I close this PR or wait for a review. There was a discussion about the issue in #8042 without any final conclusions and some fun from the Slack thread about dotnet versioning

**Comment by livarcocc** [comment]
@KathleenDollard we need to have a discussion on whether we will want to display all the components of the CLI in the summary of the installer or if we want this to appear as part of `--info` or `dotnet version`.

@4creators unfortunately, we need to reach a conclusion on the experience here before we can go ahead and take the PR. Are you ok if we keep it open for a little bit longer?

**Comment by 4creators** [comment]
@livarcocc Yes, it is fine with me

**Comment by livarcocc** [comment]
Closing this one in favor of https://github.com/dotnet/cli/pull/9001.

**Pull request closed without merging**
