### PR TITLE
update NuGet in CLI to 4.0.0.2048

### PR DESCRIPTION
**Pull request by rrelyea**
Inserting NuGet 4.0.0.2048 into CLI  (was originally 2047)

Tests will fail initially, our packages will be ready around 8pm, at that point, tests can be rerun and the PR merged.

Tracked by issue: http://github.com/nuget/home/issues/3869

### CODE REVIEW

**Comment by rrelyea** [comment]
@joelverhagen @emgarten @livarcocc @piotrpMSFT

**Comment by livarcocc** [comment]
It seems this build hasn't propagated to myget yet. The latest one I see in myget is 4.0.0-rc-2046.

**Comment by joelverhagen** [comment]
Latest version number should be `4.0.0-rc-2048`. @livarcocc, right, the build is still running. Expect to see the packages on MyGet in about 1 hour and 10 minutes.

**Comment by livarcocc** [comment]
@joelverhagen Should it be 48 or 47? If it is 48 we will need another commit updating the versions. If it will be 47, I can just re-spin CI once I see the packages showing up in myget.

**Comment by joelverhagen** [comment]
48. Rob or I will push another commit soon.

**Comment by rrelyea** [comment]
will be 48. updating it now.

**Comment by joelverhagen** [comment]
@dotnet-bot CentOS7.1 x64 Debug Build please sir
@dotnet-bot OSX x64 Release Build please sir
@dotnet-bot OpenSUSE13.2 x64 Debug Build please sir

**Comment by joelverhagen** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please sir
@dotnet-bot test OSX x64 Release Build please sir
@dotnet-bot test OpenSUSE13.2 x64 Debug Build please sir
@dotnet-bot test Fedora23 x64 Debug Build please sir

**Comment by piotrpMSFT** [comment]
@joelverhagen  looks like a real issue: Failure to restore a package: Unable to resolve 'NuGet.CommandLine.XPlat (>= 4.0.0-rc-2048)' for '.NETCoreApp,Version=v1.0'.

**Comment by joelverhagen** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please sir

**Comment by piotrpMSFT** [comment]
waiting for packages to hit myget?

**Comment by joelverhagen** [comment]
@piotrpMSFT, don't think so. Debian has gotten the packages properly. Looks like there was a caching issue either on the client (HTTP cache) or on MyGet.

**Comment by piotrpMSFT** [comment]
I can't wait for some downtime so we can bash flaky tests...

**Comment by rrelyea** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please sir

**Comment by piotrpMSFT** [comment]
this is one of our flaky tests you may be able to help with :) project.assets.json is in use :-/

**Comment by piotrpMSFT** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please.

**Comment by joelverhagen** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please sir

**Comment by piotrpMSFT** [comment]
one to go...

**Comment by piotrpMSFT** [comment]
hold off on retest. Let me investigate a bit.

**Comment by piotrpMSFT** [comment]
@joelverhagen these tests all failed to restore. Did we make some change that made nuget more likely to hold on to the project.assets.json?

**Comment by rrelyea** [comment]
Curious what you may have found

**Comment by piotrpMSFT** [comment]
notice, this PR just turned green on CentOS:
https://github.com/dotnet/cli/pull/4585

**Comment by piotrpMSFT** [comment]
In the build log, this string will get us close to where the test restore should have happened. We test in parallel, so the streams get crossed... but additional eyes may spy something of interest, particularly common nuget error messages:

`21:31:17          TestAsset Restore 'TestAppWithProjDepTool'`

**Comment by piotrpMSFT** [comment]
This one just turned green too:
https://github.com/dotnet/cli/pull/4615

**Comment by piotrpMSFT** [comment]
Log under investigation is here: https://ci.dot.net/job/dotnet_cli/job/rel_1.0.0/job/debug_centos7.1_x64_prtest/583/consoleFull 

I'll restart centos tests just in case, while investigating this log.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please sir

**Pull request merged**
