### PR TITLE
Switched telemetry to be OFF by default

### PR DESCRIPTION
**Pull request by rafaelrpinto**
Switched the telemetry option from disable if you don't agree to enable if you agree. The translations need further work.
Addresses issue #3093.
skipciplease

### CODE REVIEW

**Comment by mgravell** [comment]
Might as well rename that to "remove all telemetry", in terms of the effect it will have. Fetches popcorn...

**Comment by vcsjones** [comment]
Well, this would be one way to address #6086.

**Comment by yuhong** [comment]
This should be a build option IMO.

**Comment by rafaelrpinto** [comment]
@mgravell 
Just materializing an attempt to address all the different opinions of  #3093. Don't shoot the messenger =]

**Comment by rafaelrpinto** [comment]
Attempted to update the readme locally and messed the whole thing up. Will make a new Pr later.

**Pull request closed without merging**
