### PR TITLE
Revert "Revert "Add performance tests""

### PR DESCRIPTION
**Pull request by pakrym**
Adds performance test back

### CODE REVIEW

**Comment by pakrym** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by pakrym** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please

**Comment by brianrob** [comment]
LGTM.  @pakrym tested this against the latest version of the harness and it ran successfully.  Thanks @pakrym!

**Comment by pakrym** [comment]
@dotnet-bot test Windows_NT x64 Release Build  please

**Comment by pakrym** [comment]
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by pakrym** [comment]
@piotrpMSFT @brianrob just in case, am I OK to merge this when build goes green?

**Comment by pakrym** [comment]
:watch:

**Comment by brianrob** [comment]
@pakrym, anything else you need to merge this?

**Comment by pakrym** [comment]
@brianrob need :shipit: from @piotrpMSFT

**Comment by pakrym** [comment]
:up: :date: `rel/1.0.0` is now open to `preview2` commit, can we merge this branch now?

**Pull request merged**
