### PR TITLE
Adding a pt-BR Jenkins leg

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test Windows_NT_PTBR x64 Debug Build

**Comment by mmitche** [comment]
@dotnet-bot test Windows_NT_PTBR x64 Debug Build

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by nguerrera** [comment]
Where can I see the pt_BR run results?

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Pull request closed without merging**
