### PR TITLE
Change preview4 references to RC4

### PR DESCRIPTION
**Pull request by jchannon**
Preview4 is actually RC4 as all documentation and dotnet --info shows. I thought they were 2 separate things.

skipciplease

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please.

**Comment by piotrpMSFT** [comment]
@blackdwarf can you please review?

**Comment by blackdwarf** [comment]
LGTM

**Comment by piotrpMSFT** [comment]
@MattGertz merging a doc update to CLI repo readme

**Pull request merged**
