### PR TITLE
Update fsharp

### PR DESCRIPTION
**Pull request by KevinRansom**
Updates F# compiler to match VS 2017.6

### CODE REVIEW

**Comment by livarcocc** [comment]
Has this been inserted into VS already?

**Comment by KevinRansom** [comment]
PR:   https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/105891?_a=overview

**Comment by livarcocc** [comment]
@MattGertz FYI since this will require a VS insertion.

Given that it is 3pm and 6pm is the deadline for VS insertion, I don't believe this will make it in through the CLI for preview5. It can be in for preview6.

**Comment by MattGertz** [comment]
Yep, preview 6.

**Pull request merged**
