### PR TITLE
update nuget to 4.0.0-rtm-2259

### PR DESCRIPTION
**Pull request by rohit21agrawal**
CC: @rrelyea @piotrp

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@MattGertz FYI this was approved by shiproom along with the corresponding VS change today. Confirmed at 4:30. We'll merge and include in today's insertion.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by MattGertz** [comment]
Groovy.

**Comment by livarcocc** [comment]
@dotnet-bot Test OSX x64 Release Build
@dotnet-bot Test Windows_NT x64 Release Build
@dotnet-bot Test Windows_NT x86 Debug Build

**Pull request merged**
