### PR TITLE
Handle duplicated assemblies in binding redirects

### PR DESCRIPTION
**Pull request by pakrym**
@davidfowl

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2137)

### CODE REVIEW

**Comment by pakrym** [comment]
@dotnet-bot test Windows_NT x64 Release Build please
@dotnet-bot test Windows_NT x86 Release Build please

**Comment by pakrym** [comment]
@dotnet-bot test Windows_NT x64 Release Build please
@dotnet-bot test Windows_NT x86 Release Build please

**Comment by pakrym** [comment]
@dotnet-bot test Windows_NT x64 Release Build please
@dotnet-bot test Windows_NT x86 Release Build please

**Comment by pakrym** [comment]
@dotnet-bot test Windows_NT x64 Release Build please
@dotnet-bot test Windows_NT x86 Release Build please

**Comment by pakrym** [comment]
@dotnet-bot test Windows_NT x64 Release Build please
@dotnet-bot test Windows_NT x86 Release Build please

**Comment by pakrym** [comment]
@dotnet-bot test Windows_NT x86 Release Build please

**Comment by pakrym** [comment]
@dotnet-bot test Windows_NT x86 Release Build please

**Comment by pakrym** [comment]
@dotnet-bot test Windows_NT x86 Debug Build

**Comment by davidfowl** [comment]
Make sure you file a bug or find the one that has issues about duplicate assemblies in packages :shipit:

**Pull request merged**
