### PR TITLE
Fixed uninstaller not removing installation folder.

### PR DESCRIPTION
**Pull request by tn0502**

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@sridhar-ms @robmen can you review?

**Comment by eerhardt** [comment]
Looks like a dupe of #3042

**Comment by tn0502** [comment]
Looks like it. Although, the extra lines for deleting things inside one's home directory sounds really dangerous to me. Not something I'd do lightly.

**Comment by whoisjake** [comment]
Since this is a script running in an elevated privilege state... Please don't use `rm -rf`

The script was literally *one* character away from being dangerous (had there been a trailing slash):
`rm -rf $dotnet_install_location/`

I can see how this script is a workaround for uninstalling previous beta versions for now, so maybe:
`find $dotnet_install_root -delete` or `rm -ri $dotnet_install_root`

The idea with using `find` is that you can tighten the scope of what you want to delete using regex.

**Comment by eerhardt** [comment]
I'm closing this as a dupe of #3042.  Let's make #3042 as good as it can be.

**Pull request closed without merging**
