### PR TITLE
allow dotnet-publish to publish a library

### LINKED ISSUE #314: dotnet-publish must work for libraries too
Today for a library project dotnet-publish fails with 
> 'project name' does not have an entry point defined.

xunit test cases are libraries which are reflected over by the xunit runner. And xunit tests are usually not published along with some other application or added as a dependency to an application. So we must provide a way to publish libraries.

### PR DESCRIPTION
**Pull request by anurse**
fixes #314 

/cc @Sridhar-MS @brthor @piotrpMSFT @davidfowl

### CODE REVIEW

**Comment by anurse** [comment]
Not sure what's going on with Ubuntu.

**Comment by anurse** [comment]
@dotnet-bot test this please

**Comment by davidfowl** [comment]
What's the scenario for this?

**Comment by anurse** [comment]
1) (and yes, it a tenuous reason) remove emitEntryPoint from https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Runtime/project.json

2) See #348 - If we make Test Projects libraries and want to run the tests in the published mode (which I don't think should be the default), it's needed

3) Any scenario where a user wants a complete set of all the managed dependencies for a library

Mostly it's just really easy to move the check.

**Comment by Sridhar-MS** [comment]
@dotnet-bot test this please

I cleaned up dci-ub-fbld-12 and dci-ub-fbld-5 
cc: @brthor

**Comment by Sridhar-MS** [comment]
:shipit:

**Pull request merged**
