### PR TITLE
fixes #2408 stop using corehost to activate projectdependencycommands

### LINKED ISSUE #2408: Stop using corehost to activate apps
## Steps to reproduce
`dotnet test` uses `corehost` to activate test xunit.dll

## Expected  behavior
`dotnet test` always uses the muxer to activate xunit.dll

## Actual behavior
corehost in `sdk` is being used.

## Environment data
`dotnet --info` output:

### PR DESCRIPTION
**Pull request by brthor**
cc @schellap @eerhardt 

fixes #2408

### CODE REVIEW

**Comment by schellap** [comment]
Can we get rid of `corehost.exe` and friends in the SDK binaries and installers?

**Comment by eerhardt** [comment]
:shipit: 

I assume we can remove `corehost` and `dotnet` from the shared fx after this, right?

**Comment by brthor** [comment]
Corehost definitely, I don't know who has a dependency on the `dotnet` there.

**Comment by brthor** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by eerhardt** [comment]
> Corehost definitely, I don't know who has a dependency on the dotnet there.

I think the idea of https://github.com/dotnet/cli/pull/3106 was that you'd always use the muxer, no matter what.

**Comment by brthor** [comment]
@schellap Can you comment on whether we could remove `dotnet` from the sharedfx?

And yes we should be able to remove corehost.exe

**Comment by eerhardt** [comment]
We need to remove the CoreHost class too https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/CoreHost.cs.

Looks like there is still 1 dependency on it: 

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Compiler.Common/Executable.cs#L106

**Comment by brthor** [comment]
I was just checking on this, thanks @eerhardt :smile: 

I'm actually not sure what we should do there, that is the host the sdk copies on build output, I guess let's copy the muxer?

**Comment by eerhardt** [comment]
>  I guess let's copy the muxer?

Yes, that was my thought too.  It should be the exact same executable as corehost.exe, just a different name and in a different folder.

**Comment by schellap** [comment]
Dotnet is removed already as part of https://github.com/dotnet/cli/pull/3106/files

**Comment by schellap** [comment]
> I'm actually not sure what we should do there, that is the host the sdk copies on build output, I guess let's copy the muxer?

You should get everything from package graph. Otherwise you will end up with problems with app specified version vs. installed SDK versions. Also, hostfxr.dll won't be sxs in future SharedFX builds.

**Comment by brthor** [comment]
@schellap Okay this has become a bigger change.

I think I will put this PR in as is as only a fix to activating xunit with corehost. 

As for removing corehost we need to deal with https://github.com/dotnet/cli/issues/2444, resolve the host from the package graph during build, and then remove corehost. These will be breaking changes so we'll need to communicate appropriately.

**Comment by eerhardt** [comment]
`corehost.exe` is still in the shared framework:

https://github.com/dotnet/core-setup/blob/master/build_projects/shared-build-targets-utils/Utils/SharedFrameworkPublisher.cs#L182-L184

```
            File.Copy(
               Path.Combine(_corehostLockedDirectory, HostArtifactNames.DotnetHostBaseName),
               Path.Combine(sharedFrameworkNameAndVersionRoot, $"corehost{Constants.ExeSuffix}"), true);
```

**Comment by brthor** [comment]
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by schellap** [comment]
> These will be breaking changes so we'll need to communicate appropriately.

I see these solutions and only 1 below is breaking. Have you decided on its way forward?

1. Activate with muxer: `dotnet.exe --additionalprobingpath c:\ache\ standalone.dll`
2. Build copies `standalone.exe` and `hostfxr.dll` from package graph
  * `standalone.exe --additionalprobingpath c:\ache`
3. `dotnet.exe` and `hostfxr.dll` loaded in the CLI SDK's process is copied into `standalone.exe` base.

**Comment by schellap** [comment]
If we are getting this right and can make breaking changes we should do 1. Standalone apps are not truly standalone in the sense they don't have everything next to them. So they should be activated by the muxer, that is the rationale here.

1 will also address: #2129

**Comment by brthor** [comment]
@schellap 2 is breaking because any app which doesn't already reference HostPolicy will break. I agree it's the ideal solution though

**Comment by schellap** [comment]
> @schellap 2 is breaking because any app which doesn't already reference HostPolicy will break. I agree it's the ideal solution though

I see, 2 would have to resolve hostpolicy as well :)

**Pull request merged**
