### PR TITLE
Enable building dotnet-CLI for centos.

### PR DESCRIPTION
**Pull request by Sridhar-MS**
I had to patch up a redhat dnx package which supports NETStandard.Library package. It is currently uploaded to dotnet-cli blob storage. This hack will no longer be required when we move to xplat nuget to do 'dotnet restore'. Apart from this there are three issues that are tracked for centos.
- compile-native not yet supported - https://github.com/dotnet/cli/issues/453
- dnu restore crashes intermittently on centos. I need to investigate this a little bit more and file issues on dnx or coreclr. This will make our CI builds very flaky.
- Dotnet restore does not restore native shims when using “centos.7-x64” - https://github.com/dotnet/corefx/issues/5066

/cc: @mmitche for the netci.groovy changes

### CODE REVIEW

**Comment by mmitche** [comment]
LGTM on netci

**Comment by piotrpMSFT** [comment]
Can you resolve conflicts, @Sridhar-MS? Then we'll merge.

**Comment by Sridhar-MS** [comment]
Resolved the conflicts. I will merge once the CI builds pass.

**Comment by Sridhar-MS** [comment]
Ubuntu release builds failed due to no space left on device.
cc: @mmitche I am not able to ssh into "dci-ub-fbld-2" to clean it up. Can you take a look?

**Pull request merged**
