### PR TITLE
Ignore framework assemblies when compiling for package based frameworks.

### LINKED ISSUE #1054: dotnet build fails if a package based framework (dotnet5.4) references package with framework assemblies
Encountered this issue attempting to build https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNetCore.Mvc.Razor. The project transitively references `Microsoft.CodeAnalysis.Analyzers` which has a nuspec that looks like this:
```xml
  <metadata>
    <id>Microsoft.CodeAnalysis.Analyzers</id>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System" />
    </frameworkAssemblies>
  </metadata>
```

Building for dotnet5.4 produces this error:
`error DOTNET1011: Framework not installed: .NETPlatform,Version=v5.6 in C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework`

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #1054

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @davidfowl

**Comment by davidfowl** [comment]
:shipit:

**Comment by pranavkm** [comment]
Thanks for merging this!

**Pull request merged**
