### PR TITLE
Add more xlf files for new strings

### PR DESCRIPTION
**Pull request by nguerrera**
More xlf conversions for recently merged PRs with new strings.

There is still one more round of conversion needed after #4901 and #4902 are merged. Let's leave this open until those are merged and I'll update this PR accordingly.

@piotrpMSFT, @livarcocc for code review

@MattGertz for ask mode approval

@nataliatgit, @janbaltus FYI

### CODE REVIEW

**Comment by livarcocc** [comment]
@nguerrera The other two loc PRs have been merged. Do you want to go ahead and re-run the tool?

**Comment by nguerrera** [comment]
@livarcocc Thanks and done.

**Comment by nguerrera** [comment]
Test CentOS7.1 x64 Debug Build please

**Comment by nguerrera** [comment]
Test  RHEL7.2 x64 Release Build please

**Comment by nguerrera** [comment]
Test CentOS7.1 x64 Debug Build please

**Pull request merged**
