### PR TITLE
MSBuild 15.5.170

### PR DESCRIPTION
**Pull request by AndyGerlicher**
* Update MSBuild to 15.5.170
* NuGet ImportAfter no longer needed because of https://github.com/Microsoft/msbuild/pull/2663

This is approved from shiproom, but Val builds are still in progress.

### CODE REVIEW

**Comment by livarcocc** [comment]
Andy, some of these are failing with

```
07:10:08          D:\j\workspace\debug_windows---ffb11291\src\Microsoft.DotNet.Cli.Utils\Microsoft.DotNet.Cli.Utils.csproj : error MSB4057: The target "Restore" does not exist in the project. [D:\j\workspace\debug_windows---ffb11291\build.proj]
07:10:08 
```

**Comment by nguerrera** [comment]
@livarcocc We need a new msbuild with https://github.com/Microsoft/msbuild/pull/2672 

I assume the build is in progress.

**Comment by AndyGerlicher** [comment]
It is in progress. Will update once it finishes.

**Comment by livarcocc** [comment]
I thought that was already inserted here with 15.5.169.

**Comment by AndyGerlicher** [comment]
There was another case I missed that explicitly imported just the file I deleted to get around Common targets not being imported in CrossTargeting builds. The PR Nick mentioned fixed that and the build with that fix is in progress.

**Comment by AndyGerlicher** [comment]
@livarcocc  Took forever for RPS to finish but it's good and merged into VS.

**Pull request merged**
