### PR TITLE
bump nuget to 3.6.0-beta.1.msbuild.16

### PR DESCRIPTION
**Pull request by rohit21agrawal**
this includes @emgarten 's fix for generating the *.g.props and *.g.targets with the file extension included in the name.

CC: @eerhardt @livarcocc @rrelyea @emgarten @joelverhagen

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
@dotnet-bot test this please.

**Comment by rohit21agrawal** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by rohit21agrawal** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please.

**Comment by livarcocc** [comment]
:shipit:

**Pull request merged**
