### PR TITLE
Update to latest dotnet/sdk

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
Closing and reopening so that tests run with latest msbuild from #8161

**Comment by nguerrera** [comment]
Package isn't getting found on the transport feed. cc @johnbeisner

**Comment by johnbeisner** [comment]
Apparently there is a latency period before the packages are available on our internal feed- rerunning the failed legs...

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT_ES x64 Debug Build

**Pull request merged**
