### PR TITLE
Merge rel/1.1.0-MSRC into rel/1.1.0

### PR DESCRIPTION
**Pull request by peterhuene**

### CODE REVIEW

**Comment by peterhuene** [comment]
We're missing some bits in the expected places.  Lee is working on it.

**Comment by peterhuene** [comment]
@dotnet-bot test this please.

**Comment by peterhuene** [comment]
@dotnet-bot test this please.

**Comment by livarcocc** [comment]
This seems good to merge now.

**Comment by peterhuene** [comment]
Ignoring the RHEL issue and completing the merge.

**Pull request merged**
