### PR TITLE
Update .NET SDK

### PR DESCRIPTION
**Pull request by dsplaisted**

### CODE REVIEW

**Comment by dsplaisted** [comment]
@livarcocc Looks like I don't have merge permissions for the CLI repo.

**Comment by livarcocc** [comment]
@dsplaisted check now.

**Comment by eerhardt** [comment]
I don't understand why we made this change.  We have https://github.com/dotnet/cli/blob/master/tools/CrossGen.Dependencies/CrossGen.Dependencies.csproj, which its job is to bring in the dependencies for crossgen.

**Comment by dsplaisted** [comment]
@eerhardt I've filed #6101 to follow up.  I wasn't aware of the crossgen project, and crossgen wasn't getting restored correctly when I made the change.

**Pull request merged**
