### PR TITLE
Remove skip first run flag and simplify flags

### PR DESCRIPTION
**Pull request by wli3**
Review by commit will be easier.

### CODE REVIEW

**Comment by wli3** [comment]
@livarcocc could you review this? You have context in first run as well

**Comment by wli3** [comment]
ping review @dotnet/dotnet-cli

**Review by livarcocc — APPROVED** [review]

**Comment by cezarypiatek** [comment]
@wli3 @livarcocc  can you provide an explanation why `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` flag has been removed and what is the recommended way of disabling dotnet welcome message? This is especially annoying while building dotnet app inside the docker container.

**Comment by dsplaisted** [comment]
@cezarypiatek I think the replacement you're looking for is `DOTNET_NOLOGO`: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet#environment-variables

**Comment by cezarypiatek** [comment]
That's exactly what I was looking for. Thanks @dsplaisted

**Comment by mhoeger** [comment]
As an FYI, the Azure Functions team was relying on `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` to avoid writing to files inaccessible to hosted users, so the behavior broke us (https://github.com/Azure/azure-functions-host/issues/5893). Switching to use `DOTNET_ADD_GLOBAL_TOOLS_TO_PATH=false`

**Pull request merged**
