### PR TITLE
MSTest nuget update

### PR DESCRIPTION
**Pull request by AbhitejJohn**
Updating the MSTest nugets with the ones shipping in VS for desktop and UWP scenarios.

### CODE REVIEW

**Comment by AbhitejJohn** [comment]
Tagging @piotrpMSFT and @livarcocc for review.

**Comment by AbhitejJohn** [comment]
@livarcocc: The CI failures seem unrelated. How can I re-trigger validation on the failed configs?

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build
@dotnet-bot Test Debian8.2 x64 Debug Build
@dotnet-bot Test CentOS7.1 x64 Debug Build

**Comment by AbhitejJohn** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by livarcocc** [comment]
@MattGertz for approval.

**Comment by piotrpMSFT** [comment]
@mlorbetske this is updating dotnet-new templates. We will need the same change in the new3 templates. Is that tracked?

**Comment by livarcocc** [comment]
@piotrpMSFT this next.

**Comment by mlorbetske** [comment]
@piotrpMSFT new3 change addressed by https://github.com/dotnet/templating/pull/212

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Pull request merged**
