### PR TITLE
[DO NOT MERGE] Testing the state of our branch

### PR DESCRIPTION
**Pull request by eerhardt**
This PR should be green.

### CODE REVIEW

**Comment by brthor** [comment]
myget is down

**Comment by brthor** [comment]
https://twitter.com/MyGetTeam/status/740969668555464704

**Comment by eerhardt** [comment]
test CentOS7.1 x64 Debug Build
test Debian8.2 x64 Debug Build
test OSX x64 Release Build
test RHEL7.2 x64 Release Build
test Ubuntu x64 Release Build
test Ubuntu16.04 x64 Debug Build

**Comment by eerhardt** [comment]
@mmitche - MyGet's DNS got messed up and now we are supposed to flush our dns cache.  See:  https://twitter.com/MyGetTeam/status/740976282586996741

Is that something that can be done on Jenkins machines?

**Comment by eerhardt** [comment]
test OSX x64 Release Build
test RHEL7.2 x64 Release Build
test Ubuntu x64 Release Build
test Ubuntu16.04 x64 Debug Build

**Comment by eerhardt** [comment]
test Windows_NT x86 Debug Build

**Comment by eerhardt** [comment]
Closing.  The state of our branch looks mostly good.

The Windows failures were all `dotnet pack` exiting with ` Exit Code: -1073741819`, which is probably https://github.com/dotnet/corefx/issues/9265 rearing its head.

**Pull request closed without merging**
