### PR TITLE
Update .vsts-ci.yml

### PR DESCRIPTION
**Pull request by JohnTortugo**
Related to: https://github.com/dotnet/core-eng/issues/6291

### CODE REVIEW

**Comment by JohnTortugo** [comment]
@wli3 looks like the build failure is due to tests - which seems unrelated to my change. Do I have a go to merge?

**Comment by wli3** [comment]
I rerun it, let's merge it once it passed

**Comment by wli3** [comment]
also created https://github.com/dotnet/cli/issues/11324

**Comment by JohnTortugo** [comment]
Thanks @wli3

**Pull request merged**
