### PR TITLE
update nuget version to 4.3.0-preview1-2500

### PR DESCRIPTION
**Pull request by rohit21agrawal**
CC: @livarcocc

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
@livarcocc this is also failing with a very similar error: 
```
2>D:\j\workspace\debug_windows---8a02d2bd\artifacts\win81-x86\stage2\sdk\2.0.0-preview1-005762\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(154,5): error MSB4018: The "ResolvePackageDependencies" task failed unexpectedly. [D:\j\workspace\debug_windows---8a02d2bd\tools\Archiver\Archiver.csproj] [D:\j\workspace\debug_windows---8a02d2bd\src\redist\redist.csproj]
16:55:38 16:55:37.822     2>D:\j\workspace\debug_windows---8a02d2bd\artifacts\win81-x86\stage2\sdk\2.0.0-preview1-005762\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(154,5): error MSB4018: System.MissingMethodException: Method not found: 'System.Collections.Generic.IList`1<NuGet.Packaging.Core.PackageDependency> NuGet.ProjectModel.LockFileTargetLibrary.get_Dependencies()'. [D:\j\workspace\debug_windows---8a02d2bd\tools\Archiver\Archiver.csproj] [D:\j\workspace\debug_windows---8a02d2bd\src\redist\redist.csproj]

```

**Comment by rohit21agrawal** [comment]
ping.... @livarcocc ?

**Comment by livarcocc** [comment]
Rohit, I am not sure what is causing this break. I will try to take a look at it tomorrow. What changes are there on the NuGet side that could be causing this? Has the API that the runtime is complaining about it being missing really been removed?

**Comment by rohit21agrawal** [comment]
@livarcocc the API still exists. we have made a lot of changes in the NuGet repo, including moving everything (almost) to NETCore, and merging a few projects, but the particular API that the failure is complaining about still exists.

**Comment by livarcocc** [comment]
Trying a local build.

**Comment by livarcocc** [comment]
@gkhanna79 @ramarag can you guys help me understand why NuGet.ProjectModel.dll is not getting loaded by the host?

I attached a debugger to this and I looked at the modules window in the debugger and by the time publish fails, three other NuGet dlls have been loaded by NuGet.ProjectModel has not. Which is the dll that contains the missing method.

I have a local repro in my box if one of you guys wouldn't mind dropping by and taking a look.

**Comment by livarcocc** [comment]
@rohit21agrawal now that we think that the issue is that NuGet.ProjectModel is not being loaded, are you aware, or can think of any changes make on your side that could be causing this?

**Comment by gkhanna79** [comment]
What is the output of COREHOST_TRACE=1?
CC @eerhardt

**Comment by rohit21agrawal** [comment]
@emgarten you did some reorganizing of projects in our repo, does anything ring a bell here?

**Comment by livarcocc** [comment]
[corehost_trace.txt](https://github.com/dotnet/cli/files/921025/corehost_trace.txt)

**Comment by gkhanna79** [comment]
The library is being identfied and setup in the TPA as expected:

```
Processing TPA for deps entry [NuGet.ProjectModel, 4.3.0-preview1-2484, lib/netstandard1.3/NuGet.ProjectModel.dll]
  Considering entry [NuGet.ProjectModel/4.3.0-preview1-2484/lib/netstandard1.3/NuGet.ProjectModel.dll] and probe dir [E:\git\cli\artifacts\win10-x64\stage2\shared\Microsoft.NETCore.App\2.0.0-preview1-001915-00]
    Skipping... probe in deps json failed
    Skipping... not found in probe dir 'E:\git\cli\artifacts\win10-x64\stage2\shared\Microsoft.NETCore.App\2.0.0-preview1-001915-00'
  Considering entry [NuGet.ProjectModel/4.3.0-preview1-2484/lib/netstandard1.3/NuGet.ProjectModel.dll] and probe dir []
    Local path query exists E:\git\cli\artifacts\win10-x64\stage2\sdk\2.0.0-preview1-005761\NuGet.ProjectModel.dll
    Probed deps dir and matched 'E:\git\cli\artifacts\win10-x64\stage2\sdk\2.0.0-preview1-005761\NuGet.ProjectModel.dll'Adding tpa entry: E:\git\cli\artifacts\win10-x64\stage2\sdk\2.0.0-preview1-005761\NuGet.ProjectModel.dll
```

What is indicative of it being not loaded @livarcocc? do you see any exception? I dont see any host issue in this so far.

**Comment by livarcocc** [comment]
@gkhanna79 That's what so weird. I attached a debugger to the process and by the time we hit this exception, I don't see the dll loaded in the modules. That's why I assumed that the issue was the library not being loaded.

**Comment by gkhanna79** [comment]
Does that method even exist in the assembly in question? This is a managed exception that you should be able to catch in windbg and investigate.

**Comment by livarcocc** [comment]
@gkhanna79 yes, the API exists. That's why I believe the problem is the dll not being available in the process.

**Comment by gkhanna79** [comment]
The dll will be loaded when there is a request to use it. Can you capture the crash dump in windbg when the exception is thrown and share it? Or shared a reduced repro?


Thanks,
Gaurav
________________________________

**Comment by livarcocc** [comment]
@gkhanna79 Repro steps:
1. Clone CLI repo
2. git fetch origin
3. git checkout -b dev-ragrawal-updatenuget2484 origin/dev-ragrawal-updatenuget2484
4. build.cmd[sh]
5. cd src/dotnet-archive
6. <repo_root>/artifacts/<your_rid>/stage2/dotnet publish

You should hit this problem then.

**Comment by gkhanna79** [comment]
@ramarag can take a look at it next week once he is done with feature complete.

**Comment by emgarten** [comment]
@ramarag any idea what is causing this?

**Comment by livarcocc** [comment]
@dotnet-bot Test this please.

**Comment by livarcocc** [comment]
@MattGertz for approval.

**Pull request merged**
