### PR TITLE
Use subdirectories in publish for native

### PR DESCRIPTION
**Pull request by brthor**
First pass on including subdirectories for use in Native.

PTAL @schellap @gkhanna79

### CODE REVIEW

**Comment by schellap** [comment]
This sounds good. Does it run fine on the E2E test? We should co-ordinate checking in since CoreRT publish needs to have --native-subdirectory flag to not break CoreRT CI.

For your future PR, corerun/corehost has to be copied as well and the appdep build hack to drop inside this folder.

**Comment by brthor** [comment]
@schellap Waiting on results here for E2E.

**Comment by brthor** [comment]
@schellap I am seeing that on windows, the subdirectories are included and things are just fine.

On Ubuntu, the files are getting flat packed.

Can you quickly confirm that the Ubuntu NuGet Packages are structured to take advantage of the subdirectories?

captureaa

**Comment by schellap** [comment]
@brthor, can you give permissions to your fork so I can buddy test for you? Or if you find it easy, you can clone dotnet/corert and switch to native-subdir branch and drop a CLI (your stage2) inside <ROOT>/bin/tools/cli/.

https://github.com/dotnet/corert/pull/580

**Comment by schellap** [comment]
image

**Comment by schellap** [comment]
Are your path separators good?

**Comment by brthor** [comment]
@schellap added as a collaborator

running a local build to see what's up here. Thanks for the quick check on that.

**Comment by brthor** [comment]
Path separators shouldn't play a role here. The Publish subdirectory support splits on "native", and that seems to be where something is going wrong.

**Comment by schellap** [comment]
@brthor, I'll test this on our repo once you are ready to go with CLI CI.

**Comment by brthor** [comment]
Error: Unable to load DLL 'jitinterface': The specified module could not be found.

@schellap Do you know how this dlll is being loaded?

**Comment by brthor** [comment]
@dotnet-bot test OSX Release Build please

**Comment by brthor** [comment]
This dll is moved to the path `dotnet/lib/jitinterface.dylib`

It looks like this dll is picked up by ILCompiler, @schellap does it need accompanying changes?

**Comment by schellap** [comment]
This needs to be PInvoked by ILC. Is there a way it can land next to ilc like ryujit? Eventually it might come from ryujit like package.

**Comment by brthor** [comment]
The dll needs to not be in a subdirectory in the nuget package.

Think this:
https://github.com/dotnet/corert/blob/master/src/packaging/packages.targets#L53

```xml
<Text><![CDATA[        <file src="../%(Identity)" target="runtimes/$(NuPkgRid)/native/lib/dotnet/%(Identity)" /> ]]></Text>
```

Would need the path changed:

```xml
<Text><![CDATA[        <file src="../%(Identity)" target="runtimes/$(NuPkgRid)/native/%(Identity)" /> ]]></Text>
```

**Comment by schellap** [comment]
Ah, I see. I thought the lib/dotnet/.dll was required by NuGet and publish for it to be picked up.

**Comment by schellap** [comment]
@brthor, having it at root of `native` folder won't break when NuGet content support comes in and `native-subdirectory` goes away, right?

**Comment by brthor** [comment]
At that point we'd need to take it out of the native folder anyways wouldn't we?

**Comment by schellap** [comment]
Yeah, I realized that later. Anyway, we would have to make too many changes, so it is a non-issue.

**Comment by schellap** [comment]
How does this look for you? 1.0.4-prerelease-00005

**Comment by schellap** [comment]
I don't think we need to remove from the native folder as it is a native library. We would however change the layout of the SDK package to use the appropriate content folders. Note: jitinterface.dylib is not content but a PInvoke binary which should just do what other PInvoke binaries do. How is always using `--native-subdirectory` not an issue for the CLI, you guys don't have any PInvoke libraries?

The real issue is that `--native-subdirectory` hack overrides known folder (sdk/lib) treatment. I am fine with your current plan as anyway changes are necessary in the future and the support for content will come sooner.

**Comment by gkhanna79** [comment]
The changes, at a highlevel, look fine to me. However, have you looked into the OSX failures?

Also, please do squash the commits.

**Comment by brthor** [comment]
@gkhanna79 OSX failures are related to the discussion above. This would happen on Ubuntu as well but the test is skipped for the moment. Will definitely squash the commits, thanks.

@schellap I see what you are saying with this dll that it will not be part of the contents and will remain in `native`. Looking into similar packages though, the `lib/dotnet` portion is typically used instead of `native` not with it.

For example in `runtime.ubuntu.14.04-x64.Microsoft.NETCore.ConsoleHost` version `1.0.0-rc2-23616` I see the following path for native components: `runtimes\ubuntu.14.04-x64\native`

Whereas in `runtime.win7.System.IO.Pipes` I see the following path (for a managed dll): `runtimes\win7\lib\dotnet5.4`

I think removing the `lib/dotnet` portion will not affect the usability of the package even after content support comes online.

**Comment by brthor** [comment]
@dotnet-bot test this please

**Comment by brthor** [comment]
@dotnet-bot test this please

**Comment by brthor** [comment]
@dotnet-bot test Ubuntu Debug Build please

**Comment by brthor** [comment]
@dotnet-bot test Ubuntu Debug Build please

**Comment by brthor** [comment]
@Sridhar-MS This centos error seems to be caused by an outdated stage0 package. Can I safely ignore this for now, or should I wait on it for the merge?

**Comment by Sridhar-MS** [comment]
@brthor Let me quickly create an updated stage0 for centos. Merging this at this point will fail all the PRs.

**Comment by Sridhar-MS** [comment]
@dotnet-bot test CentOS7.1 Debug Build please

**Comment by Sridhar-MS** [comment]
@dotnet-bot test CentOS7.1 Release Build please

**Comment by Sridhar-MS** [comment]
@brthor The CentOS builds are passing, go ahead with the merge. Meanwhile I am also setting up the internal CI to push latest CentOS tarballs to azure blob storage.

**Comment by brthor** [comment]
Excellent :+1:

**Pull request merged**
