### PR TITLE
update NuGet to 4.0.0-rc2 build

### PR DESCRIPTION
**Pull request by rrelyea**
Moving from RC1's 4.0.0-rc-2048 to RC's final version of 4.0.0-rc2

@livarcocc @piotrpMSFT @joelverhagen

### CODE REVIEW

**Comment by livarcocc** [comment]
@MattGertz

**Comment by joelverhagen** [comment]
Have we verified what will happen inf the `dotnet-build` to `cli-deps` webhook if we need to re-publish a package with this very same version? Otherwise, LGTM.

**Comment by piotrpMSFT** [comment]
Sweet!

**Comment by rrelyea** [comment]
We have not verified, so we hold off on this merge until the SDK test failures are analyzed.
@emgarten

**Comment by rrelyea** [comment]
oh wait, looks like it was already merged.

**Comment by piotrpMSFT** [comment]
CLI was green when merged before we saw the SDK issues. We have a PR out to revert this until the gamut is understood. Waiting on @mattgertz's approval.

**Pull request merged**
