### PR TITLE
Eliminate imports from CLI, where possible

### LINKED ISSUE #2242: Remove imports from dotnet
We need to see if we still need these:

https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/project.json#L67-L69

Right now they are hiding incompatibilities that should be fixed

### PR DESCRIPTION
**Pull request by piotrpMSFT**
Fixes #2242

We've come a long way :)

See commit comments for notes on what stayed.

/CC @davidfowl @livarcocc @jgoshi @krwq @Petermarcu

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build please.

**Pull request merged**
