### PR TITLE
Fix System.Runtime.Extensions Issue

### PR DESCRIPTION
**Pull request by brthor**
cc @Sridhar-MS @anurse @livarcocc

### CODE REVIEW

**Comment by anurse** [comment]
:shipit:

**Comment by livarcocc** [comment]
:shipit: please.

**Comment by troydai** [comment]
:shipit:

**Comment by brthor** [comment]
Well it's getting past compilation (which is where I was stuck) but it looks like tests are still hitting the issue. This is blocking local testing too so I am trying to find a way to fix that.

**Comment by brthor** [comment]
Looks like this is caused by the dependency `xunit.runner.aspnet/2.0.0-aspnet-rc2-16079` in ProjectModel.Server.Tests

@troydai Do you know a compatible version of this dependency which pulls in an older version of `Microsoft.Dnx.Testhost` (and transitively System.Runtime.Extensions)

**Comment by brthor** [comment]
Going to give 16068 a try.

**Comment by brthor** [comment]
I've managed to get past this issue locally!

I'm working across multiple branches so I'm trying to port the changes over here to get the fix in. Let's see if this works.

**Comment by brthor** [comment]
@dotnet-bot test OSX Release Build please

**Pull request merged**
