### PR TITLE
[release/3.0.1xx] Update branding for 3.0.102

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@nguerrera Does this need to be updated below? https://github.com/dotnet/cli/pull/13093/files#diff-8b8f08ffbf7b863fb3700c1718eeb4cbR16

**Comment by nguerrera** [comment]
No, that needs to match the toolset used to build specified in global.json

**Comment by mmitche** [comment]
> No, that needs to match the toolset used to build specified in global.json

Okay, I'm planning an SDK update to 3.0.101 so will update that then.

**Comment by nguerrera** [comment]
The build should fail if you try to update global.json, but not that. The redundancy is unfortunate and should probably be fixed.

**Pull request merged**
