### PR TITLE
Remove Xlinker flag for native

### PR DESCRIPTION
**Pull request by schellap**

### CODE REVIEW

**Comment by brthor** [comment]
Ubuntu failures are nuget and nothing here touches Ubuntu. 

IMO :shipit:

**Comment by schellap** [comment]
@brthor noted offline that this is related to the quoting issue (with arg forwarding changes). We don't need `-Xlinker`. So removing it.

`"-Xlinker my.lib"`

Should be `"-Xlinker" "my.lib"`

**Comment by schellap** [comment]
OSX passed merging

**Comment by schellap** [comment]
Cc @blackdwarf

**Comment by blackdwarf** [comment]
@schellap this fixes the weird linker errors on OS X?

**Comment by schellap** [comment]
Yes @blackdwarf

**Pull request merged**
