### PR TITLE
Add UseDefaultCredentials to dotnet-install.ps1

### PR DESCRIPTION
**Pull request by axelheer**
When working behind a corporate proxy it may be necessary to authenticate properly.

### CODE REVIEW

**Comment by axelheer** [comment]
@dotnet-bot test please

**Comment by axelheer** [comment]
@livarcocc anything else I can / should do? (just randomly selected you to ask..)

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by axelheer** [comment]
@livarcocc curl using "integrated windows authentication" seems to be [another problem](http://stackoverflow.com/q/1276955/2347790). AFAIK, bash users set up [cntlm](http://cntlm.sourceforge.net/) or the like as a "proxy for the actual proxy" and register it using environment variables anyway.

I'm no bash user, but I think this is PowerShell on Windows only.

**Comment by omajid** [comment]
> Is there an equivalent to this that we can/should apply to the bash script?

I don't think so. There's nothing in `dotnet-install.sh` about proxies at all. `curl` does supporrt `--proxy` flags, but it's probably easier for users to set `http_proxy`/`HTTPS_PROXY` [environment variables]( https://curl.haxx.se/docs/manpage.html) to use proxying. Not sure if alternative ways to specify credentials are even possible.

**Pull request merged**
