### PR TITLE
Updating the websdk version to 2.0.0-rel-20170518-503

### PR DESCRIPTION
**Pull request by vijayrkn**
https://dotnet.myget.org/feed/dotnet-web/package/nuget/Microsoft.NET.Sdk.Web/2.0.0-rel-20170518-503
@mlorbetske @livarcocc

### CODE REVIEW

**Comment by mlorbetske** [comment]
@dotnet-bot test this please

**Comment by vijayrkn** [comment]
@dotnet-bot test this please

**Comment by vijayrkn** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by livarcocc** [comment]
@MattGertz just regular flow of dependencies into the CLI.

**Pull request merged**
