### PR TITLE
Bindings redirects fix

### LINKED ISSUE #865: Error on dotnet run
Guys,

I'm getting an error when running dotnet run or dotnet build:
_An item with the same key has already been added. Key: (log4net, neutral, 669e0ddf0bb1aa2a)_

Not sure how to proceed.

Thank you!

A bit more context:
My project.lock.json contains the following bits:

```
"Log4Net/2.0.5": {
        "type": "package",
        "compile": {
          "lib/net45-full/log4net.dll": {}
        },
        "runtime": {
          "lib/net45-full/log4net.dll": {}
        }
      },
      "log4net.Ext.Json.1.2.13/1.2.13.20140804": {
        "type": "package",
        "dependencies": {
        "log4net": "2.0.3"
        },
        "compile": {
          "lib/net35-full/log4net.Ext.Json.dll": {}
        },
        "runtime": {
          "lib/net35-full/log4net.Ext.Json.dll": {}
        }
      }
```

Notice the log4net dependency of log4net.Ext.Json has different casing than the root Log4Net dependency. Could this be the issue?

UPDATE2:
Changed the cached nuspec file for log4net.Ext.Json to say Log4Net and it made the error go away. At this point I think this is a bug. I'll try and have a look at the code.

### PR DESCRIPTION
**Pull request by marono**
Added tests and assembly info caching as requested in the previous PR,
which I had to close due to CLA.

Due to packages including assemblies other than their primary output,
under some circumstances, the same assembly may be considered multiple
times for bindign redirect generation, which would cause the build to
fail because of dictionary key collisions. Fixed the issue by filtering
the assemblies considered for binding redirects to only include
exports in the runtime list only when the same export is not already
published via a compilation list of another dependency.

Fix #865

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/1731)

### CODE REVIEW

**Comment by davidfowl** [comment]
Why are there so many commits?

**Comment by marono** [comment]
@davidfowl took me a while to figure out how to get tests to run only on windows machines.
Binding redirects are only generated for desktop runtimes which won't build on *nix.

The number of changed files is quite small, all in all.

**Comment by cwe1ss** [comment]
Should this also fix #1860 ?

**Comment by marono** [comment]
@cwe1ss Yes it does. While I haven't tested your particular scenario, the test projects at $/TestAssets/TestProjects/TestBindingRedirectGeneration2 reproduce a similar situation.

**Comment by marono** [comment]
This seems to have been fixed as part of a different PR. Although I'm not completely convinced the process is deterministic in generating the version to redirect to, I don't have any test scenario to prove it.

**Pull request closed without merging**
