### PR TITLE
Updating CoreFx, CoreClr, CoreSetup to rc3-24209-08, rc3-24208-04, rc3-3004442-00 respectively

### PR DESCRIPTION
**Pull request by eerhardt**

### CODE REVIEW

**Comment by eerhardt** [comment]
test Windows_NT x86 Debug Build
test Windows_NT x64 Release Build

**Comment by eerhardt** [comment]
test CentOS7.1 x64 Debug Build
test Debian8.2 x64 Debug Build
test Fedora23 x64 Debug Build

**Comment by eerhardt** [comment]
@joshfree @Petermarcu - this looks to be green on a few platforms.

**Comment by Petermarcu** [comment]
Great. Making progress...

**Comment by joshfree** [comment]
The real validation is the VSTS build however

**Comment by eerhardt** [comment]
VSTS running now:  https://mseng.visualstudio.com/dotnetcore/_build?_a=summary&favDefinitionId=3606&buildId=3054332

**Comment by eerhardt** [comment]
VSTS fails:

```
2016-06-10T03:29:53.4840326Z Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
2016-06-10T03:29:53.4840326Z    at Interop.zlib.deflate(Byte* stream, Int32 flush)
2016-06-10T03:29:53.4840326Z    at Interop.zlib.Deflate(ZStream& stream, FlushCode flush)
2016-06-10T03:29:53.4840326Z    at System.IO.Compression.ZLibNative.ZLibStreamHandle.Deflate(FlushCode flush)
2016-06-10T03:29:53.4840326Z    at System.IO.Compression.Deflater.Deflate(FlushCode flushCode)
2016-06-10T03:29:53.4840326Z    at System.IO.Compression.Deflater.ReadDeflateOutput(Byte[] outputBuffer, FlushCode flushCode, Int32& bytesRead)
2016-06-10T03:29:53.4840326Z    at System.IO.Compression.Deflater.GetDeflateOutput(Byte[] outputBuffer)
2016-06-10T03:29:53.4840326Z    at System.IO.Compression.DeflateStream.WriteDeflaterOutput()
2016-06-10T03:29:53.4840326Z    at System.IO.Compression.DeflateStream.Write(Byte[] array, Int32 offset, Int32 count)
2016-06-10T03:29:53.4840326Z    at System.IO.Compression.CheckSumAndSizeWriteStream.Write(Byte[] buffer, Int32 offset, Int32 count)
2016-06-10T03:29:53.4840326Z    at System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
2016-06-10T03:29:53.4840326Z    at System.IO.Compression.WrappedStream.Write(Byte[] buffer, Int32 offset, Int32 count)
2016-06-10T03:29:53.4840326Z    at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
2016-06-10T03:29:53.4840326Z    at NuGet.PackageBuilder.CreatePart(ZipArchive package, String path, Stream sourceStream)
2016-06-10T03:29:53.4840326Z    at NuGet.PackageBuilder.WriteFiles(ZipArchive package)
2016-06-10T03:29:53.4840326Z    at NuGet.PackageBuilder.Save(Stream stream)
2016-06-10T03:29:53.4840326Z    at Microsoft.DotNet.Tools.Compiler.PackageGenerator.GeneratePackage(String nupkg, List`1 packDiagnostics)
2016-06-10T03:29:53.4840326Z    at Microsoft.DotNet.Tools.Compiler.SymbolPackageGenerator.GeneratePackage(String nupkg, List`1 packDiagnostics)
2016-06-10T03:29:53.4840326Z    at Microsoft.DotNet.Tools.Compiler.PackageGenerator.BuildPackage(IEnumerable`1 contexts, List`1 packDiagnostics)
2016-06-10T03:29:53.4840326Z    at Microsoft.DotNet.Tools.Pack.PackagesGenerator.Build()
2016-06-10T03:29:53.4840326Z    at Microsoft.DotNet.Tools.Compiler.PackCommand.<>c__DisplayClass0_0.<Run>b__0()
2016-06-10T03:29:53.4840326Z    at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
2016-06-10T03:29:53.4840326Z    at Microsoft.DotNet.Tools.Compiler.PackCommand.Run(String[] args)
2016-06-10T03:29:53.4996547Z    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
2016-06-10T03:29:53.4996547Z    at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by Petermarcu** [comment]
Isn't this the same issue we had before with zlib?

**Comment by eerhardt** [comment]
> Isn't this the same issue we had before with zlib?

Yes, looks like the issue isn't fixed

**Comment by Petermarcu** [comment]
Can we look at the origin of the zlib native binary in the shared framework to see if its the github one or the tfs one?

**Comment by livarcocc** [comment]
This is also affecting my PR to merge the offline feature work: https://github.com/dotnet/cli/pull/3485.

**Comment by weshaggard** [comment]
Looks like the package runtime.win7-x86.runtime.native.System.IO.Compression\4.0.1-rc3-24208-00 contains clrcompression from build 23209.02 built by PROJECTKREL. So from first glance it looks like we have the expected build of clrcompression.

**Comment by weshaggard** [comment]
OK digging deeper it looks like there was some sort of package caching issue when shared framework rc3-004442-00 was created as it picked up "runtime.win7-x64.runtime.native.System.IO.Compression": "4.0.1-rc3-24208-01" which isn't what we were wanting. I pulled down shared framework version rc3-004443-00 from blob storage and it does appear to have the correct version "runtime.win7-x64.runtime.native.System.IO.Compression": "4.0.1-rc3-24208-00". The reason I think it was some package caching issue is because there was no actual code changes in core-setup between 4442 and 4443. 

I suggest that we submit an update to CLI pointing to 4443 and see if that gets us past this issue. 

FWIW I was able to repro the AccessViolationException on my local CLI build and attached the debugger which alerted me to the fact we had and different version of clrcompression in that build.

**Comment by weshaggard** [comment]
I've submit PR https://github.com/dotnet/cli/pull/3490 to update to core-setup version rc3-004443-00 in the hopes that eliminates this bad clrcompression version dependency.

**Pull request merged**
