### PR TITLE
Update msbuild to latest

### PR DESCRIPTION
**Pull request by nguerrera**
@brthor @eerhardt @livarcocc

### CODE REVIEW

**Comment by eerhardt** [comment]
```
13:08:11      1>CROSSGEN : error : Could not load file or assembly 'System.Runtime.Serialization.Xml, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) [D:\j\workspace\release_windo---4c3b899b\build.proj]
```

We've seen this episode before.  It must be a re-run.

**Comment by eerhardt** [comment]
Looks like last time this happened, we added https://github.com/dotnet/cli/pull/4083/files#diff-56ea5c107eb4ad905a6dd43116e6ee94R22

`"System.Runtime.Serialization.Xml": "4.1.0",`

@rainersigwald @jeffkl @cdmihai - what Xml do you guys reference now days?

**Comment by eerhardt** [comment]
Actually, now that MSBuild has their dependencies specified correctly, we should be able to just remove our workaround and let the dependency coming from MSBuild as is.

**Comment by eerhardt** [comment]
> Actually, now that MSBuild has their dependencies specified correctly

I think this is wrong.  I don't see any dependency on `System.Runtime.Serialization.Xml` when looking at:

https://dotnet.myget.org/feed/dotnet-buildtools/package/nuget/MSBuild
or
https://dotnet.myget.org/feed/dotnet-buildtools/package/nuget/Microsoft.Build

**Comment by rainersigwald** [comment]
@eerhardt I don't see it in our `project.json`s either . . .

**Comment by rainersigwald** [comment]
. . . but I would have if I was up to date. We're on `4.1.1`. @jeffkl that should be in our packages, right?

**Comment by eerhardt** [comment]
The assembly that fails to crossgen is `Microsoft.Build.Tasks.Core.dll`, and I don't see it listed in the dependencies on:

https://dotnet.myget.org/feed/dotnet-buildtools/package/nuget/Microsoft.Build.Tasks.Core

@nguerrera - can you try updating our hack to `4.1.1`?

**Comment by jeffkl** [comment]
Our packages are sort of in 3 places at the moment.  😢

dotnet-buildtools feed:
Version 0.1.0 is existing packages out of xplat. (these are probably still broken)
Version 15.1.X are packages from Tom's work out of master

msbuild feed:
Version 15.1.X are the packages that I've been working on which fix issues with the 0.1.0 packages, address all the issues we've encountered while spec'ing things out as well as porting the changes Tom has been making in master.

**Comment by nguerrera** [comment]
@dotnet-bot test  OSX x64 Release Build

**Pull request merged**
