### PR TITLE
Add a "repository SLA" to README.

### PR DESCRIPTION
**Pull request by peterhuene**
This commit adds a repository service-level agreement that outlines the
maintainers' commitment to community contributors for both pull requests and
issues.

Requested by @livarcocc.

### CODE REVIEW

**Comment by livarcocc** [comment]
@peterhuene Also, thanks for marking the milestone

**Comment by peterhuene** [comment]
It's obviously not word-for-word with the Roslyn SLA being discussed, but I think the intent of every paragraph of that SLA is present here.

**Comment by livarcocc** [comment]
@Pilchie FYI

**Comment by peterhuene** [comment]
I'll leave this unmerged for a few days in case others would like to review the wording; ETA to merge EOW.

**Comment by Pilchie** [comment]
LGTM

**Comment by dasMulli** [comment]
Late to the party, but:
Do you really want to use "days" or do you want to add a definition of "within X **work days**".
Or do you explicitly want to count Saturday and Sunday? (Meaning a PR on Friday has to be acted upon on Monday)

**Comment by peterhuene** [comment]
I'll amend to "business days" where appropriate.  Thanks for the feedback!

**Pull request merged**
