### PR TITLE
Fixing environment value name

### PR DESCRIPTION
**Pull request by muratg**
- DNX_HOME -> DNX_TOOLS
- Fixed the location for the Linux instructions

### CODE REVIEW

**Comment by troydai** [comment]
:shipit:

**Comment by brthor** [comment]
Where does `DOTNET_TOOLS` get used?

**Comment by muratg** [comment]
@brthor https://github.com/dotnet/cli/blob/master/scripts/install.sh#L23 

And there's no mention of DOTNET_HOME in that file.

**Comment by anurse** [comment]
It was original designed to allow a user to easily swap to a different toolchain (for internal devs, primarily). We went a different direction with Windows, so things probably got a little inconsistent.

**Comment by muratg** [comment]
If I don't set DOTNET_TOOLS, I'm not able to use dotnet CLI at all. setting DOTNET_HOME doesn't help at all.
```
Murats-MacBook-Pro% dotnet
error: the .NET tools installation appears to be corrupt!
error: specifically, the tools could not be located in the /usr/local/share/dotnet/share/dotnet/cli directory
```

**Comment by brthor** [comment]
@muratg I think the readme is targeted at a msi/pkg/deb based install rather than through the install.sh script, which is the reason for the inconsistency ( /cc @blackdwarf )

Seems like we may need to raise an issue and get this ironed out.

**Comment by muratg** [comment]
Sure, added https://github.com/dotnet/cli/issues/375 and closing this one.

**Pull request closed without merging**
