### PR TITLE
TestPlatform insertion 16.1.0 

### PR DESCRIPTION
**Pull request by vagisha-nidhi**
Release : [https://github.com/microsoft/vstest/releases/tag/v16.1.0](https://github.com/microsoft/vstest/releases/tag/v16.1.0)

### CODE REVIEW

**Comment by vagisha-nidhi** [comment]
@livarcocc Please look at this PR. Test tools insertion for 2.1.7

**Comment by ViktorHofer** [comment]
@vagisha-nidhi will this be also integrated into master so that we can use the coverlet integration with the 3.0 SDK?

**Comment by vagisha-nidhi** [comment]
> @vagisha-nidhi will this be also integrated into master so that we can use the coverlet integration with the 3.0 SDK?

@ViktorHofer 
@peterhuene and @livarcocc will be able to tell better. Will this be integrated into master?

**Comment by peterhuene** [comment]
It should flow up to master through our automatic branch merges.

**Pull request merged**
