### PR TITLE
Update Mac installer

### PR DESCRIPTION
**Pull request by wli3**
According to https://github.com/dotnet/cli/issues/6682
Window title
Update Introduction step content
Include installation location and list of all components installed
Update Summary step content

What is not included:
Remove "Welcome to ..." text -- it come from the installer tool
itself, it cannot be customized
Add 'success' graphic – cannot include picture in the html used by
the installer

Windows counterpart https://github.com/dotnet/cli/pull/6900

mac-update-installer

### CODE REVIEW

**Comment by wli3** [comment]
**Customer scenario**

User install CLI/SDK via .pkg macOS installer, the user will get better UI experience after this change.

**Bugs this fixes**

https://github.com/dotnet/cli/pull/6972

**Workarounds, if any**

N/A, No functional impact

**Risk**

User will have worse UI experience

**Performance impact**

no

**Root cause analysis**

N/A, planned

**How was the bug found?**

N/A

**Comment by wli3** [comment]
@MattGertz Could you review this change?

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by wli3** [comment]
I think i hit the same problem in core-setup. I need a dummy eula for windows

**Comment by wli3** [comment]
@dotnet-bot test OpenSUSE42.1 x64 Debug Build

**Comment by wli3** [comment]
@dotnet-bot test OpenSUSE42.1 x64 Debug Build

**Pull request merged**
