### PR TITLE
Exit the lock after a process loop

### PR DESCRIPTION
**Pull request by troydai**
Fix issue https://github.com/dotnet/cli/issues/801

### CODE REVIEW

**Comment by troydai** [comment]
Ping @davidfowl . Need to get this in ASAP.

**Comment by davidfowl** [comment]
:shipit: did we not copy from the old code?

**Comment by troydai** [comment]
Obviously missed. Merge very soon.

**Comment by livarcocc** [comment]
@troydai Did you merge with CI failing?

**Comment by anurse** [comment]
The break is unrelated, it was a failure to launch docker. This is something that has happened before and we generally check in when other builds confirm that the change is good.

**Comment by troydai** [comment]
Thanks for reminding, @livarcocc. I tried to get this in quickly since it blocks partner scenario. The PS pass on most of the build and the failure on the two Ubuntu builds doesn't indicate to be related to the change. The change itself is minimal and intuitive. It doesn't pose a significant risk to the build as far as I can see. I surely will be more patient with the build checks. Thanks.

**Pull request merged**
