### PR TITLE
Update Microsoft.Net.SDK version to 2.0.0-preview2-20170608-1.

### PR DESCRIPTION
**Pull request by livarcocc**
@dotnet/dotnet-cli 

@MattGertz Flow of dependencies into the CLI.

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by eerhardt** [comment]
@livarcocc - I updated it to include my latest 2.0 change.

**Comment by eerhardt** [comment]
The Windows tests are failing because of

https://github.com/Microsoft/vstest/issues/847

I'll try to get a fix in vstest for this.

**Comment by livarcocc** [comment]
@dotnet-bot Test this please

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE42.1 x64 Debug Build
@dotnet-bot Test Ubuntu16.10 x64 Debug Build

**Pull request merged**
