### PR TITLE
Removing debian 8 CI leg

### PR DESCRIPTION
**Pull request by sfoslund**

### CODE REVIEW

**Comment by mmitche** [comment]
I think we need more than this. The leg that is failing is https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=4392086&view=results which is just running build.sh

**Comment by mmitche** [comment]
(2.1 doesn't use .vsts-ci.yaml for the official builds)

**Comment by sfoslund** [comment]
@leecow @wli3 it looks like we'll need to remove or replace https://github.com/dotnet/cli/blob/release/2.1.5xx/build/LinuxDistrosNativeInstaller.props#L3 as well in order to get official builds working (see https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=4392086&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=e0a04e31-7f81-5a09-ed77-562f1dd354ad). Do we want to update to a newer version of debian or remove this section and stop producing .deb packages?

**Comment by wli3** [comment]
Let's directly remove it for now. These set of tests never caught anything useful in 3 years

**Comment by mmitche** [comment]
@wli3 Are you sure that won't cause us to not produce the native debian installers? The YAML file is unrelated to the official build. https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=4392086&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=e0a04e31-7f81-5a09-ed77-562f1dd354ad

**Comment by wli3** [comment]
you are right, we need that for official build

**Comment by sfoslund** [comment]
Superseded by https://github.com/dotnet/cli/pull/13679

**Pull request closed without merging**
