### PR TITLE
mark InternalAbstractions and DependencyModel Stable

### LINKED ISSUE #3465: Mark CLI stable packages as "stable"
We need to remove the -rc3 prerelease moniker for the appriopriate packages:

- ~~ProjectModel~~
- DependencyModel
- InternalAbstractions

@piotrpMSFT @ericstj @joshfree

### PR DESCRIPTION
**Pull request by brthor**
Fixes #3465 

@eerhardt @ericstj

### CODE REVIEW

**Comment by brthor** [comment]
@dotnet-bot test this please

**Comment by eerhardt** [comment]
We don't have any place that references these with "rc3" versions do we?

**Comment by eerhardt** [comment]
:shipit: pending the simple question

**Comment by eerhardt** [comment]
But let's wait to merge until we are closer to the end (and when we have approval).

**Comment by brthor** [comment]
no , I checked, everything is type project

**Pull request merged**
