### PR TITLE
Update the .xproj files to reference the "DotNet" targets and props instead of "DNX".

### PR DESCRIPTION
**Pull request by eerhardt**
IMPORTANT: With this change, anyone using VS will need to install the Visual Studio DotNetCore tools to load and work with the projects.

@livarcocc @piotrpMSFT @anurse

### CODE REVIEW

**Comment by livarcocc** [comment]
@eerhardt Just to confirm, did you manage to debug and run tests through VS after this change?

**Comment by eerhardt** [comment]
I didn't before, but I did now.  That's pretty cool!

**Comment by livarcocc** [comment]
:shipit: then.

**Comment by evorine** [comment]
Is latest Dotnet CLI (1.0.0.001806 currently) supports this change? Because I don't have any **Microsoft.DotNet.Props** file nor **DotNet** folder in my **$(VSToolsPath)** path.

**Comment by eerhardt** [comment]
@evorine - No, you need more than the Dotnet CLI to use this change. You need VS tooling that isn't public yet.  I'm reverting this change with #1899

**Comment by jamesqo** [comment]
Now that the RC2 tooling is out, should this be re-merged?

**Pull request merged**
