### PR TITLE
Update dotnet/sdk to latest from release/2.1.3xx

### PR DESCRIPTION
**Pull request by nguerrera**
Includes the fix for dotnet/sdk#2128

### CODE REVIEW

**Comment by livarcocc** [comment]
cc @mmitche

**Comment by mmitche** [comment]
@livarcocc This will have no effect on the output build...do we need to wait on it?

**Comment by nguerrera** [comment]
@mmitche We wanted to see if CI found any blocking issues before kicking off the build. But seeing as how all legs but OS X ran successfully, I think we can proceed. Let's kick off the official build now if CI isn't coming back up quickly.

**Comment by mmitche** [comment]
Will do

**Comment by nguerrera** [comment]
@mmitche I assume it's OK to merge this now, correct?

**Comment by mmitche** [comment]
Yes

**Pull request merged**
