### PR TITLE
Fix in German translation for dotnet-add-reference

### PR DESCRIPTION
**Pull request by dasMulli**
Based on a discussion in #5335 with @akoeplinger

@nguerrera is there a process yet for contributing translations?

cc @livarcocc

### CODE REVIEW

**Comment by janbaltus** [comment]
We agree with this change.

While the existing translation is linguistically correct, it has a different meaning to the suggestion (which is correct, too). If "project to project reference" could be hyphenated as an entity (i.e. "project-to-project reference"), the suggestion is correct and should replace the existing translation (I assume that this is true); otherwise, I would need more in-page context for judgment. Please keep me updated about the matter if necessary.

**Comment by nguerrera** [comment]
Thanks, @janbaltus 

> If "project to project reference" could be hyphenated as an entity (i.e. "project-to-project reference"), the suggestion is correct and should replace the existing translation (I assume that this is true)

Yes, it is true.

**Comment by nguerrera** [comment]
@livarcocc Jan from loc team has advised that we can merge this as they've made the change in their system to prevent it from being overwritten and regressed.

In the future, we should always have an issue open for translations and make sure it is tagged with 'localization'. The loc team will monitor that.

**Comment by livarcocc** [comment]
@MattGertz for approval.
cc @piotrpMSFT

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x64 Release Build please.

**Pull request merged**
