### PR TITLE
Update nunit

### PR DESCRIPTION
**Pull request by KevinRansom**

### CODE REVIEW

**Comment by peterhuene** [comment]
Looks like a few tests are failing with:

```
Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.
```

Given that this is a 2.1 insertion, I'm not sure why that's occurring.

**Comment by livarcocc** [comment]
Talked to @richaverma1 . We should take this change for 3.0. I am going to close this PR and port it to dotnet/core-sdk @ master.

**Comment by livarcocc** [comment]
Actually, @richaverma1 corrected me and mentioned we should take these for 16.2

**Comment by livarcocc** [comment]
Closing a discussed with @KevinRansom

**Pull request closed without merging**
