### PR TITLE
Argument Forwarding Changes #525

### LINKED ISSUE #525: Publish fails when the output folder passed as argument has spaces
> ddcloud@ddsridhper028:~/cli/artifacts/ubuntu.14.04-x64/stage2/bin$ ./dotnet publish /home/ddcloud/cli/test/TestProjects/TestApp -o "/home/ddcloud/dir with spaces"
Specify --help for a list of available options and commands.
Microsoft.Dnx.Runtime.Common.CommandLine.CommandParsingException: Unrecognized command or argument 'with'
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Publish.Program.Main(String[] args)

### PR DESCRIPTION
**Pull request by brthor**
Fixes #525

These changes ended up being pretty big. 
 It properly escapes arguments before passing them off to Process.Start, and special cases when using CMD.

Thanks @piotrpMSFT for the help getting in all the changes throughout the product
 and thanks @krwq for helping out with the initial product changes

cc @anurse @piotrpMSFT @livarcocc @krwq @davidfowl

### CODE REVIEW

**Comment by brthor** [comment]
@dotnet-bot test CentOS7.1 Debug Build please

**Comment by brthor** [comment]
@piotrpMSFT let's merge this?

**Comment by piotrpMSFT** [comment]
Good work, @brthor!

**Comment by NickCraver** [comment]
Just curious - how often is the `.msi` download updated? I know a lot of people who want to update their install after these fixes.

**Comment by livarcocc** [comment]
We update the dev .msi on every merge. Which is the one you can currently find in github page.

**Comment by NickCraver** [comment]
@livarcocc ah, that's awesome - thanks!

**Pull request merged**
