### PR TITLE
Update to roslyn 2.7.0-beta3-62612-07 for 2.1.1xx

### PR DESCRIPTION
**Pull request by nguerrera**
This build includes satellites built directly from the roslyn repo and so this PR also removes the messy process of getting them from cli-deps-satellites.

Version obtained from https://github.com/dotnet/versions/blob/master/build-info/dotnet/roslyn/dev15.6/Latest.txt

@livarcocc Please review

@jaredpar Please confirm this version is correct to insert for the CLI that aligns with VS 15.6

@tmeschter FYI

### CODE REVIEW

**Comment by nguerrera** [comment]
(WIP for a minute because I missed a change. Fixing.).

**Comment by nguerrera** [comment]
(Fixed)

**Comment by nguerrera** [comment]
@jasonmalinowski @jaredpar Can you confirm that Roslyn 2.7.0-beta3-62612-07 is a correct version to put in the CLI that ships with VS 15.6 (CLI 2.1.100)?

**Comment by jasonmalinowski** [comment]
@nguerrera Excellent choice. Fine vintage. :-)

**Comment by nguerrera** [comment]
@MattGertz to approve roslyn insertion in to CLI for 15.6 (+ infrastructure change to take satellites directly from the roslyn package)

**Comment by MattGertz** [comment]
So ordered.

**Pull request merged**
