### PR TITLE
Updating the version of msbuild to 15.1.0-preview-000516-03

### PR DESCRIPTION
**Pull request by livarcocc**
Fixes https://github.com/dotnet/cli/issues/5263

@piotroko @piotrpMSFT @eerhardt @jonsequitur @krwq @jgoshi

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
Migrated approved for merging label from the parent work item on behalf of @MattGertz

**Comment by livarcocc** [comment]
@dotnet-bot Test OSX x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by piotrpMSFT** [comment]
@livarcocc just chatted with @andygerlicher about this and learned that MSBuild took on a dependency for some 1.1 Native components. We won't be able to merge this PR tonight. I'm working with @andygerlicher to figure out a version of msbuild that we can use for the time being. Tomorrow, @rainersigwald will try to downgrade the dependency for Core so we can pull in a more recent package.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX x64 Release Build please.

**Comment by rainersigwald** [comment]
Just acknowledging that I’ve seen this and am working on it.
.

**Pull request merged**
