### PR TITLE
Insert NuGet Build 4.7.0-rtm.5122 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.7.0-rtm.5122 into cli release/2.1.2xx branch

### CODE REVIEW

**Comment by livarcocc** [comment]
@rohit21agrawal where is the VS PR for this? Has it been approved?

**Comment by rohit21agrawal** [comment]
@nkolev is driving this

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by livarcocc** [comment]
We will also need a matching SDK. I merged the SDK side of the changes and will update this PR with it once a build is ready there.

**Pull request merged**
