### PR TITLE
update nuget rc3 dependencies and update sdk

### PR DESCRIPTION
**Pull request by rohit21agrawal**
rc3 nuget packages were replaced by build 2188 instead of 2173 on cli-deps feed.

this PR updates the SDK version that CLI was built against and fixes a change in name of variable in nuget APIs

CC: @piotrpMSFT @livarcocc @rrelyea

### CODE REVIEW

**Comment by eerhardt** [comment]
Two things:

1. I'm already taking care of the code changes necessary to respond to the latest NuGet updates in #5258.
2. The CLI has branched for 'rc3', so we need the new SDK version in rel/1.0.0 and in rel/1.0.0-rc3 branches.

**Comment by rohit21agrawal** [comment]
ok, i'll rebase once your changes are in. should i send two separate PRs for rel/1.0.0 and rel/1.0.0-rc3?

**Comment by eerhardt** [comment]
> should i send two separate PRs for rel/1.0.0 and rel/1.0.0-rc3?

Our branching strategy is to just send the PR for `rel/1.0.0-rc3`, and then we will RI `rc3` into `rel/1.0.0`, so you shouldn't have to worry about rel/1.0.0.

@livarcocc @piotrpMSFT to confirm this is still our strategy.

**Comment by rohit21agrawal** [comment]
need to replace the SDK version in this PR with a build of SDK from the dev15-rc3 branch. waiting on https://github.com/dotnet/sdk/pull/608 for shiproom approval

**Comment by MattGertz** [comment]
@natidea

**Comment by livarcocc** [comment]
> @livarcocc @piotrpMSFT to confirm this is still our strategy.

Yes. We will RI rc3 back into rel.

**Comment by rohit21agrawal** [comment]
@eerhardt are the changes in #5258 (related to path variable name change) going to be checked into rel/1.0.0-rc3? I supsect that branch won't build until then.

**Comment by eerhardt** [comment]
> @eerhardt are the changes in #5258 (related to path variable name change) going to be checked into rel/1.0.0-rc3? I supsect that branch won't build until then.

@livarcocc has them in his PR #5250 which is fixing the "rc3" branch all up to get it off the floor.

**Pull request merged**
