### PR TITLE
Insert NuGet Build 4.9.0-preview3.5496 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.9.0-preview3.5496 into cli release/2.1.5xx branch

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build

**Comment by livarcocc** [comment]
@nkolev92 @rohit21agrawal is this merged in VS?

**Comment by nkolev92** [comment]
No, not yet. 

https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/141214

//cc @rrelyea

**Comment by rrelyea** [comment]
@livarcocc
We've just merged the matching NuGet bits into VS 15.9 preview 3.
Can you please review and insert as appropriate?
VS Insertion PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/141214
lab/d15.9stg

**Pull request merged**
