### PR TITLE
test ci in preview4 branch

### PR DESCRIPTION
**Pull request by enricosada**
test ci with empty commit

current CI fails in `preview4` /cc @livarcocc @piotrpMSFT

### CODE REVIEW

**Comment by enricosada** [comment]
ok i added a commit to try to fix test failure. 
the msbuild prop used is the same used in Sdk target, so should be ok /cc @livarcocc

**Comment by livarcocc** [comment]
@enricosada I am not sure I follow what is going on here.

What is this change that you are making? Preview4 has everything that rel has. Why isn't this happening in rel/1.0.0 as well?

**Comment by enricosada** [comment]
Dunno. I have the same test failures in my other PR so open ed this one to check why and maybe fix it. Maybe are just flacky but is reproducible

As a note, locally working in preview4 branch i see preview5 downloaded at beginnng. Maybe is that? Dunno. 
I had no time to investigate

**Comment by livarcocc** [comment]
I have a fix under test for this issue right now. Closing this PR.

**Pull request closed without merging**
