### PR TITLE
Update msbuild to latest

### PR DESCRIPTION
**Pull request by nguerrera**
@eerhardt

### CODE REVIEW

**Comment by eerhardt** [comment]
:shipit:

**Comment by eerhardt** [comment]
Closing and reopening to try to get jenkins running.

**Comment by eerhardt** [comment]
@mmitche - is Jenkins really backed up?

**Comment by mmitche** [comment]
@eerhardt Appears something is going on with inability to delete old machines.  I'm checking into it

**Comment by eerhardt** [comment]
We need this change to unblock folks, and Jenkins is busted right now.  Merging.

**Pull request merged**
