### PR TITLE
Default to C# project type guid

### LINKED ISSUE #5688: dotnet sln add uses wrong project type GUID
Projects added to a sln file using `dotnet sln add` use the wrong GUID, which means VS doesn't correctly load things like the project properties page.

## Steps to reproduce
dotnet new sln
dotnet new classlib -o SampleProj
dotnet sln add SampleProj/SampleProj.csproj

## Expected  behavior
Solution file contains
```
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "SampleProj", "SampleProj\SampleProj.csproj", "{9195DDF0-49EA-45F6-9527-7F7DFCA02BCB}"
EndProject
```

## Actual behavior
```
Project("{13B669BE-BB05-4DDF-9536-439F39A36129}") = "SampleProj", "SampleProj\SampleProj.csproj", "{9195DDF0-49EA-45F6-9527-7F7DFCA02BCB}"
EndProject
```

## Environment data
`dotnet --info` output: 1.0.0-rc4-004771

### PR DESCRIPTION
**Pull request by jgoshi**
Fixes #5688 

@piotrpMSFT @livarcocc @krwq @jonsequitur @eerhardt 

The work to have the DefaultProjectTypeGuid isn't available yet. Here is the PR:
https://github.com/Microsoft/msbuild/pull/1607

And work also has to be done for F#. What we will eventually do in the CLI is to throw if there isn't an explicit ProjectTypeGuid or a DefaultProjectTypeGuid defined. But until the work for writing DefaultProjectTypeGuid goes in we need to burn in some default. This work changes the default to be the C# one. We will still be wrong in other cases (like for a VB project or F# project or any other type of project). But at least default to C# rather than CPS.

### CODE REVIEW

**Comment by livarcocc** [comment]
@srivatsn @dsplaisted

**Comment by piotrpMSFT** [comment]
@nguerrera @dsplaisted @srivatsn can one of you review & approve?

**Comment by piotrpMSFT** [comment]
@dsplaisted this change only covers the `dotnet sln add` scenario. Migration will be covered by #5665

**Comment by livarcocc** [comment]
No, migration actually shares this code. This will fix the migration issue as well. But the migration tests don't check that GUID explicitly. We rely on the sln add tests for that.

@jgoshi can correct me if I am wrong.

**Comment by jgoshi** [comment]
@livarcocc is correct. Whenever migration needs to add a project to the sln file it calls dotnet sln add.

**Comment by jgoshi** [comment]
I also manually tried the scenario specified by 
https://github.com/dotnet/cli/issues/5665

And this fixes it.

**Pull request merged**
