### PR TITLE
Update to aspnetcore 2.1.0-preview1-28275 and react to feed layout changes

### PR DESCRIPTION
**Pull request by natemcmaster**
React to https://github.com/aspnet/Universe/pull/886.

Aspnetcore is changing the layout of files on the dotnetcli feed to be in its own subfolder. See https://github.com/aspnet/Universe/issues/878 for more context.

Changes:
 - Update to aspnetcore 2.1.0-preview1-28275
 - Update dotnet-install.ps1/sh to use the new feed layout
 - Update to use Microsoft.AspNetCore.App instead of .All as the default aspnetcore runtime

cc @leecow @eerhardt

### CODE REVIEW

**Comment by johnbeisner** [comment]
@natemcmaster
Since there is only one approved version of the install scripts [dotnet-install.ps1; dotnet-install.sh] for all releases/versions/channels, and I am assuming that this PR represents the changes for aspnet going forward, all aspnetcore runtime assets that do not match the newer URL convention are now no longer supported.

**Comment by natemcmaster** [comment]
Yes, that's correct. We want to get this layout change in now before we make the 2.1.300-preview1 release so we don't have to support the old url format. URL format should be "$azurefeed/aspnetcore/Runtime/", not "$azurefeed/Runtime" going forward.

**Comment by johnbeisner** [comment]
@natemcmaster 
Microsoft.DotNet.Web.ItemTemplates 2.1.0-preview1-28275 doesn't seem to be published at: https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json; however 2.1.0-preview1-28272 is published.

**Comment by natemcmaster** [comment]
I updated the aspnetcore-release feed to ensure 2.1.0-preview1-28275 is there.

@dotnet-bot test please

**Comment by natemcmaster** [comment]
Hmm, that didn't trigger.

@dotnet-bot test this please

**Comment by pranavkm** [comment]
:shipit:

**Comment by natemcmaster** [comment]
@johnbeisner PR validation passed now. Okay to merge?

**Comment by johnbeisner** [comment]
@natemcmaster 
Do you need us to merge this?

**Comment by natemcmaster** [comment]
Yes. I don't have permissions.

Also, should I make a PR to update dotnet-install.ps1/sh on other branches? Is release/2.0.0 still the "official" copy of these scripts?

**Comment by johnbeisner** [comment]
@natemcmaster
"should I make a PR to update dotnet-install.ps1/sh on other branches" - I'll take care of this - thanks for the offer.

**Pull request merged**
