### PR TITLE
Insert NuGet Build 4.6.0-rtm-4880 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.6.0-rtm-4880 into cli release/2.1.1xx branch

### CODE REVIEW

**Comment by livarcocc** [comment]
@rohit21agrawal has this been approved and inserted into VS? Can we get a link to the VS Insertion PR?

**Comment by rohit21agrawal** [comment]
not yet, the PR is here: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/104215

**Comment by livarcocc** [comment]
I see this still hasn't been merged in VS.

**Comment by rohit21agrawal** [comment]
@livarcocc it just got merged

**Pull request merged**
