### PR TITLE
3.1.3xx Branding Update

### PR DESCRIPTION
**Pull request by sfoslund**

### CODE REVIEW

**Comment by sfoslund** [comment]
@wtgodbe are we missing a feed here? We're also seeing similar errors in the other 3.1.3xx merges: dotnet/sdk#11977, dotnet/installer#7766, dotnet/toolset#4604

**Comment by wtgodbe** [comment]
@sfoslund we hadn't pushed the nonshipping 3.1.5 packages to the transport feed yet at the time you created this PR. The packages are pushed now, so the rebuild should (hopefully) work

**Comment by wtgodbe** [comment]
> ##[error]/opt/code/build/sdks/sdks.csproj(0,0): error NU1603: sdks depends on Microsoft.NET.Build.Extensions (>= 3.1.301-servicing.20302.9) but Microsoft.NET.Build.Extensions 3.1.301-servicing.20302.9 was not found. An approximate best match of Microsoft.NET.Build.Extensions 3.1.400-preview.20251.5 was resolved.

That's a newer version than the one we actually produced in 3.1.301. Looking into it

**Review by wtgodbe — CHANGES_REQUESTED** [review]
Please back out 7ea6b46890eee36565bcca739c1384c2ef5d2384

**Review by wtgodbe — APPROVED** [review]

**Review by wli3 — APPROVED** [review]

**Pull request merged**
