### PR TITLE
Update launch settings for ApplicationUrl handling

### PR DESCRIPTION
**Pull request by mlorbetske**
Per @danroth27, if the user sets the environment variable in a launch profile for ASPNETCORE_URLS, it should override the value of ApplicationUrl. Added tests to check that behavior & verify that ApplicationUrl is being applied in general.

### CODE REVIEW

**Comment by mlorbetske** [comment]
@dotnet-bot test Windows_NT x64 Release Build please
@dotnet-bot test Windows_NT x86 Debug Build please
@dotnet-bot test Windows_NT_ES x64 Debug Build please

**Comment by livarcocc** [comment]
@mlorbetske the failures seem to be legit on windows: the test that is failing is AppWithApplicationUrlInLaunchSettings.

**Comment by mlorbetske** [comment]
@livarcocc it's strange, the error indicates that the runtimeconfig is not valid. I've removed the RIDs from the project file - hopefully that takes care of it

**Comment by livarcocc** [comment]
@mlorbetske apparently... it did not.

**Comment by mlorbetske** [comment]
I think i see, looks like it might be a MAX_PATH thing. Will try a shorter test project name.

**Comment by livarcocc** [comment]
@MattGertz TELL

**Pull request merged**
