### PR TITLE
Add telemetry data points for .NET Core 2.0

### PR DESCRIPTION
**Pull request by wli3**
https://github.com/dotnet/cli/issues/7283

### CODE REVIEW

**Comment by livarcocc** [comment]
@wli3 we are going to need the ask mode template filled up here.

**Comment by wli3** [comment]
**Customer scenario**

Please reference issue https://github.com/dotnet/cli/issues/7283

**Bugs this fixes**

https://github.com/dotnet/cli/issues/7283

**Workarounds, if any**

N/A

**Risk**

Low

**Performance impact**

Low

**Root cause analysis**

N/A

**How was the bug found?**

N/A, feature

@MattGertz for approval

**Comment by livarcocc** [comment]
@wli3 are you fully rebased with release/2.0.0, these are tests that were failing in my PR but I had them fixed there.

**Comment by livarcocc** [comment]
@wli3, never mind. The assumption that the folder does not exist is now false, because you are putting the cache files there. We need to update the test to instead of checking that the folder does not exist, to check that the .dotnetFirstTimeUseSentinel file does not exist under that folder.

**Comment by wli3** [comment]
@livarcocc  
> .dotnetFirstTimeUseSentinel i find that later, fixed

**Comment by MichaelSimons** [comment]
@wli3, the Windows Container Runtime team asked the following of the code used to determine if running within a Windows Container - “Please only use this for telemetry purposes – do not change product behavior inside containers based on this key. I would appreciate it if you would add a comment to that effect in your code so that others that might copy and paste this code follow the same policy.”  I had sent this comment to @livarcocc at the time I shared the implementation.

**Pull request merged**
