### PR TITLE
Insert NuGet Build 4.7.0-preview1.4982 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.7.0-preview1.4982 into cli release/2.1.2xx branch

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
@livarcocc not sure how the pack target is missing here. We did change the version format of the package, could it be something to do with that?

**Comment by livarcocc** [comment]
@rohit21agrawal it must be, since nothing else has changed. Could you please investigate?

**Comment by rohit21agrawal** [comment]
@livarcocc i investigated as much as i could, but i might need some help given my limited knowledge of the CLI build system. I did verify that the package is available at the nuget-build feed.

Could someone help me dig more?

**Comment by rohit21agrawal** [comment]
nvm, i think the source is missing. will add it.

**Comment by rohit21agrawal** [comment]
@livarcocc this is now failing with the error:

```
error : The feed 'cli-deps [https://dotnet.myget.org/F/cli-deps/api/v3/index.json]' lists package 'System.Xml.ReaderWriter.4.3.0' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. [D:\j\workspace\debug_windows---6b893138\test\dotnet-new.Tests\bin\Debug\netcoreapp2.0\RestoreDoesNotUseAnyCliProducedPackagesOnItsTemplates\temp\mstest1\mstest1.csproj] [D:\j\workspace\debug_windows---6b893138\build\test\RunTest.proj]
```

Any chance someone can take a quick look?

**Comment by livarcocc** [comment]
CLI deps is not needed anymore. I will remove it.

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by livarcocc** [comment]
@MattGertz FYI.

@rohit21agrawal has this been merged into VS already?

**Comment by rohit21agrawal** [comment]
yes, https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/109913?_a=overview

**Pull request merged**
