### PR TITLE
fix reg key in cli msi

### PR DESCRIPTION
**Pull request by brthor**
Partially fixes https://github.com/dotnet/core-setup/issues/40

Need to investigate sharedframework bundles for a full fix

cc @ericstj @jhendrixMSFT

### CODE REVIEW

**Comment by brthor** [comment]
@dotnet-bot test OpenSUSE13.2 x64 Debug Build please
@dotnet-bot test Ubuntu16.04 x64 Debug Build please

**Comment by ericstj** [comment]
LGTM.  What's the keypath here: registry value?

**Comment by Petermarcu** [comment]
@dotnet-bot test OpenSUSE13.2 x64 Debug please

**Comment by Petermarcu** [comment]
@dotnet-bot test OpenSUSE13.2 x64 Debug please

**Comment by eerhardt** [comment]
Merging with approval from @Petermarcu.  The test failure in OpenSUSE is a flaky dotnet-build.test.

**Pull request merged**
