### PR TITLE
Add nuget content files support

### PR DESCRIPTION
**Pull request by pakrym**
Retarget of https://github.com/dotnet/cli/pull/879

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@pakrym  please rebase this on rel/1.0.0 and resubmit

**Comment by pakrym** [comment]
its to rel

**Comment by piotrpMSFT** [comment]
@pakrym yea, but not rebased. Conflicts.

**Comment by pakrym** [comment]
Its in progress and needs more design. So i'll just leave it hanging.

**Comment by piotrpMSFT** [comment]
please reopen when ready

**Pull request closed without merging**
