### PR TITLE
Localize changes for dotnet-remove

### PR DESCRIPTION
**Pull request by vsccarl**

### CODE REVIEW

**Comment by vsccarl** [comment]
This was written after we started localizing and has references to a non-existent LocalizableStrings, such as LocalizableStrings.RequiredArgumentNotPassed. I'm not sure what the text is for these strings or why there are references to the LocalizableStrings file that I hadn't made yet.

**Comment by piotrpMSFT** [comment]
@MattGertz can you pre-approve this change so we can merge as soon as it is green?

**Comment by piotrpMSFT** [comment]
@vsccarl this PR is failing with `error CS0117: 'LocalizableStrings' does not contain a definition for 'RequiredArgumentNotPassed'`. Can you address?

**Comment by MattGertz** [comment]
Approved pending tests passing.

**Comment by piotrpMSFT** [comment]
rebased atop #4917

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Pull request merged**
