### PR TITLE
Add new badge for linux_x64

### PR DESCRIPTION
**Pull request by jgoshi**
@eerhardt @livarcocc @krwq

### CODE REVIEW

**Comment by jgoshi** [comment]
test ci please

**Comment by jgoshi** [comment]
Note that I know why the generator_prtest failed. See this PR for the fix:
https://github.com/dotnet/cli/pull/5969

**Comment by eerhardt** [comment]
test Ubuntu x64 Release Build

**Comment by jgoshi** [comment]
test Ubuntu16.04 x64 Release Build

**Comment by jgoshi** [comment]
I'm going to merge this because one of the errors (generator_prtest) was an issue with netci.groovy which has been fixed. The other one is actually the Linux-x64 build (which was just enabled). I need to investigate that failure separately.

**Pull request merged**
