### PR TITLE
Update the 1.x templates for aspnetcore 1.0.7/1.1.4

### PR DESCRIPTION
**Pull request by natemcmaster**
Update the aspnetcore templates for 1.x. Includes this change: https://github.com/aspnet/templating/pull/65

### CODE REVIEW

**Comment by livarcocc** [comment]
@mlorbetske is there anything else that needs to be updated here? Just looking for confirmation.

**Comment by mlorbetske** [comment]
I thought there were issues with referencing the CI dev feed, @eilon?

**Comment by natemcmaster** [comment]
Good point. We should probably use aspnetcore-dev instead. aspnetcore-ci-dev has unsigned packages, aspnetcore-dev has signed. Although there is nothing to sign in the templates package, we should the possibility of a an unsigned runtime package getting picked up.

**Comment by natemcmaster** [comment]
Moved to email thread.

**Pull request closed without merging**
