### PR TITLE
SDK 1.1.1-svc-20190221-1

### PR DESCRIPTION
**Pull request by livarcocc**
@peterhuene once this gets merged you should be good to merge cli into the closed source and build with the runtime.

### CODE REVIEW

**Comment by peterhuene** [comment]
Looks like CI is failing with the SDK can't be found.

**Comment by peterhuene** [comment]
Looks like the build skipped pushing to the feed: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2431849

**Comment by livarcocc** [comment]
weird, we must have a wrong condition there.

**Comment by livarcocc** [comment]
I think I fixed the build def and added a new SDK here. 🤞

**Comment by peterhuene** [comment]
:shipit:

**Pull request merged**
