### PR TITLE
Enable VB for dotnet cli 1.1

### PR DESCRIPTION
**Pull request by KevinRansom**
Enable VB in dotnet cli 1.1.0

@livarcocc @nguerrera @srivatsn @AnthonyDGreen

### CODE REVIEW

**Comment by nguerrera** [comment]
Fill out template and tag Matt.

**Comment by KevinRansom** [comment]
Tagging @MattGertz for approval pending CI tests.
Customer scenario: VS ships with the V1.1 sdk and dotnet CLI without this change netstandard libraries and apps will not be editable in VS.
Workarounds, if any: None.
Risk:: Low
Performance impact : None only enabled for .fsproj
Is this a regression from a previous update?:, dotnet core support hasn't been provided in the past.
Root cause analysis : Not yet implemented
How was this bug found?: : Not yet implemented

**Comment by nguerrera** [comment]
> Performance impact : None only enabled for .fsproj

.vbproj, right?

**Comment by KevinRansom** [comment]
@nguerrera yup.

**Pull request merged**
