### PR TITLE
Insert NuGet Build 4.8.0-rtm.5348 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.8.0-rtm.5348 into cli release/2.1.4xx branch

### CODE REVIEW

**Comment by nguerrera** [comment]
@nkolev92 @dsplaisted @rohit21agrawal Approved to go into VS?

**Comment by rohit21agrawal** [comment]
VS PR : https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/133125 , still working on getting approval

**Comment by rohit21agrawal** [comment]
@nguerrera VS insertion is complete

**Comment by nguerrera** [comment]
@Pilchie FYI

**Comment by nguerrera** [comment]
@mmitche FYI as well. This will flow to release/2.1.401, but has to do two hops back and forth to sdk first. Exactly what I was talking about in shiproom: we can't assume no more 2.1.401 changes while 15.8 tooling changes are still being approved.

**Pull request merged**
