### PR TITLE
Port stage0 change

### PR DESCRIPTION
**Pull request by eerhardt**
Porting #5442 from master into rel/1.0.0.

### CODE REVIEW

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Comment by eerhardt** [comment]
@piotrpMSFT - can someone look at why this is failing?

**Comment by eerhardt** [comment]
Test Windows_NT x86 Debug Build

**Comment by eerhardt** [comment]
test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@MattGertz This is an infra-structure change only.

**Comment by livarcocc** [comment]
@MattGertz Merged this as this was infra-only.

**Pull request merged**
