### PR TITLE
Update rel/1.0.0 README with master's format

### PR DESCRIPTION
**Pull request by eerhardt**
Update the daily build table to be more maintainable and remove the links to runtime installers.

Adding link to Ubuntu 16.04 deb installer.

@livarcocc @piotrpMSFT @blackdwarf

### CODE REVIEW

**Comment by blackdwarf** [comment]
LGTM

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Comment by piotrpMSFT** [comment]
@MattGertz FYI, merging cleanup to CLI Repo's Readme.md

**Pull request merged**
