### PR TITLE
Improve MSI performance

### PR DESCRIPTION
**Pull request by robmen**
A few small changes for some pretty nice wins:

1. Package size reduced 17% (46.8 MB reduction to 38.8 MB)
2. Install time reduced 20% (2 seconds, on my machine)
3. Removed last custom action (except for WiX standard custom actions)
4. Repair/uninstall will always work now

### CODE REVIEW

**Comment by Sridhar-MS** [comment]
@robmen Can you un-comment [this](https://github.com/dotnet/cli/blob/rel/1.0.0/packaging/windows/testmsi.ps1#L50-L65) and rerun the build? We do not have a proper way of testing the MSIs and it is partially manual at this point.

**Comment by robmen** [comment]
@Sridhar-MS Sorry, do you want me to uncomment that and commit it to my pull request? Or do you just want me to run those tests locally?

**Comment by Sridhar-MS** [comment]
@robmen Just run these tests locally. Meanwhile I am trying to figure out a way to enable these tests in CI. But thats still some way out.

**Comment by robmen** [comment]
@Sridhar-MS Is there some way to run the tests without having to run `.\build.cmd` again and wait forever? I was sorta' able to run just the scripts in `packaging\windows` but have not found it at all easy to iterate on the MSI. Hope I'm missing something...

**Comment by brthor** [comment]
@robmen If you've already done a successful build (build.cmd), the steps below may work:

```
(from repo root)
.\scripts\use-dev.ps1
.\scripts\package\package.ps1
```

It'll do a couple other things but should help you iterate quickly.

**Comment by Sridhar-MS** [comment]
After running `build.cmd` once, you start iterating MSI generation and testing by running

`generatemsi.ps1 <repo path>\artifacts\win7-x64\stage2`

generatemsi.ps1 is at https://github.com/dotnet/cli/blob/rel/1.0.0/packaging/windows/generatemsi.ps1

**Comment by Sridhar-MS** [comment]
I would recommend using @brthor's suggestion.

**Comment by robmen** [comment]
Here is output:

    [msi-perf = +0 ~1 -1 !] ! . "$env:USERPROFILE\.dnx\packages\xunit.runner.console\2.1.0\tools\xunit.console.exe" E:\src\dotnetcli\artifacts\tests\Dotnet.Cli.Msi.Tests\Debug\net46\Dotnet.Cli.Msi.Tests.exe
    xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
      Discovering: Dotnet.Cli.Msi.Tests
      Discovered:  Dotnet.Cli.Msi.Tests
      Starting:    Dotnet.Cli.Msi.Tests
      Finished:    Dotnet.Cli.Msi.Tests
    === TEST EXECUTION SUMMARY ===
       Dotnet.Cli.Msi.Tests  Total: 8, Errors: 0, Failed: 0, Skipped: 0, Time: 105.604s

PS: Build scripts could be much easier to run and better documented if you want others to be successful. I had to run the test commands by hand, since it seems the publish command output has changed and the `testmsi.ps1` fails. Does it work for you?

Anyway, looks like it passed. Good to go?

**Comment by Sridhar-MS** [comment]
LGTM. There is definitely lot of room for improvement in MSI testing. I have created https://github.com/dotnet/cli/issues/1092 to track this.

**Comment by Sridhar-MS** [comment]
@dotnet-bot test OSX Debug Build please

**Comment by robmen** [comment]
@piotrpMSFT or @Sridhar-MS if this is good to go, can you accept this pull? I'd like to get the bundle PR in and it'd be best to build on this change.

PS: Sorry if I'm getting ahead of you guys. I'm unclear of your release schedule and want to try to get everything in before the door shuts. :smile_cat:

**Pull request merged**
