### PR TITLE
Updating the websdk to 2.0.0-rel-20170815-630

### PR DESCRIPTION
**Pull request by vijayrkn**
Bug Fix : https://github.com/Azure/app-service-announcements/issues/24 

Package location: https://dotnet.myget.org/feed/dotnet-web/package/nuget/Microsoft.NET.Sdk.Publish/2.0.0-rel-20170815-630

@mlorbetske @livarcocc

### CODE REVIEW

**Comment by mlorbetske** [comment]
@dotnet-bot test Linux x64 Release Build please
@dotnet-bot test Ubuntu16.10 x64 Debug Build please

**Comment by nguerrera** [comment]
@leecow @vijayrkn @mlorbetske Has this been approved for 2.0.1?

**Comment by leecow** [comment]
Approved

**Comment by nguerrera** [comment]
@MattGertz FYI. Approved dependency flow for 2.0.1

**Pull request merged**
