### PR TITLE
Fix installer branding dotnet --> .NET

### PR DESCRIPTION
**Pull request by piotrpMSFT**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/1891)

### CODE REVIEW

**Comment by livarcocc** [comment]
:shipit:

**Comment by Sridhar-MS** [comment]
:shipit:

**Comment by akoeplinger** [comment]
nit: you missed a few pixels of @dotnet-bot in the logo :smile: 

image

**Comment by piotrpMSFT** [comment]
@akoeplinger you found the easter egg!

**Comment by blackdwarf** [comment]
@piotrpMSFT for the logo, where did you get this one? We need to check if this is the one we can/should use.

**Comment by blackdwarf** [comment]
@piotrpMSFT confirmed, this is the one we should use. Go ahead. :)

**Comment by brthor** [comment]
@akoeplinger I kind of like it :smile:

**Comment by piotrpMSFT** [comment]
@dotnet-bot test this please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test this please.

**Comment by piotrpMSFT** [comment]
@mmitche any idea why this change hasn't been picked up by DNB yet...? it's only been 18 hours...

**Comment by mmitche** [comment]
Probably because of the restarts last night.  I'm not quite sure why it doens't pick up test this please after sometimes.  When you see this you can close and reopen the PR (same PR) and it will reinit

**Comment by brthor** [comment]
:shipit:

**Pull request merged**
