### PR TITLE
prepare dotnet-new for f# in preview2

### PR DESCRIPTION
**Pull request by enricosada**
ref #3612

Add f# library template for `dotnet new`

atm f# has issue with preview2 ( ref dotnet/netcorecli-fsc#12 ) , so template dont restore/build, but should be ok.

i tried to use same template with working `preview1` sdk using `netstandard1.5` ( 1.5.0-rc2-24027 ) and works ok.

I'll update it **for sure** after the bug is fixed, if doenst work /cc @blackdwarf

### CODE REVIEW

**Comment by eerhardt** [comment]
@enricosada - `preview2` is in escrow right now, and we will need approval to get any more changes in.

@Petermarcu @piotrpMSFT @blackdwarf

**Comment by enricosada** [comment]
@brthor @blackdwarf i fixed dotnet new templates, to avoid [the same mistakes of preview1](https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-preview1#notes) about dev feed/package version so users get a good OOTB experience. 
/cc @cartermp @KevinRansom @dsyme @jaredpar 

`dotnet new` it's really important as first entry for new users (or as reference), and f# community it's starting to use .net core.

@KevinRansom and visualfsharp team will publish fsharp.core/compiler as prerelease on nuget, I'll publish `dotnet-compile-fsc` built from https://github.com/dotnet/netcorecli-fsc (waiting for compiler fix, compile-fsc is ready), so should work when `preview2` it's released, or a bit later (but at least we can fix it for sure, because version range/feeds are ok).

I tried it locally the restore/build, should work right, package are restored (tried with `-f`), build just need fixed compiler deps.
Tried also to downgrade deps and work (run/build) with preview1 (just to be sure :smile:)

- removed nuget.config dev feeds (`dotnet-compile-fsc`, `fsharp.core.netcore`, `fsharp.compielrs.netcore` package are going to be published on nuget.org). dev feeds create risk of pulling wrong deps (rc2, rc3), and it's another stuff to explain for new users.
- generate portable pdb by default. if there are critical problem, i'll disable them in `compile-fsc`
- fixed version ranges for `fsharp.core.netcore` package, use latest released on nuget version (so can be fixed if needed).

**Comment by piotrpMSFT** [comment]
We took a bunch of `dotnet new` updates to our shiproom and it was decided that we will not be mergingany of them for preview2. Can we get this merged into rel/1.0.0 ASAP so it makes it onto the next release train?

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX x64 Release Build please.

**Comment by piotrpMSFT** [comment]
oi, just noticed this is still targetting preview2 branch which is locked now. Please rebase on rel/1.0.0. Closing PR so it doesn't get accidentally merged.

**Pull request closed without merging**
