### PR TITLE
Stop casting a unresolved LibraryDescription to avoid cast exception.

### PR DESCRIPTION
**Pull request by troydai**

### CODE REVIEW

**Comment by davidfowl** [comment]
@dotnet-bot test Windows_NT Debug please

**Comment by davidfowl** [comment]
@dotnet-bot test Windows please

**Comment by troydai** [comment]
@dotnet-bot test Windows_NT Debug Build

**Comment by troydai** [comment]
And @dotnet-bot be consistent please.

**Comment by troydai** [comment]
@dotnet-bot test OSX Debug Build please

**Comment by troydai** [comment]
@davidfowl ship it?

**Comment by davidfowl** [comment]
:shipit: yes and please add a test

**Comment by troydai** [comment]
Test the on the way. I'll merge this first since it blocks partners.

**Pull request merged**
