### PR TITLE
Update non-web templates to version 1.0.0-beta3-20171110-312

### PR DESCRIPTION
**Pull request by mlorbetske**
cc @singhsarab

### CODE REVIEW

**Comment by livarcocc** [comment]
thanks @mlorbetske

**Comment by seancpeters** [comment]
my local build, content creation, & smoke test run on generated templates looks good.

**Comment by seancpeters** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please

**Comment by seancpeters** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please

**Pull request merged**
