### PR TITLE
TestPlatform insertion 16.0-preview-20190124-02

### PR DESCRIPTION
**Pull request by mayankbansal018**
Testplatform insertion Rel Notes: https://github.com/Microsoft/vstest-docs/blob/master/docs/releases.md#1600-preview-20190124-02

### CODE REVIEW

**Comment by mayankbansal018** [comment]
@livarcocc , can you please complete the PR

**Comment by mayankbansal018** [comment]
@dotnet-bot test Linux_NoSuffix x64 Release please

**Comment by mayankbansal018** [comment]
@dotnet-bot test Linux_NoSuffix x64 Release Build please

**Comment by adamralph** [comment]
What is `2.1.6xxx`? RTM is already `2.2.104`, no?

**Comment by Pilchie** [comment]
Both 2.1.5xx and 2.2.1xx are in support right now, and 2.1 is the Long Term Servicing branch, so we are still updating it.

**Comment by Pilchie** [comment]
The "2.1.6xx" line and the "2.2.2xx" line will be the SDKs for the 2.1 and 2.2 runtimes VS 2019 version 16.0 respectively.

**Comment by adamralph** [comment]
Thanks for the info @Pilchie.

Following the breadcrumbs back to https://github.com/Microsoft/vstest/pull/1882#issuecomment-466316478 and cross referencing the PR's, commits, and tags, I _think_ this mean I should expect both https://github.com/Microsoft/vstest/issues/1866 and https://github.com/Microsoft/vstest/pull/1882 to be released in SDK's 2.1.600 and 2.2.200.

**Comment by Pilchie** [comment]
That seems right to me. @nguerrera can you check whether those would have been in the SDKs that came with VS2019 Preview 3?

**Pull request merged**
