### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by Faizan2304**
Bug fixes:
https://github.com/Microsoft/vstest/issues/192
https://github.com/Microsoft/vstest/issues/226
https://github.com/Microsoft/vstest/issues/213
https://github.com/Microsoft/vstest/issues/190
https://github.com/Microsoft/vstest/issues/231
https://github.com/Microsoft/vstest/issues/241

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
Wonderful! We have a build break we need to resolve, but I can't wait to merge this!

@MattGertz It'd be great to get your approval preemptively!

**Comment by livarcocc** [comment]
@dotnet-bot Test this please

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by livarcocc** [comment]
@MattGertz and @srivatsn for approval.

**Comment by livarcocc** [comment]
@MattGertz and @srivatsn for approval.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu x64 Release Build  please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Fedora23 x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
can't wait to click `merge`... :)

**Comment by Faizan2304** [comment]
@piotrpMSFT: Now you can merge..  :)

**Comment by piotrpMSFT** [comment]
🎉

**Pull request merged**
