### PR TITLE
WIP Do not use GetCurrentDirectory in test

### PR DESCRIPTION
**Pull request by wli3**

### CODE REVIEW

**Comment by peterhuene** [comment]
Looks like the Windows ones failed do to the mock filesystem issue I mentioned in the corefx issue; something with using a TempRoot is probably breaking the "fake" directory enumeration in the mock filesystem (it's pretty fragile; something like not normalizing the path is probably the culprit).

The other failures look transiet.

@dotnet-bot test this please

**Comment by wli3** [comment]
As i stated before, tests do not use fake file system

**Comment by wli3** [comment]
Maybe it is my memory. I remember these tests are not using in memory file system. But seems it does today

**Comment by peterhuene** [comment]
I changed the implementation as part of the uninstall command work since the mock objects were already taking an `IFileSystem`; the whole point of using this interface is to allow the file system interaction to be mocked.  If we don't intend to use a mock file system, then I see even less of a point for the existence of the tool package mocks.

**Comment by wli3** [comment]
I see, it should not be corefx's problem then

**Comment by peterhuene** [comment]
I apologize for not making that change clear to you when we were discussing this with corefx and it was easy to miss during the major refactoring for the uninstall implementation.  That's my fault.

**Pull request closed without merging**
