### PR TITLE
Point to 2.1.300-preview1 in README

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
@livarcocc I'm not seeing the badges render. Is that because I did the change wrong or have there not been 2.1.300 preview1 builds?

**Comment by johnbeisner** [comment]
@nguerrera 
there not been 2.1.300 preview1 builds - therefore some of the badges will not render

**Comment by livarcocc** [comment]
There have not been builds, like @johnbeisner is indicating. Plus, @mmitche asked us to not add triggers for this branch. He wants all the builds here to come out of prod-con.

**Comment by nguerrera** [comment]
cc  @mikeharder

**Comment by livarcocc** [comment]
This went in on https://github.com/dotnet/cli/pull/8628.

**Pull request closed without merging**
