### PR TITLE
Fix projectmodel-server regression

### PR DESCRIPTION
**Pull request by troydai**
1. Address the null reference exception when a project dependency is
broken.
2. Address the duplicate key issues after the logic of redirecting
System pacage to reference assembly was added
3. Include projectmodel-server test in the build script

Issue: https://github.com/dotnet/cli/issues/1098

### CODE REVIEW

**Comment by troydai** [comment]
Hi @Sridhar-MS, the CI keep failing to restore packages. Are there networking issues with them?

**Comment by Sridhar-MS** [comment]
@brthor recently had a fix/workaround for this.

**Comment by brthor** [comment]
@troydai adding `--disable-parallel` to all restore calls seems to fix the issue on ubuntul.

If you rebase on rel, the fix is checked in.

**Comment by troydai** [comment]
Moves to https://github.com/dotnet/cli/pull/1173 on `rel/1.0.0`

**Pull request closed without merging**
