### PR TITLE
Update Roslyn to 1.3.0-beta1-20160525-03

### PR DESCRIPTION
**Pull request by eerhardt**
@gkhanna79 @jaredpar

### CODE REVIEW

**Comment by gkhanna79** [comment]
@jaredpar @tmat Can you please confirm the version number of the package is correct?

**Comment by jaredpar** [comment]
👍

**Comment by eerhardt** [comment]
test CentOS7.1 x64 Debug Build
test Debian8.2 x64 Debug Build
test RHEL7.2 x64 Release Build


http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0/job/debug_centos7.1_x64_prtest/2074/
http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0/job/debug_debian8.2_x64_prtest/922/
http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0/job/release_rhel7.2_x64_prtest/2074/

Two kinds of errors:
```
MESSAGE:
Expected command to exit with 100 but it did not. File Name: /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/release_rhel7.2_x64_prtest/test/dotnet-publish.Tests/bin/Release/netcoreapp1.0/PublishOptionsTest1/TestAppWithLibrary/TestApp/bin/Debug/netcoreapp1.0/rhel.7.2-x64/publish/TestApp Arguments: Exit Code: 134 StdOut: StdErr:
+++++++++++++++++++
STACK TRACE:
at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) at Microsoft.DotNet.Tools.Test.Utilities.CommandResultAssertions.ExitWith(Int32 expectedExitCode) at Microsoft.DotNet.Tools.Publish.Tests.PublishTests.PublishOptionsTest(String testIdentifier, String framework, String runtime, String config, String outputDir)
```

```
MESSAGE:
Expected command to pass but it did not. File Name: /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/release_rhel7.2_x64_prtest/TestAssets/TestProjects/DependencyContextValidator/TestAppDeps/bin/Debug/netcoreapp1.0/rhel.7.2-x64/publish/TestAppDeps Arguments: Exit Code: 134 StdOut: StdErr:
+++++++++++++++++++
STACK TRACE:
at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) at Microsoft.DotNet.Tools.Test.Utilities.CommandResultAssertions.Pass() at Microsoft.DotNet.Tools.Test.Utilities.TestBase.TestExecutable(String outputDir, String executableName, String expectedOutput) at Microsoft.Extensions.DependencyModel.FunctionalTests.PublishTest(String appname, Boolean portable, Boolean checkCompilation)
```

**Comment by gkhanna79** [comment]
@eerhardt Are those infra issues or failures due to Roslyn update?

**Comment by eerhardt** [comment]
> @eerhardt Are those infra issues or failures due to Roslyn update?

Those test failures seemed to be due to Roslyn update.

**Comment by jaredpar** [comment]
The errors seem to be the following:

```
14:27:14 log  : /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_centos7.1_x64_prtest/src/Microsoft.DotNet.Files/project.json
14:27:14 log  : Restore completed in 334ms.
14:27:14 
14:27:14 Errors in /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_centos7.1_x64_prtest/src/dotnet/project.json
14:27:14     Unable to resolve 'Microsoft.NETCore.DotNetHostResolver (>= 1.0.1-rc3-004306-00)' for '.NETCoreApp,Version=v1.0'.
14:27:14 
14:27:14 Errors in /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_centos7.1_x64_prtest/src/dotnet-compile-fsc/project.json
14:27:14     Unable to resolve 'Microsoft.NETCore.DotNetHostResolver (>= 1.0.1-rc3-004306-00)' for '.NETCoreApp,Version=v1.0'.
14:27:14 
14:27:14 Errors in /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_centos7.1_x64_prtest/src/compilers/project.json
14:27:14     Unable to resolve 'Microsoft.NETCore.DotNetHostResolver (>= 1.0.1-rc3-004306-00)' for '.NETStandard,Version=v1.5'.
14:27:14 
14:27:14 NuGet Config files used:
14:27:14     /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_centos7.1_x64_prtest/NuGet.Config
14:27:14     /home/dotnet-bot/.nuget/NuGet/Nu
```

Doesn't look like Roslyn.

**Comment by eerhardt** [comment]
Those are the most recent errors where our build was broken due to the repo splitting that is happening today.  See my comment above where I was re-running the tests with the links to Jenkins runs. "publish" tests were failing on 3 Linux flavors. It may not be the Roslyn change. I have to rebase and will retest.

**Comment by gkhanna79** [comment]
@eerhardt What are the next steps on this? Do we understand the problem and next steps?

**Comment by eerhardt** [comment]
> What are the next steps on this? Do we understand the problem and next steps?

We have a Shared Framework with the latest Roslyn version:  https://github.com/dotnet/core-setup/pull/12.

I am currently working on updated CLI to all the latest versions - latest shared fx, corefx 24126, and roslyn 20160525-03.

**Comment by eerhardt** [comment]
@gkhanna79 - did you only want a Shared FX with new Roslyn?  or did you need the whole CLI on the new Roslyn?

**Comment by gkhanna79** [comment]
If CLI uses a Roslyn different from what is in SharedFX, then we will need that updated as well. Please let me know if that need to be done as well.

**Comment by eerhardt** [comment]
Yes, the CLI is not on the latest SharedFX with the new Roslyn.  I am working on making that happen now, but hit a CoreFX breaking change.

**Comment by gkhanna79** [comment]
Thanks Eric - do you think the CLI update will happen today?

**Comment by eerhardt** [comment]
> Thanks Eric - do you think the CLI update will happen today?

I am hopefully unblocked for the CoreFX breaking change.  PR soon - assuming it passes on my box.

**Comment by gkhanna79** [comment]
Cool!

**Comment by eerhardt** [comment]
Closing in favor of #3260.

**Comment by eerhardt** [comment]
@jaredpar - the test failures above for sure weren't caused by the new Roslyn.  Those same tests are now passing in #3260.  Sorry for the false blame... my mistake.

**Comment by jaredpar** [comment]
@eerhardt  no problem. Compiler is used to getting blamed for things :wink:

**Pull request closed without merging**
