### PR TITLE
Loc HB XLF files 2016-12-23

### PR DESCRIPTION
**Pull request by v-mdriml**
- If this PR should not run tests please add text "skip[REMOVE_THIS]ci[REMOVE_THIS]please" (remove the marked text, no quotes).
- Please add description for changes you are making.
- If there is an issue related to this PR, please add the reference.

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build 
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@srivatsn

**Comment by srivatsn** [comment]
@nguerrera are you going to do a spot check before mergin these in?

**Comment by livarcocc** [comment]
@srivatsn I did a check on the portuguese language and locked throught the changed files.

**Comment by srivatsn** [comment]
Sounds good. Thanks

**Pull request merged**
