### PR TITLE
Insert NuGet Build 4.7.0-preview1-4846 into cli

### PR DESCRIPTION
**Pull request by wli3**

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
can you also do the same for CLI repo?

CC: @livarcocc

**Comment by wli3** [comment]
this is cli, i need to update cli first and then sdk

**Comment by rohit21agrawal** [comment]
yeah, my bad, I realized it and deleted it hoping you wouldn't have seen ;)

**Comment by wli3** [comment]
@rohit21agrawal please approve it to make sure this is the right build number

**Comment by wli3** [comment]
cc @rrelyea

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/pull/1867

**Comment by wli3** [comment]
https://github.com/dotnet/cli/pull/8435

**Pull request closed without merging**
