### PR TITLE
Add RHEL6 leg to the CI

### PR DESCRIPTION
**Pull request by janvorli**

### CODE REVIEW

**Comment by mmitche** [comment]
@dontet-bot test ci please

**Comment by mmitche** [comment]
test RHEL6 x64 Debug Build

**Comment by johnbeisner** [comment]
CrossGen failed on the new RHel6 Jenkins leg:
From https://ci.dot.net/job/dotnet_cli/job/master/job/GenPRTest/job/debug_rhel6_x64_prtest/2/consoleText

version `GLIBC_2.14' not found (required by /opt/code/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.0-preview1-25806-02/tools/crossgen)
error MSB6006: "crossgen" exited with code 1.

**Comment by janvorli** [comment]
@johnbeisner I've forgotten to pass in the rhel.6 rid.

**Comment by janvorli** [comment]
@dotnet-bot test RHEL6 x64 Debug Build

**Comment by janvorli** [comment]
test RHEL6 x64 Debug Build

**Comment by johnbeisner** [comment]
@dontet-bot test ci please

**Comment by johnbeisner** [comment]
@dotnet-bot test RHEL6 x64 Debug Build

**Comment by johnbeisner** [comment]
test RHEL6 x64 Debug Build

**Comment by janvorli** [comment]
@mmitche it seems that only you can trigger the new leg?

**Comment by mmitche** [comment]
Sorry I disabled the job so it wouldn't show up failing on other PRs

test RHEL6 x64 Debug Build

**Pull request merged**
