### PR TITLE
Move the debian package_tool into our \tools directory.

### PR DESCRIPTION
**Pull request by eerhardt**
The package_tool isn't really part of our product, so moving it to the tools directory.

@brthor

### CODE REVIEW

**Comment by brthor** [comment]
Unfortunately we won't know if this is actually working because of the Ubuntu issues, but the change looks good to me.

IMO :shipit:

**Comment by eerhardt** [comment]
@brthor - Do you think we should wait with this until the Ubuntu build is fixed?

**Comment by brthor** [comment]
Is this move blocking you? 

If it's not blocking I think it would make sense, but if it is we're not producing Ubuntu binaries at the moment anyways so it's probably okay.

**Comment by eerhardt** [comment]
> Is this move blocking you?

No, I'm just going through cleaning up our assets. I'll wait a few days. Hopefully Ubuntu is unblocked soon.

**Comment by brthor** [comment]
@dotnet-bot test this please

**Comment by brthor** [comment]
@eerhardt 
looks like you may need to do some chmodding.. did you move things around on windows?
If possible it'd be best to do this on a unix system to retain the file permissions.

/opt/code/tools/DebianPackageTool/package_tool: Permission denied

@anurse Why would this be coming up green?

**Comment by eerhardt** [comment]
> looks like you may need to do some chmodding.. did you move things around on windows?
If possible it'd be best to do this on a unix system to retain the file permissions.

Yes that is my problem, I used Windows. Does git preserve file permissions? If so, I didn't know that.

**Comment by piotrpMSFT** [comment]
@eerhardt git does indeed!

**Comment by brthor** [comment]
git generally does when modifying files, but I'm not sure how it handles when files are being moved

**Comment by anurse** [comment]
@brthor likely because something isn't returning the correct exit code. Are you able to confirm that `package.sh` is returning a non-zero exit code?

**Comment by brthor** [comment]
hmmm appears that it is:
opt/code/scripts/package/package.sh exited with 0

Will check it out

**Comment by brthor** [comment]
Looks like set -e got taken out a while back, will add it back today.

**Comment by eerhardt** [comment]
@brthor - I will add it to this PR when I fix the file permission issue.

**Comment by brthor** [comment]
@eerhardt think I opened the PR same time as you commented
https://github.com/dotnet/cli/pull/1454

Will be good to get it in ASAP anyways

**Comment by eerhardt** [comment]
I changed the file permissions on package_tool to 755 like it previously was and rebased.

I'll manually check the Ubuntu builds to make sure the package is created.

**Comment by brthor** [comment]
Taking a look at the diff, there are a number of files that had their permissions changed.

It doesn't look like these are causing breaks, but for the following files the change is not desirable because they are used when devving on the package tool itself:

`.../debian/package_tool/setup/build_setup.sh → tools/DebianPackageTool/setup/build_setup.sh  100755 → 100644 `

`...g/debian/package_tool/setup/test_setup.sh → tools/DebianPackageTool/setup/test_setup.sh  100755 → 100644 `

`...path_relative_to_package_root/test_exe.sh → ...path_relative_to_package_root/test_exe.sh  100755 → 100644`

`...ackage_layout/package_root/test_called.sh → ...ackage_layout/package_root/test_called.sh  100755 → 100644`

`packaging/debian/package_tool/test.sh → tools/DebianPackageTool/test.sh  100755 → 100644`

**Comment by eerhardt** [comment]
:(  I'll fix those as well.  Thanks for the catch.

**Comment by brthor** [comment]
If only the file permissions were x-plat :smile:

**Comment by eerhardt** [comment]
OK - I fixed all the file permissions.
Since #1454 is merged now, we should get failures in Ubuntu if this move broke anything.

**Comment by brthor** [comment]
:shipit:

**Pull request merged**
