### PR TITLE
Re-enable Kestrel tests now that we have ASP.NET packages built on CoreFX rc3.

### LINKED ISSUE #3216: Re-enable Kestrel.Tests
In order to get on the RC3 builds of CoreFX, we needed to disable the Kestrel.Tests. This is because they were built on ASP.NET RC2, which isn't compatible with CoreFX RC3 assemblies.

We should re-enable the Kestrel.Tests when we get an ASP.NET RC3 build.

### PR DESCRIPTION
**Pull request by eerhardt**
Fix #3216

@livarcocc @pranavkm

### CODE REVIEW

**Comment by eerhardt** [comment]
test OSX x64 Release Build

21:55:04 Slave went offline during the build

**Comment by eerhardt** [comment]
Test OSX x64 Release Build

**Comment by livarcocc** [comment]
It seems like it is failing to find the kestrel test results xml file.

**Comment by eerhardt** [comment]
@pranavkm and @pakrym - can you guys check out my changes to the test for the new 'rc3' APIs?

**Comment by pranavkm** [comment]
cc @shalter \ @cesarbs

**Comment by pranavkm** [comment]
Looks good to me. @halter73 \ @cesarbs could you sign off?

**Comment by halter73** [comment]
LGTM.

This is probably out of the scope of this PR. But It looks we're testing Kestrel without HTTPS enabled. Is that something we would be interested in doing just in case there is some regression with SslStream or something related? If so, I could file an issue.

**Comment by eerhardt** [comment]
> Is that something we would be interested in doing in case there is a regression with SslStream or something related?

I think tests like that belong in ASP.NET.  These tests are for CLI to ensure we don't break running Kestrel. They aren't meant to be "test everything Kestrel can do". I don't want to be more dependent on ASP.NET than we already are.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test this please.

**Comment by eerhardt** [comment]
@piotrpMSFT looks like this needs a rebase...

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x64 Release Build  please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x64 Release Build please.

**Pull request closed without merging**
