### PR TITLE
Remove appdepssdk from sdk directory

### PR DESCRIPTION
**Pull request by krwq**
Fixes https://github.com/dotnet/cli/issues/2446
cc: @Sridhar-MS 

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2471)

### CODE REVIEW

**Comment by Sridhar-MS** [comment]
The best type of code fixes - removing code :)

:shipit:

**Comment by brthor** [comment]
:shipit:

**Comment by Sridhar-MS** [comment]
You should also be removing this - https://github.com/dotnet/cli/blob/rel/1.0.0/tools/appdep/project.json

**Comment by krwq** [comment]
I've not tested the updated version yet, running locally right now

**Comment by krwq** [comment]
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by piotrpMSFT** [comment]
:shipit:

**Pull request merged**
