### PR TITLE
Insert NuGet Build 4.8.0-preview1.5196 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.8.0-preview1.5196 into cli release/2.1.4xx branch

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test this please

**Comment by livarcocc** [comment]
@rohit21agrawal is there a breaking change on this version of Nuget?

**Comment by rohit21agrawal** [comment]
Looks like a error related to build not creating the package source:

1>D:\j\workspace\debug_windows---7af787af\bin\2\win-x64\dotnet\sdk\2.1.400-preview-008854\NuGet.targets(114,5): error : The local source 'D:\j\workspace\debug_windows---7af787af\bin\3\win-x64\test\packages' doesn't exist. [D:\j\workspace\debug_windows---7af787af\test\Microsoft.DotNet.Cli.Tests.sln] [D:\j\workspace\debug_windows---7af787af\build.proj]
Indication 3

**Comment by rohit21agrawal** [comment]
CC: @lzhi who is driving this insertion

@livarcocc given 2.1.4xx is constructed using prodcon, are these insertions required anymore? We can update our prodcon build to point to this build of nuget

**Comment by livarcocc** [comment]
4xx is not using prodcon. This is clearly something that change in NuGet, since all the other 4xx builds are passing.

**Comment by zhili1208** [comment]
looks like all nuget insertion pr build failed since May 4th, how the CI create the source The local source 'D:\j\workspace\debug_windows---7af787af\bin\3\win-x64\test\packages'? looks like it doesn't exist

**Comment by livarcocc** [comment]
It is probably being created later on, but before NuGet did not fail on it and now it does. Seems like a breaking change to me and I would like to make sure it is intentional and well understood.

**Comment by AndyGerlicher** [comment]
It looks like this is blocking #9279 since I need a new version of NuGet.

**Comment by rrelyea** [comment]
@mishra14 will investigate very soon.

**Comment by livarcocc** [comment]
The OSX failure was a machine failure.

@dotnet-bot Test OSX10.12 x64 Release Build

**Pull request merged**
