### PR TITLE
Remove dependency on run.exe

### PR DESCRIPTION
**Pull request by ellismg**
Our build scripts were pulling down all of buildtools and run.exe in
service of "clean.{cmd|sh}". While having consisent commands across
the repos is a good thing to strive for, we are pulling down a bunch
of additional stuff we don't need for simple commands that have well
known analogs (e.g. git clean).

If we had been all in on run.exe, this might have made sense, but we
aren't, so it feels like something we should clean up.

By doing this, we can stop downloading bootstrap from github when we
build (super dangerous anyway because changes in buildtools could have
broken us).

In addition, I changed the way we install dotnet to just invoke the
script in `scripts/obtain/` instead of downloading a version from
GitHub. This makes local development of changes to obtain easier and
removes yet another place we had to download a script.

### CODE REVIEW

**Comment by ellismg** [comment]
Thoughts on just cleaning stuff up?

@livarcocc I know you are making some changes to the version of stage0 we're downloading in the release/2.0.0 branch.  Do they plan to come back to master as well?  If so, I can handle merging this in with that.

**Comment by livarcocc** [comment]
@ellismg I am just pinning stage0 in release/2.0.0 as a workaround for now. We have a change in there that breaks one of the tools we are using.

**Comment by livarcocc** [comment]
@ellismg By the way, thanks for making this change. We have been meaning to do that for a while.

**Comment by livarcocc** [comment]
@MattGertz This is a infra-structure only change.

**Comment by eerhardt** [comment]
@ellismg - looks like the windows failures are real:

```
11:33:59 D:\j\workspace\release_windo---f861f43b>.\build.cmd -Configuration Release -Architecture x64 -Targets Default 
11:34:02 Join-Path : Cannot bind argument to parameter 'Path' because it is null.
11:34:02 At D:\j\workspace\release_windo---f861f43b\run-build.ps1:78 char:32
11:34:02 + $dotnetInstallPath = Join-Path $RepRoot "scripts\obtain\dotnet-install.ps1"
11:34:02 +                                ~~~~~~~~
11:34:02     + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingVa 
11:34:02    lidationException
11:34:02     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M 
11:34:02    icrosoft.PowerShell.Commands.JoinPathCommand
11:34:02  
11:34:03  -Channel "master" -InstallDir D:\j\workspace\release_windo---f861f43b\.dotnet_stage0\x64 -Architecture "x64"
11:34:40 -Channel : The term '-Channel' is not recognized as the name of a cmdlet, 
11:34:40 function, script file, or operable program. Check the spelling of the name, or 
11:34:40 if a path was included, verify that the path is correct and try again.
```

**Comment by ellismg** [comment]
> looks like the windows failures are real:

Show's what I get for editing powershell on Linux and not testing...

**Comment by ellismg** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Pull request merged**
