### PR TITLE
Updating the runtime to 2.0.7 and the CLI branding to 2.1.105.

### PR DESCRIPTION
**Pull request by livarcocc**
Marked WIP because we can't merge this until the NuGet fix is in and that build is cut.

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot Test this please

**Comment by wtgodbe** [comment]
> unable to prepare context: path "scripts/docker/opensuse.43.2" not found

In the OpenSuse build. There is no such dockerfile in `scripts/docker`, but there is `opensuse.42.3`. Error in netci.groovy/build.sh? @livarcocc

**Comment by livarcocc** [comment]
@wtgodbe I know. Working on it. Just had a more pressing update for 2.1.1xx.

**Comment by wtgodbe** [comment]
fedora27 & ubuntu1804 are failing because there are no RID-specific `Microsoft.NetCore.App` packages for them, which is accurate. @eerhardt is this supposed to be the case? I believe those distros should be looking for the generic `linux` package

**Comment by livarcocc** [comment]
@wtgodbe I think the restore issue is a test bug in the CLI. I am looking into it as well.

**Pull request merged**
