### PR TITLE
Add link to better getting started in our README.md

### PR DESCRIPTION
**Pull request by krwq**
cc: @blackdwarf  @richlander @piotrpMSFT @brthor @Sridhar-MS @anurse

### CODE REVIEW

**Comment by blackdwarf** [comment]
LGTM

**Comment by brthor** [comment]
Weird build failure

**Comment by brthor** [comment]
:shipit:

**Comment by Sridhar-MS** [comment]
csc is crashing with `AccessViolationException`. 
@krwq Can you file a bug in roslyn for this?
cc: @agocke

**Comment by krwq** [comment]
I already filed bugs on Roslyn and CoreCLR (they are blaming each other).

Thanks!

**Pull request merged**
