### PR TITLE
Merge rel/1.0.0-preview2 into rel/1.0.0

### PR DESCRIPTION
**Pull request by eerhardt**
Merging from preview2 to rel/1.0.0 to keep that branch alive.

Please pay special attention to version numbers, like in branchinfo.txt and project.json files.

@brthor @livarcocc

### CODE REVIEW

**Comment by eerhardt** [comment]
test CentOS7.1 x64 Debug Build
test RHEL7.2 x64 Release Build
test Windows_NT x86 Debug Build

All Dth flaky test failures.  @troydai.

the Ubuntu failure is because we need an update to netci.groovy.

**Comment by eerhardt** [comment]
test RHEL7.2 x64 Release Build

@troydai - another Dth test failure.

**Comment by eerhardt** [comment]
test RHEL7.2 x64 Release Build

one more time.

**Comment by eerhardt** [comment]
@brthor @livarcocc @piotrpMSFT - this change is ready to go in.  The Ubuntu failure is because we need a change to the netci.groovy file.

Please merge this if you think it looks good.  Or give it a shipit, and I'll merge when I see it.

**Comment by brthor** [comment]
I don't see any bad version changes here. :shipit:

**Comment by eerhardt** [comment]
Merging to unblock the rel/1.0.0 branch.

**Pull request merged**
