### PR TITLE
Migration: Remove System.GC.Server from runtimeconfig.template.json and inject ServerGarbageCollection property into the csproj

### LINKED ISSUE #5526: Ensure dotnet new web and dotnet migrate does not include a runtimeconfig.template.json file to set Server GC
Now that the SDK supports enabling Server GC via an MSBUILD property we need to ensure the templates and migrate output don't drop a runtimeconfig.template.json file in the case they only did so to enable Server GC. The web SDK will be setting this property by default.

### PR DESCRIPTION
**Pull request by jgoshi**
Fixes #5526 

@piotrpMSFT @livarcocc @krwq @jonsequitur

### CODE REVIEW

**Comment by jgoshi** [comment]
@livarcocc https://github.com/aspnet/websdk/pull/110 is the PR that adds the default value to the Web Sdk. This was merged yesterday, how can I figure out which version of the SDK it will be in? We need to update the CLI to use that version right?

**Comment by jgoshi** [comment]
test OpenSUSE13.2 x64 Debug Build

**Comment by livarcocc** [comment]
@mlorbetske Can you help in telling us the Web SDK version?

**Comment by jgoshi** [comment]
@eerhardt do you know what sdk version we need? I think we need to pick something up to get your change as well right? https://github.com/dotnet/sdk/issues/474

**Comment by eerhardt** [comment]
> @eerhardt do you know what sdk version we need? I think we need to pick something up to get your change as well right? dotnet/sdk#474

You should take the latest SDK that will have my changes.  Looks like anything newer than `1.0.0-alpha-20170127-2`.

**Comment by mlorbetske** [comment]
@livarcocc the Web SDK version is correct in the dependency versions file, however it relies on the .NET SDK being updated to actually perform the generation of the file at build time. I talked with @srivatsn last night & they will be updating that SDK version in the CLI soon to pull in that change & other fixes

**Comment by doublnt** [comment]
How should I use `ServerGarbageCollection property` in` .net core 2.0` and replace `runtimeconfig.template.json` file ?

**Comment by eerhardt** [comment]
If you want to set `ServerGarbageCollection` property, you can set it in your .csproj:

```XML
 <PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
```

This will cause the `runtimeconfig.json` file in your output to have the correct setting applied for the runtime to read it:

```JSON
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
}
```

**Comment by sw-carlin** [comment]
Please update the documentation for this change https://github.com/dotnet/cli/blob/v2.0.0/Documentation/specs/runtime-configuration-file.md. I can find posts from last year specifying three different places for this setting and the schema for the csproj file doesn't include it.

**Pull request merged**
