### PR TITLE
Updating the template package versions

### PR DESCRIPTION
**Pull request by vijayrkn**
/cc @seancpeters

### CODE REVIEW

**Comment by livarcocc** [comment]
All builds failed to find this package: Microsoft.TemplateEngine.Cli.Localization.

**Comment by vijayrkn** [comment]
I will get that fixed today.

**Comment by livarcocc** [comment]
@vijayrkn let me know when I should kick a retry.

**Comment by vijayrkn** [comment]
Sorry, I was not able to get this working over the weekend. Taking a look now. Will confirm once I have a fix. Thanks!

**Comment by vijayrkn** [comment]
Updated the new version which has the cli localization package. It doesn't contain the actual resource dlls (this will come in later) but for now this should unlock the build if the test is just looking for the package to be present.

**Comment by vijayrkn** [comment]
@livarcocc - All good now.

**Pull request merged**
