### PR TITLE
remove all the hacks to work around broken crossgen/coreclr

### PR DESCRIPTION
**Pull request by anurse**
/cc @piotrpMSFT @brthor @Sridhar-MS @livarcocc

### CODE REVIEW

**Comment by brthor** [comment]
:shipit:

**Comment by livarcocc** [comment]
LGTM

**Comment by anurse** [comment]
@dotnet-bot test Windows_NT Debug Build please
@dotnet-bot test Windows_NT Release Build please

**Comment by anurse** [comment]
@dotnet-bot test Windows_NT Debug Build please
@dotnet-bot test Windows_NT Release Build please

**Comment by anurse** [comment]
Alright, I got all green but only by disabling crossgen on Windows. I'm not going to merge this until we have a better idea from @schellap what the outcome of the investigation he's been doing yields, but I wanted to have a green checkmark ready so we could merge it if we need to :)

**Comment by schellap** [comment]
Please go ahead with the all greens. I've asked @JohnChen0 to take a look.

**Comment by anurse** [comment]
:+1: thanks @schellap !

**Comment by davidfowl** [comment]
:shipit: ?

**Pull request merged**
