### PR TITLE
add dotnet-init to linux build script

### PR DESCRIPTION
**Pull request by krwq**
I'm not sure how this went past the last CI build

### CODE REVIEW

**Comment by davidfowl** [comment]
bad tests

**Comment by Petermarcu** [comment]
Correct. Do we have test cases running for each of our inbox commands?

**Comment by Sridhar-MS** [comment]
We can also iterate through all folders in $reporoot/src/* to find any project.json and publish all of them.

But we also needs tests for commands in the repo.

**Comment by krwq** [comment]
Created issue for tests - currently I am not aware of any actual tests
https://github.com/dotnet/cli/issues/269

**Comment by brthor** [comment]
:shipit:

**Comment by piotrpMSFT** [comment]
@brthor is updating the end-to-end test we have to run through all commands init-->restore-->compile-->compile --native --> publish --> run --> pack.

**Pull request merged**
