### PR TITLE
Bump MSBuild to 15.1.0-preview-000539-01

### PR DESCRIPTION
**Pull request by piotrpMSFT**
@livarcocc

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
This was approved when brought by MSBuild in issue https://github.com/Microsoft/msbuild/pull/1610

**Comment by livarcocc** [comment]
@piotrpMSFT attending requests, this one next then.

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Pull request merged**
