### PR TITLE
set-content-type-for-versions

### PR DESCRIPTION
**Pull request by brthor**
@sokket @Sridhar-MS

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2745)

### CODE REVIEW

**Comment by sokket** [comment]
LGTM

**Comment by brthor** [comment]
weird test failure here...

@dotnet-bot test Windows_NT x64 Release Build  please

**Comment by Sridhar-MS** [comment]
cc @schellap for the windows x64 failure. Seems to be related to the locked muxer.

**Comment by brthor** [comment]
```
Errors in D:\j\workspace\release_windo---4c3b899b\artifacts\win81-x64\intermediate\lockedHostTemp\project.json
18:35:19     Microsoft.Win32.Primitives 4.0.1-rc2-24008 provides a compile-time reference assembly for Microsoft.Win32.Primitives on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.AppContext 4.1.0-rc2-24008 provides a compile-time reference assembly for System.AppContext on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Collections 4.0.11-rc2-24008 provides a compile-time reference assembly for System.Collections on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Console 4.0.0-rc2-24008 provides a compile-time reference assembly for System.Console on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Diagnostics.Debug 4.0.11-rc2-24008 provides a compile-time reference assembly for System.Diagnostics.Debug on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Diagnostics.Tools 4.0.1-rc2-24008 provides a compile-time reference assembly for System.Diagnostics.Tools on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Diagnostics.Tracing 4.1.0-rc2-24008 provides a compile-time reference assembly for System.Diagnostics.Tracing on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Globalization 4.0.11-rc2-24008 provides a compile-time reference assembly for System.Globalization on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Globalization.Calendars 4.0.1-rc2-24008 provides a compile-time reference assembly for System.Globalization.Calendars on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.IO 4.1.0-rc2-24008 provides a compile-time reference assembly for System.IO on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.IO.Compression 4.1.0-rc2-24008 provides a compile-time reference assembly for System.IO.Compression on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.IO.FileSystem 4.0.1-rc2-24008 provides a compile-time reference assembly for System.IO.FileSystem on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Net.Primitives 4.0.11-rc2-24008 provides a compile-time reference assembly for System.Net.Primitives on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Net.Sockets 4.1.0-rc2-24008 provides a compile-time reference assembly for System.Net.Sockets on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Reflection 4.1.0-rc2-24008 provides a compile-time reference assembly for System.Reflection on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Reflection.Extensions 4.0.1-rc2-24008 provides a compile-time reference assembly for System.Reflection.Extensions on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Reflection.Primitives 4.0.1-rc2-24008 provides a compile-time reference assembly for System.Reflection.Primitives on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Resources.ResourceManager 4.0.1-rc2-24008 provides a compile-time reference assembly for System.Resources.ResourceManager on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Runtime 4.1.0-rc2-24008 provides a compile-time reference assembly for System.Runtime on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Runtime.Extensions 4.1.0-rc2-24008 provides a compile-time reference assembly for System.Runtime.Extensions on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Runtime.Handles 4.0.1-rc2-24008 provides a compile-time reference assembly for System.Runtime.Handles on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Runtime.InteropServices 4.1.0-rc2-24008 provides a compile-time reference assembly for System.Runtime.InteropServices on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-24008 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Text.Encoding 4.0.11-rc2-24008 provides a compile-time reference assembly for System.Text.Encoding on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Text.Encoding.Extensions 4.0.11-rc2-24008 provides a compile-time reference assembly for System.Text.Encoding.Extensions on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Threading.Tasks 4.0.11-rc2-24008 provides a compile-time reference assembly for System.Threading.Tasks on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     System.Threading.Timer 4.0.1-rc2-24008 provides a compile-time reference assembly for System.Threading.Timer on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win7-x64.
18:35:19     One or more packages are incompatible with .NETCoreApp,Version=v1.0 (win7-x64).
18:35:19 
18:35:19 NuGet Config files used:
18:35:19     D:\j\workspace\release_windo---4c3b899b\NuGet.Config
18:35:19     C:\Users\dotnet-bot\AppData\Roaming\NuGet\NuGet.Config
18:35:19 
18:35:19 Feeds used:
18:35:19     https://dotnet.myget.org/F/cli-deps/api/v3/index.json
18:35:19     https://api.nuget.org/v3/index.json
18:35:19     D:\j\workspace\release_windo---4c3b899b\artifacts\win81-x64\corehost
18:35:19     D:\j\workspace\release_windo---4c3b899b\artifacts\win81-x64\corehostdummypackages
18:35:19 [EXEC       <] [FAIL] [00:02:18.844] D:\j\workspace\release_windo---4c3b899b\.dotnet_stage0\Windows\x64\dotnet.exe "restore" "--verbosity" "verbose" "--infer-runtimes" "--fallbacksource" "D:\j\workspace\release_windo---4c3b899b\artifacts\win81-x64\corehost" "--fallbacksource" "D:\j\workspace\release_windo---4c3b899b\artifacts\win81-x64\corehostdummypackages" exited with 1
18:35:19 [TARGET     <] [FAIL] [00:02:18.854] RestoreLockedCoreHost                                 (Microsoft.DotNet.Cli.Build.CompileTargets.RestoreLockedCoreHost)
18:35:19 [TARGET     <] [FAIL] [00:02:18.854] Compile                                               (Microsoft.DotNet.Cli.Build.CompileTargets.Compile)
18:35:19 [TARGET     <] [FAIL] [00:02:18.854] Default                                               (Standard Goals)
```

@schellap  Please take a look at this

**Comment by schellap** [comment]
@brthor looking...

**Comment by brthor** [comment]
@dotnet-bot test Windows_NT x64 Release Build please

talked with @schellap offline, we're unable to repro locally, he is going to get into the machine.

**Comment by schellap** [comment]
@brthor that machine got auto reclaimed. I'm setting up an xlab server 2012 until jenkins is back.

**Comment by brthor** [comment]
@dotnet-bot test this please

**Pull request merged**
