### PR TITLE
Insert new bits of testplatform.

### PR DESCRIPTION
**Pull request by Faizan2304**

### CODE REVIEW

**Comment by Faizan2304** [comment]
@dotnet-bot test Ubuntu x64 Release Build 
@dotnet-bot test Ubuntu16.10 x64 Debug Build

**Comment by Faizan2304** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by Faizan2304** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by livarcocc** [comment]
@MattGertz partner bits flowing into the CLI.

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Pull request merged**
