### PR TITLE
[WIP] Fix dependency context merge and msbuildproject resolution

### PR DESCRIPTION
**Pull request by pakrym**
Fixes: https://github.com/dotnet/cli/issues/3203
Fixes: https://github.com/dotnet/cli/issues/3202

### CODE REVIEW

**Comment by davidfowl** [comment]
:shipit:

**Comment by davidfowl** [comment]
@dotnet-bot test OSX x64 Release Build please

**Comment by eerhardt** [comment]
Let's not merge `[WIP]` PRs anymore... It makes it impossible to tell what I need to review and what is not ready for review.

**Comment by pakrym** [comment]
@eerhardt would rename next time before asking for review.

**Comment by eerhardt** [comment]
:) thanks!

**Pull request merged**
