### PR TITLE
no longer need to crossgen the CLI

### PR DESCRIPTION
**Pull request by anurse**
thank you shared framework!

this should fix VSO

/cc @eerhardt @pakrym

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2105)

### CODE REVIEW

**Comment by eerhardt** [comment]
LGTM
:ship: :it:

**Comment by pakrym** [comment]
:shipit: as soon as CI passes

**Comment by livarcocc** [comment]
:shipit: and keep an eye on VSO!

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu x64 Release Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please.

**Comment by mmitche** [comment]
@piotrpMSFT I think I pinpopinted the bug.  The system got a reboot with the fix and we'll see how it goes.

**Comment by piotrpMSFT** [comment]
Thanks @mmitche !

**Comment by mmitche** [comment]
@piotrpMSFT Actually one more tweak.  I'm going to restart it one more time and I'll restart this PR after.

**Comment by piotrpMSFT** [comment]
@mmitche it's 5-10 mins from done. Can we finish? This is blocking VSO biulds

**Comment by mmitche** [comment]
done @dotnet-bot test this please

**Comment by mmitche** [comment]
Sweet

**Comment by piotrpMSFT** [comment]
indeed!

**Comment by mmitche** [comment]
Yeah i am 99% sure I found and fixed the trigger for the bug, so we should be good an stable now.

**Comment by piotrpMSFT** [comment]
what was it?

**Comment by mmitche** [comment]
A tweak I made last week to a plugin to allow the dynamic pooling across all VMs had a slight bug in it which was causing deprovisioned machines to attempt to disconnect and reconnect a lot.  They weren't ever used and this wouldn't have made a difference except this exacerbated a race condition in the disconnect/reconnect code.

**Pull request merged**
