### PR TITLE
Updating CoreFx, CoreSetup to rc3-24201-00, rc3-004371 respectively

### PR DESCRIPTION
**Pull request by eerhardt**

### CODE REVIEW

**Comment by brthor** [comment]
CI is on the way
https://github.com/dotnet/dotnet-ci/pull/301

**Comment by livarcocc** [comment]
@eerhardt Should this go in on  rel/1.0.0 as well?

**Comment by eerhardt** [comment]
>  Should this go in on rel/1.0.0 as well?

We need to decide how we want to handle the CLI branches going forward.  I know @piotrpMSFT wanted to use GitFlow to handle our branching story. But this is not the way corefx is managed.

If we use GitFlow, any change made to rel/1.0.0-preview2 will go into rel/1.0.0.

**Comment by eerhardt** [comment]
Closing in favor of #3351

**Pull request closed without merging**
