### PR TITLE
Testplatform release 15.0.0-preview-20161227-02

### PR DESCRIPTION
**Pull request by smadala**
- Changes:
      1. Translationlayer timeout for CustomHost Launch changed to indefinate.
      2. Change testcase gereration id algorithm to SHA1 to be in compat with Associate-WorkItem scenarios 
      3. Bug fixes.

     Edit:
     4. Capability in the trx logger to give custom logfilename.
     5. Capability for giving RunSetting arguments directly.

### CODE REVIEW

**Comment by codito** [comment]
Build issue should be fixed by https://github.com/dotnet/cli/pull/5056

**Comment by livarcocc** [comment]
@dotnet-bot Test this

**Comment by livarcocc** [comment]
@dotnet-bot Test this please

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build

**Comment by livarcocc** [comment]
We have started using this file to pass along dependency version as properties: https://github.com/dotnet/cli/blob/rel/1.0.0/dir.props.

Take a look at it. Feels to me like we should do the same with test dependency versions.

**Comment by piotrpMSFT** [comment]
@srivatsn

**Comment by srivatsn** [comment]
I'll wait for responding to Livar's comment and signoffs to approve

**Comment by smadala** [comment]
Defined Testplatform version in targets and referred.

**Comment by smadala** [comment]
@dotnet-bot Test this please

**Comment by smadala** [comment]
@livarcocc Can you please review the changes?

**Comment by smadala** [comment]
@livarcocc Can please merge this, if it looks good.

**Pull request merged**
