### PR TITLE
Prepare for non windows builds to MIT Licensed

### PR DESCRIPTION
**Pull request by ellismg**
I want to get a read from CI on this change.  I need to also update the RTF files for the OSX installers.

Note that this will also need changes from Core-Setup (since that's what drops the LICENSE.TXT file in the root).

Please don't merge this yet.

### CODE REVIEW

**Comment by ellismg** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please

**Comment by eerhardt** [comment]
Do you want this for 2.0?  If yes, then it should go into the `release/2.0.0` branch.

Unless you plan on cherry-picking the change into both branches.

**Comment by eerhardt** [comment]
:shipit:

**Comment by ellismg** [comment]
> Unless you plan on cherry-picking the change into both branches.

Yes, I will do that for preview 3 (since I have to make corresponding core-setup changes and they don't want to respin a build).

**Pull request merged**
