### PR TITLE
Fix dependency context builder regression

### PR DESCRIPTION
**Pull request by pakrym**
Fix regression in dependency builder when having multiple dependencies with same name.
@anurse

### CODE REVIEW

**Comment by anurse** [comment]
:shipit: when builds succeed

**Comment by pranavkm** [comment]
Any idea where the `IDictionary<>.Add` call is? Could we change that to indexer assignment so it doesn't throw?

**Comment by pakrym** [comment]
I wasn't dictionary add call it's `Can not add property System.Collections to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.` thrown at https://github.com/dotnet/cli/blob/pakrym/deps-duplication-fix/src/Microsoft.Extensions.DependencyModel/DependencyContextWriter.cs#L246

**Comment by troydai** [comment]
:shipit:

**Comment by pranavkm** [comment]
:shipit:

**Comment by davidfowl** [comment]
When does this happen?

**Comment by pakrym** [comment]
Won't merge per @davidfowl request, we'll need to fix root cause

**Pull request merged**
