### PR TITLE
Workaround for corefx symlink resolution on Unix

### PR DESCRIPTION
**Pull request by schellap**
CoreHost works correctly for app local because app_dir is already realpath'ed on Unix. I could fix servicing separately as well for path resolution. But since this is a workaround I wanted to keep it just before the point of passing it on to CoreCLR.

Corrects a potential bad pointer read.

@gkhanna79 PTAL.
/Cc @anurse @brthor

### CODE REVIEW

**Comment by anurse** [comment]
:shipit: (assuming build failures are fixed or diagnosed as unrelated)

**Comment by gkhanna79** [comment]
>  I could fix servicing separately as well for path resolution.

It would be good to ensure that host is passing all the right information to the runtime. FX doing the right thing should be orthogonal.

Other than that, LGTM - please squash the commits.

**Comment by schellap** [comment]
> > I could fix servicing separately as well for path resolution.

> It would be good to ensure that host is passing all the right information to the runtime. FX doing the right thing should be orthogonal.

`symlink` is not wrong information, right? It is whether you want to do eager resolution in the host vs. lazy resolution at load time.

**Comment by brthor** [comment]
Nice :shipit:

**Comment by piotrpMSFT** [comment]
@schellap this got merged after we branched rel/1.0.0. Sorry, didn't think anyone was working that late :) We need to PR this change into rel/1.0.0 please.

**Pull request merged**
