### PR TITLE
Fixing CLIBUILD_SKIP_TESTS on docker by passing the environment variable through to the docker container.

### PR DESCRIPTION
**Pull request by eerhardt**
Tests are still running on our Linux builds on official VSO runs.

@livarcocc @piotrpMSFT @jonsequitur @krwq

### CODE REVIEW

**Comment by eerhardt** [comment]
See #5275 to fix this issue for real.

**Comment by livarcocc** [comment]
Maybe we shouold make these fixes into rc3, so that we can then just merge that branch back into rel. Not a big deal, but this way we need to keep cherry-picking these commits.

**Comment by piotrpMSFT** [comment]
This got fixed in RC3 last night... should we just merge RC3 into rel/1.0.0?

**Comment by piotrpMSFT** [comment]
Superseded by #5282

**Pull request closed without merging**
