### PR TITLE
Update download link to RC4 from RC3

### PR DESCRIPTION
**Pull request by svick**
The document talks about RC4, but then links to download page for RC3. I think the link should point to downloads for RC4.

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@blackdwarf can you review?

**Comment by blackdwarf** [comment]
LGTM

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x86 Debug Build

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by svick** [comment]
https://github.com/dotnet/cli/pull/5928 and the fact that RC4 is no longer newest obsoletes this PR, so closing.

**Pull request closed without merging**
