### PR TITLE
Insert NuGet Build 4.6.0-preview1-4688 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.6.0-preview1-4688 into cli master branch

CC: @livarcocc

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
@dotnet-bot  test this please.

**Comment by rohit21agrawal** [comment]
ping @livarcocc

**Comment by livarcocc** [comment]
It can't find NuGet.Build.Tasks with the version you are inserting. So, everything fails. Any information you can add around that?

**Comment by rohit21agrawal** [comment]
what are the sources you look at? nothing has changed about where we upload this package. it still goes into the nuget-build feed on myget .  
**https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.Build.Tasks/4.6.0-preview1-4688**

**Comment by rohit21agrawal** [comment]
@livarcocc any clue?

**Comment by livarcocc** [comment]
This is the list of our feeds: https://github.com/dotnet/cli/blob/master/NuGet.Config. 

@johnbeisner did we remove any feed that might have been a nuget feed?

**Comment by johnbeisner** [comment]
@livarcocc
@rohit21agrawal 
"did we remove any feed that might have been a nuget feed?" - not at the root NuGet.config
We replaced: 'https://dotnet.myget.org/F/dotnet-core/api/v3/index.json' with 'https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json'
However, both the versions, '4.5.0-preview2-4529' and '4.6.0-preview1-4688' are not at either of the aforementioned feeds. Looking further...

**Comment by johnbeisner** [comment]
@livarcocc
@rohit21agrawal
It appears that NuGet.Build.Tasks, and others, are being consistently published to: https://dotnet.myget.org/feed/cli-deps/package/nuget/NuGet.Build.Tasks on a regular cadence; there was a version upload last Friday, 1/1/2017.

**Comment by rohit21agrawal** [comment]
most likely nuget-build feed is mirrored by cli-deps . Did cli-deps not get 4688 because of the same issues that the dotnet-core feed was facing? is there  a way to manually do this? i don't have permissions for cli-deps

**Comment by livarcocc** [comment]
I want to decommission cli-deps, so, let's go ahead and add that NuGet feed to our list of feeds.

**Comment by rohit21agrawal** [comment]
@livarcocc @johnbeisner could you guys also take a peek at the equivalent SDK PR :  https://github.com/dotnet/sdk/pull/1774

**Comment by johnbeisner** [comment]
@dotnet-bot test this please.

**Pull request closed without merging**
