### PR TITLE
remove clang-3.5 as a dependency of the deb package

### LINKED ISSUE #3088: Go through the DEB dependencies with a fine-tooth comb
We need to go through all of the dependencies on our DEB packages and fix all of the dependencies to be only the set we really need.

### PR DESCRIPTION
**Pull request by brthor**
Partially fixes #3088 

This removes the clang dependency from our sdk package

cc @blackdwarf

### CODE REVIEW

**Comment by blackdwarf** [comment]
:shipit:

**Comment by blackdwarf** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please

**Comment by blackdwarf** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by blackdwarf** [comment]
@dotnet-bot test Debian8.2 x64 Debug Build please

**Comment by joshfree** [comment]
@blackdwarf please create issues whenever you see a CI failure

**Comment by blackdwarf** [comment]
@joshfree sorry, don't follow?

**Comment by brthor** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Pull request merged**
