### PR TITLE
Everything in the same project

### PR DESCRIPTION
**Pull request by davidfowl**
- Build in intrinsic commands as part of `dotnet`.

Starting a discussion about taking the path described in #1149. A few things to note:

- We could remove the special casing of built in command and instead generate stub executables for each built in command.
- With this change you can't remove override built in commands via packages. This wouldn't be too hard to allow but that's how it looks right now.
- I probably need to fix help for built in commands.

### CODE REVIEW

**Comment by Petermarcu** [comment]
the proposal is this.. Can we make this PR follow along? These are the high level commands that we think will be in the core and we want to make sure there is a first class experience for everything in the next layer of "Power tools". 

There are some sub commands that are not explicitly listed that these depend on.

dotnet new
dotnet install
dotnet restore
dotnet build
dotnet compile
dotnet test
dotnet debug
dotnet pack
dotnet publish

**Comment by davidfowl** [comment]
> the proposal is this.. Can we make this PR follow along? These are the high level commands that we think will be in the core and we want to make sure there is a first class experience for everything in the next layer of "Power tools".

We should do that in another PR. I don't want to fold this into a single change and restructure.

**Comment by Petermarcu** [comment]
Is it cleaner to just abandon this one and merge the right projects once as opposed to merging and then pulling some back out?

**Comment by davidfowl** [comment]
> Is it cleaner to just abandon this one and merge the right projects once as opposed to merging and then pulling some back out?

Nope, I'm going to merge this thing. We can pull things out in another change.

**Comment by davidfowl** [comment]
Do we know how those commands will ship? Or where they'll be getting built?

**Pull request merged**
