### PR TITLE
TestPlatform insertion 16.1.0

### PR DESCRIPTION
**Pull request by vagisha-nidhi**
Release : [https://github.com/microsoft/vstest/releases/tag/v16.1.0](https://github.com/microsoft/vstest/releases/tag/v16.1.0)

### CODE REVIEW

**Comment by peterhuene** [comment]
On a quick glance at some of the test failures, it looks like the test run summary format has changed. 

Actual:

```
Total tests: 2
     Passed: 1
     Failed: 1
```

Expected:

```
Total tests: 2. Passed: 1. Failed: 1. Skipped: 0.
```

Thus the tests will need to be updated.

I'm not sure why some of the platforms (such as macOS) are green.

**Comment by peterhuene** [comment]
Also, will there also be a test tools insertion to the `release/2.1.7xx` branch?

**Comment by livarcocc** [comment]
@vagisha-nidhi And one more questions, should this be 16.1 instead of 16.0? 2.2.3xx is shipping with 16.1.

**Comment by vagisha-nidhi** [comment]
> On a quick glance at some of the test failures, it looks like the test run summary format has changed.
> 
> Actual:
> 
> ```
> Total tests: 2
>      Passed: 1
>      Failed: 1
> ```
> 
> Expected:
> 
> ```
> Total tests: 2. Passed: 1. Failed: 1. Skipped: 0.
> ```
> 
> Thus the tests will need to be updated.
> 
> I'm not sure why some of the platforms (such as macOS) are green.

Yes. The format has been changed with this version. I'll fix the tests soon.

**Comment by livarcocc** [comment]
@vagisha-nidhi what about the version and the 2.1.7xx insertion?

**Comment by vagisha-nidhi** [comment]
> @vagisha-nidhi what about the version and the 2.1.7xx insertion?

We have released 16.1.0 and changed the version. I shall raise a PR for 2.1.7xx branch also.

**Comment by vagisha-nidhi** [comment]
@dotnet-bot test again please

**Comment by vagisha-nidhi** [comment]
@livarcocc @peterhuene  Can you please help me understand when will 2.2.3xx and 2.1.7xx be released next? These have some important fixes I need to get the timeline for.

**Comment by peterhuene** [comment]
@vagisha-nidhi 2.2.3xx and 2.1.7xx are releasing with 16.1 and are effectively locked down for anything but critical fixes at this point.

If you want to get them in for 16.2, target the release/2.1.8xx and release/2.2.4xx branches.  If you have important fixes that you would like for servicing for the 2.1/2.2 SDKs, you'll need to take them to .NET Core Shiproom for approval; servicing releases occur each month.

**Comment by vagisha-nidhi** [comment]
@peterhuene The fixes have already gone with TP 16.1.0. Just wanted to know when these will be released for the customers.

**Comment by peterhuene** [comment]
Hi @vagisha-nidhi.  I've responded by email.  Thanks!

**Pull request merged**
