### PR TITLE
update product monikers from rc2

### LINKED ISSUE #3400: CLI Windows Installer Title/ARP string still uses `Preview1`
## Steps to reproduce
Run Windows Installer

## Expected  behavior
Product name in title, install UI, ARP, should read 'Preview2'

## Actual behavior
Product name in title, install UI, ARP, reads 'Preview1'

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-002973)

Product Information:
 Version:            1.0.0-preview2-002973
 Commit SHA-1 hash:  512287ec03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

### PR DESCRIPTION
**Pull request by brthor**
Fixes #3400 

@blackdwarf @piotrpMSFT

### CODE REVIEW

**Comment by brthor** [comment]
myget is down

**Comment by eerhardt** [comment]
Does the title of this PR need updating?  "to RC2" doesn't seem right.

**Comment by brthor** [comment]
from rc2 :smile:

**Comment by brthor** [comment]
@dotnet-bot test this please

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu x64 Release Build  please.

**Comment by piotrpMSFT** [comment]
@blackdwarf can you sign off on the string changes?

**Comment by blackdwarf** [comment]
:shipit: but also cc @leecow for sign off as well.

**Comment by leecow** [comment]
I just don't get the squirrel ;-) Anyway, change looks good.

**Pull request merged**
