### PR TITLE
Update the branding of the SDK to 2.2.100-preview1.

### PR DESCRIPTION
**Pull request by livarcocc**

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test Debian8.2 x64 Debug Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Debian8.2 x64 Debug Build

**Comment by dsplaisted** [comment]
@livarcocc Do different legs have different feeds set up?  It looks like the failing legs are finding newer patches of Microsoft.NETCore.App (2.0.7, for example), and failing because the corresponding properties should be updated in the bundled versions .props.  However, the passing legs aren't finding the updated patch version (otherwise they would also be failing).

Basically, what's causing this is that the failing legs are finding version 2.0.7 etc of Microsoft.NETCore.App when restoring for 2.0.*, while the passing legs are only finding version 2.0.6.  I don't currently know why there would be a difference.  If the legs were consistent we would just update the property values in the bundled versions.

**Comment by livarcocc** [comment]
I think this was a timing issue. This may be because 2.0.7 has been pushed to nuget.org. I will update the test on this PR to expect the new versions of M.NC.App.

**Comment by dsplaisted** [comment]
@livarcocc Yes, @johnbeisner pointed out to me that it was probably a timing issue.  I've pushed an update to the version properties which should hopefully fix this.

**Comment by dsplaisted** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build

**Pull request merged**
