### PR TITLE
Update Roslyn to 2.8.0-dev-62817-01

### PR DESCRIPTION
**Pull request by livarcocc**

### CODE REVIEW

**Comment by tannergooding** [comment]
Why did we move to a `dev` version (and where did we get it from)? `dev` versions should never come from official builds, AFAIK.

**Comment by nguerrera** [comment]
@jaredpar

**Comment by livarcocc** [comment]
That's what @jaredpar pointed me to yesterday. I took the version from https://github.com/dotnet/versions/blob/master/build-info/dotnet/roslyn/dev15.7/Latest_Packages.txt

**Comment by jaredpar** [comment]
That's odd that we switched from beta to dev. It's the same bits, just the label is off. I will look into that.

**Comment by jaredpar** [comment]
This is completely fine BTW for CLI. Same bits. Just we're pushing the wrong label to the versions feed.

**Comment by tannergooding** [comment]
> Just we're pushing the wrong label to the versions feed.

Good to hear that the bits are still correct 😄

**Pull request merged**
