### PR TITLE
Update the support package on the CLI to fix binding redirects on 4.7.1

### PR DESCRIPTION
**Pull request by joperezr**
cc: @livarcocc @AlexGhiondea @weshaggard 

Doing the insertion of the support package into the CLI so that we fix the binding redirects for 4.7.1

### CODE REVIEW

**Comment by livarcocc** [comment]
I imagine this also needs the SDK change?

**Comment by joperezr** [comment]
It doesn't necessarily since there are no SDK changes on the targets file other than the bump up of the version of the support package. That means that the whole fix is only in the Support package. That said, if you want to first merge the SDK change and then update the version in here I'm fine with that too.

**Comment by joperezr** [comment]
Here is the SDK change for reference: https://github.com/dotnet/sdk/pull/1819

**Comment by joperezr** [comment]
Hey @livarcocc can we merge this PR now? I want to make sure that we are still set for inserting this into VS on time.

**Comment by joperezr** [comment]
Thanks for taking a look @livarcocc , do you mind merging the PR? seems like I don't have permissions...

**Comment by livarcocc** [comment]
Working on the appropriate branch to merge this in. May end up being this one.

**Comment by joperezr** [comment]
Ok, let me know if I need to port this PR to a different branch if it's necessary.

**Pull request merged**
