### PR TITLE
Update/Upgrade CLI Maestro dependency updater

### PR DESCRIPTION
**Pull request by mmitche**
- Updates the dependency updater
- Removes unused DIA dependency that I found while evaluating the things that need updating.

### CODE REVIEW

**Comment by mmitche** [comment]
Don't merge this yet.  Fixing the title issues

**Comment by mmitche** [comment]
Improved so that the commit messages aren't so giant

**Comment by eerhardt** [comment]
@mmitche - I think this broke CLI master updating of core-setup.

Note that for the 'master' subscription, we aren't setting the core-setup fragment variable:

https://github.com/dotnet/versions/blob/d0ef2fd7f9725fb51773bd8f5e3a89fffe538d47/Maestro/subscriptions.json#L796-L810

That used to mean `use the matching branch in core-setup`.  See [this code](https://github.com/dotnet/cli/blob/b0ee5db411a7c257757b6c70e0b9ae0ceb58ed5f/build_projects/update-dependencies/Config.cs#L90-L96). However, your change broke it so this no longer happens.  So we are no longer getting auto-PRs of core-setup into CLI.

I've opened https://github.com/dotnet/cli/issues/9051 for this.

**Comment by mmitche** [comment]
@eerhardt I think we just want to make the core-setup fragment explicit, rather than making an assumption based on the lack of environment variable.

**Comment by eerhardt** [comment]
The only thing I care deeply about is the auto PRs flowing again.  However you want to make that work will be fine with me.

**Pull request merged**
