### PR TITLE
Insert NuGet Build 4.6.0-rtm-4791 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.6.0-rtm-4791 into cli release/2.1 branch

### CODE REVIEW

**Comment by livarcocc** [comment]
This seems to be failing because `dotnet pack` is, once again, not including the `prefercliruntime` file in the nupkg. We had to fix this in the last insertion because pack moved the location of the file based on the nuspec we were using.

What has changed in NuGet that could have caused this?

**Comment by nkolev92** [comment]
Is it maybe that the test hasn't been fixed in this branch, but has been fixed in the master branch?
cc @johnbeisner should be able to help.

**Comment by rohit21agrawal** [comment]
ping....

**Comment by livarcocc** [comment]
@rohit21agrawal is this a matching insertion for VS 15.6? Or for 15.5? release/2.1 is servicing 2.1.x, which gets inserted into 15.5.

If you are targeting 2.1.1xx which will be inserted into 15.6, than please re-target this PR to release/2.1.1xx.

**Comment by rohit21agrawal** [comment]
@livarcocc done.

**Pull request merged**
