### PR TITLE
Upgrade to aspnetcore 2.1.1-rtm-30818 and react to file name change

### PR DESCRIPTION
**Pull request by natemcmaster**
React to https://github.com/aspnet/Universe/pull/1191.

~~**NO MERGE**~~ - wait until we have approval and https://github.com/aspnet/Universe/pull/1191 has been completed before pulling this in.

### CODE REVIEW

**Comment by natemcmaster** [comment]
https://github.com/aspnet/Universe/pull/1191 was merged.

**Comment by mmitche** [comment]
@livarcocc ASP's change is now merged, so whenever we're ready on this.  We can't get a good CLI build until this happens.

**Comment by natemcmaster** [comment]
@dotnet-bot test OSX10.12 x64 Release Build please

It appeared to fail due to network flakiness in `restore.Tests/GivenThatIWantToRestoreApp.cs:line 82`

**Comment by natemcmaster** [comment]
All checks have passed.

**Pull request merged**
