### PR TITLE
[WIP] Update the template engine bits in the 2.1.1xx CLI

### PR DESCRIPTION
**Pull request by mlorbetske**
Updating the engine bits to latest. @seancpeters please confirm that these are ones we'd like to ship.

### CODE REVIEW

**Comment by mlorbetske** [comment]
I don't believe we're looking at this making a servicing or escrow bar. I'm just making these updates as they don't flow automatically. It looks like there's an issue in picking up the packages - I'll investigate.

**Comment by mlorbetske** [comment]
@dotnet-bot test this please

**Comment by mlorbetske** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please
@dotnet-bot test Ubuntu16.04 x64 Debug Build please

**Comment by livarcocc** [comment]
Closing as we have 200 out now.

**Pull request closed without merging**
