### PR TITLE
Adding publishing variables to the dockerrun.sh file

### PR DESCRIPTION
**Pull request by livarcocc**
Adding the storage variables to the dockerrun.sh file so that they are set as env variables in docker.

cc @brthor @eerhardt @piotrpMSFT

### CODE REVIEW

**Comment by brthor** [comment]
Do we still need connection string?

**Comment by livarcocc** [comment]
I did not scan the entire code, but there may be places in the c# code that still uses it. That's why I left it there. My plan is to remove it as we do a bit clean up on the tasks.

**Comment by brthor** [comment]
ok :shipit:

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build please
@dotnet-bot Test Ubuntu x64 Release Build  please

**Comment by eerhardt** [comment]
:shipit:

**Pull request merged**
