### PR TITLE
Bump MSBuild to 15.1.0-preview-000544-02

### PR DESCRIPTION
**Pull request by piotrpMSFT**
@andygerlicher @livarcocc @jonsequitur

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@MattGertz FYI this was approved at shiproom today. It is the CLI portion of this MSBuild update.

**Comment by MattGertz** [comment]
Ten-four.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Fedora23 x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Fedora23 x64 Debug Build please.

**Pull request merged**
