### PR TITLE
Increase HttpClient Timeout in bootstrap script

### PR DESCRIPTION
**Pull request by MattGal**
CDN is really slow this afternoon.  I'm having a hard time getting the necessary 100+ K/s to download this on my machine.  Increasing the timeout solves this locally.

@weshaggard  @piotrpMSFT

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please.

**Comment by piotrpMSFT** [comment]
:shipit:

**Comment by weshaggard** [comment]
Looks good to me. Should we also put some extra logic in here to properly report a timeout?

**Comment by MattGal** [comment]
Should be as easy as just stating that if the result object is null.  It would be nice before we touch this next to decide what the minimum average bandwidth a customer has should be, as any timeout could still be hit with a slow enough connection.

**Pull request merged**
