### PR TITLE
Remove NuGet.config from dotnet new drop.

### LINKED ISSUE #656: Remove Nuget.Config from `dotnet new` drop for release
The nuget.config drop was added as a temporary step until the StdLib is available on nuget.org.

When this is true, we should remove the nuget.config drop.

### PR DESCRIPTION
**Pull request by brthor**
Fixes #656 

cc @piotrpMSFT

### CODE REVIEW

**Comment by davidfowl** [comment]
This change looks like a bad idea. Dropping a nuget.config is much less magic. And you can turn it off. Baking a switch into code like that will cause all sorts of problems.

**Comment by piotrpMSFT** [comment]
@davidfowl this change brings nuget in-line with the rest of the ecosystem for pre-releases. Adding a Nuget config for a Beta toolchain to acces Beta packages is pretty broken. It's both another concept and a code artifact that will need to get eliminated when we RTM. The Beta should provide exactly the RTM experience.

/cc @ericstj

**Comment by davidfowl** [comment]
It's just plain wrong baking in defaults like this.

**Comment by krwq** [comment]
I think @davidfowl has a point. I think it is good if `dotnet run` worked when you have only `Program.cs` on your path and do fallback to some defaults if `project.json` or `NuGet.config` are missing but `dotnet new` feels like should not produce too much magic. We could create a switch `--slim` or simply `dotnet new Program.cs` `dotnet new Program.fs`, `dotnet new NuGet.config`. IMO `dotnet new` should be create a complete but slim project which you can modify and start your project with.

**Comment by weshaggard** [comment]
I do not like hard-coding this in the tool, but I also don't like having a bunch of nuget.config's files being created with direct references to our dev feed. As long as we ensure this gets removed, which appears to be tracked by #839, I can live with the hard-coding temporarily.

**Comment by davidfowl** [comment]
Please do not hardcore anything into dotnet restore. This tool will be used in other places and having a feed that you cannot turn off is a non starter.

**Comment by piotrpMSFT** [comment]
We moved this out of beta but need to find a path for getting rid of nuget.config. This may mean getting CoreFx bits to nuget faster...

**Comment by piotrpMSFT** [comment]
@brthor if this is intended to go into 1.0, please retarget the PR to rel/1.0.0.

Of course, it's not clear we want to move in this direction, so consider closing the RP for now.

**Pull request closed without merging**
