### PR TITLE
WIP Migrate src to csproj

### PR DESCRIPTION
**Pull request by jgoshi**
This is all throw away code (I want to migrate from the root of src once projects are removed). But just to give an idea in case people are intersted.

### CODE REVIEW

**Comment by jgoshi** [comment]
test Ubuntu x64 Release Build

**Comment by jgoshi** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by jgoshi** [comment]
test Ubuntu x64 Release Build

**Comment by livarcocc** [comment]
I am going to close this one since I saw you submitted a new one.

**Pull request closed without merging**
