### PR TITLE
Removes bootstrapping workarounds for Ubuntu builds

### PR DESCRIPTION
**Pull request by piotrpMSFT**
@anurse @livarcocc @pakrym @Sridhar-MS @brthor

### CODE REVIEW

**Comment by livarcocc** [comment]
:shipit:

**Comment by anurse** [comment]
:shipit: (once the Ubuntu build finishes :))

**Comment by piotrpMSFT** [comment]
Ubuntu just got past the previous failure. Happily Nugittying up.

**Comment by anurse** [comment]
mergemergemergemergemergemergemergemergemergemergemergemergemergemergemergemergemergemergemergemergemergemergemergemerge :) (or fine... I guess you could wait for the other builds)

**Comment by Sridhar-MS** [comment]
@dotnet-bot test Windows_2016 x64 Release Build please

**Comment by brthor** [comment]
:shipit:

**Comment by Sridhar-MS** [comment]
Windows failure is unrelated. Already had a discussion with @troydai, it may be an intermittent issue. Merging to unblock ubuntu builds.

**Pull request merged**
