### PR TITLE
Update template engine & template versions

### PR DESCRIPTION
**Pull request by mlorbetske**

### CODE REVIEW

**Comment by mlorbetske** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test OSX10.12 x64 Release Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test OSX10.12 x64 Release Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test OSX10.12 x64 Release Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test OSX10.12 x64 Release Build please

**Comment by mlorbetske** [comment]
@livarcocc the mac build seems to be timing out with network issues repetitively, not sure what to do here - any ideas?

**Comment by livarcocc** [comment]
This is a known issue right now I believe. I think it is happening across the board. @mmitche for confirmation and ETA on the fix.

**Comment by livarcocc** [comment]
We validated OSX locally. Merging.

**Pull request merged**
