### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ellismg**
- Pull dotnet-bot's PR.
- Fixup OSX RID.

### CODE REVIEW

**Comment by ellismg** [comment]
@eerhardt @livarcocc 

Going forward, Microsoft.NETCore.App only supports OSX 10.12 and newer.

**Comment by ellismg** [comment]
test Debian8.2 x64 Debug Build please
test Fedora24 x64 Release Build please
test OSX x64 Release Build please

**Comment by ellismg** [comment]
OSX CI run is failing because it doesn't run on 10.12.  I can fix this in CI but I'm guessing we'all need to make a similar change in the official build system.

**Comment by ellismg** [comment]
Needs #6137 to be merged and the OSX job to be regenerated.  @livarcocc or @eerhardt can you help me move the official build machines to a 10.12 pool (or verify that the pool we are using is already a 10.12 pool?)

**Comment by eerhardt** [comment]
https://devdiv.visualstudio.com/DevDiv/_build/definitionEditor?definitionId=5445&_a=general

Looks like it just says:

image

Should be able to update this to tell it we need 10.12 (however you do that in VSTS).

**Comment by livarcocc** [comment]
@dotnet-bot Test OSX x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test this please.

**Pull request merged**
