### PR TITLE
Fix broken publish for official builds

### PR DESCRIPTION
**Pull request by jgoshi**
@eerhardt @piotrpMSFT @livarcocc @krwq @jonsequitur

### CODE REVIEW

**Comment by jgoshi** [comment]
test Ubuntu x64 Release Build

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu x64 Release Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu x64 Release Build please.

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE13.2 x64 Debug Build
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by piotrpMSFT** [comment]
From Ubuntu x64 build:

```
11:37:15 Step 1 : FROM ubuntu:14.04
11:39:17 Pulling repository docker.io/library/ubuntu
11:39:18 Could not reach any registry endpoint
11:39:18 Build step 'Execute shell' marked build as failure
```

it looks like we are seeing an unrelated infra issue.

**Comment by piotrpMSFT** [comment]
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OpenSUSE13.2 x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OpenSUSE13.2 x64 Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu x64 Release Build please.

**Pull request merged**
