### PR TITLE
Insert NuGet Build 4.8.0-preview1.5158 into cli

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.8.0-preview1.5158 into cli release/2.1.3xx branch

### CODE REVIEW

**Comment by jainaashish** [comment]
@livarcocc corresponding VS insertion PR has been merged. Can you also run with merging this into cli and SDK?

**Comment by livarcocc** [comment]
@jainaashish which version of VS is this targeting? If this is for 15.8, it should target release/2.1.4xx.

**Comment by jainaashish** [comment]
@livarcocc yes it's for 15.8 do we still need this PR? given 15.8 will be from Prodcon?

**Comment by PatoBeltran** [comment]
@livarcocc given that we can't change the target branch of this PR, and to avoid creating a new PR, can you update the target branch for this and the SDK PR? or should we close this PR and create a new one?

**Comment by livarcocc** [comment]
Me re-targeting brought a lot more commits than we wanted. I am going to close the PR. Please, create a new one for this.

**Pull request closed without merging**
