### PR TITLE
FragileNonVersionable

### LINKED ISSUE #1785: AccessUnhandled exception: Access violation reading location
## Steps to reproduce

1. Clone the latest MVC.
2. If you already have one delete your .build folder so that you get 1672.
2. build.cmd

## Expected  behavior
No exceptions.

## Actual behavior
Exception `Unhandled exception at 0x00007FF85F6EB108 (coreclr.dll) in csc.exe: 0xC0000005: Access violation reading location 0x000001C71F9FC8D0.` is thrown when we reach compilation of Microsoft.AspNetCore.Mvc.Core for NetStandard1.3.

## Environment data
`dotnet --version` output:
```
.NET Command Line Tools (1.0.0-beta-001672)

Product Information:
 Version:     1.0.0-beta-001672
 Commit Sha:  12dd8d6112

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```
Here's (\\RyanB-01\Shared\Microsoft.AspNetCore.Mvc.Core.dmp) a dump.

### PR DESCRIPTION
**Pull request by piotrpMSFT**
Fixes #1785 

@gkhanna79

### CODE REVIEW

**Comment by gkhanna79** [comment]
LGTM - did you not need the change to get the updated crossgen for the stage 2 build?

**Comment by piotrpMSFT** [comment]
Both stages are corssgen'd by the same invoking method.

**Comment by gkhanna79** [comment]
I dont follow - why did it fail for me indicating that crossgen didnt understand the switch?

**Comment by piotrpMSFT** [comment]
I suspect this is because you were working in master, which does not yet have the latest corefx bits.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX Release Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX Release Build please

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX Debug Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX Release Build please.

**Comment by piotrpMSFT** [comment]
@dotnet-bot test CentOS7.1 Debug Build please.

**Pull request merged**
