### PR TITLE
Fixing the lzma archive upload

### PR DESCRIPTION
**Pull request by livarcocc**
I had a wrong condition before, where I forgot to reference a variable. Fixing that here.

@piotrpMSFT @jgoshi @krwq

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build
@dotnet-bot Test RHEL7.2 x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build

**Comment by piotrpMSFT** [comment]
:shipit:

**Pull request merged**
