### PR TITLE
Update to Json.NET 9.0.1

### PR DESCRIPTION
**Pull request by javiercn**
Updates the CLI to the RTM version of Json.NET 9.0.1

### CODE REVIEW

**Comment by javiercn** [comment]
@Eilon

**Comment by eerhardt** [comment]
Looks like this is failing `dotnet-new.Tests`.

```
15:24:53       StdErr:
15:24:53       /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0-preview2/debug_centos7.1_x64_prtest/artifacts/centos.7-x64/tests/artifacts/98926edb-1503-49e4-8ef3-9f720fb0773e/project.json(7,67): warning NU1012: Dependency conflict. Newtonsoft.Json 9.0.1 expected System.Runtime.Serialization.Primitives >= 4.1.1 but received 4.1.1-rc3-24210-10
```

@blackdwarf @brthor

**Comment by eerhardt** [comment]
Probably need to wait until we take all the CoreFX RTM packages.

**Comment by javiercn** [comment]
@eerhardt Yes, @pranavkm told me that that work was already going on. I just put it out preemptively.

**Comment by pranavkm** [comment]
https://dotnet.myget.org/feed/dotnet-core/package/nuget/Newtonsoft.Json says it references RTM versions. Maybe just needs a rebuild?

**Comment by pranavkm** [comment]
@dotnet-bot test Windows_NT x64 Release Build

**Comment by eerhardt** [comment]
> https://dotnet.myget.org/feed/dotnet-core/package/nuget/Newtonsoft.Json says it references RTM versions. Maybe just needs a rebuild?

It isn't the Newtonsoft package that is the problem - it is the CLI.  CLI is bringing in pre-release CoreFX packages, but Newtonsoft is expecting stable versions. That's why the test is failing:

```
Newtonsoft.Json 9.0.1 expected System.Runtime.Serialization.Primitives >= 4.1.1 but received 4.1.1-rc3-24210-10
```

**Comment by pranavkm** [comment]
Gotcha. When is the CLI planning on upgrading to RTM builds?

**Comment by eerhardt** [comment]
We are in the middle of it now:  #3555.  However, F# is broke right now.  Looking for a fix or we may need to disable the F# tests.

**Comment by eerhardt** [comment]
Thanks, @javiercn for the help!

I cherry-picked this change as part of #3555, so I will close this PR now.  CLI is updated to the stable version of Newtonsoft.Json.

**Pull request closed without merging**
