### PR TITLE
Realpath deps runtimeconfig files and improve error messages

### PR DESCRIPTION
**Pull request by schellap**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2648)

### CODE REVIEW

**Comment by schellap** [comment]
@dotnet-bot test Windows_NT x64 Release Build please
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by schellap** [comment]
@gkhanna79 improvements to error messages and fix for https://github.com/dotnet/cli/issues/2682

**Comment by gkhanna79** [comment]
LGTM

**Comment by schellap** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Pull request merged**
