### PR TITLE
Initial tab completion documentation

### PR DESCRIPTION
**Pull request by jonsequitur**
This is an initial document describing how to enable tab completion in v2.0.0, as there is currently no automated installation process for this feature.

### CODE REVIEW

**Comment by jonsequitur** [comment]
@livarcocc @piotrpMSFT @richlander @billwert

**Comment by livarcocc** [comment]
@dotnet-bot Test this please.

**Comment by livarcocc** [comment]
@MattGertz this is a documentation only change.

**Comment by livarcocc** [comment]
@richlander you talked about making an announcement on this in the announcements repo.

**Pull request merged**
