### PR TITLE
fix install scripts and README to reference combined SDK/framework package

### PR DESCRIPTION
**Pull request by anurse**
This updates our README and `install.ps1/install.sh` to use the combine SDK/framework package. (FYI @krwq, you can totally just stomp out these changes when you have your refactoring, I just wanted to unblock some scenarios right now)

### CODE REVIEW

**Comment by anurse** [comment]
Actually can't merge it yet. We need to update the build scripts to use the new layout and #1908 blocks that.

**Comment by anurse** [comment]
Ok, :up: :date:

Now we can actually build (at least on my OS X machine)!

**Comment by anurse** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please

**Comment by anurse** [comment]
What's the situation with Ubuntu, @piotrpMSFT @Sridhar-MS @brthor ? Should I merge even though it's failing or with @livarcocc come and hunt me down? :stuck_out_tongue:

**Comment by Sridhar-MS** [comment]
@anurse I accidentally pushed some commits into your branch. I am closing this PR. I made sure that your changes went into rel/1.0.0

**Comment by anurse** [comment]
:+1:

**Pull request merged**
