### PR TITLE
Add tests for Code coverage with dotnet test

### PR DESCRIPTION
**Pull request by smadala**
- Add tests for `dotnet test --collect "Code Coverage"` scenario
- https://github.com/Microsoft/vstest/issues/981

### CODE REVIEW

**Comment by smadala** [comment]
@livarcocc This is ready for review.

**Comment by peterhuene** [comment]
Note to maintainers: this should be squashed when merged; too many commits and a few merge commits present (or we can rebase).

**Comment by peterhuene** [comment]
Ping @Pilchie.  This is a set of tests to ensure a 15.8 feature from the MSTest team doesn't get regressed.

**Comment by Pilchie** [comment]
Approved to merge (don't need QB approval, since it only affects test assets).

**Pull request merged**
