### PR TITLE
Fix the help string for the driver

### LINKED ISSUE #1007: Change help to show dotnet build instead of compile
Compile should really never be used directly anymore.

### PR DESCRIPTION
**Pull request by blackdwarf**
Change the compile verb to build.

Fix #1007

/cc @brthor @davidfowl

### CODE REVIEW

**Comment by brthor** [comment]
Looks good to me :shipit:

**Comment by brthor** [comment]
Should probably get this in rel?

**Comment by blackdwarf** [comment]
@brthor yup, will rebase and re-push.

**Comment by blackdwarf** [comment]
Closing this, needs to go into a different branch.

**Pull request closed without merging**
