### PR TITLE
Update MSBuild to 15.2.0-preview-000093-02

### PR DESCRIPTION
**Pull request by eerhardt**
@livarcocc @nguerrera @dsplaisted @jeffkl @cdmihai

### CODE REVIEW

**Comment by nguerrera** [comment]
I would have expected the version flowing to master to 15.3.x based.

**Comment by eerhardt** [comment]
We already have 15.2 in master.  Why would you expect 15.3?

I don't see any 15.3 versions on https://dotnet.myget.org/feed/msbuild/package/nuget/Microsoft.Build.Runtime

**Comment by nguerrera** [comment]
Because 15.3 is the VS milestore we're aligned with for 2.0.

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT x64 Release Build
@dotnet-bot Test Ubuntu x64 Release Build

**Pull request merged**
