### PR TITLE
First pass on fixing spaces in build. Blocked #525 for full solution

### PR DESCRIPTION
**Pull request by brthor**
Quotes everywhere...

Partial fix for #529 

If the repo exists in a directory with a space in the path, it will still break because of #525 

cc @Sridhar-MS

### CODE REVIEW

**Comment by Sridhar-MS** [comment]
@dotnet-bot test this please

**Comment by brthor** [comment]
The merge conflicts are going to be constant on this one until it's merged. Will fix it up.

**Comment by Sridhar-MS** [comment]
@brthor Can you resolve the conflicts. Otherwise LGTM.

**Comment by Sridhar-MS** [comment]
I think I caused another merge conflict :)

**Comment by brthor** [comment]
Going to wait on #650 to put this in.

**Comment by brthor** [comment]
Going to close this PR because of build refactoring.

Will bring fixes in another PR.

**Pull request closed without merging**
