### PR TITLE
Update project.json template to be netcoreapp1.0

### PR DESCRIPTION
**Pull request by Petermarcu**
It should be time, now that RID inference is off, to update dotnet new to finally use netcoreapp1.0.

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2198)

### CODE REVIEW

**Comment by davidfowl** [comment]
:shipit:

**Comment by Petermarcu** [comment]
@schellap , I think I'm blocked by this: https://github.com/dotnet/cli/issues/2250 . Symptom match whats failing in CI.

**Comment by Petermarcu** [comment]
@piotrpMSFT , can you have someone take a look at the other failure here?

**Comment by krwq** [comment]
This was happening because the test was calling `--infer-runtimes`. I'm overwriting project.lock.json right now.

**Comment by Petermarcu** [comment]
@dotnet test OSX x64 Release Build please

**Pull request merged**
