### PR TITLE
Vstest honor nologo

### PR DESCRIPTION
**Pull request by mayankbansal018**
Passing /nologo user input to VSTest task

Related: https://github.com/Microsoft/vstest/pull/1717

Bug: https://github.com/Microsoft/vstest/issues/1701

### CODE REVIEW

**Comment by mayankbansal018** [comment]
@dotnet-bot test .NET Core CLI CI please

**Comment by mayankbansal018** [comment]
@livarcocc , can you please complete this PR.

**Comment by adamralph** [comment]
In which version of the .NET SDK can we expect this change?

**Comment by peterhuene** [comment]
@adamralph it looks like this went into Preview 3 of the 3.0 .NET Core SDK.

**Pull request merged**
