### PR TITLE
Update NuGet.* dependencies of CLI to use 3.5.0-beta-final

### PR DESCRIPTION
**Pull request by rrelyea**
this change is targeting 1.0.0-preview1 release
@piotrpMSFT @yishaigalatzer @emgarten @alpaix

### CODE REVIEW

**Comment by piotrpMSFT** [comment]
@dotnet-bot test this please.

**Comment by rrelyea** [comment]
pretty please

**Comment by piotrpMSFT** [comment]
@rrelyea I found the issue. This will take me ~20 mins to fix.

**Comment by piotrpMSFT** [comment]
Mostly because Jenkins is quite overloaded so a click takes 30s :-/

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX x64 Release Build please.

**Comment by piotrpMSFT** [comment]
@mmitche if you're online, do you have any hints about these failures?

**Comment by piotrpMSFT** [comment]
@dotnet-bot test OSX x64 Release Build please.

**Comment by Petermarcu** [comment]
Skip Jenkins and deal with the issues if they come up in the VSTS build?

**Comment by mmitche** [comment]
It looks like we are hitting Azure network issues again.  We saw these originally when Azure misconfigured a bunch of switch firmware, then again briefly two weeks ago on a Friday, then again today.  There is a Jenkins bug that prevents 'easy' recovery from this situation.  There are also other Azure issues today, like it not accepting requests from us for teardown/bringup of VMs.  All of these issues have been communicated to the Azure, DDIT teams.

**Comment by piotrpMSFT** [comment]
Merged. I'm going to watch VSO.

**Comment by piotrpMSFT** [comment]
First few runs are done and green.

**Pull request merged**
