### PR TITLE
Porting @svick's fix to change a hard-coded URL to a redirect link.

### PR DESCRIPTION
**Pull request by eerhardt**
Porting the URL fix in #3472 to preview2.

@svick @blackdwarf @piotrpMSFT @cdmihai

### CODE REVIEW

**Comment by svick** [comment]
This change is slightly different from my change. Depending on merging strategy between branches here (which I don't know anything about), I think that might cause merge conflicts in the future.

Since #3472 hasn't been merged yet, I can change it to be the same as this one, if that helps.

**Comment by eerhardt** [comment]
test OpenSUSE13.2 x64 Debug Build

**Comment by eerhardt** [comment]
@svick the reason I choose this format was because it is the absolute minimal change to fix the issue. We are locking down preview2 right now, and so I didn't want to make any unnecessary changes.

**Comment by eerhardt** [comment]
Approved in email.

**Comment by svick** [comment]
@eerhardt I understand and I'm fine with that format. My question is whether I should change my PR to mirror yours or whether I should not worry about the possible future merge conflict and keep it the way it is.

**Comment by eerhardt** [comment]
> @eerhardt I understand and I'm fine with that format. My question is whether I should change my PR to mirror yours or whether I should not worry about the possible future merge conflict and keep it the way it is.

Totally up to you.  If you feel your format was better, stick with it and we'll deal with the merge conflict when we merge preview2 branch up to rel/1.0.0.

**Pull request merged**
