### PR TITLE
Updating dependencies from last known good builds

### PR DESCRIPTION
**Pull request by eerhardt**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2092)

### CODE REVIEW

**Comment by joshfree** [comment]
:+1: thanks @eerhardt

**Comment by joshfree** [comment]
@jaredpar can we also get an updated build of Roslyn which uses coreclr/corefx projectkrel 23928.00

**Comment by jaredpar** [comment]
@joshfree we're in the middle of a big NuGet change right now.  Once that's done we're planning on updating CoreFx / CoreCLR.

**Comment by eerhardt** [comment]
Windows builds appear to be hung for over an hour.  @mmitche - Is Jenkins still acting up?

**Comment by eerhardt** [comment]
test Windows_NT x64 Release Build
test Windows_NT x86 Debug Build

**Comment by eerhardt** [comment]
test Windows_NT x64 Release Build
test Windows_NT x86 Debug Build

**Pull request merged**
