### PR TITLE
Treat /? the same as --help

### LINKED ISSUE #4539: dotnet /? -> Object reference not set to an instance of an object
Catching arbitrary exceptions and passing off their message alone as a user error is a colossal anti-pattern. Please stop it. 
## Steps to reproduce

`dotnet /?`
## Expected  behavior

If you want to be mean, something like "error: invalid switch: /?"
If you want to be nice, just give me dotnet --help
## Actual behavior

`Object reference not set to an instance of an object`
## Environment data

```
.NET Command Line Tools (1.0.0-preview3-003913)

Product Information:
 Version:            1.0.0-preview3-003913
 Commit SHA-1 hash:  967957698e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
```

### PR DESCRIPTION
**Pull request by jgoshi**
@piotrpMSFT @livarcocc @krwq @jonsequitur @eerhardt @piotroko @blackdwarf 

Fixes #4539

### CODE REVIEW

**Comment by eerhardt** [comment]
What about -?  Should that show help as well?

@blackdwarf

**Comment by MattGertz** [comment]
RTW, right?  Definitely don't need this for RC3.

**Comment by blackdwarf** [comment]
@MattGertz it is not, but if possible, I would like to have it in. If it creates problems, RTW it is.

@eerhardt we already do that. 😃

**Comment by MattGertz** [comment]
@blackdwarf The bar is sky-high for RC3; this won't even come close.  Sorry.

**Comment by blackdwarf** [comment]
@MattGertz c'est la vie. :)

**Comment by jgoshi** [comment]
@krwq I added the /? option in one of the subcommand test (dotnet sln add /?). So it does work for that as well.

**Comment by eerhardt** [comment]
> @eerhardt we already do that. 😃

```
F:\DotNetTest\MyCoolLib>dotnet -?
Unknown option: -?
...
```

```
F:\DotNetTest\MyCoolLib>dotnet run -?
F:\dotnet\sdk\2.0.0-alpha-004477\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(154,5): error : Unexpected dependency 'Microsoft.NETCore.DotNetHostPolicy' with no version number. [F:\DotNetTest\MyCoolLib\MyCoolLib.csproj]
....
```

**Comment by blackdwarf** [comment]
@eerhardt my bad, my bad, I missed the "Uknown option" bit above. @jgoshi we could handle this one special case as well.

**Comment by piotrpMSFT** [comment]
@jgoshi you will need to cherrypick as @krwq suggested. Let's not bring over RC3 merges as part of this PR.

**Comment by jgoshi** [comment]
I'm closing this PR and will create a new one for rel/1.0.0

**Comment by jgoshi** [comment]
Sorry, talking with @piotrpMSFT I should re-open this and push my changes to the same PR. Minus all the RC3 merges.

**Comment by jgoshi** [comment]
Will special case -? as well

**Comment by piotrpMSFT** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please.

**Pull request merged**
