### PR TITLE
Re-enable solution building tests

### LINKED ISSUE #5205: Re-enable solution building tests
The solution building portion of these tests have been disabled
1. WhenValidProjectIsPassedTheSlnBuilds
2. MigrateAndBuild

Tracking an issue on the sdk
https://github.com/dotnet/sdk/issues/545

### PR DESCRIPTION
**Pull request by jgoshi**
Fixes #5205 

@piotrpMSFT @livarcocc @krwq @jonsequitur @eerhardt

### CODE REVIEW

**Comment by jgoshi** [comment]
Seems like the issue still repros.

**Comment by rainersigwald** [comment]
Looks like the MSBuild used to build this is `15.2.2`, which didn't have the MSBuild side of the fix merged in. We now have a packaged `15.2.0-preview-000033-01` that should have the fix.

**Comment by jgoshi** [comment]
@rainersigwald Do you know which version of Net SDK pulls this in? I'm trying to track down what I need to pull in from the CLI side in order to get your fix.

**Comment by rainersigwald** [comment]
I think you'll need to make a change like https://github.com/dotnet/cli/pull/5535/commits/9404dd2f9822cbff53955c95696e9c2a2d570007 (but point to `15.2.0-preview-000033-01` now). CLI references that directly.

**Comment by jgoshi** [comment]
I tried updating the msbuild version but now I'm getting this error:
Failure to restore a package: One or more packages are incompatible with .NETFramework,Version=v4.6. 

Any ideas?

**Comment by rainersigwald** [comment]
Looks like we introduced a bug in the package 😞. Microsoft/MSBuild#1725

Is this high-pri for you or can you wait until next week for a fix?

**Comment by jgoshi** [comment]
No problem we can wait. Can you let me know when the fix is ready? Thank you.

**Comment by jgoshi** [comment]
Closing this because we are fixing it in the rel/1.0.0 branch. That fix will eventually be merged over to master.
https://github.com/dotnet/cli/pull/5757

**Pull request closed without merging**
