### PR TITLE
Update to SetupCrossgen 92 - Coherence 24937

### PR DESCRIPTION
**Pull request by mlorbetske**
@Eilon

### CODE REVIEW

**Comment by livarcocc** [comment]
@MattGertz regular flow of bits from Asp.Net into the CLI.

**Comment by livarcocc** [comment]
@dotnet-bot Test OpenSUSE42.1 x64 Debug Build
@dotnet-bot Test Ubuntu x64 Release Build

**Comment by mlorbetske** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Pull request merged**
