### PR TITLE
new home for dotnet-compile-fsc

### PR DESCRIPTION
**Pull request by enricosada**
This remove the sources of `dotnet-compile-fsc`, who are already imported in https://github.com/dotnet/netcorecli-fsc/ ( up to commit https://github.com/dotnet/cli/commit/c1f1f20197696a5d64f365d06133a4776874921e when was removed the system.commandline )

a valid package can be:  https://github.com/dotnet/netcorecli-fsc/releases/tag/v1.0.0-rc2-010000

i didnt published it yet in the usual feeds because i dont want to override current package.

i used version `1.0.0-rc2-010000` so is after current version `1.0.0-rc2-002474`.

@brthor should i move tests too? 
I'd like to leave tests in dotnet/cli because is really the best place, so every version is checked, and less fear about parameters changes (compile-csc is there), project.json changes etc otherwise they are going to be stale.
After 1.0.0 we can move also tests i think.
for sure i'll add tests inside dotnet/netcorecli-fsc too

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2638)

### CODE REVIEW

**Comment by cdmihai** [comment]
I'd keep 1-2 simple tests to test that the fsc compiler runner (dotnet-compile-fsc) is getting picked up by the ManagedCompiler.

**Comment by eerhardt** [comment]
I'd really like to take this change, but it needs merge conflicts fixed.

@enricosada - is this something you can take care of today?  If not, I'll pull these commits into my own fork, rebase and fix up.

Thanks!

**Comment by enricosada** [comment]
@eerhardt as per mail, i am doing the migration, i started yesterday, i hope to finish really soon (i need to check everything work + some test to make sure things continue to work)

**Comment by enricosada** [comment]
ok added https://github.com/dotnet/netcorecli-fsc/issues/5 to track migration from dotnet/cli -> dotnet/netcore-fsc.
atm the package doesnt work with preview 2 ( ref #3506 and https://github.com/dotnet/netcorecli-fsc/issues/12 ), so i'll do rebase after there is a working package

**Comment by piotrpMSFT** [comment]
@enricosada can you rebase this one as well?

**Comment by enricosada** [comment]
Yes tomorrow

**Comment by brthor** [comment]
Hey @enricosada I'd like to get this change in now that netcorecli-fsc looks to be all set up and going. 

What remains to be done here? Is it just rebase or is there more work involved?

**Pull request closed without merging**
