### PR TITLE
Update fsharp templates for preview4 with latest msbuild style

### PR DESCRIPTION
**Pull request by enricosada**
- add test for all `dotnet-new` templates
- align to version attributes (and #4821):
  - [x] `web`
  - [x] xunit (aligned but using package version of commit eb8e0cfa409d2ef89091f2058487be0e48e8a32e)
  - [x] console
  - [x] lib
  - [x] mstest

### CODE REVIEW

**Comment by enricosada** [comment]
both c# and f# `.Microsoft.DotNet.New.Tests.GivenThatIWantANew*SAppWithSpecifiedType` tests [fails, ref test report](https://ci.dot.net/job/dotnet_cli/job/rel_1.0.0/job/debug_windows_nt_x86_prtest/120/testReport/) strange

**Comment by enricosada** [comment]
@dotnet-bot Test this please

**Comment by enricosada** [comment]
@dotnet-bot Test Ubuntu16.04 x64 Debug Build

**Comment by enricosada** [comment]
@dotnet-bot test Windows_NT x64 Release Build

**Comment by enricosada** [comment]
@piotrpMSFT the test failure is not related to this pr.
There is also a flacky test `.Microsoft.DotNet.Migration.Tests.GivenThatAnAppWasMigrated.When_skipbackup_specified_Then_project_json_artifacts_do_not_get_moved_to_backup(testProjectName: "PJTestAppSimple")` who fails intermittently

i can repro the current build failure with another pr #4838 (it's an empty commit), just building current `HEAD` eb8e0cfa409d2ef89091f2058487be0e48e8a32e

**Comment by enricosada** [comment]
Cherry picked fix for #4840 from #4838 now is green. No time/ideas how to fix intermittent test failure #4839 (it's not related to this pr)

Now f# is aligned (with test for all templates) to:

- using `Version` attribute on `PackageReference`
- minimal diff with c# templates
- latest c# `console`/`lib`/`mstest`/`xunittest` ( #4821 )
  - but i used current `HEAD` xunit package versions, because i think there is a merge mistake in #4821. If  i am wrong, pls update it
- latest c# `web` from `HEAD`

@cartermp @KevinRansom for review

@piotrpMSFT @livarcocc @krwq @MattGertz @srivatsn @mlorbetske for signoff for new release, if possibile? asking for a `approved for next preview` label  🙏 😄

**Comment by piotrpMSFT** [comment]
Lgtm. :shipit: once @srivatsn or @mattgertz approves

**Pull request merged**
