### PR TITLE
Fixing dotnet test help text

### LINKED ISSUE #5021: dotnet test -h is misleading on usage of --test-case-filter switch
## Steps to reproduce

`dotnet test -h`

## Expected  behavior

The help text should give a clearer example of usage. The examples given are misleading.

## Actual behavior

```
> dotnet test -h
--test-case-filter <Expression>       Run tests that match the given expression.
                                      Examples:
                                      --test-case-filter:"Priority = 1"
                                      --test-case-filter: "(FullyQualifiedName~Nightly | Name = MyTestMethod)"
```

The command actually requires, for example:

`dotnet test --test-case-filter "FullyQualifiedName=Microsoft.DotNet.Migration.T
ests.GivenThatIWantToMigrateTestApps.ItMigratesRootProjectAndReferences"`

This does not work:

`dotnet test --test-case-filter "Name=ItMigratesRootProjectAndReferences"`

## Environment data
`dotnet --info` output:

Product Information:
 Version:            1.0.0-preview5-004253
 Commit SHA-1 hash:  0caae96daf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\dev\github\cli\artifacts\win10-x64\stage2\sdk\1.0.0-preview5-004253

### PR DESCRIPTION
**Pull request by blackdwarf**
Renaming --test-case-filter to just --filter to make it easier to use.
Placing more examples and more clarity for the --filter command.

Fixes #5021

/cc @livarcocc @jonsequitur @Faizan2304 @codito

### CODE REVIEW

**Comment by blackdwarf** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by blackdwarf** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by blackdwarf** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by blackdwarf** [comment]
@dotnet-bot test this please

**Comment by blackdwarf** [comment]
@srivatsn @piotrpMSFT this ok for merge?

**Comment by piotrpMSFT** [comment]
@srivatsn

**Comment by srivatsn** [comment]
Approved

**Pull request merged**
