### PR TITLE
Updating dependencies from last known good builds

### PR DESCRIPTION
**Pull request by eerhardt**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2056)

### CODE REVIEW

**Comment by eerhardt** [comment]
@schellap @Sridhar-MS  - please review my build script change to no longer copy dotnet.exe and hostpolicy.dll

**Comment by brthor** [comment]
@eerhardt three windows builds running for this PR that aren't the latest commit, going to cancel them

**Comment by eerhardt** [comment]
@bryhor :+1:

**Comment by eerhardt** [comment]
Replaced with https://github.com/dotnet/cli/pull/2067

**Pull request closed without merging**
