### PR TITLE
update nuget to 3.5.0-beta2-1392

### PR DESCRIPTION
**Pull request by rohit21agrawal**
Creating new pull request as the previous (https://github.com/dotnet/cli/pull/3337) one cannot be merged.

Update nuget to 3.5.0-beta2-1392 . This build has been upgraded to depend on the following:
• CoreCLR/CoreFX/WCF – rc3-24128-00
• Microsoft.NetCore.App – 1.0.0-rc3-004338
• CLI – 1.0.0-preview2-002911

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
@eerhardt The ubuntu failure looks weird and unrelated...can you please take a look at it ?

**Comment by rohit21agrawal** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please

**Comment by rohit21agrawal** [comment]
@rrelyea @eerhardt 

The ubuntu build failed again (it doesn't show it here, but if you click on details, it shows the status as failed).

**Comment by eerhardt** [comment]
@rohit21agrawal - do you have a link to the failure?  I can take a look, if you need it.  I know that Jenkins was having issues last night, it could have been those.

**Comment by rohit21agrawal** [comment]
@eerhardt 
http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0-preview2/job/debug_ubuntu16.04_x64_prtest/62/

**Comment by eerhardt** [comment]
That appears to be hung/broken.  @mmitche any ideas on what is going on with this run?  http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0-preview2/job/debug_ubuntu16.04_x64_prtest/62/

**Comment by mmitche** [comment]
Results of the disconnects yesterday: @dotnet-bot test Ubuntu16.04 x64 Debug Build

**Comment by eerhardt** [comment]
:shipit:

**Pull request merged**
