### PR TITLE
Add retry to download

### PR DESCRIPTION
**Pull request by wli3**
Reuse retry code from https://github.com/dotnet/cli/commit/7f54ccb903f43cd7c8a8b774a4d3e84cecf1064a

That PR is reverted later due to no need for publish deb to the feed.

### CODE REVIEW

**Comment by wli3** [comment]
@dotnet-bot test this please

**Comment by wli3** [comment]
ping @dotnet/dotnet-cli review

@livarcocc I also need a tell mode email right?

**Comment by livarcocc** [comment]
@wli3 right. TELL MODE, as this is infra-change.

**Comment by wli3** [comment]
#### Description
Add retry to downloading  build dependency assert.

#### Customer Impact
No customer impact. Build improvement 

#### Regression?
No

#### Risk
Low. Only test infrastructure change.

**Comment by wli3** [comment]
@livarcocc could you review this?

**Pull request merged**
