### PR TITLE
Remove JsonParser dependency

### PR DESCRIPTION
**Pull request by eerhardt**
@pranavkm

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2750)

### CODE REVIEW

**Comment by livarcocc** [comment]
I avoided doing this when I initially changed the ProjectReader, GlobalSettingsReader, etc because I didn't have the cycles to add unit tests for the LockFileReader like I did for all the others. I would say don't make this change unless you are prepared to add the unit tests for cover it, given that this is such a critical piece of our code.

**Comment by eerhardt** [comment]
You don't think the rest of our tests cover this?

**Comment by eerhardt** [comment]
I can add a couple unit tests tomorrow that read a lock file with all the properties and inspects the values are parsed correctly.

**Comment by davidfowl** [comment]
This affects the VS experience. Errors with line numbers and file paths are used to squiggle locations in the IDE. It's also used to show better errors on the command line. 

@troydai can help identify the equivalent APIs on JSON.NET. We used to do this in DNX.

**Comment by eerhardt** [comment]
@davidfowl this is already using those APIs for JSON.NET. FileFormatException could read line numbers for both. I just moved it from JsonParser to JSON.NET and removed the JsonParser methods in order to remove the dependency.

**Comment by troydai** [comment]
Can I know the motivation behind replace JsonDeserializer with JSON.NET? We wrote a customized json deserializer because we identified JSON.NET has a performance issue in lock file and project file parsing. It allocated a lot. Is it not a problem any more? Did we profile the performance recently to prove that?

Otherwise is there a feature of Json.NET that we need so much that we flip entire deserializer back?

**Comment by eerhardt** [comment]
The motivation is to remove more dependencies on ASP.NET and make the CLI repo more self contained. Also to make the code base consistent (why use two different JSON parsers in the same project?).

If there are perf issues with JSON.NET, why not help out the entire community and fix the perf issues in the defacto JSON library? Instead of writing a brand new parser for a single usage.

**Comment by davidfowl** [comment]
This is a good change. We just need to make sure that we don't have less data is all.

**Comment by JamesNK** [comment]
Hi

If you care about performance then I suggest you use the low level JsonTextReader. That will allow you to read the JSON into the ExportFile without any intermediary objects.

**Comment by pranavkm** [comment]
@troydai could you review this? You're probably more familiar with this area of code

**Comment by troydai** [comment]
Reviewed last night. The code itself looks good bar from my question regarding why. 

It removes dead code here. I'm taking another look now and probably sign off soon.

**Comment by troydai** [comment]
:shipit:

**Comment by eerhardt** [comment]
@Petermarcu approved in email.

**Comment by eerhardt** [comment]
@troydai - I ran a little perf test on my machine:

```
public static void Main(string[] args)
{
    while (true)
    {
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();

        for (int i = 0; i < 100; i++)
        {
            var projectContext = ProjectContext.Create(@"C:\cli\src\dotnet\", new NuGetFramework("netcoreapp1.0"), new[] { "win10-x64" });
        }

        Console.WriteLine($"Time: {stopwatch.ElapsedMilliseconds}ms");
    }
}
```

I used `C:\cli\src\dotnet` for the test because it has the biggest lock file in our product: 648 KB (15k lines) on my machine.

`C:\cli\artifacts\win10-x64\stage2\dotnet.exe run -c Release`

Output without my changes (so using the JsonParser from ASP.NET):

```
Time: 3712ms
Time: 3382ms
Time: 3789ms
Time: 3635ms
Time: 3490ms
Time: 3375ms
Time: 3341ms
Time: 3575ms
Time: 3371ms
Time: 3365ms
Time: 3376ms
Time: 3372ms
```

Output with my changes (using Newtonsoft):

```
Time: 3650ms
Time: 3421ms
Time: 3422ms
Time: 3368ms
Time: 3443ms
Time: 3718ms
Time: 3567ms
Time: 3468ms
Time: 3337ms
Time: 3488ms
Time: 3702ms
```

I went back and forth reverting and un-reverting the change 4 times, and the results were very consistently in the 3.3s - 3.7s range for each.

**Pull request merged**
