### PR TITLE
Implement support for Embedded PDB

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@livarcocc

**Comment by tmat** [comment]
test CentOS7.1 x64 Debug Build  please

**Comment by tmat** [comment]
@livarcocc Looks good?

**Comment by tmat** [comment]
@livarcocc Ping

**Comment by livarcocc** [comment]
LGTM.

**Comment by tmat** [comment]
Thanks

**Pull request merged**
