### PR TITLE
Removing the word please from the ASP.NET first run message.

### PR DESCRIPTION
**Pull request by livarcocc**
@MattGertz for approval to take to ship room for RTM

**Issues fixed**

https://github.com/dotnet/cli/issues/9195

**Description of Issue**

We have the word please in one of our messages in a situation where MS guidance asks us not to use it. We are just removing that message.

**Customer Impact**

We are violating MS guidance.

**Risk**

Low - Just a small text change.

**Testing**

CLI CI.

### CODE REVIEW

**Comment by MattGertz** [comment]
@livarcocc Yep.

**Comment by peterhuene** [comment]
We have a number of other instances of "please" that we should probably check for guidance (some of which have a similar context to this issue, such as "please view this link"):

* `src/dotnet/commands/dotnet-add/dotnet-add-package/LocalizableStrings.resx`:
  * `SpecifyExactlyOnePackageReference`
  * `CmdDGFileIOException`
* `src/dotnet/commands/dotnet-help/LocalizableStrings.resx`:
  * `CommandDoesNotExist`
* `src/dotnet/commands/dotnet-migrate/LocalizableStrings.resx`:
  * `MigrationAdditionalHelp`
* `src/dotnet/commands/dotnet-pack/LocalizableStrings.resx`:
  * `CmdServiceableDescription`
* `src/dotnet/commands/dotnet-remove/dotnet-remove-package/LocalizableStrings.resx`:
  * `SpecifyExactlyOnePackageReference`
* `src/dotnet/commands/dotnet-run/LocalizableStrings.resx`:
  * `RunCommandException`
  * `RunCommandExceptionUnableToRunSpecifyFramework`
  * `RunCommandExceptionUnableToRun`
* `src/dotnet/commands/dotnet-tool/install/LocalizableStrings.resx`:
  * `SpecifyExactlyOnePackageId`
  * `ToolInstallationFailedContactAuthor`
  * `InstallToolCommandNeedGlobalOrToolPath`
  * `InstallToolCommandInvalidGlobalAndToolPath`
* `src/dotnet/commands/dotnet-tool/list/LocalizableStrings.resx`:
  * `NeedGlobalOrToolPath`
  * `GlobalAndToolPathConflict`
* `src/dotnet/commands/dotnet-tool/uninstall/LocalizableStrings.resx`:
  * `SpecifyExactlyOnePackageId`
  * `UninstallToolCommandNeedGlobalOrToolPath`
  * `UninstallToolCommandInvalidGlobalAndToolPath`
* `cli/src/dotnet/commands/dotnet-tool/update/LocalizableStrings.resx`:
  * `SpecifyExactlyOnePackageId`
  * `UpdateToolCommandNeedGlobalOrToolPath`
  * `UpdateToolCommandInvalidGlobalAndToolPath`
* `src/dotnet/commands/dotnet-tool/update/LocalizableStrings.resx`:
  * A lot of strings have "please".
* `src/Microsoft.DotNet.Cli.Utils/LocalizableStrings.resx`:
  * `CannotFindCommandAvailableAsTool`

This shouldn't hold up this particular PR, just that we need to scrub these as appropriate.

**Comment by KathleenDollard** [comment]
@peterhuene Can you please :) create a new issue with your comment here. I think we can target 2.1.400 with those updates.

**Comment by peterhuene** [comment]
Opened as https://github.com/dotnet/cli/issues/9203.

**Comment by livarcocc** [comment]
@dotnet-bot Test CentOS7.1 x64 Debug Build

**Pull request merged**
