### PR TITLE
Pin down version for xunit.netcore.extensions.

### PR DESCRIPTION
**Pull request by Sridhar-MS**
cc: @anurse @livarcocc 

Going to wait for some passing builds before merging.

---
This change is [Reviewable](https://reviewable.io/reviews/dotnet/cli/2019)

### CODE REVIEW

**Comment by anurse** [comment]
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit:

**Comment by livarcocc** [comment]
:shipit: once CI passes.

**Comment by anurse** [comment]
@dotnet-bot test Ubuntu x64 Debug Build please
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by brthor** [comment]
:shipit: :ship: :rocket: :+1:

**Comment by anurse** [comment]
```
16:12:36     Microsoft.DotNet.Tests.PackagedCommandTests.TestProjectToolIsAvailableThroughDriver(appName: "AppWithDirectAndToolDependency") [FAIL]
16:12:36       Command did not output with Expected Output. Expected: Hello Portable World!
16:12:36       
16:12:36       File Name: /mnt/resource/j/workspace/dotnet_cli/rel_1.0.0/debug_centos7.1_x64_prtest/artifacts/centos.7-x64/stage2/dotnet
16:12:36       Arguments: portable 
16:12:36       Exit Code: 0
16:12:36       StdOut:
16:12:36       
16:12:36       StdErr:
16:12:36       Invalid .deps file
16:12:36       
16:12:36       
16:12:36       Stack Trace:
16:12:36            at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
16:12:36            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
16:12:36            at Microsoft.DotNet.Tools.Test.Utilities.CommandResultAssertions.HaveStdOut(String expectedOutput)
16:12:36            at Microsoft.DotNet.Tests.PackagedCommandTests.TestProjectToolIsAvailableThroughDriver(String appName)
```

Weird...

**Comment by brthor** [comment]
@anurse likely a cached test package, @eerhardt 's fix should fix this

**Comment by Sridhar-MS** [comment]
PR #2011 has the required changes.

**Pull request closed without merging**
