### PR TITLE
Add additional package version updaters for other aspnet dependencies

### PR DESCRIPTION
**Pull request by mmitche**
- If this PR should not run tests please add text "skip[REMOVE_THIS]ci[REMOVE_THIS]please" (remove the marked text, no quotes).
- Please add description for changes you are making.
- If there is an issue related to this PR, please add the reference.

### CODE REVIEW

**Comment by mmitche** [comment]
Updated to use AspNetCore.All instead of Netcore.app, since App is based off of .All in the dependency versions file

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by wli3** [comment]
@mmitche this PR broke github build. The test failure is legit. Although it is due to github MicrosoftNETCoreAppPackage version too old.

cc @dotnet/dotnet-cli

**Comment by wli3** [comment]
I am updating to latest source build version

**Pull request merged**
