### PR TITLE
Update to NuGet 3.5.0-rc1-final

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/dotnet/cli/issues/4946

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @livarcocc

**Comment by livarcocc** [comment]
I think we may be hitting the whole package casing problem here.

**Comment by pranavkm** [comment]
Yeah, I've been trying to cherry-pick a commit from a different branch to see if it fixes it. We'd also need to revert the change in https://github.com/dotnet/core-setup/commit/631f826b99faf23ad215e1f2155995d341bbde43 once this is produced so that DependencyModel can work with the new path casing.

**Comment by pranavkm** [comment]
@livarcocc I manually tested the scenario from https://github.com/dotnet/cli/issues/4946#issue-193871547 and that worked. Wasn't sure if you wanted me to set up a test for this since this isn't a primary development branch for you any more.

**Comment by pranavkm** [comment]
Should I merge it in?

**Comment by livarcocc** [comment]
@pranavkm We are checking if we need approval for this. I will merge it once we figure it out.

**Comment by piotrpMSFT** [comment]
@MattGertz

**Pull request merged**
