### PR TITLE
deps.json pass 2

### PR DESCRIPTION
**Pull request by pakrym**
Add resource assemblies and runtime targets to dependency context builder.

### CODE REVIEW

**Comment by schellap** [comment]
@pakrym a quick question, does this fix issue #1562, I am at a point in host implementation to read this file and do some testing...

**Comment by anurse** [comment]
It looks like this phase doesn't yet write the "runtime targets" to the deps file. Am I correct in that observation? Is that the next phase?

**Comment by pakrym** [comment]
@schellap @anurse yes, this doesn't write file yet

**Comment by anurse** [comment]
:shipit:

**Comment by brthor** [comment]
0 / 11 passing :frowning:

**Comment by pakrym** [comment]
Everything was green, squash messed up ci.

**Comment by anurse** [comment]
With the CI times we're seeing and given the amount of traffic, it's really hard to wait for the CI after rebasing since the change often needs to be rebased again when that finishes.

**Pull request merged**
